In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15    
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

# class FocalLoss(nn.Module):
#     def __init__(self, alpha=1, gamma=2, reduction='mean'):
#         super(FocalLoss, self).__init__()
#         self.alpha = alpha
#         self.gamma = gamma
#         self.reduction = reduction
# 
#     def forward(self, inputs, targets):
#         ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
#         pt = torch.exp(-ce_loss)  # 预测的概率
#         focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss
# 
#         if self.reduction == 'mean':
#             return focal_loss.mean()
#         elif self.reduction == 'sum':
#             return focal_loss.sum()
#         else:
#             return focal_loss

# criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-CEloss1.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4929/4929 [00:55<00:00, 89.12it/s, loss=0.3548]


Epoch 1/15 - Loss: 0.4736, Accuracy: 0.8220


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.57it/s, loss=0.4403]


Epoch 2/15 - Loss: 0.3905, Accuracy: 0.8478


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.97it/s, loss=0.2396]


Epoch 3/15 - Loss: 0.3725, Accuracy: 0.8532


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.3563]


Epoch 4/15 - Loss: 0.3607, Accuracy: 0.8560


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.79it/s, loss=0.2667]


Epoch 5/15 - Loss: 0.3515, Accuracy: 0.8589


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.99it/s, loss=0.2827]


Epoch 6/15 - Loss: 0.3454, Accuracy: 0.8604


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.08it/s, loss=0.2234]


Epoch 7/15 - Loss: 0.3413, Accuracy: 0.8621


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.16it/s, loss=0.3513]


Epoch 8/15 - Loss: 0.3371, Accuracy: 0.8627


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.15it/s, loss=0.4491]


Epoch 9/15 - Loss: 0.3339, Accuracy: 0.8641


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.96it/s, loss=0.3059]


Epoch 10/15 - Loss: 0.3318, Accuracy: 0.8650


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.28it/s, loss=0.1504]


Epoch 11/15 - Loss: 0.3290, Accuracy: 0.8654


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.18it/s, loss=0.2869]


Epoch 12/15 - Loss: 0.3261, Accuracy: 0.8668


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.26it/s, loss=0.4896]


Epoch 13/15 - Loss: 0.3233, Accuracy: 0.8679


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.31it/s, loss=0.3753]


Epoch 14/15 - Loss: 0.3224, Accuracy: 0.8684


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.26it/s, loss=0.4451]


Epoch 15/15 - Loss: 0.3200, Accuracy: 0.8689
Fold 1 Accuracy: 0.8125
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.91it/s, loss=0.5183]


Epoch 1/15 - Loss: 0.3210, Accuracy: 0.8686


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.55it/s, loss=0.1932]


Epoch 2/15 - Loss: 0.3183, Accuracy: 0.8694


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.51it/s, loss=0.1542]


Epoch 3/15 - Loss: 0.3177, Accuracy: 0.8697


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.57it/s, loss=0.2541]


Epoch 4/15 - Loss: 0.3148, Accuracy: 0.8701


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.49it/s, loss=0.3750]


Epoch 5/15 - Loss: 0.3131, Accuracy: 0.8710


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.66it/s, loss=0.2815]


Epoch 6/15 - Loss: 0.3120, Accuracy: 0.8714


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.50it/s, loss=0.3232]


Epoch 7/15 - Loss: 0.3104, Accuracy: 0.8724


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.51it/s, loss=0.3702]


Epoch 8/15 - Loss: 0.3087, Accuracy: 0.8722


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.3586]


Epoch 9/15 - Loss: 0.3075, Accuracy: 0.8732


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.58it/s, loss=0.2734]


Epoch 10/15 - Loss: 0.3069, Accuracy: 0.8729


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.52it/s, loss=0.3932]


Epoch 11/15 - Loss: 0.3055, Accuracy: 0.8739


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.59it/s, loss=0.3228]


Epoch 12/15 - Loss: 0.3045, Accuracy: 0.8736


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.29it/s, loss=0.3164]


Epoch 13/15 - Loss: 0.3034, Accuracy: 0.8744


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.27it/s, loss=0.3497]


Epoch 14/15 - Loss: 0.3017, Accuracy: 0.8750


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.13it/s, loss=0.2254]


Epoch 15/15 - Loss: 0.3011, Accuracy: 0.8752
Fold 2 Accuracy: 0.8263
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.40it/s, loss=0.3541]


Epoch 1/15 - Loss: 0.3044, Accuracy: 0.8743


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.25it/s, loss=0.1869]


Epoch 2/15 - Loss: 0.3014, Accuracy: 0.8750


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.14it/s, loss=0.2645]


Epoch 3/15 - Loss: 0.3019, Accuracy: 0.8752


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.26it/s, loss=0.4166]


Epoch 4/15 - Loss: 0.2996, Accuracy: 0.8761


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.4233]


Epoch 5/15 - Loss: 0.2982, Accuracy: 0.8757


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.25it/s, loss=0.1474]


Epoch 6/15 - Loss: 0.2980, Accuracy: 0.8767


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.1728]


Epoch 7/15 - Loss: 0.2965, Accuracy: 0.8767


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.96it/s, loss=0.2501]


Epoch 8/15 - Loss: 0.2957, Accuracy: 0.8774


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.24it/s, loss=0.4239]


Epoch 9/15 - Loss: 0.2954, Accuracy: 0.8775


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.28it/s, loss=0.3243]


Epoch 10/15 - Loss: 0.2933, Accuracy: 0.8787


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.46it/s, loss=0.2132]


Epoch 11/15 - Loss: 0.2922, Accuracy: 0.8784


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.61it/s, loss=0.2537]


Epoch 12/15 - Loss: 0.2924, Accuracy: 0.8780


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.48it/s, loss=0.3803]


Epoch 13/15 - Loss: 0.2908, Accuracy: 0.8788


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.90it/s, loss=0.2536]


Epoch 14/15 - Loss: 0.2906, Accuracy: 0.8793


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.27it/s, loss=0.3304]


Epoch 15/15 - Loss: 0.2895, Accuracy: 0.8796
Fold 3 Accuracy: 0.8301
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.36it/s, loss=0.1571]


Epoch 1/15 - Loss: 0.2915, Accuracy: 0.8790


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.07it/s, loss=0.2892]


Epoch 2/15 - Loss: 0.2900, Accuracy: 0.8794


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.32it/s, loss=0.1750]


Epoch 3/15 - Loss: 0.2888, Accuracy: 0.8800


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.83it/s, loss=0.4052]


Epoch 4/15 - Loss: 0.2874, Accuracy: 0.8803


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.30it/s, loss=0.3980]


Epoch 5/15 - Loss: 0.2872, Accuracy: 0.8803


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.21it/s, loss=0.1428]


Epoch 6/15 - Loss: 0.2859, Accuracy: 0.8805


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.29it/s, loss=0.2876]


Epoch 7/15 - Loss: 0.2857, Accuracy: 0.8808


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.48it/s, loss=0.1827]


Epoch 8/15 - Loss: 0.2849, Accuracy: 0.8810


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.3645]


Epoch 9/15 - Loss: 0.2843, Accuracy: 0.8819


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.22it/s, loss=0.3067]


Epoch 10/15 - Loss: 0.2830, Accuracy: 0.8816


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.3051]


Epoch 11/15 - Loss: 0.2818, Accuracy: 0.8822


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.86it/s, loss=0.3535]


Epoch 12/15 - Loss: 0.2815, Accuracy: 0.8824


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.43it/s, loss=0.1696]


Epoch 13/15 - Loss: 0.2810, Accuracy: 0.8826


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.2244]


Epoch 14/15 - Loss: 0.2808, Accuracy: 0.8833


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.60it/s, loss=0.2912]


Epoch 15/15 - Loss: 0.2800, Accuracy: 0.8827
Fold 4 Accuracy: 0.8323
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.27it/s, loss=0.2356]


Epoch 1/15 - Loss: 0.2839, Accuracy: 0.8819


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.2828]


Epoch 2/15 - Loss: 0.2819, Accuracy: 0.8829


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.25it/s, loss=0.3291]


Epoch 3/15 - Loss: 0.2817, Accuracy: 0.8827


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.4421]


Epoch 4/15 - Loss: 0.2803, Accuracy: 0.8831


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.54it/s, loss=0.1093]


Epoch 5/15 - Loss: 0.2801, Accuracy: 0.8830


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.40it/s, loss=0.1815]


Epoch 6/15 - Loss: 0.2787, Accuracy: 0.8836


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.10it/s, loss=0.3625]


Epoch 7/15 - Loss: 0.2785, Accuracy: 0.8837


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.48it/s, loss=0.2327]


Epoch 8/15 - Loss: 0.2771, Accuracy: 0.8841


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.16it/s, loss=0.3573]


Epoch 9/15 - Loss: 0.2774, Accuracy: 0.8837


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.12it/s, loss=0.3021]


Epoch 10/15 - Loss: 0.2757, Accuracy: 0.8848


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.82it/s, loss=0.2913]


Epoch 11/15 - Loss: 0.2756, Accuracy: 0.8855


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.62it/s, loss=0.3758]


Epoch 12/15 - Loss: 0.2748, Accuracy: 0.8851


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.28it/s, loss=0.3476]


Epoch 13/15 - Loss: 0.2741, Accuracy: 0.8851


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.33it/s, loss=0.2513]


Epoch 14/15 - Loss: 0.2741, Accuracy: 0.8852


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.46it/s, loss=0.2043]


Epoch 15/15 - Loss: 0.2736, Accuracy: 0.8855
Fold 5 Accuracy: 0.8412
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.24it/s, loss=0.4485]


Epoch 1/15 - Loss: 0.2764, Accuracy: 0.8844


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.3590]


Epoch 2/15 - Loss: 0.2754, Accuracy: 0.8848


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.56it/s, loss=0.3022]


Epoch 3/15 - Loss: 0.2736, Accuracy: 0.8859


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.53it/s, loss=0.2424]


Epoch 4/15 - Loss: 0.2726, Accuracy: 0.8858


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.55it/s, loss=0.1580]


Epoch 5/15 - Loss: 0.2724, Accuracy: 0.8857


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.14it/s, loss=0.4059]


Epoch 6/15 - Loss: 0.2720, Accuracy: 0.8862


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.50it/s, loss=0.2822]


Epoch 7/15 - Loss: 0.2711, Accuracy: 0.8868


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.48it/s, loss=0.1540]


Epoch 8/15 - Loss: 0.2700, Accuracy: 0.8872


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.41it/s, loss=0.1550]


Epoch 9/15 - Loss: 0.2701, Accuracy: 0.8869


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.33it/s, loss=0.2349]


Epoch 10/15 - Loss: 0.2691, Accuracy: 0.8878


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.47it/s, loss=0.3005]


Epoch 11/15 - Loss: 0.2683, Accuracy: 0.8878


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.61it/s, loss=0.2112]


Epoch 12/15 - Loss: 0.2674, Accuracy: 0.8881


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.36it/s, loss=0.3132]


Epoch 13/15 - Loss: 0.2681, Accuracy: 0.8874


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.52it/s, loss=0.2685]


Epoch 14/15 - Loss: 0.2673, Accuracy: 0.8881


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.58it/s, loss=0.2749]


Epoch 15/15 - Loss: 0.2662, Accuracy: 0.8884
Fold 6 Accuracy: 0.8439
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.08it/s, loss=0.2417]


Epoch 1/15 - Loss: 0.2690, Accuracy: 0.8875


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.24it/s, loss=0.1970]


Epoch 2/15 - Loss: 0.2682, Accuracy: 0.8879


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.60it/s, loss=0.2408]


Epoch 3/15 - Loss: 0.2666, Accuracy: 0.8884


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.49it/s, loss=0.2533]


Epoch 4/15 - Loss: 0.2665, Accuracy: 0.8888


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.06it/s, loss=0.2846]


Epoch 5/15 - Loss: 0.2660, Accuracy: 0.8887


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.63it/s, loss=0.5161]


Epoch 6/15 - Loss: 0.2650, Accuracy: 0.8891


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.3016]


Epoch 7/15 - Loss: 0.2650, Accuracy: 0.8890


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.79it/s, loss=0.2640]


Epoch 8/15 - Loss: 0.2644, Accuracy: 0.8889


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.17it/s, loss=0.2151]


Epoch 9/15 - Loss: 0.2629, Accuracy: 0.8897


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.50it/s, loss=0.2639]


Epoch 10/15 - Loss: 0.2633, Accuracy: 0.8901


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.2016]


Epoch 11/15 - Loss: 0.2620, Accuracy: 0.8899


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.39it/s, loss=0.2915]


Epoch 12/15 - Loss: 0.2619, Accuracy: 0.8903


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.4431]


Epoch 13/15 - Loss: 0.2612, Accuracy: 0.8906


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.90it/s, loss=0.2208]


Epoch 14/15 - Loss: 0.2616, Accuracy: 0.8902


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.66it/s, loss=0.2053]


Epoch 15/15 - Loss: 0.2609, Accuracy: 0.8909
Fold 7 Accuracy: 0.8472
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.40it/s, loss=0.1389]


Epoch 1/15 - Loss: 0.2652, Accuracy: 0.8895


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.36it/s, loss=0.2115]


Epoch 2/15 - Loss: 0.2632, Accuracy: 0.8901


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.64it/s, loss=0.1592]


Epoch 3/15 - Loss: 0.2624, Accuracy: 0.8903


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.63it/s, loss=0.2853]


Epoch 4/15 - Loss: 0.2625, Accuracy: 0.8903


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.43it/s, loss=0.3473]


Epoch 5/15 - Loss: 0.2621, Accuracy: 0.8906


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.12it/s, loss=0.2102]


Epoch 6/15 - Loss: 0.2607, Accuracy: 0.8907


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.3755]


Epoch 7/15 - Loss: 0.2606, Accuracy: 0.8913


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.22it/s, loss=0.5002]


Epoch 8/15 - Loss: 0.2597, Accuracy: 0.8909


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.96it/s, loss=0.2723]


Epoch 9/15 - Loss: 0.2592, Accuracy: 0.8919


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.27it/s, loss=0.3811]


Epoch 10/15 - Loss: 0.2592, Accuracy: 0.8916


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.45it/s, loss=0.4326]


Epoch 11/15 - Loss: 0.2581, Accuracy: 0.8920


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.52it/s, loss=0.2503]


Epoch 12/15 - Loss: 0.2577, Accuracy: 0.8922


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.60it/s, loss=0.1628]


Epoch 13/15 - Loss: 0.2572, Accuracy: 0.8920


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.2556]


Epoch 14/15 - Loss: 0.2567, Accuracy: 0.8923


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.74it/s, loss=0.1839]


Epoch 15/15 - Loss: 0.2562, Accuracy: 0.8926
Fold 8 Accuracy: 0.8524
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.84it/s, loss=0.2661]


Epoch 1/15 - Loss: 0.2600, Accuracy: 0.8913


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.57it/s, loss=0.3534]


Epoch 2/15 - Loss: 0.2596, Accuracy: 0.8916


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.34it/s, loss=0.3306]


Epoch 3/15 - Loss: 0.2580, Accuracy: 0.8922


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.50it/s, loss=0.2964]


Epoch 4/15 - Loss: 0.2581, Accuracy: 0.8918


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.1872]


Epoch 5/15 - Loss: 0.2562, Accuracy: 0.8924


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.50it/s, loss=0.1735]


Epoch 6/15 - Loss: 0.2556, Accuracy: 0.8929


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.68it/s, loss=0.1241]


Epoch 7/15 - Loss: 0.2561, Accuracy: 0.8928


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.43it/s, loss=0.1594]


Epoch 8/15 - Loss: 0.2556, Accuracy: 0.8930


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.46it/s, loss=0.2066]


Epoch 9/15 - Loss: 0.2550, Accuracy: 0.8935


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.37it/s, loss=0.1817]


Epoch 10/15 - Loss: 0.2542, Accuracy: 0.8937


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.79it/s, loss=0.2494]


Epoch 11/15 - Loss: 0.2541, Accuracy: 0.8936


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.57it/s, loss=0.2881]


Epoch 12/15 - Loss: 0.2533, Accuracy: 0.8937


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.51it/s, loss=0.2320]


Epoch 13/15 - Loss: 0.2533, Accuracy: 0.8935


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.72it/s, loss=0.2685]


Epoch 14/15 - Loss: 0.2527, Accuracy: 0.8945


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.51it/s, loss=0.3382]


Epoch 15/15 - Loss: 0.2531, Accuracy: 0.8939
Fold 9 Accuracy: 0.8559
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.67it/s, loss=0.3676]


Epoch 1/15 - Loss: 0.2564, Accuracy: 0.8928


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.53it/s, loss=0.1418]


Epoch 2/15 - Loss: 0.2553, Accuracy: 0.8931


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.78it/s, loss=0.2582]


Epoch 3/15 - Loss: 0.2550, Accuracy: 0.8933


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.87it/s, loss=0.3369]


Epoch 4/15 - Loss: 0.2540, Accuracy: 0.8940


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.63it/s, loss=0.2084]


Epoch 5/15 - Loss: 0.2532, Accuracy: 0.8935


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.37it/s, loss=0.1452]


Epoch 6/15 - Loss: 0.2528, Accuracy: 0.8941


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.56it/s, loss=0.3839]


Epoch 7/15 - Loss: 0.2522, Accuracy: 0.8940


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.37it/s, loss=0.2521]


Epoch 8/15 - Loss: 0.2521, Accuracy: 0.8943


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.77it/s, loss=0.2232]


Epoch 9/15 - Loss: 0.2515, Accuracy: 0.8948


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.43it/s, loss=0.2240]


Epoch 10/15 - Loss: 0.2519, Accuracy: 0.8946


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.63it/s, loss=0.2107]


Epoch 11/15 - Loss: 0.2506, Accuracy: 0.8948


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.88it/s, loss=0.2323]


Epoch 12/15 - Loss: 0.2503, Accuracy: 0.8951


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.59it/s, loss=0.2906]


Epoch 13/15 - Loss: 0.2505, Accuracy: 0.8954


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.69it/s, loss=0.2447]


Epoch 14/15 - Loss: 0.2503, Accuracy: 0.8950


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.63it/s, loss=0.2395]


Epoch 15/15 - Loss: 0.2493, Accuracy: 0.8951
Fold 10 Accuracy: 0.8610
Complete model saved to UNSW-CEloss1.pth
Fold Accuracies:
  Fold 1: 0.8125
  Fold 2: 0.8263
  Fold 3: 0.8301
  Fold 4: 0.8323
  Fold 5: 0.8412
  Fold 6: 0.8439
  Fold 7: 0.8472
  Fold 8: 0.8524
  Fold 9: 0.8559
  Fold 10: 0.8610


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  37    0   22  165   28    0   16    0    0    0]
 [   0   34   31  130   35    0    1    1    0    0]
 [   0    1  397 1165   36    5   11   10    9    1]
 [   0    5  239 3968  101   15   39   72   10    3]
 [   0    0   37  193 1748    3  430    7    7    0]
 [   0    0    5   36    1 5840    3    2    0    0]
 [   4    0    5   35  341    1 8905    5    4    0]
 [   0    0   44  216    1    1    3 1134    0    0]
 [   0    1    1   17    7    1   10   10  104    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.90      0.14      0.24       268
      Backdoor       0.83      0.15      0.25       232
           DoS       0.51      0.24      0.33      1635
      Exploits       0.67      0.89      0.76      4452
       Fuzzers       0.76      0.72      0.74      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.