In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        # self.att_gate = nn.Sequential(
        #     nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
        #     nn.GELU(),
        #     nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
        #     nn.Sigmoid()
        # )

        # 残差连接
        # self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        # res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        # att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        # attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return lstm_out                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        # self.lstm = BiResAttLSTM(
        #     input_size=48,
        #     hidden_size=hidden_size,
        #     num_layers=2,
        #     dropout=0.2
        # )

        # Transformer 编码器
        # self.transformer_encoder = nn.TransformerEncoder(
        #     nn.TransformerEncoderLayer(
        #         d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
        #         nhead=4,
        #         dim_feedforward=256,
        #         batch_first=True,
        #         activation=F.gelu
        #     ),
        #     num_layers=2
        # )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * 48, 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        # lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        # trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(x)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-PCNN.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
Epoch 1/15: 100%|██████████| 4929/4929 [00:24<00:00, 201.83it/s, loss=0.2318]


Epoch 1/15 - Loss: 0.5029, Accuracy: 0.8135


Epoch 2/15: 100%|██████████| 4929/4929 [00:22<00:00, 222.15it/s, loss=0.2776]


Epoch 2/15 - Loss: 0.4122, Accuracy: 0.8418


Epoch 3/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.15it/s, loss=0.1945]


Epoch 3/15 - Loss: 0.3930, Accuracy: 0.8479


Epoch 4/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.39it/s, loss=0.4606]


Epoch 4/15 - Loss: 0.3828, Accuracy: 0.8501


Epoch 5/15: 100%|██████████| 4929/4929 [00:22<00:00, 221.79it/s, loss=0.4419]


Epoch 5/15 - Loss: 0.3752, Accuracy: 0.8522


Epoch 6/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.34it/s, loss=0.2077]


Epoch 6/15 - Loss: 0.3698, Accuracy: 0.8541


Epoch 7/15: 100%|██████████| 4929/4929 [00:22<00:00, 223.34it/s, loss=0.2855]


Epoch 7/15 - Loss: 0.3650, Accuracy: 0.8554


Epoch 8/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.31it/s, loss=0.6104]


Epoch 8/15 - Loss: 0.3613, Accuracy: 0.8565


Epoch 9/15: 100%|██████████| 4929/4929 [00:22<00:00, 221.25it/s, loss=0.2468]


Epoch 9/15 - Loss: 0.3573, Accuracy: 0.8577


Epoch 10/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.67it/s, loss=0.3985]


Epoch 10/15 - Loss: 0.3548, Accuracy: 0.8581


Epoch 11/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.30it/s, loss=0.6556]


Epoch 11/15 - Loss: 0.3529, Accuracy: 0.8585


Epoch 12/15: 100%|██████████| 4929/4929 [00:23<00:00, 214.25it/s, loss=0.2399]


Epoch 12/15 - Loss: 0.3508, Accuracy: 0.8599


Epoch 13/15: 100%|██████████| 4929/4929 [00:22<00:00, 215.40it/s, loss=0.3316]


Epoch 13/15 - Loss: 0.3490, Accuracy: 0.8597


Epoch 14/15: 100%|██████████| 4929/4929 [00:22<00:00, 217.16it/s, loss=0.4181]


Epoch 14/15 - Loss: 0.3474, Accuracy: 0.8603


Epoch 15/15: 100%|██████████| 4929/4929 [00:22<00:00, 214.61it/s, loss=0.2726]


Epoch 15/15 - Loss: 0.3451, Accuracy: 0.8611
Fold 1 Accuracy: 0.8067
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.89it/s, loss=0.4162]


Epoch 1/15 - Loss: 0.3477, Accuracy: 0.8606


Epoch 2/15: 100%|██████████| 4929/4929 [00:22<00:00, 215.56it/s, loss=0.4307]


Epoch 2/15 - Loss: 0.3444, Accuracy: 0.8615


Epoch 3/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.18it/s, loss=0.3540]


Epoch 3/15 - Loss: 0.3429, Accuracy: 0.8619


Epoch 4/15: 100%|██████████| 4929/4929 [00:22<00:00, 217.75it/s, loss=0.2995]


Epoch 4/15 - Loss: 0.3415, Accuracy: 0.8623


Epoch 5/15: 100%|██████████| 4929/4929 [00:22<00:00, 218.19it/s, loss=0.4151]


Epoch 5/15 - Loss: 0.3403, Accuracy: 0.8627


Epoch 6/15: 100%|██████████| 4929/4929 [00:22<00:00, 216.23it/s, loss=0.3478]


Epoch 6/15 - Loss: 0.3393, Accuracy: 0.8630


Epoch 7/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.77it/s, loss=0.3819]


Epoch 7/15 - Loss: 0.3377, Accuracy: 0.8635


Epoch 8/15: 100%|██████████| 4929/4929 [00:22<00:00, 216.26it/s, loss=0.2508]


Epoch 8/15 - Loss: 0.3371, Accuracy: 0.8634


Epoch 9/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.56it/s, loss=0.2057]


Epoch 9/15 - Loss: 0.3367, Accuracy: 0.8638


Epoch 10/15: 100%|██████████| 4929/4929 [00:22<00:00, 218.37it/s, loss=0.3053]


Epoch 10/15 - Loss: 0.3353, Accuracy: 0.8639


Epoch 11/15: 100%|██████████| 4929/4929 [00:22<00:00, 222.11it/s, loss=0.3495]


Epoch 11/15 - Loss: 0.3346, Accuracy: 0.8641


Epoch 12/15: 100%|██████████| 4929/4929 [00:22<00:00, 216.36it/s, loss=0.3001]


Epoch 12/15 - Loss: 0.3332, Accuracy: 0.8647


Epoch 13/15: 100%|██████████| 4929/4929 [00:22<00:00, 217.40it/s, loss=0.3044]


Epoch 13/15 - Loss: 0.3328, Accuracy: 0.8650


Epoch 14/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.99it/s, loss=0.3394]


Epoch 14/15 - Loss: 0.3318, Accuracy: 0.8651


Epoch 15/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.36it/s, loss=0.2633]


Epoch 15/15 - Loss: 0.3312, Accuracy: 0.8652
Fold 2 Accuracy: 0.8145
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:22<00:00, 218.93it/s, loss=0.2689]


Epoch 1/15 - Loss: 0.3346, Accuracy: 0.8646


Epoch 2/15: 100%|██████████| 4929/4929 [00:22<00:00, 217.12it/s, loss=0.4343]


Epoch 2/15 - Loss: 0.3326, Accuracy: 0.8652


Epoch 3/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.01it/s, loss=0.3876]


Epoch 3/15 - Loss: 0.3321, Accuracy: 0.8652


Epoch 4/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.58it/s, loss=0.3010]


Epoch 4/15 - Loss: 0.3309, Accuracy: 0.8655


Epoch 5/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.29it/s, loss=0.3589]


Epoch 5/15 - Loss: 0.3305, Accuracy: 0.8660


Epoch 6/15: 100%|██████████| 4929/4929 [00:29<00:00, 165.56it/s, loss=0.3472]


Epoch 6/15 - Loss: 0.3300, Accuracy: 0.8653


Epoch 7/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.27it/s, loss=0.4953]


Epoch 7/15 - Loss: 0.3289, Accuracy: 0.8658


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 170.84it/s, loss=0.3049]


Epoch 8/15 - Loss: 0.3283, Accuracy: 0.8662


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.81it/s, loss=0.3997]


Epoch 9/15 - Loss: 0.3279, Accuracy: 0.8666


Epoch 10/15: 100%|██████████| 4929/4929 [00:28<00:00, 170.14it/s, loss=0.3425]


Epoch 10/15 - Loss: 0.3268, Accuracy: 0.8673


Epoch 11/15: 100%|██████████| 4929/4929 [00:29<00:00, 169.51it/s, loss=0.2397]


Epoch 11/15 - Loss: 0.3264, Accuracy: 0.8668


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 182.32it/s, loss=0.3223]


Epoch 12/15 - Loss: 0.3262, Accuracy: 0.8670


Epoch 13/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.67it/s, loss=0.3407]


Epoch 13/15 - Loss: 0.3253, Accuracy: 0.8668


Epoch 14/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.88it/s, loss=0.3235]


Epoch 14/15 - Loss: 0.3251, Accuracy: 0.8672


Epoch 15/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.88it/s, loss=0.4286]


Epoch 15/15 - Loss: 0.3239, Accuracy: 0.8673
Fold 3 Accuracy: 0.8226
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.72it/s, loss=0.3628]


Epoch 1/15 - Loss: 0.3259, Accuracy: 0.8673


Epoch 2/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.03it/s, loss=0.3839]


Epoch 2/15 - Loss: 0.3244, Accuracy: 0.8678


Epoch 3/15: 100%|██████████| 4929/4929 [00:45<00:00, 108.14it/s, loss=0.3832]


Epoch 3/15 - Loss: 0.3241, Accuracy: 0.8676


Epoch 4/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.89it/s, loss=0.3485]


Epoch 4/15 - Loss: 0.3235, Accuracy: 0.8680


Epoch 5/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.94it/s, loss=0.3162]


Epoch 5/15 - Loss: 0.3225, Accuracy: 0.8685


Epoch 6/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.09it/s, loss=0.3850]


Epoch 6/15 - Loss: 0.3219, Accuracy: 0.8685


Epoch 7/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.62it/s, loss=0.3366]


Epoch 7/15 - Loss: 0.3224, Accuracy: 0.8687


Epoch 8/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.38it/s, loss=0.2195]


Epoch 8/15 - Loss: 0.3218, Accuracy: 0.8687


Epoch 9/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.70it/s, loss=0.4659]


Epoch 9/15 - Loss: 0.3214, Accuracy: 0.8686


Epoch 10/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.99it/s, loss=0.2466]


Epoch 10/15 - Loss: 0.3200, Accuracy: 0.8689


Epoch 11/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.31it/s, loss=0.2196]


Epoch 11/15 - Loss: 0.3204, Accuracy: 0.8692


Epoch 12/15: 100%|██████████| 4929/4929 [00:45<00:00, 109.13it/s, loss=0.2859]


Epoch 12/15 - Loss: 0.3192, Accuracy: 0.8694


Epoch 13/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.58it/s, loss=0.3147]


Epoch 13/15 - Loss: 0.3195, Accuracy: 0.8692


Epoch 14/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.27it/s, loss=0.2829]


Epoch 14/15 - Loss: 0.3188, Accuracy: 0.8698


Epoch 15/15: 100%|██████████| 4929/4929 [00:45<00:00, 109.41it/s, loss=0.3220]


Epoch 15/15 - Loss: 0.3191, Accuracy: 0.8693
Fold 4 Accuracy: 0.8222
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.98it/s, loss=0.3488]


Epoch 1/15 - Loss: 0.3209, Accuracy: 0.8690


Epoch 2/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.56it/s, loss=0.2986]


Epoch 2/15 - Loss: 0.3202, Accuracy: 0.8686


Epoch 3/15: 100%|██████████| 4929/4929 [00:43<00:00, 114.33it/s, loss=0.2460]


Epoch 3/15 - Loss: 0.3190, Accuracy: 0.8693


Epoch 4/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.63it/s, loss=0.2796]


Epoch 4/15 - Loss: 0.3192, Accuracy: 0.8694


Epoch 5/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.23it/s, loss=0.4017]


Epoch 5/15 - Loss: 0.3190, Accuracy: 0.8694


Epoch 6/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.89it/s, loss=0.4262]


Epoch 6/15 - Loss: 0.3185, Accuracy: 0.8693


Epoch 7/15: 100%|██████████| 4929/4929 [00:44<00:00, 109.84it/s, loss=0.1849]


Epoch 7/15 - Loss: 0.3182, Accuracy: 0.8697


Epoch 8/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.49it/s, loss=0.4795]


Epoch 8/15 - Loss: 0.3174, Accuracy: 0.8698


Epoch 9/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.37it/s, loss=0.2690]


Epoch 9/15 - Loss: 0.3173, Accuracy: 0.8697


Epoch 10/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.66it/s, loss=0.2771]


Epoch 10/15 - Loss: 0.3164, Accuracy: 0.8700


Epoch 11/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.17it/s, loss=0.2819]


Epoch 11/15 - Loss: 0.3165, Accuracy: 0.8703


Epoch 12/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.87it/s, loss=0.2386]


Epoch 12/15 - Loss: 0.3158, Accuracy: 0.8709


Epoch 13/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.04it/s, loss=0.4244]


Epoch 13/15 - Loss: 0.3156, Accuracy: 0.8707


Epoch 14/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.61it/s, loss=0.2706]


Epoch 14/15 - Loss: 0.3155, Accuracy: 0.8702


Epoch 15/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.36it/s, loss=0.4650]


Epoch 15/15 - Loss: 0.3151, Accuracy: 0.8709
Fold 5 Accuracy: 0.8245
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:45<00:00, 108.04it/s, loss=0.5295]


Epoch 1/15 - Loss: 0.3169, Accuracy: 0.8700


Epoch 2/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.02it/s, loss=0.3274]


Epoch 2/15 - Loss: 0.3154, Accuracy: 0.8704


Epoch 3/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.69it/s, loss=0.1969]


Epoch 3/15 - Loss: 0.3156, Accuracy: 0.8706


Epoch 4/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.84it/s, loss=0.2433]


Epoch 4/15 - Loss: 0.3150, Accuracy: 0.8709


Epoch 5/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.22it/s, loss=0.2924]


Epoch 5/15 - Loss: 0.3149, Accuracy: 0.8708


Epoch 6/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.73it/s, loss=0.2201]


Epoch 6/15 - Loss: 0.3144, Accuracy: 0.8709


Epoch 7/15: 100%|██████████| 4929/4929 [00:22<00:00, 223.64it/s, loss=0.2504]


Epoch 7/15 - Loss: 0.3138, Accuracy: 0.8711


Epoch 8/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.54it/s, loss=0.3494]


Epoch 8/15 - Loss: 0.3134, Accuracy: 0.8708


Epoch 9/15: 100%|██████████| 4929/4929 [00:21<00:00, 227.41it/s, loss=0.2506]


Epoch 9/15 - Loss: 0.3133, Accuracy: 0.8712


Epoch 10/15: 100%|██████████| 4929/4929 [00:22<00:00, 223.77it/s, loss=0.2581]


Epoch 10/15 - Loss: 0.3127, Accuracy: 0.8714


Epoch 11/15: 100%|██████████| 4929/4929 [00:21<00:00, 226.31it/s, loss=0.3899]


Epoch 11/15 - Loss: 0.3132, Accuracy: 0.8712


Epoch 12/15: 100%|██████████| 4929/4929 [00:21<00:00, 225.06it/s, loss=0.2981]


Epoch 12/15 - Loss: 0.3123, Accuracy: 0.8718


Epoch 13/15: 100%|██████████| 4929/4929 [00:21<00:00, 225.35it/s, loss=0.3564]


Epoch 13/15 - Loss: 0.3119, Accuracy: 0.8719


Epoch 14/15: 100%|██████████| 4929/4929 [00:21<00:00, 228.35it/s, loss=0.2387]


Epoch 14/15 - Loss: 0.3122, Accuracy: 0.8717


Epoch 15/15: 100%|██████████| 4929/4929 [00:22<00:00, 223.38it/s, loss=0.2641]


Epoch 15/15 - Loss: 0.3116, Accuracy: 0.8716
Fold 6 Accuracy: 0.8275
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:22<00:00, 223.18it/s, loss=0.4505]


Epoch 1/15 - Loss: 0.3122, Accuracy: 0.8717


Epoch 2/15: 100%|██████████| 4929/4929 [00:21<00:00, 228.40it/s, loss=0.3818]


Epoch 2/15 - Loss: 0.3112, Accuracy: 0.8716


Epoch 3/15: 100%|██████████| 4929/4929 [00:22<00:00, 222.93it/s, loss=0.2225]


Epoch 3/15 - Loss: 0.3113, Accuracy: 0.8721


Epoch 4/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.02it/s, loss=0.6208]


Epoch 4/15 - Loss: 0.3105, Accuracy: 0.8725


Epoch 5/15: 100%|██████████| 4929/4929 [00:22<00:00, 220.32it/s, loss=0.2316]


Epoch 5/15 - Loss: 0.3101, Accuracy: 0.8724


Epoch 6/15: 100%|██████████| 4929/4929 [00:29<00:00, 167.60it/s, loss=0.2752]


Epoch 6/15 - Loss: 0.3098, Accuracy: 0.8723


Epoch 7/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.29it/s, loss=0.4806]


Epoch 7/15 - Loss: 0.3093, Accuracy: 0.8722


Epoch 8/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.02it/s, loss=0.2557]


Epoch 8/15 - Loss: 0.3098, Accuracy: 0.8723


Epoch 9/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.51it/s, loss=0.2764]


Epoch 9/15 - Loss: 0.3095, Accuracy: 0.8724


Epoch 10/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.92it/s, loss=0.2220]


Epoch 10/15 - Loss: 0.3092, Accuracy: 0.8724


Epoch 11/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.24it/s, loss=0.3476]


Epoch 11/15 - Loss: 0.3092, Accuracy: 0.8723


Epoch 12/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.41it/s, loss=0.2607]


Epoch 12/15 - Loss: 0.3087, Accuracy: 0.8727


Epoch 13/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.65it/s, loss=0.2623]


Epoch 13/15 - Loss: 0.3082, Accuracy: 0.8729


Epoch 14/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.09it/s, loss=0.3960]


Epoch 14/15 - Loss: 0.3082, Accuracy: 0.8730


Epoch 15/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.46it/s, loss=0.3586]


Epoch 15/15 - Loss: 0.3080, Accuracy: 0.8734
Fold 7 Accuracy: 0.8242
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.44it/s, loss=0.3760]


Epoch 1/15 - Loss: 0.3099, Accuracy: 0.8723


Epoch 2/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.80it/s, loss=0.2695]


Epoch 2/15 - Loss: 0.3094, Accuracy: 0.8723


Epoch 3/15: 100%|██████████| 4929/4929 [00:44<00:00, 111.97it/s, loss=0.2944]


Epoch 3/15 - Loss: 0.3086, Accuracy: 0.8735


Epoch 4/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.08it/s, loss=0.2083]


Epoch 4/15 - Loss: 0.3083, Accuracy: 0.8733


Epoch 5/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.60it/s, loss=0.4818]


Epoch 5/15 - Loss: 0.3080, Accuracy: 0.8727


Epoch 6/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.87it/s, loss=0.2063]


Epoch 6/15 - Loss: 0.3078, Accuracy: 0.8734


Epoch 7/15: 100%|██████████| 4929/4929 [00:43<00:00, 114.52it/s, loss=0.2448]


Epoch 7/15 - Loss: 0.3076, Accuracy: 0.8732


Epoch 8/15: 100%|██████████| 4929/4929 [00:43<00:00, 114.53it/s, loss=0.4122]


Epoch 8/15 - Loss: 0.3075, Accuracy: 0.8736


Epoch 9/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.74it/s, loss=0.3240]


Epoch 9/15 - Loss: 0.3075, Accuracy: 0.8734


Epoch 10/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.90it/s, loss=0.1663]


Epoch 10/15 - Loss: 0.3068, Accuracy: 0.8736


Epoch 11/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.31it/s, loss=0.4085]


Epoch 11/15 - Loss: 0.3063, Accuracy: 0.8733


Epoch 12/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.31it/s, loss=0.3971]


Epoch 12/15 - Loss: 0.3065, Accuracy: 0.8739


Epoch 13/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.77it/s, loss=0.2505]


Epoch 13/15 - Loss: 0.3071, Accuracy: 0.8735


Epoch 14/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.31it/s, loss=0.2086]


Epoch 14/15 - Loss: 0.3063, Accuracy: 0.8739


Epoch 15/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.41it/s, loss=0.2980]


Epoch 15/15 - Loss: 0.3056, Accuracy: 0.8741
Fold 8 Accuracy: 0.8276
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.21it/s, loss=0.1906]


Epoch 1/15 - Loss: 0.3069, Accuracy: 0.8736


Epoch 2/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.80it/s, loss=0.2545]


Epoch 2/15 - Loss: 0.3070, Accuracy: 0.8738


Epoch 3/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.17it/s, loss=0.3266]


Epoch 3/15 - Loss: 0.3059, Accuracy: 0.8736


Epoch 4/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.41it/s, loss=0.2842]


Epoch 4/15 - Loss: 0.3062, Accuracy: 0.8737


Epoch 5/15: 100%|██████████| 4929/4929 [00:34<00:00, 142.87it/s, loss=0.5208]


Epoch 5/15 - Loss: 0.3049, Accuracy: 0.8745


Epoch 6/15: 100%|██████████| 4929/4929 [00:20<00:00, 235.65it/s, loss=0.3817]


Epoch 6/15 - Loss: 0.3054, Accuracy: 0.8742


Epoch 7/15: 100%|██████████| 4929/4929 [00:34<00:00, 141.57it/s, loss=0.3522]


Epoch 7/15 - Loss: 0.3051, Accuracy: 0.8742


Epoch 8/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.43it/s, loss=0.3077]


Epoch 8/15 - Loss: 0.3048, Accuracy: 0.8745


Epoch 9/15: 100%|██████████| 4929/4929 [00:26<00:00, 184.50it/s, loss=0.2511]


Epoch 9/15 - Loss: 0.3056, Accuracy: 0.8745


Epoch 10/15: 100%|██████████| 4929/4929 [00:25<00:00, 192.79it/s, loss=0.5220]


Epoch 10/15 - Loss: 0.3045, Accuracy: 0.8746


Epoch 11/15: 100%|██████████| 4929/4929 [00:25<00:00, 193.99it/s, loss=0.2500]


Epoch 11/15 - Loss: 0.3043, Accuracy: 0.8743


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.65it/s, loss=0.2128]


Epoch 12/15 - Loss: 0.3041, Accuracy: 0.8743


Epoch 13/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.62it/s, loss=0.2242]


Epoch 13/15 - Loss: 0.3041, Accuracy: 0.8746


Epoch 14/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.24it/s, loss=0.2555]


Epoch 14/15 - Loss: 0.3040, Accuracy: 0.8747


Epoch 15/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.12it/s, loss=0.4073]


Epoch 15/15 - Loss: 0.3040, Accuracy: 0.8748
Fold 9 Accuracy: 0.8319
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:30<00:00, 160.91it/s, loss=0.3655]


Epoch 1/15 - Loss: 0.3047, Accuracy: 0.8734


Epoch 2/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.08it/s, loss=0.2428]


Epoch 2/15 - Loss: 0.3047, Accuracy: 0.8743


Epoch 3/15: 100%|██████████| 4929/4929 [00:26<00:00, 186.83it/s, loss=0.2553]


Epoch 3/15 - Loss: 0.3043, Accuracy: 0.8746


Epoch 4/15: 100%|██████████| 4929/4929 [00:30<00:00, 163.88it/s, loss=0.1918]


Epoch 4/15 - Loss: 0.3044, Accuracy: 0.8739


Epoch 5/15: 100%|██████████| 4929/4929 [00:30<00:00, 160.77it/s, loss=0.4184]


Epoch 5/15 - Loss: 0.3041, Accuracy: 0.8746


Epoch 6/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.39it/s, loss=0.2851]


Epoch 6/15 - Loss: 0.3042, Accuracy: 0.8741


Epoch 7/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.56it/s, loss=0.2701]


Epoch 7/15 - Loss: 0.3033, Accuracy: 0.8744


Epoch 8/15: 100%|██████████| 4929/4929 [00:26<00:00, 183.87it/s, loss=0.2819]


Epoch 8/15 - Loss: 0.3033, Accuracy: 0.8750


Epoch 9/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.59it/s, loss=0.2424]


Epoch 9/15 - Loss: 0.3032, Accuracy: 0.8745


Epoch 10/15: 100%|██████████| 4929/4929 [00:29<00:00, 168.74it/s, loss=0.4320]


Epoch 10/15 - Loss: 0.3034, Accuracy: 0.8745


Epoch 11/15: 100%|██████████| 4929/4929 [00:29<00:00, 168.36it/s, loss=0.1786]


Epoch 11/15 - Loss: 0.3029, Accuracy: 0.8747


Epoch 12/15: 100%|██████████| 4929/4929 [00:26<00:00, 183.39it/s, loss=0.4012]


Epoch 12/15 - Loss: 0.3026, Accuracy: 0.8747


Epoch 13/15: 100%|██████████| 4929/4929 [00:29<00:00, 166.98it/s, loss=0.3977]


Epoch 13/15 - Loss: 0.3023, Accuracy: 0.8748


Epoch 14/15: 100%|██████████| 4929/4929 [00:22<00:00, 219.94it/s, loss=0.6419]


Epoch 14/15 - Loss: 0.3022, Accuracy: 0.8757


Epoch 15/15: 100%|██████████| 4929/4929 [00:22<00:00, 218.27it/s, loss=0.3279]


Epoch 15/15 - Loss: 0.3024, Accuracy: 0.8752
Fold 10 Accuracy: 0.8348
Complete model saved to UNSW-PCNN.pth
Fold Accuracies:
  Fold 1: 0.8067
  Fold 2: 0.8145
  Fold 3: 0.8226
  Fold 4: 0.8222
  Fold 5: 0.8245
  Fold 6: 0.8275
  Fold 7: 0.8242
  Fold 8: 0.8276
  Fold 9: 0.8319
  Fold 10: 0.8348


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  20    0   24  166   29    0   29    0    0    0]
 [   0   22   33  148   26    0    1    0    2    0]
 [   0    0  326 1223   39    9   15   12   10    1]
 [   0    4  283 3838  109   12   76   98   15   17]
 [   0    0   42  188 1472    0  699   11    7    6]
 [   0    0   10   62    2 5802    8    2    1    0]
 [   2    0    3   50  391    0 8834   13    5    2]
 [   0    1   47  246    6    0    4 1093    2    0]
 [   0    0    1   13   17    2   20   12   86    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.91      0.07      0.14       268
      Backdoor       0.81      0.09      0.17       232
           DoS       0.42      0.20      0.27      1635
      Exploits       0.65      0.86      0.74      4452
       Fuzzers       0.70      0.61      0.65      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.