In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=2
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-NB-PCNN-AttBiLSTM-Transformer-2fold.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 175249 train samples, 128837 validation samples


Epoch 1/15:   0%|          | 0/2739 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 2739/2739 [00:27<00:00, 98.70it/s, loss=0.4318] 


Epoch 1/15 - Loss: 0.4995, Accuracy: 0.8134


Epoch 2/15: 100%|██████████| 2739/2739 [00:27<00:00, 100.59it/s, loss=0.1598]


Epoch 2/15 - Loss: 0.4064, Accuracy: 0.8414


Epoch 3/15: 100%|██████████| 2739/2739 [00:31<00:00, 87.75it/s, loss=0.4820]


Epoch 3/15 - Loss: 0.3894, Accuracy: 0.8469


Epoch 4/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.16it/s, loss=0.3590]


Epoch 4/15 - Loss: 0.3773, Accuracy: 0.8504


Epoch 5/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.96it/s, loss=0.2830]


Epoch 5/15 - Loss: 0.3700, Accuracy: 0.8532


Epoch 6/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.31it/s, loss=0.3812]


Epoch 6/15 - Loss: 0.3627, Accuracy: 0.8552


Epoch 7/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.28it/s, loss=0.3494]


Epoch 7/15 - Loss: 0.3575, Accuracy: 0.8564


Epoch 8/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.36it/s, loss=0.2129]


Epoch 8/15 - Loss: 0.3520, Accuracy: 0.8577


Epoch 9/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.54it/s, loss=0.1900]


Epoch 9/15 - Loss: 0.3480, Accuracy: 0.8593


Epoch 10/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.32it/s, loss=0.0726]


Epoch 10/15 - Loss: 0.3449, Accuracy: 0.8597


Epoch 11/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.76it/s, loss=0.6386]


Epoch 11/15 - Loss: 0.3415, Accuracy: 0.8614


Epoch 12/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.10it/s, loss=0.2842]


Epoch 12/15 - Loss: 0.3383, Accuracy: 0.8624


Epoch 13/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.49it/s, loss=0.0558]


Epoch 13/15 - Loss: 0.3336, Accuracy: 0.8642


Epoch 14/15: 100%|██████████| 2739/2739 [00:32<00:00, 84.73it/s, loss=0.2292]


Epoch 14/15 - Loss: 0.3315, Accuracy: 0.8648


Epoch 15/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.18it/s, loss=0.1984]


Epoch 15/15 - Loss: 0.3302, Accuracy: 0.8650
Fold 1 Accuracy: 0.8122
Fold 2: 175250 train samples, 128836 validation samples


Epoch 1/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.85it/s, loss=0.2148]


Epoch 1/15 - Loss: 0.3571, Accuracy: 0.8578


Epoch 2/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.13it/s, loss=0.3236]


Epoch 2/15 - Loss: 0.3434, Accuracy: 0.8616


Epoch 3/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.78it/s, loss=0.3113]


Epoch 3/15 - Loss: 0.3377, Accuracy: 0.8630


Epoch 4/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.30it/s, loss=0.2003]


Epoch 4/15 - Loss: 0.3344, Accuracy: 0.8640


Epoch 5/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.07it/s, loss=0.3154]


Epoch 5/15 - Loss: 0.3305, Accuracy: 0.8647


Epoch 6/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.40it/s, loss=0.6083]


Epoch 6/15 - Loss: 0.3272, Accuracy: 0.8663


Epoch 7/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.69it/s, loss=0.3390]


Epoch 7/15 - Loss: 0.3251, Accuracy: 0.8669


Epoch 8/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.30it/s, loss=0.2898]


Epoch 8/15 - Loss: 0.3234, Accuracy: 0.8673


Epoch 9/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.51it/s, loss=0.1990]


Epoch 9/15 - Loss: 0.3220, Accuracy: 0.8679


Epoch 10/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.71it/s, loss=0.3487]


Epoch 10/15 - Loss: 0.3191, Accuracy: 0.8687


Epoch 11/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.13it/s, loss=0.1384]


Epoch 11/15 - Loss: 0.3177, Accuracy: 0.8695


Epoch 12/15: 100%|██████████| 2739/2739 [00:31<00:00, 86.03it/s, loss=0.2652]


Epoch 12/15 - Loss: 0.3156, Accuracy: 0.8701


Epoch 13/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.48it/s, loss=0.2307]


Epoch 13/15 - Loss: 0.3146, Accuracy: 0.8708


Epoch 14/15: 100%|██████████| 2739/2739 [00:31<00:00, 85.92it/s, loss=0.3062]


Epoch 14/15 - Loss: 0.3129, Accuracy: 0.8703


Epoch 15/15: 100%|██████████| 2739/2739 [00:32<00:00, 85.39it/s, loss=0.1779]


Epoch 15/15 - Loss: 0.3110, Accuracy: 0.8713
Fold 2 Accuracy: 0.8210
Complete model saved to UNSW-NB-PCNN-AttBiLSTM-Transformer-2fold.pth
Fold Accuracies:
  Fold 1: 0.8122
  Fold 2: 0.8210


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[   70     3    11   922   111     0   222     0     0     0]
 [    0    76    26   911   115     2    12     7    13     2]
 [    1    16   438  7201   188    52   130    65    78     8]
 [    0    18   289 20033   463    72   672   530    80   105]
 [    0     6    27  1316  6757    13  3817   108    64    15]
 [    0     4    33   468    41 28843    29     6     8     3]
 [    0     0    42   286  2279     8 43651   162    65     7]
 [    0     4    29  1437    37     4    82  5393     6     2]
 [    0     0     5   106    64     8    66    54   450     2]
 [    0     0     0    22     3     0     3     0     2    57]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.99      0.05      0.10      1339
      Backdoor       0.60      0.07      0.12      1164
           DoS       0.49      0.05      0.10      8177
      Exploits       0.61      0.90      0.73     22262
       Fuzzers       0.67      0.56