In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=6
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-NB-PCNN-AttBiLSTM-Transformer-6fold.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 292082 train samples, 42946 validation samples


Epoch 1/15:   0%|          | 0/4564 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4564/4564 [00:52<00:00, 87.63it/s, loss=0.4500]


Epoch 1/15 - Loss: 0.4736, Accuracy: 0.8217


Epoch 2/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.81it/s, loss=0.2806]


Epoch 2/15 - Loss: 0.3899, Accuracy: 0.8480


Epoch 3/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.39it/s, loss=0.3614]


Epoch 3/15 - Loss: 0.3717, Accuracy: 0.8534


Epoch 4/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.39it/s, loss=0.3798]


Epoch 4/15 - Loss: 0.3602, Accuracy: 0.8570


Epoch 5/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.08it/s, loss=0.3131]


Epoch 5/15 - Loss: 0.3528, Accuracy: 0.8594


Epoch 6/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.09it/s, loss=0.3419]


Epoch 6/15 - Loss: 0.3481, Accuracy: 0.8607


Epoch 7/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.02it/s, loss=0.3213]


Epoch 7/15 - Loss: 0.3432, Accuracy: 0.8621


Epoch 8/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.36it/s, loss=0.3101]


Epoch 8/15 - Loss: 0.3395, Accuracy: 0.8625


Epoch 9/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.23it/s, loss=0.3474]


Epoch 9/15 - Loss: 0.3365, Accuracy: 0.8631


Epoch 10/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.22it/s, loss=0.3539]


Epoch 10/15 - Loss: 0.3334, Accuracy: 0.8645


Epoch 11/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.52it/s, loss=0.1544]


Epoch 11/15 - Loss: 0.3310, Accuracy: 0.8653


Epoch 12/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.23it/s, loss=0.3471]


Epoch 12/15 - Loss: 0.3286, Accuracy: 0.8661


Epoch 13/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.32it/s, loss=0.3003]


Epoch 13/15 - Loss: 0.3267, Accuracy: 0.8666


Epoch 14/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.25it/s, loss=0.3477]


Epoch 14/15 - Loss: 0.3239, Accuracy: 0.8678


Epoch 15/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.19it/s, loss=0.3679]


Epoch 15/15 - Loss: 0.3225, Accuracy: 0.8677
Fold 1 Accuracy: 0.8170
Fold 2: 292082 train samples, 42946 validation samples


Epoch 1/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.33it/s, loss=0.2775]


Epoch 1/15 - Loss: 0.3278, Accuracy: 0.8661


Epoch 2/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.25it/s, loss=0.2802]


Epoch 2/15 - Loss: 0.3219, Accuracy: 0.8677


Epoch 3/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.32it/s, loss=0.3128]


Epoch 3/15 - Loss: 0.3202, Accuracy: 0.8688


Epoch 4/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.50it/s, loss=0.1882]


Epoch 4/15 - Loss: 0.3186, Accuracy: 0.8686


Epoch 5/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.39it/s, loss=0.1943]


Epoch 5/15 - Loss: 0.3164, Accuracy: 0.8705


Epoch 6/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.60it/s, loss=0.2091]


Epoch 6/15 - Loss: 0.3154, Accuracy: 0.8705


Epoch 7/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.15it/s, loss=0.3359]


Epoch 7/15 - Loss: 0.3137, Accuracy: 0.8706


Epoch 8/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.35it/s, loss=0.1974]


Epoch 8/15 - Loss: 0.3120, Accuracy: 0.8716


Epoch 9/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.32it/s, loss=0.3311]


Epoch 9/15 - Loss: 0.3105, Accuracy: 0.8723


Epoch 10/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.46it/s, loss=0.1932]


Epoch 10/15 - Loss: 0.3094, Accuracy: 0.8722


Epoch 11/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.42it/s, loss=0.2124]


Epoch 11/15 - Loss: 0.3074, Accuracy: 0.8732


Epoch 12/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.33it/s, loss=0.4288]


Epoch 12/15 - Loss: 0.3072, Accuracy: 0.8730


Epoch 13/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.29it/s, loss=0.2946]


Epoch 13/15 - Loss: 0.3053, Accuracy: 0.8736


Epoch 14/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.27it/s, loss=0.2464]


Epoch 14/15 - Loss: 0.3044, Accuracy: 0.8737


Epoch 15/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.25it/s, loss=0.2828]


Epoch 15/15 - Loss: 0.3035, Accuracy: 0.8746
Fold 2 Accuracy: 0.8277
Fold 3: 292082 train samples, 42946 validation samples


Epoch 1/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.29it/s, loss=0.3196]


Epoch 1/15 - Loss: 0.3066, Accuracy: 0.8738


Epoch 2/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.29it/s, loss=0.3071]


Epoch 2/15 - Loss: 0.3047, Accuracy: 0.8740


Epoch 3/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.63it/s, loss=0.2691]


Epoch 3/15 - Loss: 0.3036, Accuracy: 0.8744


Epoch 4/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.26it/s, loss=0.4726]


Epoch 4/15 - Loss: 0.3018, Accuracy: 0.8749


Epoch 5/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.88it/s, loss=0.4307]


Epoch 5/15 - Loss: 0.3007, Accuracy: 0.8754


Epoch 6/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.17it/s, loss=0.3568]


Epoch 6/15 - Loss: 0.2988, Accuracy: 0.8758


Epoch 7/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.04it/s, loss=0.2166]


Epoch 7/15 - Loss: 0.2986, Accuracy: 0.8759


Epoch 8/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.64it/s, loss=0.3801]


Epoch 8/15 - Loss: 0.2970, Accuracy: 0.8765


Epoch 9/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.01it/s, loss=0.1497]


Epoch 9/15 - Loss: 0.2960, Accuracy: 0.8771


Epoch 10/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.95it/s, loss=0.3616]


Epoch 10/15 - Loss: 0.2943, Accuracy: 0.8780


Epoch 11/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.11it/s, loss=0.2735]


Epoch 11/15 - Loss: 0.2943, Accuracy: 0.8777


Epoch 12/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.08it/s, loss=0.2081]


Epoch 12/15 - Loss: 0.2934, Accuracy: 0.8781


Epoch 13/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.77it/s, loss=0.1460]


Epoch 13/15 - Loss: 0.2927, Accuracy: 0.8781


Epoch 14/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.35it/s, loss=0.2802]


Epoch 14/15 - Loss: 0.2917, Accuracy: 0.8782


Epoch 15/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.03it/s, loss=0.1681]


Epoch 15/15 - Loss: 0.2912, Accuracy: 0.8793
Fold 3 Accuracy: 0.8301
Fold 4: 292083 train samples, 42945 validation samples


Epoch 1/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.18it/s, loss=0.2701]


Epoch 1/15 - Loss: 0.2962, Accuracy: 0.8772


Epoch 2/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.95it/s, loss=0.2083]


Epoch 2/15 - Loss: 0.2940, Accuracy: 0.8775


Epoch 3/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.08it/s, loss=0.2164]


Epoch 3/15 - Loss: 0.2920, Accuracy: 0.8782


Epoch 4/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.56it/s, loss=0.2417]


Epoch 4/15 - Loss: 0.2910, Accuracy: 0.8784


Epoch 5/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.24it/s, loss=0.4008]


Epoch 5/15 - Loss: 0.2896, Accuracy: 0.8794


Epoch 6/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.15it/s, loss=0.4245]


Epoch 6/15 - Loss: 0.2887, Accuracy: 0.8797


Epoch 7/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.12it/s, loss=0.2599]


Epoch 7/15 - Loss: 0.2881, Accuracy: 0.8794


Epoch 8/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.07it/s, loss=0.1620]


Epoch 8/15 - Loss: 0.2872, Accuracy: 0.8800


Epoch 9/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.58it/s, loss=0.2043]


Epoch 9/15 - Loss: 0.2864, Accuracy: 0.8803


Epoch 10/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.96it/s, loss=0.2862]


Epoch 10/15 - Loss: 0.2859, Accuracy: 0.8809


Epoch 11/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.10it/s, loss=0.2083]


Epoch 11/15 - Loss: 0.2846, Accuracy: 0.8811


Epoch 12/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.08it/s, loss=0.4621]


Epoch 12/15 - Loss: 0.2839, Accuracy: 0.8814


Epoch 13/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.35it/s, loss=0.1582]


Epoch 13/15 - Loss: 0.2833, Accuracy: 0.8816


Epoch 14/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.26it/s, loss=0.2274]


Epoch 14/15 - Loss: 0.2820, Accuracy: 0.8818


Epoch 15/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.66it/s, loss=0.3365]


Epoch 15/15 - Loss: 0.2811, Accuracy: 0.8828
Fold 4 Accuracy: 0.8333
Fold 5: 292083 train samples, 42945 validation samples


Epoch 1/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.96it/s, loss=0.3723]


Epoch 1/15 - Loss: 0.2884, Accuracy: 0.8798


Epoch 2/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.45it/s, loss=0.3227]


Epoch 2/15 - Loss: 0.2849, Accuracy: 0.8817


Epoch 3/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.14it/s, loss=0.1707]


Epoch 3/15 - Loss: 0.2842, Accuracy: 0.8812


Epoch 4/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.36it/s, loss=0.3756]


Epoch 4/15 - Loss: 0.2835, Accuracy: 0.8821


Epoch 5/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.09it/s, loss=0.2574]


Epoch 5/15 - Loss: 0.2830, Accuracy: 0.8819


Epoch 6/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.55it/s, loss=0.3422]


Epoch 6/15 - Loss: 0.2807, Accuracy: 0.8831


Epoch 7/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.30it/s, loss=0.2469]


Epoch 7/15 - Loss: 0.2807, Accuracy: 0.8826


Epoch 8/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.29it/s, loss=0.3059]


Epoch 8/15 - Loss: 0.2802, Accuracy: 0.8830


Epoch 9/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.08it/s, loss=0.2750]


Epoch 9/15 - Loss: 0.2790, Accuracy: 0.8830


Epoch 10/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.42it/s, loss=0.1937]


Epoch 10/15 - Loss: 0.2786, Accuracy: 0.8832


Epoch 11/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.37it/s, loss=0.3861]


Epoch 11/15 - Loss: 0.2772, Accuracy: 0.8842


Epoch 12/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.40it/s, loss=0.2849]


Epoch 12/15 - Loss: 0.2766, Accuracy: 0.8842


Epoch 13/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.18it/s, loss=0.2267]


Epoch 13/15 - Loss: 0.2761, Accuracy: 0.8847


Epoch 14/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.11it/s, loss=0.3009]


Epoch 14/15 - Loss: 0.2751, Accuracy: 0.8847


Epoch 15/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.18it/s, loss=0.2324]


Epoch 15/15 - Loss: 0.2744, Accuracy: 0.8851
Fold 5 Accuracy: 0.8315
Fold 6: 292083 train samples, 42945 validation samples


Epoch 1/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.15it/s, loss=0.2508]


Epoch 1/15 - Loss: 0.2811, Accuracy: 0.8824


Epoch 2/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.29it/s, loss=0.5462]


Epoch 2/15 - Loss: 0.2802, Accuracy: 0.8828


Epoch 3/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.58it/s, loss=0.3088]


Epoch 3/15 - Loss: 0.2785, Accuracy: 0.8837


Epoch 4/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.18it/s, loss=0.2863]


Epoch 4/15 - Loss: 0.2772, Accuracy: 0.8837


Epoch 5/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.30it/s, loss=0.2615]


Epoch 5/15 - Loss: 0.2764, Accuracy: 0.8847


Epoch 6/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.18it/s, loss=0.2233]


Epoch 6/15 - Loss: 0.2758, Accuracy: 0.8843


Epoch 7/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.34it/s, loss=0.1769]


Epoch 7/15 - Loss: 0.2747, Accuracy: 0.8846


Epoch 8/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.16it/s, loss=0.3003]


Epoch 8/15 - Loss: 0.2740, Accuracy: 0.8846


Epoch 9/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.47it/s, loss=0.1803]


Epoch 9/15 - Loss: 0.2729, Accuracy: 0.8854


Epoch 10/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.25it/s, loss=0.2325]


Epoch 10/15 - Loss: 0.2729, Accuracy: 0.8857


Epoch 11/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.30it/s, loss=0.2263]


Epoch 11/15 - Loss: 0.2717, Accuracy: 0.8860


Epoch 12/15: 100%|██████████| 4564/4564 [00:53<00:00, 84.84it/s, loss=0.6346]


Epoch 12/15 - Loss: 0.2708, Accuracy: 0.8862


Epoch 13/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.16it/s, loss=0.3002]


Epoch 13/15 - Loss: 0.2701, Accuracy: 0.8868


Epoch 14/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.26it/s, loss=0.3301]


Epoch 14/15 - Loss: 0.2695, Accuracy: 0.8869


Epoch 15/15: 100%|██████████| 4564/4564 [00:53<00:00, 85.65it/s, loss=0.1862]


Epoch 15/15 - Loss: 0.2688, Accuracy: 0.8870
Fold 6 Accuracy: 0.8429
Complete model saved to UNSW-NB-PCNN-AttBiLSTM-Transformer-6fold.pth
Fold Accuracies:
  Fold 1: 0.8170
  Fold 2: 0.8277
  Fold 3: 0.8301
  Fold 4: 0.8333
  Fold 5: 0.8315
  Fold 6: 0.8429


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[   41     0    33   266    59     0    47     0     0     0]
 [    0    53    44   227    57     0     1     1     5     0]
 [    0     6   527  2037    83    18    23    13    18     0]
 [    3     2   377  6581   182    29   116    92    25    14]
 [    1     0    38   329  2535     2  1090    27    15     4]
 [    0     2     7    99     6  9688     7     2     1     0]
 [    9     0     5    70   552     2 14804    43    15     0]
 [    0     1    72   453     9     2    16  1774     4     0]
 [    0     0     5    22    19     3    22    14   167     0]
 [    0     0     0     0     0     1     0     0     0    28]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.76      0.09      0.16       446
      Backdoor       0.83      0.14      0.23       388
           DoS       0.48      0.19      0.27      2725
      Exploits       0.65      0.89      0.75      7421
       Fuzzers       0.72      0.63