In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        # self.transformer_encoder = nn.TransformerEncoder(
        #     nn.TransformerEncoderLayer(
        #         d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
        #         nhead=4,
        #         dim_feedforward=256,
        #         batch_first=True,
        #         activation=F.gelu
        #     ),
        #     num_layers=2
        # )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        # trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(lstm_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')



criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-PCNN-AttBiLSTM.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
Epoch 1/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.42it/s, loss=0.4289]


Epoch 1/15 - Loss: 0.5032, Accuracy: 0.8122


Epoch 2/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.62it/s, loss=0.3135]


Epoch 2/15 - Loss: 0.4037, Accuracy: 0.8445


Epoch 3/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.91it/s, loss=0.4480]


Epoch 3/15 - Loss: 0.3846, Accuracy: 0.8492


Epoch 4/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.08it/s, loss=0.3108]


Epoch 4/15 - Loss: 0.3723, Accuracy: 0.8528


Epoch 5/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.54it/s, loss=0.2669]


Epoch 5/15 - Loss: 0.3636, Accuracy: 0.8558


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.19it/s, loss=0.4080]


Epoch 6/15 - Loss: 0.3562, Accuracy: 0.8574


Epoch 7/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.84it/s, loss=0.4305]


Epoch 7/15 - Loss: 0.3491, Accuracy: 0.8600


Epoch 8/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.81it/s, loss=0.4182]


Epoch 8/15 - Loss: 0.3453, Accuracy: 0.8611


Epoch 9/15: 100%|██████████| 4929/4929 [00:32<00:00, 152.10it/s, loss=0.4414]


Epoch 9/15 - Loss: 0.3415, Accuracy: 0.8621


Epoch 10/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.92it/s, loss=0.4626]


Epoch 10/15 - Loss: 0.3379, Accuracy: 0.8629


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.22it/s, loss=0.4552]


Epoch 11/15 - Loss: 0.3347, Accuracy: 0.8638


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.11it/s, loss=0.4428]


Epoch 12/15 - Loss: 0.3317, Accuracy: 0.8650


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.90it/s, loss=0.3122]


Epoch 13/15 - Loss: 0.3292, Accuracy: 0.8659


Epoch 14/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.51it/s, loss=0.3927]


Epoch 14/15 - Loss: 0.3271, Accuracy: 0.8667


Epoch 15/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.84it/s, loss=0.4091]


Epoch 15/15 - Loss: 0.3250, Accuracy: 0.8670
Fold 1 Accuracy: 0.8144
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.13it/s, loss=0.3926]


Epoch 1/15 - Loss: 0.3261, Accuracy: 0.8667


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.58it/s, loss=0.2283]


Epoch 2/15 - Loss: 0.3223, Accuracy: 0.8676


Epoch 3/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.37it/s, loss=0.3432]


Epoch 3/15 - Loss: 0.3214, Accuracy: 0.8684


Epoch 4/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.97it/s, loss=0.4162]


Epoch 4/15 - Loss: 0.3194, Accuracy: 0.8683


Epoch 5/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.47it/s, loss=0.2539]


Epoch 5/15 - Loss: 0.3168, Accuracy: 0.8698


Epoch 6/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.02it/s, loss=0.3828]


Epoch 6/15 - Loss: 0.3166, Accuracy: 0.8697


Epoch 7/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.73it/s, loss=0.2628]


Epoch 7/15 - Loss: 0.3158, Accuracy: 0.8700


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.08it/s, loss=0.3317]


Epoch 8/15 - Loss: 0.3143, Accuracy: 0.8706


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.40it/s, loss=0.3479]


Epoch 9/15 - Loss: 0.3121, Accuracy: 0.8711


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.21it/s, loss=0.3329]


Epoch 10/15 - Loss: 0.3111, Accuracy: 0.8711


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.81it/s, loss=0.2374]


Epoch 11/15 - Loss: 0.3109, Accuracy: 0.8715


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.30it/s, loss=0.3568]


Epoch 12/15 - Loss: 0.3096, Accuracy: 0.8716


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.55it/s, loss=0.3813]


Epoch 13/15 - Loss: 0.3084, Accuracy: 0.8724


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.06it/s, loss=0.4001]


Epoch 14/15 - Loss: 0.3093, Accuracy: 0.8718


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.36it/s, loss=0.1975]


Epoch 15/15 - Loss: 0.3069, Accuracy: 0.8727
Fold 2 Accuracy: 0.8255
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.70it/s, loss=0.4133]


Epoch 1/15 - Loss: 0.3087, Accuracy: 0.8723


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.37it/s, loss=0.2807]


Epoch 2/15 - Loss: 0.3071, Accuracy: 0.8725


Epoch 3/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.15it/s, loss=0.2941]


Epoch 3/15 - Loss: 0.3051, Accuracy: 0.8734


Epoch 4/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.74it/s, loss=0.2953]


Epoch 4/15 - Loss: 0.3043, Accuracy: 0.8740


Epoch 5/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.27it/s, loss=0.3919]


Epoch 5/15 - Loss: 0.3049, Accuracy: 0.8736


Epoch 6/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.78it/s, loss=0.4985]


Epoch 6/15 - Loss: 0.3024, Accuracy: 0.8744


Epoch 7/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.65it/s, loss=0.2796]


Epoch 7/15 - Loss: 0.3018, Accuracy: 0.8746


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.22it/s, loss=0.2597]


Epoch 8/15 - Loss: 0.3005, Accuracy: 0.8751


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.52it/s, loss=0.3146]


Epoch 9/15 - Loss: 0.3003, Accuracy: 0.8750


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.86it/s, loss=0.2452]


Epoch 10/15 - Loss: 0.3005, Accuracy: 0.8753


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.81it/s, loss=0.3280]


Epoch 11/15 - Loss: 0.2991, Accuracy: 0.8755


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.33it/s, loss=0.2291]


Epoch 12/15 - Loss: 0.2969, Accuracy: 0.8757


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.55it/s, loss=0.2264]


Epoch 13/15 - Loss: 0.2973, Accuracy: 0.8764


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.09it/s, loss=0.3514]


Epoch 14/15 - Loss: 0.2960, Accuracy: 0.8769


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.97it/s, loss=0.3722]


Epoch 15/15 - Loss: 0.2958, Accuracy: 0.8766
Fold 3 Accuracy: 0.8258
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.20it/s, loss=0.3246]


Epoch 1/15 - Loss: 0.2966, Accuracy: 0.8770


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.47it/s, loss=0.2088]


Epoch 2/15 - Loss: 0.2961, Accuracy: 0.8767


Epoch 3/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.18it/s, loss=0.2944]


Epoch 3/15 - Loss: 0.2948, Accuracy: 0.8774


Epoch 4/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.22it/s, loss=0.2741]


Epoch 4/15 - Loss: 0.2938, Accuracy: 0.8774


Epoch 5/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.83it/s, loss=0.2439]


Epoch 5/15 - Loss: 0.2932, Accuracy: 0.8780


Epoch 6/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.17it/s, loss=0.1876]


Epoch 6/15 - Loss: 0.2925, Accuracy: 0.8776


Epoch 7/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.50it/s, loss=0.2323]


Epoch 7/15 - Loss: 0.2922, Accuracy: 0.8778


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.08it/s, loss=0.2916]


Epoch 8/15 - Loss: 0.2911, Accuracy: 0.8784


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.84it/s, loss=0.2547]


Epoch 9/15 - Loss: 0.2907, Accuracy: 0.8784


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.94it/s, loss=0.4081]


Epoch 10/15 - Loss: 0.2896, Accuracy: 0.8791


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.09it/s, loss=0.2101]


Epoch 11/15 - Loss: 0.2887, Accuracy: 0.8797


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.17it/s, loss=0.2144]


Epoch 12/15 - Loss: 0.2885, Accuracy: 0.8798


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.05it/s, loss=0.3446]


Epoch 13/15 - Loss: 0.2879, Accuracy: 0.8794


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.62it/s, loss=0.3202]


Epoch 14/15 - Loss: 0.2868, Accuracy: 0.8800


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.10it/s, loss=0.2550]


Epoch 15/15 - Loss: 0.2862, Accuracy: 0.8802
Fold 4 Accuracy: 0.8294
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.13it/s, loss=0.2307]


Epoch 1/15 - Loss: 0.2896, Accuracy: 0.8796


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.04it/s, loss=0.3768]


Epoch 2/15 - Loss: 0.2890, Accuracy: 0.8797


Epoch 3/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.98it/s, loss=0.2728]


Epoch 3/15 - Loss: 0.2882, Accuracy: 0.8794


Epoch 4/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.96it/s, loss=0.3025]


Epoch 4/15 - Loss: 0.2870, Accuracy: 0.8799


Epoch 5/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.94it/s, loss=0.2011]


Epoch 5/15 - Loss: 0.2865, Accuracy: 0.8801


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.47it/s, loss=0.3820]


Epoch 6/15 - Loss: 0.2861, Accuracy: 0.8801


Epoch 7/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.30it/s, loss=0.2183]


Epoch 7/15 - Loss: 0.2855, Accuracy: 0.8806


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.84it/s, loss=0.2174]


Epoch 8/15 - Loss: 0.2846, Accuracy: 0.8810


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.47it/s, loss=0.1894]


Epoch 9/15 - Loss: 0.2844, Accuracy: 0.8814


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.98it/s, loss=0.2800]


Epoch 10/15 - Loss: 0.2831, Accuracy: 0.8814


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.08it/s, loss=0.2351]


Epoch 11/15 - Loss: 0.2827, Accuracy: 0.8815


Epoch 12/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.40it/s, loss=0.1893]


Epoch 12/15 - Loss: 0.2822, Accuracy: 0.8820


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.90it/s, loss=0.4622]


Epoch 13/15 - Loss: 0.2823, Accuracy: 0.8819


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.36it/s, loss=0.4140]


Epoch 14/15 - Loss: 0.2817, Accuracy: 0.8822


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.45it/s, loss=0.2629]


Epoch 15/15 - Loss: 0.2810, Accuracy: 0.8822
Fold 5 Accuracy: 0.8334
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.63it/s, loss=0.2672]


Epoch 1/15 - Loss: 0.2824, Accuracy: 0.8814


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.35it/s, loss=0.3856]


Epoch 2/15 - Loss: 0.2818, Accuracy: 0.8822


Epoch 3/15: 100%|██████████| 4929/4929 [00:35<00:00, 137.62it/s, loss=0.3639]


Epoch 3/15 - Loss: 0.2813, Accuracy: 0.8823


Epoch 4/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.05it/s, loss=0.3181]


Epoch 4/15 - Loss: 0.2807, Accuracy: 0.8825


Epoch 5/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.24it/s, loss=0.3561]


Epoch 5/15 - Loss: 0.2799, Accuracy: 0.8828


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.07it/s, loss=0.2177]


Epoch 6/15 - Loss: 0.2789, Accuracy: 0.8827


Epoch 7/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.16it/s, loss=0.4176]


Epoch 7/15 - Loss: 0.2786, Accuracy: 0.8832


Epoch 8/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.80it/s, loss=0.3660]


Epoch 8/15 - Loss: 0.2781, Accuracy: 0.8836


Epoch 9/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.81it/s, loss=0.3658]


Epoch 9/15 - Loss: 0.2773, Accuracy: 0.8838


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.09it/s, loss=0.3383]


Epoch 10/15 - Loss: 0.2772, Accuracy: 0.8839


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.65it/s, loss=0.3869]


Epoch 11/15 - Loss: 0.2759, Accuracy: 0.8837


Epoch 12/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.77it/s, loss=0.3905]


Epoch 12/15 - Loss: 0.2766, Accuracy: 0.8839


Epoch 13/15: 100%|██████████| 4929/4929 [01:00<00:00, 81.53it/s, loss=0.3546]


Epoch 13/15 - Loss: 0.2754, Accuracy: 0.8847


Epoch 14/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.27it/s, loss=0.2507]


Epoch 14/15 - Loss: 0.2756, Accuracy: 0.8844


Epoch 15/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.68it/s, loss=0.2297]


Epoch 15/15 - Loss: 0.2746, Accuracy: 0.8844
Fold 6 Accuracy: 0.8376
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:58<00:00, 84.16it/s, loss=0.2955]


Epoch 1/15 - Loss: 0.2766, Accuracy: 0.8840


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.52it/s, loss=0.3450]


Epoch 2/15 - Loss: 0.2756, Accuracy: 0.8847


Epoch 3/15: 100%|██████████| 4929/4929 [00:58<00:00, 84.04it/s, loss=0.2401]


Epoch 3/15 - Loss: 0.2746, Accuracy: 0.8852


Epoch 4/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.14it/s, loss=0.3001]


Epoch 4/15 - Loss: 0.2741, Accuracy: 0.8847


Epoch 5/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.22it/s, loss=0.2439]


Epoch 5/15 - Loss: 0.2729, Accuracy: 0.8855


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 152.53it/s, loss=0.4384]


Epoch 6/15 - Loss: 0.2731, Accuracy: 0.8856


Epoch 7/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.06it/s, loss=0.3239]


Epoch 7/15 - Loss: 0.2720, Accuracy: 0.8855


Epoch 8/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.80it/s, loss=0.1920]


Epoch 8/15 - Loss: 0.2721, Accuracy: 0.8860


Epoch 9/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.64it/s, loss=0.2362]


Epoch 9/15 - Loss: 0.2707, Accuracy: 0.8859


Epoch 10/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.61it/s, loss=0.2867]


Epoch 10/15 - Loss: 0.2712, Accuracy: 0.8861


Epoch 11/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.28it/s, loss=0.2330]


Epoch 11/15 - Loss: 0.2703, Accuracy: 0.8863


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.83it/s, loss=0.3606]


Epoch 12/15 - Loss: 0.2701, Accuracy: 0.8862


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.48it/s, loss=0.4441]


Epoch 13/15 - Loss: 0.2700, Accuracy: 0.8864


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.62it/s, loss=0.2293]


Epoch 14/15 - Loss: 0.2692, Accuracy: 0.8866


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.08it/s, loss=0.2240]


Epoch 15/15 - Loss: 0.2690, Accuracy: 0.8872
Fold 7 Accuracy: 0.8424
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.93it/s, loss=0.2779]


Epoch 1/15 - Loss: 0.2724, Accuracy: 0.8859


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.06it/s, loss=0.1945]


Epoch 2/15 - Loss: 0.2711, Accuracy: 0.8858


Epoch 3/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.49it/s, loss=0.1836]


Epoch 3/15 - Loss: 0.2707, Accuracy: 0.8865


Epoch 4/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.24it/s, loss=0.2191]


Epoch 4/15 - Loss: 0.2697, Accuracy: 0.8869


Epoch 5/15: 100%|██████████| 4929/4929 [00:33<00:00, 149.10it/s, loss=0.3233]


Epoch 5/15 - Loss: 0.2697, Accuracy: 0.8862


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.54it/s, loss=0.3435]


Epoch 6/15 - Loss: 0.2687, Accuracy: 0.8873


Epoch 7/15: 100%|██████████| 4929/4929 [00:32<00:00, 149.39it/s, loss=0.3418]


Epoch 7/15 - Loss: 0.2689, Accuracy: 0.8871


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.53it/s, loss=0.2887]


Epoch 8/15 - Loss: 0.2676, Accuracy: 0.8871


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.63it/s, loss=0.3401]


Epoch 9/15 - Loss: 0.2674, Accuracy: 0.8873


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.20it/s, loss=0.1320]


Epoch 10/15 - Loss: 0.2670, Accuracy: 0.8881


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.30it/s, loss=0.4309]


Epoch 11/15 - Loss: 0.2665, Accuracy: 0.8881


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.67it/s, loss=0.2458]


Epoch 12/15 - Loss: 0.2663, Accuracy: 0.8883


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.60it/s, loss=0.3330]


Epoch 13/15 - Loss: 0.2658, Accuracy: 0.8880


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.46it/s, loss=0.2403]


Epoch 14/15 - Loss: 0.2653, Accuracy: 0.8880


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.47it/s, loss=0.1364]


Epoch 15/15 - Loss: 0.2650, Accuracy: 0.8882
Fold 8 Accuracy: 0.8476
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.74it/s, loss=0.2453]


Epoch 1/15 - Loss: 0.2673, Accuracy: 0.8878


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.95it/s, loss=0.1643]


Epoch 2/15 - Loss: 0.2664, Accuracy: 0.8878


Epoch 3/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.66it/s, loss=0.2696]


Epoch 3/15 - Loss: 0.2661, Accuracy: 0.8880


Epoch 4/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.93it/s, loss=0.1404]


Epoch 4/15 - Loss: 0.2653, Accuracy: 0.8885


Epoch 5/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.08it/s, loss=0.2352]


Epoch 5/15 - Loss: 0.2651, Accuracy: 0.8883


Epoch 6/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.47it/s, loss=0.3187]


Epoch 6/15 - Loss: 0.2644, Accuracy: 0.8886


Epoch 7/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.40it/s, loss=0.4266]


Epoch 7/15 - Loss: 0.2637, Accuracy: 0.8887


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.02it/s, loss=0.2997]


Epoch 8/15 - Loss: 0.2633, Accuracy: 0.8894


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.50it/s, loss=0.2429]


Epoch 9/15 - Loss: 0.2627, Accuracy: 0.8896


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.95it/s, loss=0.2773]


Epoch 10/15 - Loss: 0.2630, Accuracy: 0.8896


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.41it/s, loss=0.1512]


Epoch 11/15 - Loss: 0.2621, Accuracy: 0.8898


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.00it/s, loss=0.0937]


Epoch 12/15 - Loss: 0.2622, Accuracy: 0.8896


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.97it/s, loss=0.2546]


Epoch 13/15 - Loss: 0.2613, Accuracy: 0.8901


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.18it/s, loss=0.3171]


Epoch 14/15 - Loss: 0.2613, Accuracy: 0.8896


Epoch 15/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.14it/s, loss=0.2759]


Epoch 15/15 - Loss: 0.2606, Accuracy: 0.8901
Fold 9 Accuracy: 0.8468
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.23it/s, loss=0.2350]


Epoch 1/15 - Loss: 0.2645, Accuracy: 0.8885


Epoch 2/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.60it/s, loss=0.1523]


Epoch 2/15 - Loss: 0.2629, Accuracy: 0.8892


Epoch 3/15: 100%|██████████| 4929/4929 [00:34<00:00, 143.79it/s, loss=0.2143]


Epoch 3/15 - Loss: 0.2622, Accuracy: 0.8898


Epoch 4/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.23it/s, loss=0.3329]


Epoch 4/15 - Loss: 0.2619, Accuracy: 0.8894


Epoch 5/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.22it/s, loss=0.1983]


Epoch 5/15 - Loss: 0.2619, Accuracy: 0.8899


Epoch 6/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.28it/s, loss=0.3039]


Epoch 6/15 - Loss: 0.2611, Accuracy: 0.8900


Epoch 7/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.30it/s, loss=0.2011]


Epoch 7/15 - Loss: 0.2612, Accuracy: 0.8901


Epoch 8/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.47it/s, loss=0.1679]


Epoch 8/15 - Loss: 0.2605, Accuracy: 0.8903


Epoch 9/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.57it/s, loss=0.1203]


Epoch 9/15 - Loss: 0.2600, Accuracy: 0.8905


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.67it/s, loss=0.1877]


Epoch 10/15 - Loss: 0.2599, Accuracy: 0.8904


Epoch 11/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.96it/s, loss=0.3024]


Epoch 11/15 - Loss: 0.2585, Accuracy: 0.8914


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.70it/s, loss=0.3911]


Epoch 12/15 - Loss: 0.2591, Accuracy: 0.8911


Epoch 13/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.18it/s, loss=0.2140]


Epoch 13/15 - Loss: 0.2581, Accuracy: 0.8908


Epoch 14/15: 100%|██████████| 4929/4929 [00:33<00:00, 145.96it/s, loss=0.1900]


Epoch 14/15 - Loss: 0.2583, Accuracy: 0.8913


Epoch 15/15: 100%|██████████| 4929/4929 [00:33<00:00, 148.15it/s, loss=0.0991]


Epoch 15/15 - Loss: 0.2571, Accuracy: 0.8916
Fold 10 Accuracy: 0.8519
Complete model saved to UNSW-PCNN-AttBiLSTM.pth
Fold Accuracies:
  Fold 1: 0.8144
  Fold 2: 0.8255
  Fold 3: 0.8258
  Fold 4: 0.8294
  Fold 5: 0.8334
  Fold 6: 0.8376
  Fold 7: 0.8424
  Fold 8: 0.8476
  Fold 9: 0.8468
  Fold 10: 0.8519


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  33    0   30  159   24    0   22    0    0    0]
 [   0   29   42  124   35    0    1    0    1    0]
 [   1    1  466 1093   38    7    8   13    7    1]
 [   3    1  354 3830   95   14   43  102    7    3]
 [   0    0   51  181 1589    2  587    6    9    0]
 [   0    0   15   39    3 5824    3    2    1    0]
 [   4    0    5   42  298    1 8933   10    7    0]
 [   1    0   57  206    0    0    4 1131    0    0]
 [   0    0    5   17    9    2   12    9   97    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.79      0.12      0.21       268
      Backdoor       0.94      0.12      0.22       232
           DoS       0.45      0.29      0.35      1635
      Exploits       0.67      0.86      0.76      4452
       Fuzzers       0.76      0.66      0.70      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.