In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=8
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-NB-PCNN-AttBiLSTM-Transformer-8fold.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 306686 train samples, 32210 validation samples


Epoch 1/15:   0%|          | 0/4792 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4792/4792 [00:49<00:00, 96.38it/s, loss=0.2525] 


Epoch 1/15 - Loss: 0.4740, Accuracy: 0.8214


Epoch 2/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.90it/s, loss=0.3609]


Epoch 2/15 - Loss: 0.3892, Accuracy: 0.8482


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.50it/s, loss=0.2963]


Epoch 3/15 - Loss: 0.3721, Accuracy: 0.8531


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.33it/s, loss=0.4250]


Epoch 4/15 - Loss: 0.3612, Accuracy: 0.8558


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.22it/s, loss=0.4474]


Epoch 5/15 - Loss: 0.3524, Accuracy: 0.8587


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.08it/s, loss=0.3397]


Epoch 6/15 - Loss: 0.3464, Accuracy: 0.8608


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.49it/s, loss=0.2878]


Epoch 7/15 - Loss: 0.3426, Accuracy: 0.8614


Epoch 8/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.63it/s, loss=0.4616]


Epoch 8/15 - Loss: 0.3386, Accuracy: 0.8624


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.35it/s, loss=0.3370]


Epoch 9/15 - Loss: 0.3353, Accuracy: 0.8637


Epoch 10/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.68it/s, loss=0.3748]


Epoch 10/15 - Loss: 0.3330, Accuracy: 0.8644


Epoch 11/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.72it/s, loss=0.4097]


Epoch 11/15 - Loss: 0.3307, Accuracy: 0.8653


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.56it/s, loss=0.3108]


Epoch 12/15 - Loss: 0.3277, Accuracy: 0.8661


Epoch 13/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.79it/s, loss=0.2916]


Epoch 13/15 - Loss: 0.3266, Accuracy: 0.8664


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.54it/s, loss=0.2772]


Epoch 14/15 - Loss: 0.3241, Accuracy: 0.8670


Epoch 15/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.63it/s, loss=0.1822]


Epoch 15/15 - Loss: 0.3223, Accuracy: 0.8679
Fold 1 Accuracy: 0.8160
Fold 2: 306687 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.19it/s, loss=0.3353]


Epoch 1/15 - Loss: 0.3247, Accuracy: 0.8671


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.21it/s, loss=0.3421]


Epoch 2/15 - Loss: 0.3217, Accuracy: 0.8683


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.24it/s, loss=0.3221]


Epoch 3/15 - Loss: 0.3196, Accuracy: 0.8685


Epoch 4/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.58it/s, loss=0.2384]


Epoch 4/15 - Loss: 0.3177, Accuracy: 0.8696


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.45it/s, loss=0.3713]


Epoch 5/15 - Loss: 0.3152, Accuracy: 0.8703


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.41it/s, loss=0.4497]


Epoch 6/15 - Loss: 0.3144, Accuracy: 0.8707


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.10it/s, loss=0.2640]


Epoch 7/15 - Loss: 0.3126, Accuracy: 0.8714


Epoch 8/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.11it/s, loss=0.1687]


Epoch 8/15 - Loss: 0.3121, Accuracy: 0.8709


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.04it/s, loss=0.2588]


Epoch 9/15 - Loss: 0.3100, Accuracy: 0.8722


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.19it/s, loss=0.2295]


Epoch 10/15 - Loss: 0.3093, Accuracy: 0.8722


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.45it/s, loss=0.3478]


Epoch 11/15 - Loss: 0.3077, Accuracy: 0.8726


Epoch 12/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.58it/s, loss=0.3616]


Epoch 12/15 - Loss: 0.3059, Accuracy: 0.8732


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.48it/s, loss=0.1384]


Epoch 13/15 - Loss: 0.3049, Accuracy: 0.8734


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.51it/s, loss=0.2642]


Epoch 14/15 - Loss: 0.3039, Accuracy: 0.8739


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.41it/s, loss=0.3186]


Epoch 15/15 - Loss: 0.3028, Accuracy: 0.8747
Fold 2 Accuracy: 0.8251
Fold 3: 306686 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.48it/s, loss=0.5370]


Epoch 1/15 - Loss: 0.3056, Accuracy: 0.8741


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.48it/s, loss=0.2039]


Epoch 2/15 - Loss: 0.3033, Accuracy: 0.8744


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.19it/s, loss=0.3755]


Epoch 3/15 - Loss: 0.3017, Accuracy: 0.8751


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.07it/s, loss=0.2485]


Epoch 4/15 - Loss: 0.3009, Accuracy: 0.8749


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.25it/s, loss=0.2410]


Epoch 5/15 - Loss: 0.2999, Accuracy: 0.8756


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.12it/s, loss=0.2337]


Epoch 6/15 - Loss: 0.2989, Accuracy: 0.8760


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.28it/s, loss=0.3443]


Epoch 7/15 - Loss: 0.2972, Accuracy: 0.8765


Epoch 8/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.31it/s, loss=0.3311]


Epoch 8/15 - Loss: 0.2962, Accuracy: 0.8772


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.16it/s, loss=0.2076]


Epoch 9/15 - Loss: 0.2955, Accuracy: 0.8770


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.28it/s, loss=0.4048]


Epoch 10/15 - Loss: 0.2951, Accuracy: 0.8777


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.12it/s, loss=0.2950]


Epoch 11/15 - Loss: 0.2943, Accuracy: 0.8777


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.11it/s, loss=0.1220]


Epoch 12/15 - Loss: 0.2925, Accuracy: 0.8780


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.08it/s, loss=0.1940]


Epoch 13/15 - Loss: 0.2919, Accuracy: 0.8783


Epoch 14/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.58it/s, loss=0.2824]


Epoch 14/15 - Loss: 0.2911, Accuracy: 0.8788


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.20it/s, loss=0.2717]


Epoch 15/15 - Loss: 0.2895, Accuracy: 0.8793
Fold 3 Accuracy: 0.8279
Fold 4: 306686 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.49it/s, loss=0.4972]


Epoch 1/15 - Loss: 0.2942, Accuracy: 0.8779


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.16it/s, loss=0.2335]


Epoch 2/15 - Loss: 0.2919, Accuracy: 0.8784


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.98it/s, loss=0.2844]


Epoch 3/15 - Loss: 0.2908, Accuracy: 0.8789


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.17it/s, loss=0.2086]


Epoch 4/15 - Loss: 0.2902, Accuracy: 0.8790


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.46it/s, loss=0.2741]


Epoch 5/15 - Loss: 0.2889, Accuracy: 0.8797


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.39it/s, loss=0.5005]


Epoch 6/15 - Loss: 0.2886, Accuracy: 0.8800


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.18it/s, loss=0.2607]


Epoch 7/15 - Loss: 0.2878, Accuracy: 0.8804


Epoch 8/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.17it/s, loss=0.3097]


Epoch 8/15 - Loss: 0.2862, Accuracy: 0.8805


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.14it/s, loss=0.4532]


Epoch 9/15 - Loss: 0.2860, Accuracy: 0.8810


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.01it/s, loss=0.2919]


Epoch 10/15 - Loss: 0.2846, Accuracy: 0.8811


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.87it/s, loss=0.4500]


Epoch 11/15 - Loss: 0.2846, Accuracy: 0.8816


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.48it/s, loss=0.3111]


Epoch 12/15 - Loss: 0.2841, Accuracy: 0.8817


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.35it/s, loss=0.1554]


Epoch 13/15 - Loss: 0.2829, Accuracy: 0.8824


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.29it/s, loss=0.3689]


Epoch 14/15 - Loss: 0.2820, Accuracy: 0.8819


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.62it/s, loss=0.2751]


Epoch 15/15 - Loss: 0.2813, Accuracy: 0.8823
Fold 4 Accuracy: 0.8364
Fold 5: 306687 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.50it/s, loss=0.1619]


Epoch 1/15 - Loss: 0.2857, Accuracy: 0.8806


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.67it/s, loss=0.1962]


Epoch 2/15 - Loss: 0.2839, Accuracy: 0.8812


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.08it/s, loss=0.4010]


Epoch 3/15 - Loss: 0.2820, Accuracy: 0.8823


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.25it/s, loss=0.2724]


Epoch 4/15 - Loss: 0.2813, Accuracy: 0.8827


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.16it/s, loss=0.2182]


Epoch 5/15 - Loss: 0.2809, Accuracy: 0.8830


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.59it/s, loss=0.1920]


Epoch 6/15 - Loss: 0.2794, Accuracy: 0.8836


Epoch 7/15: 100%|██████████| 4792/4792 [00:57<00:00, 83.57it/s, loss=0.2598]


Epoch 7/15 - Loss: 0.2791, Accuracy: 0.8832


Epoch 8/15: 100%|██████████| 4792/4792 [00:57<00:00, 83.68it/s, loss=0.2056]


Epoch 8/15 - Loss: 0.2779, Accuracy: 0.8839


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.96it/s, loss=0.2803]


Epoch 9/15 - Loss: 0.2779, Accuracy: 0.8834


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.93it/s, loss=0.1544]


Epoch 10/15 - Loss: 0.2766, Accuracy: 0.8842


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.93it/s, loss=0.2579]


Epoch 11/15 - Loss: 0.2769, Accuracy: 0.8839


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.40it/s, loss=0.2199]


Epoch 12/15 - Loss: 0.2758, Accuracy: 0.8848


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.25it/s, loss=0.2642]


Epoch 13/15 - Loss: 0.2746, Accuracy: 0.8849


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.82it/s, loss=0.1938]


Epoch 14/15 - Loss: 0.2750, Accuracy: 0.8853


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.13it/s, loss=0.2856]


Epoch 15/15 - Loss: 0.2747, Accuracy: 0.8849
Fold 5 Accuracy: 0.8409
Fold 6: 306687 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.86it/s, loss=0.2940]


Epoch 1/15 - Loss: 0.2783, Accuracy: 0.8840


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.87it/s, loss=0.3102]


Epoch 2/15 - Loss: 0.2763, Accuracy: 0.8844


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.81it/s, loss=0.3572]


Epoch 3/15 - Loss: 0.2752, Accuracy: 0.8851


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.49it/s, loss=0.2047]


Epoch 4/15 - Loss: 0.2746, Accuracy: 0.8855


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.14it/s, loss=0.3912]


Epoch 5/15 - Loss: 0.2737, Accuracy: 0.8857


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.25it/s, loss=0.2550]


Epoch 6/15 - Loss: 0.2721, Accuracy: 0.8861


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.25it/s, loss=0.2861]


Epoch 7/15 - Loss: 0.2715, Accuracy: 0.8868


Epoch 8/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.53it/s, loss=0.4841]


Epoch 8/15 - Loss: 0.2715, Accuracy: 0.8867


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.42it/s, loss=0.1653]


Epoch 9/15 - Loss: 0.2710, Accuracy: 0.8868


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.96it/s, loss=0.2882]


Epoch 10/15 - Loss: 0.2699, Accuracy: 0.8875


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.94it/s, loss=0.3014]


Epoch 11/15 - Loss: 0.2694, Accuracy: 0.8866


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.05it/s, loss=0.2818]


Epoch 12/15 - Loss: 0.2686, Accuracy: 0.8877


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.55it/s, loss=0.3347]


Epoch 13/15 - Loss: 0.2691, Accuracy: 0.8870


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.24it/s, loss=0.2243]


Epoch 14/15 - Loss: 0.2681, Accuracy: 0.8879


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.43it/s, loss=0.2753]


Epoch 15/15 - Loss: 0.2678, Accuracy: 0.8878
Fold 6 Accuracy: 0.8431
Fold 7: 306687 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.87it/s, loss=0.1327]


Epoch 1/15 - Loss: 0.2726, Accuracy: 0.8865


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.19it/s, loss=0.3536]


Epoch 2/15 - Loss: 0.2712, Accuracy: 0.8868


Epoch 3/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.62it/s, loss=0.3208]


Epoch 3/15 - Loss: 0.2695, Accuracy: 0.8871


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.33it/s, loss=0.1616]


Epoch 4/15 - Loss: 0.2691, Accuracy: 0.8869


Epoch 5/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.24it/s, loss=0.2814]


Epoch 5/15 - Loss: 0.2691, Accuracy: 0.8876


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.25it/s, loss=0.3065]


Epoch 6/15 - Loss: 0.2676, Accuracy: 0.8878


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.87it/s, loss=0.2951]


Epoch 7/15 - Loss: 0.2670, Accuracy: 0.8887


Epoch 8/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.15it/s, loss=0.1885]


Epoch 8/15 - Loss: 0.2660, Accuracy: 0.8883


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.29it/s, loss=0.3573]


Epoch 9/15 - Loss: 0.2659, Accuracy: 0.8886


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.27it/s, loss=0.3677]


Epoch 10/15 - Loss: 0.2657, Accuracy: 0.8887


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.96it/s, loss=0.2039]


Epoch 11/15 - Loss: 0.2653, Accuracy: 0.8890


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.05it/s, loss=0.3591]


Epoch 12/15 - Loss: 0.2643, Accuracy: 0.8889


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.08it/s, loss=0.2167]


Epoch 13/15 - Loss: 0.2635, Accuracy: 0.8896


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.41it/s, loss=0.3332]


Epoch 14/15 - Loss: 0.2639, Accuracy: 0.8895


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.28it/s, loss=0.2068]


Epoch 15/15 - Loss: 0.2625, Accuracy: 0.8897
Fold 7 Accuracy: 0.8471
Fold 8: 306687 train samples, 32209 validation samples


Epoch 1/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.03it/s, loss=0.2625]


Epoch 1/15 - Loss: 0.2669, Accuracy: 0.8885


Epoch 2/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.74it/s, loss=0.2725]


Epoch 2/15 - Loss: 0.2664, Accuracy: 0.8888


Epoch 3/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.43it/s, loss=0.2822]


Epoch 3/15 - Loss: 0.2648, Accuracy: 0.8888


Epoch 4/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.21it/s, loss=0.2707]


Epoch 4/15 - Loss: 0.2640, Accuracy: 0.8893


Epoch 5/15: 100%|██████████| 4792/4792 [00:55<00:00, 85.58it/s, loss=0.2165]


Epoch 5/15 - Loss: 0.2634, Accuracy: 0.8898


Epoch 6/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.14it/s, loss=0.4506]


Epoch 6/15 - Loss: 0.2629, Accuracy: 0.8896


Epoch 7/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.27it/s, loss=0.1647]


Epoch 7/15 - Loss: 0.2620, Accuracy: 0.8902


Epoch 8/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.26it/s, loss=0.2431]


Epoch 8/15 - Loss: 0.2611, Accuracy: 0.8903


Epoch 9/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.18it/s, loss=0.1982]


Epoch 9/15 - Loss: 0.2612, Accuracy: 0.8904


Epoch 10/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.21it/s, loss=0.3869]


Epoch 10/15 - Loss: 0.2606, Accuracy: 0.8905


Epoch 11/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.32it/s, loss=0.3147]


Epoch 11/15 - Loss: 0.2599, Accuracy: 0.8906


Epoch 12/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.09it/s, loss=0.5350]


Epoch 12/15 - Loss: 0.2593, Accuracy: 0.8909


Epoch 13/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.28it/s, loss=0.2164]


Epoch 13/15 - Loss: 0.2597, Accuracy: 0.8911


Epoch 14/15: 100%|██████████| 4792/4792 [00:56<00:00, 84.70it/s, loss=0.3209]


Epoch 14/15 - Loss: 0.2596, Accuracy: 0.8908


Epoch 15/15: 100%|██████████| 4792/4792 [00:56<00:00, 85.36it/s, loss=0.4944]


Epoch 15/15 - Loss: 0.2588, Accuracy: 0.8911
Fold 8 Accuracy: 0.8518
Complete model saved to UNSW-NB-PCNN-AttBiLSTM-Transformer-8fold.pth
Fold Accuracies:
  Fold 1: 0.8160
  Fold 2: 0.8251
  Fold 3: 0.8279
  Fold 4: 0.8364
  Fold 5: 0.8409
  Fold 6: 0.8431
  Fold 7: 0.8471
  Fold 8: 0.8518


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[   37     0    42   181    43     0    31     0     0     0]
 [    0    38    42   160    46     0     1     1     3     0]
 [    0     1   503  1438    61     8    11    12     9     1]
 [    0     3   332  4907   132    16    76    69    19    12]
 [    0     0    45   207  2094     3   654    11    12     5]
 [    0     0    17    52     3  7281     2     3     1     0]
 [    1     0     6    42   485     0 11072     7    12     0]
 [    0     0    62   328     2     1     4  1349     2     0]
 [    0     0     2    15    16     2    11    10   133     0]
 [    0     0     0     0     0     1     0     0     0    21]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.97      0.11      0.20       334
      Backdoor       0.90      0.13      0.23       291
           DoS       0.48      0.25      0.33      2044
      Exploits       0.67      0.88      0.76      5566
       Fuzzers       0.73      0.69