In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# -------------------- ParallelDilatedTCN（保持不使用） --------------------
class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()
        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )
        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )
        # 残差连接：使输入和 LSTM 输出的维度对齐
        self.res_proj = nn.Linear(input_size, hidden_size * 2)

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射，输出 [B, L, H*2]
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]
        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]
        return attended + res                   # 残差连接增强 [B, L, H*2]

# ========================= NSLKDDModel（消融实验版：去除 TCN） ========================= #
class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):
        """
        参数说明：
          input_dim: 原始输入的长度（例如196）
          num_classes: 分类数
          hidden_size: LSTM隐藏层单元数（实际LSTM输出维度为hidden_size*2）
        """
        super().__init__()
        
        # ----- 消融：移除TCN，增加简单投影层 ----- 
        # 原始输入 x: [B, 1, input_dim]
        # 先通过自适应池化将时间步缩减到 input_dim//4，
        # 再通过1×1卷积将通道数从1扩展到48，与原来 TCN 输出保持一致
        self.proj = nn.Sequential(
            nn.AdaptiveMaxPool1d(input_dim // 4),  # 输出: [B, 1, input_dim//4]
            nn.Conv1d(1, 48, kernel_size=1, padding='same'),  # 输出: [B, 48, input_dim//4]
            nn.BatchNorm1d(48)
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,  # 与投影后的通道数保持一致
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )
        
        # Transformer部分暂时移除，可根据需要恢复
        # self.transformer_encoder = nn.TransformerEncoder(
        #     nn.TransformerEncoderLayer(
        #         d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
        #         nhead=4,
        #         dim_feedforward=256,
        #         batch_first=True,
        #         activation=F.gelu
        #     ),
        #     num_layers=2
        # )
        
        # 分类器：输入尺寸 = (input_dim//4) * (hidden_size * 2)
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        
    def forward(self, x):
        # 原始输入 x: [B, 1, input_dim]
        x = self.proj(x)               # 投影后 x: [B, 48, input_dim//4]
        x = x.permute(0, 2, 1)         # 调整为 [B, input_dim//4, 48]，适配LSTM
        
        lstm_out = self.lstm(x)        # Bi-ResAtt-LSTM 输出: [B, input_dim//4, hidden_size*2]
        # 如有Transformer则可在此处接入：trans_out = self.transformer_encoder(lstm_out)
        
        return self.classifier(lstm_out)  # 分类器处理后输出: [B, num_classes]



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-AttBiLSTM.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.97it/s, loss=0.6394]


Epoch 1/15 - Loss: 0.5323, Accuracy: 0.8066


Epoch 2/15: 100%|██████████| 4929/4929 [00:26<00:00, 184.49it/s, loss=0.5888]


Epoch 2/15 - Loss: 0.4390, Accuracy: 0.8327


Epoch 3/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.61it/s, loss=0.3633]


Epoch 3/15 - Loss: 0.4173, Accuracy: 0.8382


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.63it/s, loss=0.4526]


Epoch 4/15 - Loss: 0.4071, Accuracy: 0.8410


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.12it/s, loss=0.3806]


Epoch 5/15 - Loss: 0.3994, Accuracy: 0.8432


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.91it/s, loss=0.4300]


Epoch 6/15 - Loss: 0.3942, Accuracy: 0.8447


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.72it/s, loss=0.4501]


Epoch 7/15 - Loss: 0.3892, Accuracy: 0.8464


Epoch 8/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.53it/s, loss=0.3091]


Epoch 8/15 - Loss: 0.3859, Accuracy: 0.8473


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.14it/s, loss=0.4167]


Epoch 9/15 - Loss: 0.3821, Accuracy: 0.8480


Epoch 10/15: 100%|██████████| 4929/4929 [00:29<00:00, 169.90it/s, loss=0.5171]


Epoch 10/15 - Loss: 0.3793, Accuracy: 0.8492


Epoch 11/15: 100%|██████████| 4929/4929 [00:28<00:00, 170.57it/s, loss=0.4289]


Epoch 11/15 - Loss: 0.3766, Accuracy: 0.8499


Epoch 12/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.54it/s, loss=0.2688]


Epoch 12/15 - Loss: 0.3742, Accuracy: 0.8506


Epoch 13/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.90it/s, loss=0.2465]


Epoch 13/15 - Loss: 0.3725, Accuracy: 0.8513


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.74it/s, loss=0.3052]


Epoch 14/15 - Loss: 0.3705, Accuracy: 0.8518


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 180.22it/s, loss=0.5275]


Epoch 15/15 - Loss: 0.3689, Accuracy: 0.8522
Fold 1 Accuracy: 0.8005
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.12it/s, loss=0.4300]


Epoch 1/15 - Loss: 0.3701, Accuracy: 0.8523


Epoch 2/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.30it/s, loss=0.6658]


Epoch 2/15 - Loss: 0.3669, Accuracy: 0.8536


Epoch 3/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.91it/s, loss=0.2798]


Epoch 3/15 - Loss: 0.3653, Accuracy: 0.8535


Epoch 4/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.65it/s, loss=0.3768]


Epoch 4/15 - Loss: 0.3641, Accuracy: 0.8537


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.70it/s, loss=0.4508]


Epoch 5/15 - Loss: 0.3623, Accuracy: 0.8542


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.63it/s, loss=0.4049]


Epoch 6/15 - Loss: 0.3606, Accuracy: 0.8551


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.23it/s, loss=0.4155]


Epoch 7/15 - Loss: 0.3601, Accuracy: 0.8551


Epoch 8/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.25it/s, loss=0.2681]


Epoch 8/15 - Loss: 0.3588, Accuracy: 0.8555


Epoch 9/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.89it/s, loss=0.5738]


Epoch 9/15 - Loss: 0.3582, Accuracy: 0.8558


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.93it/s, loss=0.3983]


Epoch 10/15 - Loss: 0.3564, Accuracy: 0.8561


Epoch 11/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.48it/s, loss=0.4138]


Epoch 11/15 - Loss: 0.3562, Accuracy: 0.8562


Epoch 12/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.43it/s, loss=0.3347]


Epoch 12/15 - Loss: 0.3547, Accuracy: 0.8571


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.51it/s, loss=0.4041]


Epoch 13/15 - Loss: 0.3535, Accuracy: 0.8572


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.12it/s, loss=0.3847]


Epoch 14/15 - Loss: 0.3530, Accuracy: 0.8574


Epoch 15/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.98it/s, loss=0.3806]


Epoch 15/15 - Loss: 0.3516, Accuracy: 0.8579
Fold 2 Accuracy: 0.8041
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.37it/s, loss=0.2529]


Epoch 1/15 - Loss: 0.3542, Accuracy: 0.8569


Epoch 2/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.41it/s, loss=0.2702]


Epoch 2/15 - Loss: 0.3514, Accuracy: 0.8574


Epoch 3/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.91it/s, loss=0.4919]


Epoch 3/15 - Loss: 0.3510, Accuracy: 0.8580


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.30it/s, loss=0.2735]


Epoch 4/15 - Loss: 0.3498, Accuracy: 0.8585


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.78it/s, loss=0.3054]


Epoch 5/15 - Loss: 0.3496, Accuracy: 0.8581


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.14it/s, loss=0.2748]


Epoch 6/15 - Loss: 0.3490, Accuracy: 0.8585


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.06it/s, loss=0.2826]


Epoch 7/15 - Loss: 0.3474, Accuracy: 0.8591


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.88it/s, loss=0.3308]


Epoch 8/15 - Loss: 0.3474, Accuracy: 0.8589


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.65it/s, loss=0.4220]


Epoch 9/15 - Loss: 0.3462, Accuracy: 0.8597


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.05it/s, loss=0.3597]


Epoch 10/15 - Loss: 0.3457, Accuracy: 0.8595


Epoch 11/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.78it/s, loss=0.4353]


Epoch 11/15 - Loss: 0.3453, Accuracy: 0.8599


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.64it/s, loss=0.3528]


Epoch 12/15 - Loss: 0.3449, Accuracy: 0.8599


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.00it/s, loss=0.4053]


Epoch 13/15 - Loss: 0.3444, Accuracy: 0.8596


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.76it/s, loss=0.3490]


Epoch 14/15 - Loss: 0.3436, Accuracy: 0.8607


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.00it/s, loss=0.3667]


Epoch 15/15 - Loss: 0.3432, Accuracy: 0.8607
Fold 3 Accuracy: 0.8105
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.04it/s, loss=0.2472]


Epoch 1/15 - Loss: 0.3448, Accuracy: 0.8601


Epoch 2/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.10it/s, loss=0.2355]


Epoch 2/15 - Loss: 0.3434, Accuracy: 0.8605


Epoch 3/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.58it/s, loss=0.3546]


Epoch 3/15 - Loss: 0.3426, Accuracy: 0.8607


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.80it/s, loss=0.4190]


Epoch 4/15 - Loss: 0.3416, Accuracy: 0.8608


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.41it/s, loss=0.3878]


Epoch 5/15 - Loss: 0.3408, Accuracy: 0.8612


Epoch 6/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.73it/s, loss=0.4135]


Epoch 6/15 - Loss: 0.3410, Accuracy: 0.8614


Epoch 7/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.14it/s, loss=0.2313]


Epoch 7/15 - Loss: 0.3396, Accuracy: 0.8617


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.86it/s, loss=0.3004]


Epoch 8/15 - Loss: 0.3392, Accuracy: 0.8617


Epoch 9/15: 100%|██████████| 4929/4929 [00:28<00:00, 171.83it/s, loss=0.3724]


Epoch 9/15 - Loss: 0.3390, Accuracy: 0.8614


Epoch 10/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.28it/s, loss=0.2717]


Epoch 10/15 - Loss: 0.3381, Accuracy: 0.8615


Epoch 11/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.26it/s, loss=0.2407]


Epoch 11/15 - Loss: 0.3381, Accuracy: 0.8621


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.07it/s, loss=0.2683]


Epoch 12/15 - Loss: 0.3379, Accuracy: 0.8622


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.79it/s, loss=0.3754]


Epoch 13/15 - Loss: 0.3364, Accuracy: 0.8628


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.46it/s, loss=0.3745]


Epoch 14/15 - Loss: 0.3364, Accuracy: 0.8630


Epoch 15/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.20it/s, loss=0.2605]


Epoch 15/15 - Loss: 0.3359, Accuracy: 0.8628
Fold 4 Accuracy: 0.8120
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.26it/s, loss=0.2235]


Epoch 1/15 - Loss: 0.3385, Accuracy: 0.8621


Epoch 2/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.39it/s, loss=0.2529]


Epoch 2/15 - Loss: 0.3370, Accuracy: 0.8630


Epoch 3/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.76it/s, loss=0.2629]


Epoch 3/15 - Loss: 0.3352, Accuracy: 0.8634


Epoch 4/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.65it/s, loss=0.5202]


Epoch 4/15 - Loss: 0.3361, Accuracy: 0.8629


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.19it/s, loss=0.3333]


Epoch 5/15 - Loss: 0.3346, Accuracy: 0.8637


Epoch 6/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.73it/s, loss=0.4335]


Epoch 6/15 - Loss: 0.3344, Accuracy: 0.8635


Epoch 7/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.62it/s, loss=0.3959]


Epoch 7/15 - Loss: 0.3343, Accuracy: 0.8636


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.95it/s, loss=0.3603]


Epoch 8/15 - Loss: 0.3337, Accuracy: 0.8637


Epoch 9/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.47it/s, loss=0.3190]


Epoch 9/15 - Loss: 0.3332, Accuracy: 0.8640


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.98it/s, loss=0.2987]


Epoch 10/15 - Loss: 0.3323, Accuracy: 0.8641


Epoch 11/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.21it/s, loss=0.3865]


Epoch 11/15 - Loss: 0.3333, Accuracy: 0.8643


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.08it/s, loss=0.3082]


Epoch 12/15 - Loss: 0.3323, Accuracy: 0.8644


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.82it/s, loss=0.3363]


Epoch 13/15 - Loss: 0.3327, Accuracy: 0.8646


Epoch 14/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.08it/s, loss=0.3452]


Epoch 14/15 - Loss: 0.3312, Accuracy: 0.8644


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.42it/s, loss=0.3110]


Epoch 15/15 - Loss: 0.3313, Accuracy: 0.8644
Fold 5 Accuracy: 0.8162
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.94it/s, loss=0.3900]


Epoch 1/15 - Loss: 0.3334, Accuracy: 0.8635


Epoch 2/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.05it/s, loss=0.3695]


Epoch 2/15 - Loss: 0.3326, Accuracy: 0.8646


Epoch 3/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.96it/s, loss=0.3872]


Epoch 3/15 - Loss: 0.3317, Accuracy: 0.8644


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.86it/s, loss=0.5346]


Epoch 4/15 - Loss: 0.3315, Accuracy: 0.8647


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.60it/s, loss=0.7011]


Epoch 5/15 - Loss: 0.3313, Accuracy: 0.8649


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.12it/s, loss=0.4022]


Epoch 6/15 - Loss: 0.3300, Accuracy: 0.8652


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.94it/s, loss=0.2484]


Epoch 7/15 - Loss: 0.3298, Accuracy: 0.8652


Epoch 8/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.12it/s, loss=0.1979]


Epoch 8/15 - Loss: 0.3304, Accuracy: 0.8652


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.84it/s, loss=0.3459]


Epoch 9/15 - Loss: 0.3282, Accuracy: 0.8660


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.29it/s, loss=0.3157]


Epoch 10/15 - Loss: 0.3291, Accuracy: 0.8650


Epoch 11/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.93it/s, loss=0.3340]


Epoch 11/15 - Loss: 0.3284, Accuracy: 0.8656


Epoch 12/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.52it/s, loss=0.1727]


Epoch 12/15 - Loss: 0.3282, Accuracy: 0.8650


Epoch 13/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.49it/s, loss=0.2721]


Epoch 13/15 - Loss: 0.3277, Accuracy: 0.8662


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.47it/s, loss=0.2023]


Epoch 14/15 - Loss: 0.3271, Accuracy: 0.8661


Epoch 15/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.49it/s, loss=0.3174]


Epoch 15/15 - Loss: 0.3271, Accuracy: 0.8665
Fold 6 Accuracy: 0.8205
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.20it/s, loss=0.3432]


Epoch 1/15 - Loss: 0.3289, Accuracy: 0.8653


Epoch 2/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.96it/s, loss=0.2736]


Epoch 2/15 - Loss: 0.3274, Accuracy: 0.8659


Epoch 3/15: 100%|██████████| 4929/4929 [00:28<00:00, 172.92it/s, loss=0.2905]


Epoch 3/15 - Loss: 0.3270, Accuracy: 0.8662


Epoch 4/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.61it/s, loss=0.1168]


Epoch 4/15 - Loss: 0.3263, Accuracy: 0.8661


Epoch 5/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.30it/s, loss=0.4004]


Epoch 5/15 - Loss: 0.3264, Accuracy: 0.8660


Epoch 6/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.88it/s, loss=0.2156]


Epoch 6/15 - Loss: 0.3253, Accuracy: 0.8666


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.63it/s, loss=0.2778]


Epoch 7/15 - Loss: 0.3251, Accuracy: 0.8664


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.63it/s, loss=0.2937]


Epoch 8/15 - Loss: 0.3254, Accuracy: 0.8670


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.45it/s, loss=0.2071]


Epoch 9/15 - Loss: 0.3248, Accuracy: 0.8667


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.11it/s, loss=0.3005]


Epoch 10/15 - Loss: 0.3239, Accuracy: 0.8673


Epoch 11/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.98it/s, loss=0.2939]


Epoch 11/15 - Loss: 0.3239, Accuracy: 0.8673


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.12it/s, loss=0.3849]


Epoch 12/15 - Loss: 0.3226, Accuracy: 0.8678


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.53it/s, loss=0.3927]


Epoch 13/15 - Loss: 0.3236, Accuracy: 0.8675


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.00it/s, loss=0.4084]


Epoch 14/15 - Loss: 0.3235, Accuracy: 0.8674


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.92it/s, loss=0.4287]


Epoch 15/15 - Loss: 0.3235, Accuracy: 0.8674
Fold 7 Accuracy: 0.8213
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.31it/s, loss=0.1985]


Epoch 1/15 - Loss: 0.3254, Accuracy: 0.8668


Epoch 2/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.44it/s, loss=0.2595]


Epoch 2/15 - Loss: 0.3240, Accuracy: 0.8672


Epoch 3/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.45it/s, loss=0.1991]


Epoch 3/15 - Loss: 0.3231, Accuracy: 0.8670


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.46it/s, loss=0.3677]


Epoch 4/15 - Loss: 0.3229, Accuracy: 0.8675


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.08it/s, loss=0.2175]


Epoch 5/15 - Loss: 0.3230, Accuracy: 0.8676


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.71it/s, loss=0.1954]


Epoch 6/15 - Loss: 0.3221, Accuracy: 0.8682


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.87it/s, loss=0.3750]


Epoch 7/15 - Loss: 0.3217, Accuracy: 0.8682


Epoch 8/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.92it/s, loss=0.5230]


Epoch 8/15 - Loss: 0.3216, Accuracy: 0.8678


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.41it/s, loss=0.5606]


Epoch 9/15 - Loss: 0.3213, Accuracy: 0.8682


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.49it/s, loss=0.1710]


Epoch 10/15 - Loss: 0.3209, Accuracy: 0.8682


Epoch 11/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.85it/s, loss=0.4127]


Epoch 11/15 - Loss: 0.3201, Accuracy: 0.8683


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.11it/s, loss=0.4339]


Epoch 12/15 - Loss: 0.3209, Accuracy: 0.8682


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.04it/s, loss=0.2796]


Epoch 13/15 - Loss: 0.3202, Accuracy: 0.8688


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.60it/s, loss=0.2414]


Epoch 14/15 - Loss: 0.3202, Accuracy: 0.8685


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.14it/s, loss=0.4009]


Epoch 15/15 - Loss: 0.3204, Accuracy: 0.8682
Fold 8 Accuracy: 0.8201
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.70it/s, loss=0.2686]


Epoch 1/15 - Loss: 0.3219, Accuracy: 0.8677


Epoch 2/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.79it/s, loss=0.0930]


Epoch 2/15 - Loss: 0.3219, Accuracy: 0.8683


Epoch 3/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.63it/s, loss=0.3381]


Epoch 3/15 - Loss: 0.3212, Accuracy: 0.8681


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.45it/s, loss=0.3828]


Epoch 4/15 - Loss: 0.3208, Accuracy: 0.8682


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.51it/s, loss=0.2799]


Epoch 5/15 - Loss: 0.3202, Accuracy: 0.8687


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.68it/s, loss=0.1738]


Epoch 6/15 - Loss: 0.3195, Accuracy: 0.8686


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 180.37it/s, loss=0.3275]


Epoch 7/15 - Loss: 0.3193, Accuracy: 0.8691


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.39it/s, loss=0.2908]


Epoch 8/15 - Loss: 0.3193, Accuracy: 0.8689


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.83it/s, loss=0.3480]


Epoch 9/15 - Loss: 0.3193, Accuracy: 0.8681


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.09it/s, loss=0.2932]


Epoch 10/15 - Loss: 0.3182, Accuracy: 0.8691


Epoch 11/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.65it/s, loss=0.2996]


Epoch 11/15 - Loss: 0.3186, Accuracy: 0.8690


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.49it/s, loss=0.5284]


Epoch 12/15 - Loss: 0.3183, Accuracy: 0.8695


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.04it/s, loss=0.2725]


Epoch 13/15 - Loss: 0.3183, Accuracy: 0.8684


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.69it/s, loss=0.3847]


Epoch 14/15 - Loss: 0.3174, Accuracy: 0.8696


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.96it/s, loss=0.2301]


Epoch 15/15 - Loss: 0.3173, Accuracy: 0.8701
Fold 9 Accuracy: 0.8262
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.48it/s, loss=0.2964]


Epoch 1/15 - Loss: 0.3203, Accuracy: 0.8682


Epoch 2/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.28it/s, loss=0.3147]


Epoch 2/15 - Loss: 0.3192, Accuracy: 0.8687


Epoch 3/15: 100%|██████████| 4929/4929 [00:27<00:00, 179.52it/s, loss=0.2663]


Epoch 3/15 - Loss: 0.3192, Accuracy: 0.8691


Epoch 4/15: 100%|██████████| 4929/4929 [00:27<00:00, 181.31it/s, loss=0.3027]


Epoch 4/15 - Loss: 0.3187, Accuracy: 0.8692


Epoch 5/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.06it/s, loss=0.2863]


Epoch 5/15 - Loss: 0.3185, Accuracy: 0.8689


Epoch 6/15: 100%|██████████| 4929/4929 [00:27<00:00, 181.24it/s, loss=0.2346]


Epoch 6/15 - Loss: 0.3176, Accuracy: 0.8693


Epoch 7/15: 100%|██████████| 4929/4929 [00:27<00:00, 180.86it/s, loss=0.3211]


Epoch 7/15 - Loss: 0.3179, Accuracy: 0.8690


Epoch 8/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.95it/s, loss=0.3143]


Epoch 8/15 - Loss: 0.3171, Accuracy: 0.8692


Epoch 9/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.79it/s, loss=0.3139]


Epoch 9/15 - Loss: 0.3174, Accuracy: 0.8699


Epoch 10/15: 100%|██████████| 4929/4929 [00:27<00:00, 180.34it/s, loss=0.3017]


Epoch 10/15 - Loss: 0.3168, Accuracy: 0.8697


Epoch 11/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.64it/s, loss=0.3896]


Epoch 11/15 - Loss: 0.3165, Accuracy: 0.8699


Epoch 12/15: 100%|██████████| 4929/4929 [00:27<00:00, 180.45it/s, loss=0.2508]


Epoch 12/15 - Loss: 0.3160, Accuracy: 0.8699


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 180.62it/s, loss=0.3328]


Epoch 13/15 - Loss: 0.3165, Accuracy: 0.8694


Epoch 14/15: 100%|██████████| 4929/4929 [00:27<00:00, 181.26it/s, loss=0.2843]


Epoch 14/15 - Loss: 0.3161, Accuracy: 0.8697


Epoch 15/15: 100%|██████████| 4929/4929 [00:29<00:00, 168.08it/s, loss=0.2916]


Epoch 15/15 - Loss: 0.3160, Accuracy: 0.8700
Fold 10 Accuracy: 0.8317
Complete model saved to UNSW-AttBiLSTM.pth
Fold Accuracies:
  Fold 1: 0.8005
  Fold 2: 0.8041
  Fold 3: 0.8105
  Fold 4: 0.8120
  Fold 5: 0.8162
  Fold 6: 0.8205
  Fold 7: 0.8213
  Fold 8: 0.8201
  Fold 9: 0.8262
  Fold 10: 0.8317


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  18    0    5  181   31    0   33    0    0    0]
 [   0   19   11  155   36    0    3    5    3    0]
 [   0    0  140 1391   38    6   29   15   15    1]
 [   0    3   69 4015  114   15   97   93   18   28]
 [   1    0   16  226 1509    1  617   45    8    2]
 [   0    1    5   70    4 5796    5    5    0    1]
 [   1    0    0   51  410    0 8779   51    8    0]
 [   0    0   12  297    7    0   33 1045    1    4]
 [   0    0    1   21   12    1    7   18   91    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.90      0.07      0.12       268
      Backdoor       0.83      0.08      0.15       232
           DoS       0.54      0.09      0.15      1635
      Exploits       0.63      0.90      0.74      4452
       Fuzzers       0.70      0.62      0.66      2425
       Generic       1.00      0.98      0.99      5887
        Normal       0.