In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        # self.att_gate = nn.Sequential(
        #     nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
        #     nn.GELU(),
        #     nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
        #     nn.Sigmoid()
        # )

        # 残差连接
        # self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        # res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        # att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        # attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return lstm_out                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        # self.transformer_encoder = nn.TransformerEncoder(
        #     nn.TransformerEncoderLayer(
        #         d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
        #         nhead=4,
        #         dim_feedforward=256,
        #         batch_first=True,
        #         activation=F.gelu
        #     ),
        #     num_layers=2
        # )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        # trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(lstm_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
        pt = torch.exp(-ce_loss)  # 预测的概率
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-PCNN-BiLSTM.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
Epoch 1/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.15it/s, loss=0.2217]


Epoch 1/15 - Loss: 0.2950, Accuracy: 0.8024


Epoch 2/15: 100%|██████████| 4929/4929 [00:25<00:00, 195.62it/s, loss=0.1923]


Epoch 2/15 - Loss: 0.2243, Accuracy: 0.8384


Epoch 3/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.82it/s, loss=0.0929]


Epoch 3/15 - Loss: 0.2070, Accuracy: 0.8454


Epoch 4/15: 100%|██████████| 4929/4929 [00:26<00:00, 187.77it/s, loss=0.2365]


Epoch 4/15 - Loss: 0.1977, Accuracy: 0.8494


Epoch 5/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.36it/s, loss=0.1168]


Epoch 5/15 - Loss: 0.1903, Accuracy: 0.8532


Epoch 6/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.28it/s, loss=0.2335]


Epoch 6/15 - Loss: 0.1870, Accuracy: 0.8539


Epoch 7/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.35it/s, loss=0.0936]


Epoch 7/15 - Loss: 0.1828, Accuracy: 0.8564


Epoch 8/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.91it/s, loss=0.2168]


Epoch 8/15 - Loss: 0.1796, Accuracy: 0.8579


Epoch 9/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.04it/s, loss=0.0591]


Epoch 9/15 - Loss: 0.1771, Accuracy: 0.8589


Epoch 10/15: 100%|██████████| 4929/4929 [00:25<00:00, 189.88it/s, loss=0.1526]


Epoch 10/15 - Loss: 0.1748, Accuracy: 0.8608


Epoch 11/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.54it/s, loss=0.1611]


Epoch 11/15 - Loss: 0.1733, Accuracy: 0.8612


Epoch 12/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.79it/s, loss=0.1494]


Epoch 12/15 - Loss: 0.1716, Accuracy: 0.8621


Epoch 13/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.05it/s, loss=0.1617]


Epoch 13/15 - Loss: 0.1702, Accuracy: 0.8624


Epoch 14/15: 100%|██████████| 4929/4929 [00:25<00:00, 189.99it/s, loss=0.1501]


Epoch 14/15 - Loss: 0.1684, Accuracy: 0.8627


Epoch 15/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.22it/s, loss=0.3015]


Epoch 15/15 - Loss: 0.1676, Accuracy: 0.8636
Fold 1 Accuracy: 0.8154
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:26<00:00, 186.96it/s, loss=0.2256]


Epoch 1/15 - Loss: 0.1676, Accuracy: 0.8637


Epoch 2/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.26it/s, loss=0.2178]


Epoch 2/15 - Loss: 0.1663, Accuracy: 0.8643


Epoch 3/15: 100%|██████████| 4929/4929 [00:26<00:00, 182.62it/s, loss=0.1857]


Epoch 3/15 - Loss: 0.1646, Accuracy: 0.8656


Epoch 4/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.15it/s, loss=0.1988]


Epoch 4/15 - Loss: 0.1635, Accuracy: 0.8659


Epoch 5/15: 100%|██████████| 4929/4929 [00:26<00:00, 185.73it/s, loss=0.1616]


Epoch 5/15 - Loss: 0.1626, Accuracy: 0.8656


Epoch 6/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.56it/s, loss=0.0931]


Epoch 6/15 - Loss: 0.1616, Accuracy: 0.8665


Epoch 7/15: 100%|██████████| 4929/4929 [00:26<00:00, 187.46it/s, loss=0.1847]


Epoch 7/15 - Loss: 0.1606, Accuracy: 0.8670


Epoch 8/15: 100%|██████████| 4929/4929 [00:25<00:00, 192.44it/s, loss=0.2066]


Epoch 8/15 - Loss: 0.1598, Accuracy: 0.8672


Epoch 9/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.66it/s, loss=0.1131]


Epoch 9/15 - Loss: 0.1589, Accuracy: 0.8675


Epoch 10/15: 100%|██████████| 4929/4929 [00:25<00:00, 192.31it/s, loss=0.1094]


Epoch 10/15 - Loss: 0.1583, Accuracy: 0.8691


Epoch 11/15: 100%|██████████| 4929/4929 [00:25<00:00, 192.32it/s, loss=0.1014]


Epoch 11/15 - Loss: 0.1571, Accuracy: 0.8687


Epoch 12/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.93it/s, loss=0.1383]


Epoch 12/15 - Loss: 0.1573, Accuracy: 0.8686


Epoch 13/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.57it/s, loss=0.1209]


Epoch 13/15 - Loss: 0.1562, Accuracy: 0.8692


Epoch 14/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.16it/s, loss=0.0858]


Epoch 14/15 - Loss: 0.1554, Accuracy: 0.8695


Epoch 15/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.69it/s, loss=0.2200]


Epoch 15/15 - Loss: 0.1549, Accuracy: 0.8693
Fold 2 Accuracy: 0.8176
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.05it/s, loss=0.1424]


Epoch 1/15 - Loss: 0.1563, Accuracy: 0.8689


Epoch 2/15: 100%|██████████| 4929/4929 [00:26<00:00, 186.69it/s, loss=0.1490]


Epoch 2/15 - Loss: 0.1548, Accuracy: 0.8694


Epoch 3/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.87it/s, loss=0.1885]


Epoch 3/15 - Loss: 0.1541, Accuracy: 0.8704


Epoch 4/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.32it/s, loss=0.1412]


Epoch 4/15 - Loss: 0.1534, Accuracy: 0.8705


Epoch 5/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.06it/s, loss=0.1084]


Epoch 5/15 - Loss: 0.1526, Accuracy: 0.8709


Epoch 6/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.50it/s, loss=0.0932]


Epoch 6/15 - Loss: 0.1520, Accuracy: 0.8711


Epoch 7/15: 100%|██████████| 4929/4929 [00:25<00:00, 193.24it/s, loss=0.1379]


Epoch 7/15 - Loss: 0.1517, Accuracy: 0.8719


Epoch 8/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.46it/s, loss=0.1395]


Epoch 8/15 - Loss: 0.1508, Accuracy: 0.8722


Epoch 9/15: 100%|██████████| 4929/4929 [00:26<00:00, 186.39it/s, loss=0.0813]


Epoch 9/15 - Loss: 0.1502, Accuracy: 0.8724


Epoch 10/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.78it/s, loss=0.1995]


Epoch 10/15 - Loss: 0.1499, Accuracy: 0.8720


Epoch 11/15: 100%|██████████| 4929/4929 [00:26<00:00, 187.23it/s, loss=0.2602]


Epoch 11/15 - Loss: 0.1491, Accuracy: 0.8724


Epoch 12/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.89it/s, loss=0.1726]


Epoch 12/15 - Loss: 0.1486, Accuracy: 0.8733


Epoch 13/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.09it/s, loss=0.1074]


Epoch 13/15 - Loss: 0.1484, Accuracy: 0.8737


Epoch 14/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.29it/s, loss=0.2335]


Epoch 14/15 - Loss: 0.1480, Accuracy: 0.8735


Epoch 15/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.81it/s, loss=0.1700]


Epoch 15/15 - Loss: 0.1477, Accuracy: 0.8733
Fold 3 Accuracy: 0.8300
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:26<00:00, 186.56it/s, loss=0.0314]


Epoch 1/15 - Loss: 0.1488, Accuracy: 0.8736


Epoch 2/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.42it/s, loss=0.0999]


Epoch 2/15 - Loss: 0.1480, Accuracy: 0.8737


Epoch 3/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.17it/s, loss=0.1679]


Epoch 3/15 - Loss: 0.1474, Accuracy: 0.8738


Epoch 4/15: 100%|██████████| 4929/4929 [00:25<00:00, 193.35it/s, loss=0.1699]


Epoch 4/15 - Loss: 0.1472, Accuracy: 0.8748


Epoch 5/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.57it/s, loss=0.1686]


Epoch 5/15 - Loss: 0.1467, Accuracy: 0.8744


Epoch 6/15: 100%|██████████| 4929/4929 [00:25<00:00, 189.83it/s, loss=0.1250]


Epoch 6/15 - Loss: 0.1460, Accuracy: 0.8750


Epoch 7/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.78it/s, loss=0.1166]


Epoch 7/15 - Loss: 0.1450, Accuracy: 0.8755


Epoch 8/15: 100%|██████████| 4929/4929 [00:54<00:00, 89.75it/s, loss=0.1407] 


Epoch 8/15 - Loss: 0.1447, Accuracy: 0.8753


Epoch 9/15: 100%|██████████| 4929/4929 [00:42<00:00, 114.83it/s, loss=0.1970]


Epoch 9/15 - Loss: 0.1444, Accuracy: 0.8760


Epoch 10/15: 100%|██████████| 4929/4929 [00:24<00:00, 197.72it/s, loss=0.1449]


Epoch 10/15 - Loss: 0.1439, Accuracy: 0.8761


Epoch 11/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.48it/s, loss=0.1685]


Epoch 11/15 - Loss: 0.1436, Accuracy: 0.8763


Epoch 12/15: 100%|██████████| 4929/4929 [00:25<00:00, 189.65it/s, loss=0.1183]


Epoch 12/15 - Loss: 0.1433, Accuracy: 0.8765


Epoch 13/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.18it/s, loss=0.1480]


Epoch 13/15 - Loss: 0.1425, Accuracy: 0.8771


Epoch 14/15: 100%|██████████| 4929/4929 [00:25<00:00, 189.66it/s, loss=0.1459]


Epoch 14/15 - Loss: 0.1427, Accuracy: 0.8768


Epoch 15/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.70it/s, loss=0.1520]


Epoch 15/15 - Loss: 0.1421, Accuracy: 0.8771
Fold 4 Accuracy: 0.8254
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.63it/s, loss=0.2042]


Epoch 1/15 - Loss: 0.1443, Accuracy: 0.8756


Epoch 2/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.57it/s, loss=0.1247]


Epoch 2/15 - Loss: 0.1434, Accuracy: 0.8767


Epoch 3/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.37it/s, loss=0.1953]


Epoch 3/15 - Loss: 0.1435, Accuracy: 0.8762


Epoch 4/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.26it/s, loss=0.0912]


Epoch 4/15 - Loss: 0.1428, Accuracy: 0.8770


Epoch 5/15: 100%|██████████| 4929/4929 [00:25<00:00, 190.56it/s, loss=0.0777]


Epoch 5/15 - Loss: 0.1420, Accuracy: 0.8772


Epoch 6/15: 100%|██████████| 4929/4929 [00:26<00:00, 189.23it/s, loss=0.1004]


Epoch 6/15 - Loss: 0.1419, Accuracy: 0.8773


Epoch 7/15: 100%|██████████| 4929/4929 [00:25<00:00, 192.81it/s, loss=0.2538]


Epoch 7/15 - Loss: 0.1414, Accuracy: 0.8779


Epoch 8/15: 100%|██████████| 4929/4929 [00:25<00:00, 191.19it/s, loss=0.0464]


Epoch 8/15 - Loss: 0.1412, Accuracy: 0.8772


Epoch 9/15: 100%|██████████| 4929/4929 [00:25<00:00, 193.34it/s, loss=0.3007]


Epoch 9/15 - Loss: 0.1408, Accuracy: 0.8781


Epoch 10/15: 100%|██████████| 4929/4929 [00:25<00:00, 189.72it/s, loss=0.0982]


Epoch 10/15 - Loss: 0.1405, Accuracy: 0.8779


Epoch 11/15: 100%|██████████| 4929/4929 [00:26<00:00, 188.93it/s, loss=0.1090]


Epoch 11/15 - Loss: 0.1404, Accuracy: 0.8780


Epoch 12/15: 100%|██████████| 4929/4929 [00:26<00:00, 187.76it/s, loss=0.1075]


Epoch 12/15 - Loss: 0.1397, Accuracy: 0.8786


Epoch 13/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.78it/s, loss=0.1599]


Epoch 13/15 - Loss: 0.1392, Accuracy: 0.8794


Epoch 14/15: 100%|██████████| 4929/4929 [00:36<00:00, 135.49it/s, loss=0.0654]


Epoch 14/15 - Loss: 0.1390, Accuracy: 0.8793


Epoch 15/15: 100%|██████████| 4929/4929 [00:25<00:00, 194.55it/s, loss=0.1647]


Epoch 15/15 - Loss: 0.1385, Accuracy: 0.8797
Fold 5 Accuracy: 0.8339
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:48<00:00, 100.66it/s, loss=0.1250]


Epoch 1/15 - Loss: 0.1411, Accuracy: 0.8783


Epoch 2/15: 100%|██████████| 4929/4929 [00:52<00:00, 94.12it/s, loss=0.1098] 


Epoch 2/15 - Loss: 0.1398, Accuracy: 0.8787


Epoch 3/15: 100%|██████████| 4929/4929 [00:49<00:00, 100.15it/s, loss=0.1230]


Epoch 3/15 - Loss: 0.1393, Accuracy: 0.8792


Epoch 4/15: 100%|██████████| 4929/4929 [00:51<00:00, 95.03it/s, loss=0.1076] 


Epoch 4/15 - Loss: 0.1388, Accuracy: 0.8798


Epoch 5/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.27it/s, loss=0.0930]


Epoch 5/15 - Loss: 0.1383, Accuracy: 0.8800


Epoch 6/15: 100%|██████████| 4929/4929 [00:55<00:00, 89.34it/s, loss=0.0895] 


Epoch 6/15 - Loss: 0.1380, Accuracy: 0.8798


Epoch 7/15: 100%|██████████| 4929/4929 [00:51<00:00, 95.77it/s, loss=0.3163] 


Epoch 7/15 - Loss: 0.1383, Accuracy: 0.8799


Epoch 8/15: 100%|██████████| 4929/4929 [00:51<00:00, 96.60it/s, loss=0.1517] 


Epoch 8/15 - Loss: 0.1375, Accuracy: 0.8802


Epoch 9/15: 100%|██████████| 4929/4929 [00:49<00:00, 100.04it/s, loss=0.2327]


Epoch 9/15 - Loss: 0.1373, Accuracy: 0.8802


Epoch 10/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.17it/s, loss=0.0774]


Epoch 10/15 - Loss: 0.1370, Accuracy: 0.8807


Epoch 11/15: 100%|██████████| 4929/4929 [00:51<00:00, 95.60it/s, loss=0.0706] 


Epoch 11/15 - Loss: 0.1366, Accuracy: 0.8808


Epoch 12/15: 100%|██████████| 4929/4929 [00:35<00:00, 139.45it/s, loss=0.1919]


Epoch 12/15 - Loss: 0.1368, Accuracy: 0.8810


Epoch 13/15: 100%|██████████| 4929/4929 [00:27<00:00, 176.49it/s, loss=0.1471]


Epoch 13/15 - Loss: 0.1360, Accuracy: 0.8813


Epoch 14/15: 100%|██████████| 4929/4929 [00:25<00:00, 194.64it/s, loss=0.1998]


Epoch 14/15 - Loss: 0.1363, Accuracy: 0.8811


Epoch 15/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.72it/s, loss=0.1641]


Epoch 15/15 - Loss: 0.1359, Accuracy: 0.8812
Fold 6 Accuracy: 0.8383
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:27<00:00, 177.36it/s, loss=0.1337]


Epoch 1/15 - Loss: 0.1369, Accuracy: 0.8807


Epoch 2/15: 100%|██████████| 4929/4929 [00:26<00:00, 186.75it/s, loss=0.0888]


Epoch 2/15 - Loss: 0.1363, Accuracy: 0.8810


Epoch 3/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.58it/s, loss=0.0693]


Epoch 3/15 - Loss: 0.1358, Accuracy: 0.8814


Epoch 4/15: 100%|██████████| 4929/4929 [00:28<00:00, 173.98it/s, loss=0.0965]


Epoch 4/15 - Loss: 0.1352, Accuracy: 0.8815


Epoch 5/15: 100%|██████████| 4929/4929 [00:28<00:00, 172.36it/s, loss=0.2222]


Epoch 5/15 - Loss: 0.1353, Accuracy: 0.8817


Epoch 6/15: 100%|██████████| 4929/4929 [00:54<00:00, 89.63it/s, loss=0.1098]


Epoch 6/15 - Loss: 0.1350, Accuracy: 0.8816


Epoch 7/15: 100%|██████████| 4929/4929 [01:02<00:00, 78.48it/s, loss=0.1838]


Epoch 7/15 - Loss: 0.1344, Accuracy: 0.8823


Epoch 8/15: 100%|██████████| 4929/4929 [01:02<00:00, 78.93it/s, loss=0.0921]


Epoch 8/15 - Loss: 0.1343, Accuracy: 0.8819


Epoch 9/15: 100%|██████████| 4929/4929 [01:00<00:00, 81.14it/s, loss=0.1070]


Epoch 9/15 - Loss: 0.1343, Accuracy: 0.8820


Epoch 10/15: 100%|██████████| 4929/4929 [00:55<00:00, 89.28it/s, loss=0.1769]


Epoch 10/15 - Loss: 0.1339, Accuracy: 0.8825


Epoch 11/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.01it/s, loss=0.1007]


Epoch 11/15 - Loss: 0.1337, Accuracy: 0.8826


Epoch 12/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.25it/s, loss=0.0667]


Epoch 12/15 - Loss: 0.1336, Accuracy: 0.8826


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.64it/s, loss=0.1199] 


Epoch 13/15 - Loss: 0.1332, Accuracy: 0.8830


Epoch 14/15: 100%|██████████| 4929/4929 [00:53<00:00, 91.72it/s, loss=0.0797] 


Epoch 14/15 - Loss: 0.1335, Accuracy: 0.8829


Epoch 15/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.10it/s, loss=0.1255]


Epoch 15/15 - Loss: 0.1329, Accuracy: 0.8833
Fold 7 Accuracy: 0.8403
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:51<00:00, 96.09it/s, loss=0.1179] 


Epoch 1/15 - Loss: 0.1355, Accuracy: 0.8823


Epoch 2/15: 100%|██████████| 4929/4929 [00:27<00:00, 178.26it/s, loss=0.0994]


Epoch 2/15 - Loss: 0.1348, Accuracy: 0.8827


Epoch 3/15: 100%|██████████| 4929/4929 [00:28<00:00, 174.68it/s, loss=0.1733]


Epoch 3/15 - Loss: 0.1340, Accuracy: 0.8831


Epoch 4/15: 100%|██████████| 4929/4929 [00:28<00:00, 175.27it/s, loss=0.1424]


Epoch 4/15 - Loss: 0.1337, Accuracy: 0.8828


Epoch 5/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.34it/s, loss=0.1232]


Epoch 5/15 - Loss: 0.1332, Accuracy: 0.8838


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.06it/s, loss=0.0901]


Epoch 6/15 - Loss: 0.1336, Accuracy: 0.8834


Epoch 7/15: 100%|██████████| 4929/4929 [00:31<00:00, 155.20it/s, loss=0.1782]


Epoch 7/15 - Loss: 0.1337, Accuracy: 0.8832


Epoch 8/15: 100%|██████████| 4929/4929 [00:31<00:00, 156.50it/s, loss=0.1504]


Epoch 8/15 - Loss: 0.1331, Accuracy: 0.8837


Epoch 9/15: 100%|██████████| 4929/4929 [00:31<00:00, 158.03it/s, loss=0.2461]


Epoch 9/15 - Loss: 0.1328, Accuracy: 0.8837


Epoch 10/15: 100%|██████████| 4929/4929 [00:32<00:00, 152.55it/s, loss=0.1968]


Epoch 10/15 - Loss: 0.1329, Accuracy: 0.8837


Epoch 11/15: 100%|██████████| 4929/4929 [00:31<00:00, 156.02it/s, loss=0.1292]


Epoch 11/15 - Loss: 0.1327, Accuracy: 0.8841


Epoch 12/15: 100%|██████████| 4929/4929 [00:31<00:00, 156.26it/s, loss=0.1082]


Epoch 12/15 - Loss: 0.1321, Accuracy: 0.8848


Epoch 13/15: 100%|██████████| 4929/4929 [00:31<00:00, 158.50it/s, loss=0.2777]


Epoch 13/15 - Loss: 0.1321, Accuracy: 0.8847


Epoch 14/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.74it/s, loss=0.1560]


Epoch 14/15 - Loss: 0.1323, Accuracy: 0.8838


Epoch 15/15: 100%|██████████| 4929/4929 [00:31<00:00, 156.46it/s, loss=0.2103]


Epoch 15/15 - Loss: 0.1314, Accuracy: 0.8847
Fold 8 Accuracy: 0.8450
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.82it/s, loss=0.0895]


Epoch 1/15 - Loss: 0.1331, Accuracy: 0.8836


Epoch 2/15: 100%|██████████| 4929/4929 [00:31<00:00, 155.90it/s, loss=0.1866]


Epoch 2/15 - Loss: 0.1324, Accuracy: 0.8842


Epoch 3/15: 100%|██████████| 4929/4929 [00:31<00:00, 156.81it/s, loss=0.1752]


Epoch 3/15 - Loss: 0.1324, Accuracy: 0.8837


Epoch 4/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.15it/s, loss=0.1647]


Epoch 4/15 - Loss: 0.1319, Accuracy: 0.8843


Epoch 5/15: 100%|██████████| 4929/4929 [00:34<00:00, 143.33it/s, loss=0.0413]


Epoch 5/15 - Loss: 0.1320, Accuracy: 0.8844


Epoch 6/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.83it/s, loss=0.0925]


Epoch 6/15 - Loss: 0.1310, Accuracy: 0.8848


Epoch 7/15: 100%|██████████| 4929/4929 [00:31<00:00, 156.19it/s, loss=0.2548]


Epoch 7/15 - Loss: 0.1314, Accuracy: 0.8854


Epoch 8/15: 100%|██████████| 4929/4929 [00:31<00:00, 155.29it/s, loss=0.0663]


Epoch 8/15 - Loss: 0.1310, Accuracy: 0.8849


Epoch 9/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.82it/s, loss=0.1697]


Epoch 9/15 - Loss: 0.1305, Accuracy: 0.8857


Epoch 10/15: 100%|██████████| 4929/4929 [00:33<00:00, 147.15it/s, loss=0.0732]


Epoch 10/15 - Loss: 0.1307, Accuracy: 0.8856


Epoch 11/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.88it/s, loss=0.2203]


Epoch 11/15 - Loss: 0.1307, Accuracy: 0.8854


Epoch 12/15: 100%|██████████| 4929/4929 [00:33<00:00, 146.05it/s, loss=0.1219]


Epoch 12/15 - Loss: 0.1308, Accuracy: 0.8852


Epoch 13/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.57it/s, loss=0.1098]


Epoch 13/15 - Loss: 0.1304, Accuracy: 0.8857


Epoch 14/15: 100%|██████████| 4929/4929 [00:32<00:00, 152.20it/s, loss=0.0844]


Epoch 14/15 - Loss: 0.1298, Accuracy: 0.8861


Epoch 15/15: 100%|██████████| 4929/4929 [00:31<00:00, 154.50it/s, loss=0.0441]


Epoch 15/15 - Loss: 0.1296, Accuracy: 0.8863
Fold 9 Accuracy: 0.8387
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:32<00:00, 153.49it/s, loss=0.1037]


Epoch 1/15 - Loss: 0.1313, Accuracy: 0.8852


Epoch 2/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.78it/s, loss=0.1598]


Epoch 2/15 - Loss: 0.1311, Accuracy: 0.8851


Epoch 3/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.66it/s, loss=0.1204]


Epoch 3/15 - Loss: 0.1308, Accuracy: 0.8855


Epoch 4/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.57it/s, loss=0.1092]


Epoch 4/15 - Loss: 0.1307, Accuracy: 0.8855


Epoch 5/15: 100%|██████████| 4929/4929 [00:51<00:00, 95.54it/s, loss=0.1773] 


Epoch 5/15 - Loss: 0.1301, Accuracy: 0.8858


Epoch 6/15: 100%|██████████| 4929/4929 [00:29<00:00, 169.87it/s, loss=0.1570]


Epoch 6/15 - Loss: 0.1301, Accuracy: 0.8861


Epoch 7/15: 100%|██████████| 4929/4929 [00:28<00:00, 170.37it/s, loss=0.1770]


Epoch 7/15 - Loss: 0.1301, Accuracy: 0.8860


Epoch 8/15: 100%|██████████| 4929/4929 [00:28<00:00, 170.86it/s, loss=0.1932]


Epoch 8/15 - Loss: 0.1297, Accuracy: 0.8861


Epoch 9/15: 100%|██████████| 4929/4929 [00:31<00:00, 155.30it/s, loss=0.0609]


Epoch 9/15 - Loss: 0.1296, Accuracy: 0.8859


Epoch 10/15: 100%|██████████| 4929/4929 [00:32<00:00, 152.17it/s, loss=0.1283]


Epoch 10/15 - Loss: 0.1296, Accuracy: 0.8863


Epoch 11/15: 100%|██████████| 4929/4929 [00:34<00:00, 143.94it/s, loss=0.0677]


Epoch 11/15 - Loss: 0.1290, Accuracy: 0.8867


Epoch 12/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.83it/s, loss=0.1632]


Epoch 12/15 - Loss: 0.1289, Accuracy: 0.8870


Epoch 13/15: 100%|██████████| 4929/4929 [00:32<00:00, 151.69it/s, loss=0.1228]


Epoch 13/15 - Loss: 0.1287, Accuracy: 0.8868


Epoch 14/15: 100%|██████████| 4929/4929 [00:31<00:00, 157.08it/s, loss=0.0341]


Epoch 14/15 - Loss: 0.1291, Accuracy: 0.8869


Epoch 15/15: 100%|██████████| 4929/4929 [00:32<00:00, 150.93it/s, loss=0.0713]


Epoch 15/15 - Loss: 0.1286, Accuracy: 0.8866
Fold 10 Accuracy: 0.8525
Complete model saved to UNSW-PCNN-BiLSTM.pth
Fold Accuracies:
  Fold 1: 0.8154
  Fold 2: 0.8176
  Fold 3: 0.8300
  Fold 4: 0.8254
  Fold 5: 0.8339
  Fold 6: 0.8383
  Fold 7: 0.8403
  Fold 8: 0.8450
  Fold 9: 0.8387
  Fold 10: 0.8525


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  40    0   50  126   37    0   15    0    0    0]
 [   0   35   50  105   42    0    0    0    0    0]
 [   0    1  572  988   41    6    6   12    8    1]
 [   1    3  470 3692  101   10   46  109   14    6]
 [   0    0   62  149 1624    1  568    6   13    2]
 [   0    0   20   24    3 5837    1    2    0    0]
 [   7    0    5   38  349    1 8887    7    6    0]
 [   0    0   57  199    2    1    2 1138    0    0]
 [   0    0    0   11    4    1    6    6  123    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.83      0.15      0.25       268
      Backdoor       0.90      0.15      0.26       232
           DoS       0.44      0.35      0.39      1635
      Exploits       0.69      0.83      0.75      4452
       Fuzzers       0.74      0.67      0.70      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.