In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15    
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

# class FocalLoss(nn.Module):
#     def __init__(self, alpha=1, gamma=2, reduction='mean'):
#         super(FocalLoss, self).__init__()
#         self.alpha = alpha
#         self.gamma = gamma
#         self.reduction = reduction
# 
#     def forward(self, inputs, targets):
#         ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
#         pt = torch.exp(-ce_loss)  # 预测的概率
#         focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss
# 
#         if self.reduction == 'mean':
#             return focal_loss.mean()
#         elif self.reduction == 'sum':
#             return focal_loss.sum()
#         else:
#             return focal_loss

# criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-CEloss.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4929/4929 [00:58<00:00, 83.60it/s, loss=0.5087]


Epoch 1/15 - Loss: 0.4743, Accuracy: 0.8223


Epoch 2/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.13it/s, loss=0.2367]


Epoch 2/15 - Loss: 0.3937, Accuracy: 0.8471


Epoch 3/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.41it/s, loss=0.3303]


Epoch 3/15 - Loss: 0.3741, Accuracy: 0.8528


Epoch 4/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.20it/s, loss=0.4370]


Epoch 4/15 - Loss: 0.3634, Accuracy: 0.8553


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.80it/s, loss=0.3291]


Epoch 5/15 - Loss: 0.3548, Accuracy: 0.8581


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.54it/s, loss=0.2587]


Epoch 6/15 - Loss: 0.3498, Accuracy: 0.8595


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.96it/s, loss=0.2564]


Epoch 7/15 - Loss: 0.3454, Accuracy: 0.8607


Epoch 8/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.18it/s, loss=0.2895]


Epoch 8/15 - Loss: 0.3412, Accuracy: 0.8617


Epoch 9/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.29it/s, loss=0.1437]


Epoch 9/15 - Loss: 0.3378, Accuracy: 0.8629


Epoch 10/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.08it/s, loss=0.3735]


Epoch 10/15 - Loss: 0.3346, Accuracy: 0.8643


Epoch 11/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.33it/s, loss=0.3351]


Epoch 11/15 - Loss: 0.3318, Accuracy: 0.8656


Epoch 12/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.31it/s, loss=0.3547]


Epoch 12/15 - Loss: 0.3294, Accuracy: 0.8663


Epoch 13/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.15it/s, loss=0.3432]


Epoch 13/15 - Loss: 0.3267, Accuracy: 0.8666


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.94it/s, loss=0.2952]


Epoch 14/15 - Loss: 0.3239, Accuracy: 0.8670


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.88it/s, loss=0.3025]


Epoch 15/15 - Loss: 0.3213, Accuracy: 0.8681
Fold 1 Accuracy: 0.8171
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.07it/s, loss=0.2431]


Epoch 1/15 - Loss: 0.3235, Accuracy: 0.8676


Epoch 2/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.11it/s, loss=0.2518]


Epoch 2/15 - Loss: 0.3209, Accuracy: 0.8686


Epoch 3/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.34it/s, loss=0.2967]


Epoch 3/15 - Loss: 0.3189, Accuracy: 0.8699


Epoch 4/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.82it/s, loss=0.2775]


Epoch 4/15 - Loss: 0.3168, Accuracy: 0.8703


Epoch 5/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.38it/s, loss=0.2639]


Epoch 5/15 - Loss: 0.3148, Accuracy: 0.8702


Epoch 6/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.57it/s, loss=0.3943]


Epoch 6/15 - Loss: 0.3138, Accuracy: 0.8712


Epoch 7/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.34it/s, loss=0.3160]


Epoch 7/15 - Loss: 0.3124, Accuracy: 0.8713


Epoch 8/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.09it/s, loss=0.2103]


Epoch 8/15 - Loss: 0.3099, Accuracy: 0.8725


Epoch 9/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.45it/s, loss=0.3663]


Epoch 9/15 - Loss: 0.3092, Accuracy: 0.8731


Epoch 10/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.11it/s, loss=0.2605]


Epoch 10/15 - Loss: 0.3082, Accuracy: 0.8731


Epoch 11/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.53it/s, loss=0.3148]


Epoch 11/15 - Loss: 0.3069, Accuracy: 0.8734


Epoch 12/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.49it/s, loss=0.2291]


Epoch 12/15 - Loss: 0.3057, Accuracy: 0.8741


Epoch 13/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.22it/s, loss=0.3436]


Epoch 13/15 - Loss: 0.3044, Accuracy: 0.8739


Epoch 14/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.22it/s, loss=0.4251]


Epoch 14/15 - Loss: 0.3039, Accuracy: 0.8745


Epoch 15/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.56it/s, loss=0.4328]


Epoch 15/15 - Loss: 0.3023, Accuracy: 0.8752
Fold 2 Accuracy: 0.8259
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.12it/s, loss=0.2587]


Epoch 1/15 - Loss: 0.3051, Accuracy: 0.8740


Epoch 2/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.36it/s, loss=0.3638]


Epoch 2/15 - Loss: 0.3040, Accuracy: 0.8748


Epoch 3/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.44it/s, loss=0.1861]


Epoch 3/15 - Loss: 0.3020, Accuracy: 0.8751


Epoch 4/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.31it/s, loss=0.3038]


Epoch 4/15 - Loss: 0.3013, Accuracy: 0.8752


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.91it/s, loss=0.2270]


Epoch 5/15 - Loss: 0.2995, Accuracy: 0.8764


Epoch 6/15: 100%|██████████| 4929/4929 [01:03<00:00, 77.69it/s, loss=0.1896]


Epoch 6/15 - Loss: 0.2985, Accuracy: 0.8764


Epoch 7/15: 100%|██████████| 4929/4929 [01:16<00:00, 64.04it/s, loss=0.3427]


Epoch 7/15 - Loss: 0.2977, Accuracy: 0.8769


Epoch 8/15: 100%|██████████| 4929/4929 [01:37<00:00, 50.32it/s, loss=0.3107]


Epoch 8/15 - Loss: 0.2969, Accuracy: 0.8769


Epoch 9/15: 100%|██████████| 4929/4929 [01:42<00:00, 48.21it/s, loss=0.2562]


Epoch 9/15 - Loss: 0.2965, Accuracy: 0.8766


Epoch 10/15: 100%|██████████| 4929/4929 [01:38<00:00, 50.09it/s, loss=0.2262]


Epoch 10/15 - Loss: 0.2946, Accuracy: 0.8773


Epoch 11/15: 100%|██████████| 4929/4929 [01:35<00:00, 51.70it/s, loss=0.1916]


Epoch 11/15 - Loss: 0.2953, Accuracy: 0.8769


Epoch 12/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.63it/s, loss=0.3318]


Epoch 12/15 - Loss: 0.2936, Accuracy: 0.8785


Epoch 13/15: 100%|██████████| 4929/4929 [01:23<00:00, 58.89it/s, loss=0.2773]


Epoch 13/15 - Loss: 0.2932, Accuracy: 0.8781


Epoch 14/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.57it/s, loss=0.4277]


Epoch 14/15 - Loss: 0.2921, Accuracy: 0.8784


Epoch 15/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.76it/s, loss=0.4241]


Epoch 15/15 - Loss: 0.2919, Accuracy: 0.8791
Fold 3 Accuracy: 0.8328
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.34it/s, loss=0.3324]


Epoch 1/15 - Loss: 0.2931, Accuracy: 0.8783


Epoch 2/15: 100%|██████████| 4929/4929 [01:31<00:00, 54.04it/s, loss=0.3113]


Epoch 2/15 - Loss: 0.2921, Accuracy: 0.8788


Epoch 3/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.52it/s, loss=0.2103]


Epoch 3/15 - Loss: 0.2908, Accuracy: 0.8796


Epoch 4/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.57it/s, loss=0.3414]


Epoch 4/15 - Loss: 0.2901, Accuracy: 0.8798


Epoch 5/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.37it/s, loss=0.2677]


Epoch 5/15 - Loss: 0.2889, Accuracy: 0.8804


Epoch 6/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.63it/s, loss=0.3860]


Epoch 6/15 - Loss: 0.2885, Accuracy: 0.8803


Epoch 7/15: 100%|██████████| 4929/4929 [01:34<00:00, 52.07it/s, loss=0.2616]


Epoch 7/15 - Loss: 0.2875, Accuracy: 0.8801


Epoch 8/15: 100%|██████████| 4929/4929 [01:31<00:00, 53.72it/s, loss=0.3994]


Epoch 8/15 - Loss: 0.2873, Accuracy: 0.8804


Epoch 9/15: 100%|██████████| 4929/4929 [01:31<00:00, 54.09it/s, loss=0.2944]


Epoch 9/15 - Loss: 0.2857, Accuracy: 0.8813


Epoch 10/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.67it/s, loss=0.2596]


Epoch 10/15 - Loss: 0.2852, Accuracy: 0.8811


Epoch 11/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.12it/s, loss=0.4550]


Epoch 11/15 - Loss: 0.2847, Accuracy: 0.8815


Epoch 12/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.14it/s, loss=0.2650]


Epoch 12/15 - Loss: 0.2844, Accuracy: 0.8813


Epoch 13/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.27it/s, loss=0.3004]


Epoch 13/15 - Loss: 0.2835, Accuracy: 0.8819


Epoch 14/15: 100%|██████████| 4929/4929 [01:00<00:00, 81.49it/s, loss=0.2039]


Epoch 14/15 - Loss: 0.2828, Accuracy: 0.8824


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.70it/s, loss=0.2782]


Epoch 15/15 - Loss: 0.2820, Accuracy: 0.8822
Fold 4 Accuracy: 0.8303
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.66it/s, loss=0.1217]


Epoch 1/15 - Loss: 0.2862, Accuracy: 0.8816


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.66it/s, loss=0.1787]


Epoch 2/15 - Loss: 0.2850, Accuracy: 0.8819


Epoch 3/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.13it/s, loss=0.3962]


Epoch 3/15 - Loss: 0.2837, Accuracy: 0.8820


Epoch 4/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.62it/s, loss=0.2428]


Epoch 4/15 - Loss: 0.2831, Accuracy: 0.8818


Epoch 5/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.00it/s, loss=0.2655]


Epoch 5/15 - Loss: 0.2821, Accuracy: 0.8825


Epoch 6/15: 100%|██████████| 4929/4929 [01:30<00:00, 54.55it/s, loss=0.2251]


Epoch 6/15 - Loss: 0.2816, Accuracy: 0.8824


Epoch 7/15: 100%|██████████| 4929/4929 [01:31<00:00, 54.07it/s, loss=0.3434]


Epoch 7/15 - Loss: 0.2810, Accuracy: 0.8830


Epoch 8/15: 100%|██████████| 4929/4929 [01:26<00:00, 56.78it/s, loss=0.2464]


Epoch 8/15 - Loss: 0.2793, Accuracy: 0.8838


Epoch 9/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.91it/s, loss=0.4599]


Epoch 9/15 - Loss: 0.2806, Accuracy: 0.8831


Epoch 10/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.54it/s, loss=0.2680]


Epoch 10/15 - Loss: 0.2790, Accuracy: 0.8837


Epoch 11/15: 100%|██████████| 4929/4929 [01:27<00:00, 56.12it/s, loss=0.2703]


Epoch 11/15 - Loss: 0.2777, Accuracy: 0.8844


Epoch 12/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.95it/s, loss=0.3236]


Epoch 12/15 - Loss: 0.2773, Accuracy: 0.8846


Epoch 13/15: 100%|██████████| 4929/4929 [01:26<00:00, 56.79it/s, loss=0.2281]


Epoch 13/15 - Loss: 0.2768, Accuracy: 0.8848


Epoch 14/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.51it/s, loss=0.1968]


Epoch 14/15 - Loss: 0.2776, Accuracy: 0.8841


Epoch 15/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.10it/s, loss=0.2507]


Epoch 15/15 - Loss: 0.2760, Accuracy: 0.8845
Fold 5 Accuracy: 0.8406
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.41it/s, loss=0.3257]


Epoch 1/15 - Loss: 0.2795, Accuracy: 0.8835


Epoch 2/15: 100%|██████████| 4929/4929 [01:35<00:00, 51.84it/s, loss=0.2189]


Epoch 2/15 - Loss: 0.2774, Accuracy: 0.8845


Epoch 3/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.25it/s, loss=0.3420]


Epoch 3/15 - Loss: 0.2771, Accuracy: 0.8849


Epoch 4/15: 100%|██████████| 4929/4929 [01:00<00:00, 81.42it/s, loss=0.2011]


Epoch 4/15 - Loss: 0.2754, Accuracy: 0.8854


Epoch 5/15: 100%|██████████| 4929/4929 [01:11<00:00, 68.57it/s, loss=0.2899]


Epoch 5/15 - Loss: 0.2753, Accuracy: 0.8854


Epoch 6/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.12it/s, loss=0.3073]


Epoch 6/15 - Loss: 0.2748, Accuracy: 0.8852


Epoch 7/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.06it/s, loss=0.1939]


Epoch 7/15 - Loss: 0.2742, Accuracy: 0.8858


Epoch 8/15: 100%|██████████| 4929/4929 [01:27<00:00, 56.24it/s, loss=0.2433]


Epoch 8/15 - Loss: 0.2741, Accuracy: 0.8857


Epoch 9/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.47it/s, loss=0.2929]


Epoch 9/15 - Loss: 0.2729, Accuracy: 0.8863


Epoch 10/15: 100%|██████████| 4929/4929 [01:26<00:00, 56.81it/s, loss=0.3549]


Epoch 10/15 - Loss: 0.2724, Accuracy: 0.8860


Epoch 11/15: 100%|██████████| 4929/4929 [01:23<00:00, 59.31it/s, loss=0.2186]


Epoch 11/15 - Loss: 0.2716, Accuracy: 0.8864


Epoch 12/15: 100%|██████████| 4929/4929 [01:26<00:00, 56.72it/s, loss=0.2233]


Epoch 12/15 - Loss: 0.2717, Accuracy: 0.8866


Epoch 13/15: 100%|██████████| 4929/4929 [01:29<00:00, 54.99it/s, loss=0.3492]


Epoch 13/15 - Loss: 0.2709, Accuracy: 0.8868


Epoch 14/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.01it/s, loss=0.3692]


Epoch 14/15 - Loss: 0.2707, Accuracy: 0.8872


Epoch 15/15: 100%|██████████| 4929/4929 [01:23<00:00, 58.74it/s, loss=0.2049]


Epoch 15/15 - Loss: 0.2702, Accuracy: 0.8875
Fold 6 Accuracy: 0.8453
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.12it/s, loss=0.2416]


Epoch 1/15 - Loss: 0.2721, Accuracy: 0.8864


Epoch 2/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.72it/s, loss=0.5374]


Epoch 2/15 - Loss: 0.2716, Accuracy: 0.8871


Epoch 3/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.51it/s, loss=0.2749]


Epoch 3/15 - Loss: 0.2700, Accuracy: 0.8867


Epoch 4/15: 100%|██████████| 4929/4929 [01:23<00:00, 59.02it/s, loss=0.2731]


Epoch 4/15 - Loss: 0.2692, Accuracy: 0.8875


Epoch 5/15: 100%|██████████| 4929/4929 [01:29<00:00, 54.80it/s, loss=0.2745]


Epoch 5/15 - Loss: 0.2690, Accuracy: 0.8876


Epoch 6/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.56it/s, loss=0.2167]


Epoch 6/15 - Loss: 0.2687, Accuracy: 0.8872


Epoch 7/15: 100%|██████████| 4929/4929 [01:23<00:00, 59.03it/s, loss=0.3253]


Epoch 7/15 - Loss: 0.2677, Accuracy: 0.8883


Epoch 8/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.97it/s, loss=0.1698]


Epoch 8/15 - Loss: 0.2672, Accuracy: 0.8877


Epoch 9/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.30it/s, loss=0.2649]


Epoch 9/15 - Loss: 0.2665, Accuracy: 0.8887


Epoch 10/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.28it/s, loss=0.2316]


Epoch 10/15 - Loss: 0.2669, Accuracy: 0.8883


Epoch 11/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.28it/s, loss=0.3121]


Epoch 11/15 - Loss: 0.2657, Accuracy: 0.8888


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.65it/s, loss=0.1868]


Epoch 12/15 - Loss: 0.2657, Accuracy: 0.8888


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.80it/s, loss=0.1722]


Epoch 13/15 - Loss: 0.2644, Accuracy: 0.8895


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.17it/s, loss=0.1797]


Epoch 14/15 - Loss: 0.2644, Accuracy: 0.8896


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.89it/s, loss=0.2718]


Epoch 15/15 - Loss: 0.2643, Accuracy: 0.8899
Fold 7 Accuracy: 0.8436
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.48it/s, loss=0.2631]


Epoch 1/15 - Loss: 0.2680, Accuracy: 0.8883


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.93it/s, loss=0.2729]


Epoch 2/15 - Loss: 0.2669, Accuracy: 0.8888


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.2425]


Epoch 3/15 - Loss: 0.2664, Accuracy: 0.8887


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.40it/s, loss=0.2081]


Epoch 4/15 - Loss: 0.2646, Accuracy: 0.8889


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.96it/s, loss=0.1864]


Epoch 5/15 - Loss: 0.2649, Accuracy: 0.8895


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.01it/s, loss=0.2078]


Epoch 6/15 - Loss: 0.2651, Accuracy: 0.8890


Epoch 7/15: 100%|██████████| 4929/4929 [01:16<00:00, 64.20it/s, loss=0.3466]


Epoch 7/15 - Loss: 0.2638, Accuracy: 0.8898


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.66it/s, loss=0.2651]


Epoch 8/15 - Loss: 0.2638, Accuracy: 0.8895


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.42it/s, loss=0.2430]


Epoch 9/15 - Loss: 0.2627, Accuracy: 0.8906


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.12it/s, loss=0.1382]


Epoch 10/15 - Loss: 0.2625, Accuracy: 0.8900


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.44it/s, loss=0.2585]


Epoch 11/15 - Loss: 0.2618, Accuracy: 0.8905


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.62it/s, loss=0.1925]


Epoch 12/15 - Loss: 0.2621, Accuracy: 0.8909


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.3776]


Epoch 13/15 - Loss: 0.2614, Accuracy: 0.8905


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.83it/s, loss=0.4714]


Epoch 14/15 - Loss: 0.2606, Accuracy: 0.8908


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.18it/s, loss=0.1963]


Epoch 15/15 - Loss: 0.2602, Accuracy: 0.8913
Fold 8 Accuracy: 0.8521
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.11it/s, loss=0.1421]


Epoch 1/15 - Loss: 0.2647, Accuracy: 0.8893


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.15it/s, loss=0.2987]


Epoch 2/15 - Loss: 0.2627, Accuracy: 0.8901


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.34it/s, loss=0.3396]


Epoch 3/15 - Loss: 0.2622, Accuracy: 0.8907


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.68it/s, loss=0.2204]


Epoch 4/15 - Loss: 0.2606, Accuracy: 0.8911


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.68it/s, loss=0.2870]


Epoch 5/15 - Loss: 0.2605, Accuracy: 0.8914


Epoch 6/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.20it/s, loss=0.3699]


Epoch 6/15 - Loss: 0.2598, Accuracy: 0.8910


Epoch 7/15: 100%|██████████| 4929/4929 [01:19<00:00, 61.66it/s, loss=0.2403]


Epoch 7/15 - Loss: 0.2590, Accuracy: 0.8917


Epoch 8/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.52it/s, loss=0.3884]


Epoch 8/15 - Loss: 0.2588, Accuracy: 0.8915


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.89it/s, loss=0.2309]


Epoch 9/15 - Loss: 0.2585, Accuracy: 0.8922


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.97it/s, loss=0.3687]


Epoch 10/15 - Loss: 0.2587, Accuracy: 0.8913


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.61it/s, loss=0.1920]


Epoch 11/15 - Loss: 0.2576, Accuracy: 0.8925


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.97it/s, loss=0.1923]


Epoch 12/15 - Loss: 0.2578, Accuracy: 0.8924


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.89it/s, loss=0.1929]


Epoch 13/15 - Loss: 0.2567, Accuracy: 0.8922


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.07it/s, loss=0.1226]


Epoch 14/15 - Loss: 0.2568, Accuracy: 0.8922


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.80it/s, loss=0.2271]


Epoch 15/15 - Loss: 0.2564, Accuracy: 0.8927
Fold 9 Accuracy: 0.8518
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.35it/s, loss=0.1744]


Epoch 1/15 - Loss: 0.2608, Accuracy: 0.8908


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.52it/s, loss=0.3742]


Epoch 2/15 - Loss: 0.2584, Accuracy: 0.8915


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.27it/s, loss=0.3209]


Epoch 3/15 - Loss: 0.2578, Accuracy: 0.8923


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.52it/s, loss=0.1178]


Epoch 4/15 - Loss: 0.2584, Accuracy: 0.8918


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.63it/s, loss=0.2727]


Epoch 5/15 - Loss: 0.2576, Accuracy: 0.8925


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.70it/s, loss=0.2723]


Epoch 6/15 - Loss: 0.2566, Accuracy: 0.8925


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.85it/s, loss=0.3239]


Epoch 7/15 - Loss: 0.2566, Accuracy: 0.8925


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.88it/s, loss=0.2574]


Epoch 8/15 - Loss: 0.2560, Accuracy: 0.8935


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.97it/s, loss=0.3771]


Epoch 9/15 - Loss: 0.2558, Accuracy: 0.8927


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.86it/s, loss=0.2130]


Epoch 10/15 - Loss: 0.2550, Accuracy: 0.8932


Epoch 11/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.04it/s, loss=0.2891]


Epoch 11/15 - Loss: 0.2546, Accuracy: 0.8936


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.70it/s, loss=0.3010]


Epoch 12/15 - Loss: 0.2553, Accuracy: 0.8935


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.98it/s, loss=0.3271]


Epoch 13/15 - Loss: 0.2539, Accuracy: 0.8937


Epoch 14/15: 100%|██████████| 4929/4929 [01:09<00:00, 70.98it/s, loss=0.3617]


Epoch 14/15 - Loss: 0.2534, Accuracy: 0.8941


Epoch 15/15: 100%|██████████| 4929/4929 [01:35<00:00, 51.54it/s, loss=0.2724]


Epoch 15/15 - Loss: 0.2532, Accuracy: 0.8942
Fold 10 Accuracy: 0.8595
Complete model saved to modelU12.pth
Fold Accuracies:
  Fold 1: 0.8171
  Fold 2: 0.8259
  Fold 3: 0.8328
  Fold 4: 0.8303
  Fold 5: 0.8406
  Fold 6: 0.8453
  Fold 7: 0.8436
  Fold 8: 0.8521
  Fold 9: 0.8518
  Fold 10: 0.8595


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  28    0   11  186   16    0   27    0    0    0]
 [   0   31   16  169   15    0    0    0    1    0]
 [   0    0  265 1311   22   10    5   12    9    1]
 [   1    4  114 4112   78   19   49   53   12   10]
 [   1    0   15  223 1704    1  460    8   11    2]
 [   0    0    5   39    1 5837    2    3    0    0]
 [   4    0    4   32  306    1 8943    5    4    1]
 [   0    0   14  271    1    1    2 1107    3    0]
 [   0    0    3   18   10    0   14    5  101    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.82      0.10      0.19       268
      Backdoor       0.89      0.13      0.23       232
           DoS       0.59      0.16      0.25      1635
      Exploits       0.65      0.92      0.76      4452
       Fuzzers       0.79      0.70      0.74      2425
       Generic       0.99      0.99      0.99      5887
        Normal       0.