In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
criterion = nn.CrossEntropyLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "modelU12.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.89it/s, loss=0.4649]


Epoch 1/15 - Loss: 0.2682, Accuracy: 0.8184


Epoch 2/15: 100%|██████████| 4929/4929 [00:41<00:00, 117.99it/s, loss=0.1927]


Epoch 2/15 - Loss: 0.2061, Accuracy: 0.8467


Epoch 3/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.12it/s, loss=0.1734]


Epoch 3/15 - Loss: 0.1950, Accuracy: 0.8510


Epoch 4/15: 100%|██████████| 4929/4929 [01:07<00:00, 72.67it/s, loss=0.2758] 


Epoch 4/15 - Loss: 0.1883, Accuracy: 0.8547


Epoch 5/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.25it/s, loss=0.2204]


Epoch 5/15 - Loss: 0.1851, Accuracy: 0.8561


Epoch 6/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.22it/s, loss=0.1548]


Epoch 6/15 - Loss: 0.1816, Accuracy: 0.8570


Epoch 7/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.90it/s, loss=0.1382]


Epoch 7/15 - Loss: 0.1785, Accuracy: 0.8583


Epoch 8/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.84it/s, loss=0.0714]


Epoch 8/15 - Loss: 0.1772, Accuracy: 0.8588


Epoch 9/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.90it/s, loss=0.3156]


Epoch 9/15 - Loss: 0.1745, Accuracy: 0.8603


Epoch 10/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.09it/s, loss=0.1947]


Epoch 10/15 - Loss: 0.1735, Accuracy: 0.8606


Epoch 11/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.94it/s, loss=0.1889]


Epoch 11/15 - Loss: 0.1710, Accuracy: 0.8619


Epoch 12/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.19it/s, loss=0.1528]


Epoch 12/15 - Loss: 0.1701, Accuracy: 0.8624


Epoch 13/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.34it/s, loss=0.2841]


Epoch 13/15 - Loss: 0.1693, Accuracy: 0.8620


Epoch 14/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.92it/s, loss=0.1452]


Epoch 14/15 - Loss: 0.1678, Accuracy: 0.8639


Epoch 15/15: 100%|██████████| 4929/4929 [01:24<00:00, 57.99it/s, loss=0.1916]


Epoch 15/15 - Loss: 0.1666, Accuracy: 0.8640
Fold 1 Accuracy: 0.8157
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.93it/s, loss=0.1687]


Epoch 1/15 - Loss: 0.1677, Accuracy: 0.8633


Epoch 2/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.76it/s, loss=0.2360]


Epoch 2/15 - Loss: 0.1662, Accuracy: 0.8648


Epoch 3/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.76it/s, loss=0.1183]


Epoch 3/15 - Loss: 0.1645, Accuracy: 0.8656


Epoch 4/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.04it/s, loss=0.1972]


Epoch 4/15 - Loss: 0.1636, Accuracy: 0.8660


Epoch 5/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.55it/s, loss=0.0647]


Epoch 5/15 - Loss: 0.1629, Accuracy: 0.8660


Epoch 6/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.89it/s, loss=0.0668]


Epoch 6/15 - Loss: 0.1614, Accuracy: 0.8677


Epoch 7/15: 100%|██████████| 4929/4929 [01:20<00:00, 61.42it/s, loss=0.1420] 


Epoch 7/15 - Loss: 0.1607, Accuracy: 0.8668


Epoch 8/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.55it/s, loss=0.1495]


Epoch 8/15 - Loss: 0.1601, Accuracy: 0.8671


Epoch 9/15: 100%|██████████| 4929/4929 [00:42<00:00, 114.68it/s, loss=0.1476]


Epoch 9/15 - Loss: 0.1590, Accuracy: 0.8683


Epoch 10/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.52it/s, loss=0.1137]


Epoch 10/15 - Loss: 0.1582, Accuracy: 0.8687


Epoch 11/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.31it/s, loss=0.1112]


Epoch 11/15 - Loss: 0.1571, Accuracy: 0.8696


Epoch 12/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.03it/s, loss=0.3153]


Epoch 12/15 - Loss: 0.1560, Accuracy: 0.8700


Epoch 13/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.23it/s, loss=0.3521]


Epoch 13/15 - Loss: 0.1563, Accuracy: 0.8697


Epoch 14/15: 100%|██████████| 4929/4929 [00:42<00:00, 114.88it/s, loss=0.2052]


Epoch 14/15 - Loss: 0.1557, Accuracy: 0.8697


Epoch 15/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.27it/s, loss=0.1217]


Epoch 15/15 - Loss: 0.1547, Accuracy: 0.8703
Fold 2 Accuracy: 0.8228
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.58it/s, loss=0.1654]


Epoch 1/15 - Loss: 0.1562, Accuracy: 0.8697


Epoch 2/15: 100%|██████████| 4929/4929 [00:42<00:00, 115.03it/s, loss=0.0864]


Epoch 2/15 - Loss: 0.1549, Accuracy: 0.8702


Epoch 3/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.20it/s, loss=0.1351]


Epoch 3/15 - Loss: 0.1539, Accuracy: 0.8707


Epoch 4/15: 100%|██████████| 4929/4929 [00:42<00:00, 114.76it/s, loss=0.1752]


Epoch 4/15 - Loss: 0.1528, Accuracy: 0.8707


Epoch 5/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.84it/s, loss=0.0877]


Epoch 5/15 - Loss: 0.1524, Accuracy: 0.8715


Epoch 6/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.05it/s, loss=0.2245]


Epoch 6/15 - Loss: 0.1519, Accuracy: 0.8714


Epoch 7/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.00it/s, loss=0.1232]


Epoch 7/15 - Loss: 0.1512, Accuracy: 0.8721


Epoch 8/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.15it/s, loss=0.1750]


Epoch 8/15 - Loss: 0.1506, Accuracy: 0.8727


Epoch 9/15: 100%|██████████| 4929/4929 [01:18<00:00, 63.10it/s, loss=0.1569] 


Epoch 9/15 - Loss: 0.1502, Accuracy: 0.8722


Epoch 10/15: 100%|██████████| 4929/4929 [01:22<00:00, 59.74it/s, loss=0.0915]


Epoch 10/15 - Loss: 0.1496, Accuracy: 0.8729


Epoch 11/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.96it/s, loss=0.1525]


Epoch 11/15 - Loss: 0.1492, Accuracy: 0.8729


Epoch 12/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.62it/s, loss=0.0412]


Epoch 12/15 - Loss: 0.1491, Accuracy: 0.8733


Epoch 13/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.75it/s, loss=0.1271]


Epoch 13/15 - Loss: 0.1484, Accuracy: 0.8735


Epoch 14/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.87it/s, loss=0.2027]


Epoch 14/15 - Loss: 0.1478, Accuracy: 0.8741


Epoch 15/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.83it/s, loss=0.2412]


Epoch 15/15 - Loss: 0.1476, Accuracy: 0.8739
Fold 3 Accuracy: 0.8308
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.27it/s, loss=0.1516]


Epoch 1/15 - Loss: 0.1485, Accuracy: 0.8735


Epoch 2/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.24it/s, loss=0.1008]


Epoch 2/15 - Loss: 0.1481, Accuracy: 0.8743


Epoch 3/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.96it/s, loss=0.1714]


Epoch 3/15 - Loss: 0.1475, Accuracy: 0.8746


Epoch 4/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.98it/s, loss=0.2364]


Epoch 4/15 - Loss: 0.1466, Accuracy: 0.8749


Epoch 5/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.93it/s, loss=0.2307]


Epoch 5/15 - Loss: 0.1466, Accuracy: 0.8748


Epoch 6/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.52it/s, loss=0.0829]


Epoch 6/15 - Loss: 0.1457, Accuracy: 0.8753


Epoch 7/15: 100%|██████████| 4929/4929 [01:32<00:00, 53.10it/s, loss=0.1284]


Epoch 7/15 - Loss: 0.1451, Accuracy: 0.8755


Epoch 8/15: 100%|██████████| 4929/4929 [01:33<00:00, 52.47it/s, loss=0.0647]


Epoch 8/15 - Loss: 0.1446, Accuracy: 0.8761


Epoch 9/15: 100%|██████████| 4929/4929 [01:30<00:00, 54.32it/s, loss=0.3741]


Epoch 9/15 - Loss: 0.1444, Accuracy: 0.8762


Epoch 10/15: 100%|██████████| 4929/4929 [01:31<00:00, 54.11it/s, loss=0.2202]


Epoch 10/15 - Loss: 0.1441, Accuracy: 0.8764


Epoch 11/15: 100%|██████████| 4929/4929 [01:31<00:00, 53.84it/s, loss=0.1027]


Epoch 11/15 - Loss: 0.1438, Accuracy: 0.8766


Epoch 12/15: 100%|██████████| 4929/4929 [01:30<00:00, 54.38it/s, loss=0.1387]


Epoch 12/15 - Loss: 0.1434, Accuracy: 0.8771


Epoch 13/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.87it/s, loss=0.1195]


Epoch 13/15 - Loss: 0.1426, Accuracy: 0.8775


Epoch 14/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.68it/s, loss=0.2300]


Epoch 14/15 - Loss: 0.1426, Accuracy: 0.8768


Epoch 15/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.51it/s, loss=0.1524]


Epoch 15/15 - Loss: 0.1422, Accuracy: 0.8777
Fold 4 Accuracy: 0.8287
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.44it/s, loss=0.1599]


Epoch 1/15 - Loss: 0.1449, Accuracy: 0.8761


Epoch 2/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.50it/s, loss=0.1992]


Epoch 2/15 - Loss: 0.1441, Accuracy: 0.8763


Epoch 3/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.84it/s, loss=0.1253]


Epoch 3/15 - Loss: 0.1432, Accuracy: 0.8766


Epoch 4/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.67it/s, loss=0.1375]


Epoch 4/15 - Loss: 0.1429, Accuracy: 0.8774


Epoch 5/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.72it/s, loss=0.1516]


Epoch 5/15 - Loss: 0.1429, Accuracy: 0.8774


Epoch 6/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.61it/s, loss=0.1026]


Epoch 6/15 - Loss: 0.1419, Accuracy: 0.8774


Epoch 7/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.87it/s, loss=0.0915]


Epoch 7/15 - Loss: 0.1424, Accuracy: 0.8776


Epoch 8/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.06it/s, loss=0.2789]


Epoch 8/15 - Loss: 0.1414, Accuracy: 0.8782


Epoch 9/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.18it/s, loss=0.2243]


Epoch 9/15 - Loss: 0.1412, Accuracy: 0.8779


Epoch 10/15: 100%|██████████| 4929/4929 [01:27<00:00, 56.38it/s, loss=0.1656]


Epoch 10/15 - Loss: 0.1404, Accuracy: 0.8789


Epoch 11/15: 100%|██████████| 4929/4929 [01:31<00:00, 53.93it/s, loss=0.1833]


Epoch 11/15 - Loss: 0.1407, Accuracy: 0.8785


Epoch 12/15: 100%|██████████| 4929/4929 [01:34<00:00, 52.44it/s, loss=0.1147]


Epoch 12/15 - Loss: 0.1405, Accuracy: 0.8785


Epoch 13/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.45it/s, loss=0.1133]


Epoch 13/15 - Loss: 0.1398, Accuracy: 0.8791


Epoch 14/15: 100%|██████████| 4929/4929 [01:28<00:00, 55.50it/s, loss=0.1148]


Epoch 14/15 - Loss: 0.1393, Accuracy: 0.8797


Epoch 15/15: 100%|██████████| 4929/4929 [01:31<00:00, 53.71it/s, loss=0.0597]


Epoch 15/15 - Loss: 0.1389, Accuracy: 0.8795
Fold 5 Accuracy: 0.8345
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [01:27<00:00, 56.53it/s, loss=0.1039]


Epoch 1/15 - Loss: 0.1411, Accuracy: 0.8788


Epoch 2/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.80it/s, loss=0.0977]


Epoch 2/15 - Loss: 0.1405, Accuracy: 0.8789


Epoch 3/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.33it/s, loss=0.1386]


Epoch 3/15 - Loss: 0.1398, Accuracy: 0.8791


Epoch 4/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.23it/s, loss=0.1598]


Epoch 4/15 - Loss: 0.1399, Accuracy: 0.8798


Epoch 5/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.42it/s, loss=0.1815]


Epoch 5/15 - Loss: 0.1390, Accuracy: 0.8800


Epoch 6/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.76it/s, loss=0.1354]


Epoch 6/15 - Loss: 0.1387, Accuracy: 0.8794


Epoch 7/15: 100%|██████████| 4929/4929 [01:26<00:00, 57.28it/s, loss=0.1192]


Epoch 7/15 - Loss: 0.1385, Accuracy: 0.8800


Epoch 8/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.51it/s, loss=0.1322]


Epoch 8/15 - Loss: 0.1376, Accuracy: 0.8805


Epoch 9/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.68it/s, loss=0.2051]


Epoch 9/15 - Loss: 0.1378, Accuracy: 0.8803


Epoch 10/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.60it/s, loss=0.1760]


Epoch 10/15 - Loss: 0.1376, Accuracy: 0.8809


Epoch 11/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.08it/s, loss=0.1146]


Epoch 11/15 - Loss: 0.1371, Accuracy: 0.8814


Epoch 12/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.01it/s, loss=0.1671]


Epoch 12/15 - Loss: 0.1370, Accuracy: 0.8806


Epoch 13/15: 100%|██████████| 4929/4929 [01:25<00:00, 57.84it/s, loss=0.1863]


Epoch 13/15 - Loss: 0.1366, Accuracy: 0.8814


Epoch 14/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.03it/s, loss=0.0394]


Epoch 14/15 - Loss: 0.1366, Accuracy: 0.8815


Epoch 15/15: 100%|██████████| 4929/4929 [01:20<00:00, 60.94it/s, loss=0.0943] 


Epoch 15/15 - Loss: 0.1366, Accuracy: 0.8816
Fold 6 Accuracy: 0.8385
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.67it/s, loss=0.1771]


Epoch 1/15 - Loss: 0.1374, Accuracy: 0.8808


Epoch 2/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.40it/s, loss=0.1836]


Epoch 2/15 - Loss: 0.1371, Accuracy: 0.8812


Epoch 3/15: 100%|██████████| 4929/4929 [00:41<00:00, 117.49it/s, loss=0.2334]


Epoch 3/15 - Loss: 0.1365, Accuracy: 0.8813


Epoch 4/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.35it/s, loss=0.1227]


Epoch 4/15 - Loss: 0.1359, Accuracy: 0.8823


Epoch 5/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.85it/s, loss=0.1487]


Epoch 5/15 - Loss: 0.1353, Accuracy: 0.8821


Epoch 6/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.52it/s, loss=0.1218]


Epoch 6/15 - Loss: 0.1351, Accuracy: 0.8823


Epoch 7/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.17it/s, loss=0.0979]


Epoch 7/15 - Loss: 0.1353, Accuracy: 0.8824


Epoch 8/15: 100%|██████████| 4929/4929 [00:41<00:00, 117.47it/s, loss=0.2163]


Epoch 8/15 - Loss: 0.1350, Accuracy: 0.8823


Epoch 9/15: 100%|██████████| 4929/4929 [00:41<00:00, 117.82it/s, loss=0.2278]


Epoch 9/15 - Loss: 0.1342, Accuracy: 0.8831


Epoch 10/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.23it/s, loss=0.0795]


Epoch 10/15 - Loss: 0.1344, Accuracy: 0.8831


Epoch 11/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.76it/s, loss=0.1366]


Epoch 11/15 - Loss: 0.1339, Accuracy: 0.8834


Epoch 12/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.20it/s, loss=0.1333]


Epoch 12/15 - Loss: 0.1337, Accuracy: 0.8831


Epoch 13/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.67it/s, loss=0.1164]


Epoch 13/15 - Loss: 0.1335, Accuracy: 0.8838


Epoch 14/15: 100%|██████████| 4929/4929 [00:41<00:00, 117.52it/s, loss=0.1449]


Epoch 14/15 - Loss: 0.1334, Accuracy: 0.8840


Epoch 15/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.91it/s, loss=0.1742]


Epoch 15/15 - Loss: 0.1332, Accuracy: 0.8839
Fold 7 Accuracy: 0.8329
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:50<00:00, 96.84it/s, loss=0.2208] 


Epoch 1/15 - Loss: 0.1361, Accuracy: 0.8827


Epoch 2/15: 100%|██████████| 4929/4929 [00:50<00:00, 97.27it/s, loss=0.1713] 


Epoch 2/15 - Loss: 0.1349, Accuracy: 0.8831


Epoch 3/15: 100%|██████████| 4929/4929 [00:50<00:00, 98.37it/s, loss=0.1051] 


Epoch 3/15 - Loss: 0.1349, Accuracy: 0.8828


Epoch 4/15: 100%|██████████| 4929/4929 [00:51<00:00, 96.32it/s, loss=0.1019] 


Epoch 4/15 - Loss: 0.1345, Accuracy: 0.8833


Epoch 5/15: 100%|██████████| 4929/4929 [00:50<00:00, 97.51it/s, loss=0.0980] 


Epoch 5/15 - Loss: 0.1339, Accuracy: 0.8837


Epoch 6/15: 100%|██████████| 4929/4929 [00:49<00:00, 98.82it/s, loss=0.1457] 


Epoch 6/15 - Loss: 0.1342, Accuracy: 0.8838


Epoch 7/15: 100%|██████████| 4929/4929 [00:50<00:00, 97.11it/s, loss=0.2134] 


Epoch 7/15 - Loss: 0.1334, Accuracy: 0.8844


Epoch 8/15: 100%|██████████| 4929/4929 [00:49<00:00, 100.19it/s, loss=0.2880]


Epoch 8/15 - Loss: 0.1335, Accuracy: 0.8836


Epoch 9/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.51it/s, loss=0.0852]


Epoch 9/15 - Loss: 0.1333, Accuracy: 0.8846


Epoch 10/15: 100%|██████████| 4929/4929 [00:43<00:00, 112.83it/s, loss=0.1026]


Epoch 10/15 - Loss: 0.1326, Accuracy: 0.8843


Epoch 11/15: 100%|██████████| 4929/4929 [00:50<00:00, 97.36it/s, loss=0.1408] 


Epoch 11/15 - Loss: 0.1328, Accuracy: 0.8851


Epoch 12/15: 100%|██████████| 4929/4929 [00:50<00:00, 96.69it/s, loss=0.1194] 


Epoch 12/15 - Loss: 0.1327, Accuracy: 0.8847


Epoch 13/15: 100%|██████████| 4929/4929 [00:35<00:00, 138.79it/s, loss=0.1334]


Epoch 13/15 - Loss: 0.1322, Accuracy: 0.8847


Epoch 14/15: 100%|██████████| 4929/4929 [00:35<00:00, 139.01it/s, loss=0.1245]


Epoch 14/15 - Loss: 0.1322, Accuracy: 0.8852


Epoch 15/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.95it/s, loss=0.1332]


Epoch 15/15 - Loss: 0.1320, Accuracy: 0.8848
Fold 8 Accuracy: 0.8423
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.38it/s, loss=0.1251]


Epoch 1/15 - Loss: 0.1337, Accuracy: 0.8844


Epoch 2/15: 100%|██████████| 4929/4929 [01:24<00:00, 58.46it/s, loss=0.1377] 


Epoch 2/15 - Loss: 0.1328, Accuracy: 0.8842


Epoch 3/15: 100%|██████████| 4929/4929 [01:47<00:00, 45.90it/s, loss=0.1206] 


Epoch 3/15 - Loss: 0.1320, Accuracy: 0.8858


Epoch 4/15: 100%|██████████| 4929/4929 [00:44<00:00, 109.76it/s, loss=0.1099]


Epoch 4/15 - Loss: 0.1320, Accuracy: 0.8848


Epoch 5/15: 100%|██████████| 4929/4929 [00:45<00:00, 108.68it/s, loss=0.1389]


Epoch 5/15 - Loss: 0.1322, Accuracy: 0.8849


Epoch 6/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.09it/s, loss=0.0229]


Epoch 6/15 - Loss: 0.1316, Accuracy: 0.8856


Epoch 7/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.53it/s, loss=0.1703]


Epoch 7/15 - Loss: 0.1313, Accuracy: 0.8854


Epoch 8/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.56it/s, loss=0.1127]


Epoch 8/15 - Loss: 0.1317, Accuracy: 0.8852


Epoch 9/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.33it/s, loss=0.1713]


Epoch 9/15 - Loss: 0.1309, Accuracy: 0.8857


Epoch 10/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.31it/s, loss=0.0647]


Epoch 10/15 - Loss: 0.1308, Accuracy: 0.8865


Epoch 11/15: 100%|██████████| 4929/4929 [00:42<00:00, 116.72it/s, loss=0.1344]


Epoch 11/15 - Loss: 0.1308, Accuracy: 0.8862


Epoch 12/15: 100%|██████████| 4929/4929 [00:41<00:00, 117.52it/s, loss=0.1222]


Epoch 12/15 - Loss: 0.1307, Accuracy: 0.8859


Epoch 13/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.22it/s, loss=0.1771]


Epoch 13/15 - Loss: 0.1301, Accuracy: 0.8865


Epoch 14/15: 100%|██████████| 4929/4929 [00:44<00:00, 110.64it/s, loss=0.1810]


Epoch 14/15 - Loss: 0.1304, Accuracy: 0.8864


Epoch 15/15: 100%|██████████| 4929/4929 [00:45<00:00, 108.98it/s, loss=0.2048]


Epoch 15/15 - Loss: 0.1303, Accuracy: 0.8861
Fold 9 Accuracy: 0.8437
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:43<00:00, 114.48it/s, loss=0.2354]


Epoch 1/15 - Loss: 0.1327, Accuracy: 0.8849


Epoch 2/15: 100%|██████████| 4929/4929 [00:41<00:00, 118.75it/s, loss=0.0869]


Epoch 2/15 - Loss: 0.1313, Accuracy: 0.8860


Epoch 3/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.58it/s, loss=0.2813]


Epoch 3/15 - Loss: 0.1312, Accuracy: 0.8856


Epoch 4/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.66it/s, loss=0.1840]


Epoch 4/15 - Loss: 0.1308, Accuracy: 0.8851


Epoch 5/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.55it/s, loss=0.0769]


Epoch 5/15 - Loss: 0.1303, Accuracy: 0.8861


Epoch 6/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.47it/s, loss=0.1301]


Epoch 6/15 - Loss: 0.1300, Accuracy: 0.8863


Epoch 7/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.40it/s, loss=0.1003]


Epoch 7/15 - Loss: 0.1301, Accuracy: 0.8868


Epoch 8/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.45it/s, loss=0.1649]


Epoch 8/15 - Loss: 0.1296, Accuracy: 0.8870


Epoch 9/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.16it/s, loss=0.1625]


Epoch 9/15 - Loss: 0.1295, Accuracy: 0.8871


Epoch 10/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.20it/s, loss=0.0902]


Epoch 10/15 - Loss: 0.1294, Accuracy: 0.8869


Epoch 11/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.50it/s, loss=0.0536]


Epoch 11/15 - Loss: 0.1298, Accuracy: 0.8875


Epoch 12/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.79it/s, loss=0.1049]


Epoch 12/15 - Loss: 0.1292, Accuracy: 0.8873


Epoch 13/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.45it/s, loss=0.0849]


Epoch 13/15 - Loss: 0.1293, Accuracy: 0.8876


Epoch 14/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.94it/s, loss=0.2059]


Epoch 14/15 - Loss: 0.1295, Accuracy: 0.8870


Epoch 15/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.27it/s, loss=0.0519]


Epoch 15/15 - Loss: 0.1294, Accuracy: 0.8871
Fold 10 Accuracy: 0.8526
Complete model saved to modelU12.pth
Fold Accuracies:
  Fold 1: 0.8157
  Fold 2: 0.8228
  Fold 3: 0.8308
  Fold 4: 0.8287
  Fold 5: 0.8345
  Fold 6: 0.8385
  Fold 7: 0.8329
  Fold 8: 0.8423
  Fold 9: 0.8437
  Fold 10: 0.8526


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  41    0   12  166   35    0   14    0    0    0]
 [   0   32   17  145   38    0    0    0    0    0]
 [   0    1  251 1304   36    6   12   14   10    1]
 [   0    4  122 4056  103   19   66   59   15    8]
 [   0    0   19  195 1536    1  659    8    7    0]
 [   0    0    8   31    1 5839    3    4    1    0]
 [   2    0    5   23  273    1 8981   10    5    0]
 [   0    0   17  273    2    1    3 1103    0    0]
 [   0    0    3   10   13    0    9    5  111    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.95      0.15      0.26       268
      Backdoor       0.86      0.14      0.24       232
           DoS       0.55      0.15      0.24      1635
      Exploits       0.65      0.91      0.76      4452
       Fuzzers       0.75      0.63      0.69      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.