In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15    
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

class LabelSmoothingCrossEntropy(nn.Module):
    def __init__(self, smoothing=0.1, reduction='mean'):
        """
        Args:
            smoothing: 平滑系数，通常在0.0~0.2之间。
            reduction: 损失聚合方式 ('mean', 'sum' or 'none')。
        """
        super(LabelSmoothingCrossEntropy, self).__init__()
        self.smoothing = smoothing
        self.reduction = reduction

    def forward(self, inputs, targets):
        """
        inputs: [B, num_classes] 的 logits（未经过 softmax）
        targets: [B] 的类别标签（long 类型）
        """
        num_classes = inputs.size(1)
        # 将标签进行 one-hot 编码
        with torch.no_grad():
            true_dist = torch.zeros_like(inputs)
            true_dist.fill_(self.smoothing / (num_classes - 1))
            true_dist.scatter_(1, targets.unsqueeze(1), 1 - self.smoothing)
        log_prob = F.log_softmax(inputs, dim=1)
        loss = -(true_dist * log_prob).sum(dim=1)
        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:
            return loss

criterion = LabelSmoothingCrossEntropy()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
# criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-LSCEloss.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4929/4929 [00:59<00:00, 83.47it/s, loss=0.7452]


Epoch 1/15 - Loss: 0.9181, Accuracy: 0.8225


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.20it/s, loss=0.7302]


Epoch 2/15 - Loss: 0.8534, Accuracy: 0.8494


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.88it/s, loss=0.7195]


Epoch 3/15 - Loss: 0.8405, Accuracy: 0.8543


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.29it/s, loss=0.7573]


Epoch 4/15 - Loss: 0.8327, Accuracy: 0.8568


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.63it/s, loss=0.8471]


Epoch 5/15 - Loss: 0.8267, Accuracy: 0.8588


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.50it/s, loss=0.8131]


Epoch 6/15 - Loss: 0.8229, Accuracy: 0.8606


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.51it/s, loss=0.7239]


Epoch 7/15 - Loss: 0.8194, Accuracy: 0.8616


Epoch 8/15: 100%|██████████| 4929/4929 [00:58<00:00, 84.81it/s, loss=0.8648]


Epoch 8/15 - Loss: 0.8167, Accuracy: 0.8621


Epoch 9/15: 100%|██████████| 4929/4929 [00:58<00:00, 84.54it/s, loss=0.8149]


Epoch 9/15 - Loss: 0.8144, Accuracy: 0.8637


Epoch 10/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.95it/s, loss=0.7969]


Epoch 10/15 - Loss: 0.8128, Accuracy: 0.8642


Epoch 11/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.13it/s, loss=0.8096]


Epoch 11/15 - Loss: 0.8107, Accuracy: 0.8650


Epoch 12/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.39it/s, loss=0.8599]


Epoch 12/15 - Loss: 0.8087, Accuracy: 0.8657


Epoch 13/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.46it/s, loss=0.8539]


Epoch 13/15 - Loss: 0.8074, Accuracy: 0.8661


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.42it/s, loss=0.7749]


Epoch 14/15 - Loss: 0.8055, Accuracy: 0.8675


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.59it/s, loss=0.7938]


Epoch 15/15 - Loss: 0.8036, Accuracy: 0.8676
Fold 1 Accuracy: 0.8184
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.53it/s, loss=0.8154]


Epoch 1/15 - Loss: 0.8039, Accuracy: 0.8680


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.56it/s, loss=0.8110]


Epoch 2/15 - Loss: 0.8024, Accuracy: 0.8684


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.51it/s, loss=0.7497]


Epoch 3/15 - Loss: 0.8016, Accuracy: 0.8688


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.67it/s, loss=0.6812]


Epoch 4/15 - Loss: 0.7997, Accuracy: 0.8694


Epoch 5/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.14it/s, loss=0.7750]


Epoch 5/15 - Loss: 0.7988, Accuracy: 0.8703


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.45it/s, loss=0.8154]


Epoch 6/15 - Loss: 0.7975, Accuracy: 0.8709


Epoch 7/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.41it/s, loss=0.7094]


Epoch 7/15 - Loss: 0.7971, Accuracy: 0.8711


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.66it/s, loss=0.8841]


Epoch 8/15 - Loss: 0.7952, Accuracy: 0.8716


Epoch 9/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.47it/s, loss=0.8194]


Epoch 9/15 - Loss: 0.7943, Accuracy: 0.8722


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.49it/s, loss=0.8517]


Epoch 10/15 - Loss: 0.7940, Accuracy: 0.8727


Epoch 11/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.18it/s, loss=0.7884]


Epoch 11/15 - Loss: 0.7934, Accuracy: 0.8727


Epoch 12/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.19it/s, loss=0.7656]


Epoch 12/15 - Loss: 0.7924, Accuracy: 0.8731


Epoch 13/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.38it/s, loss=0.8627]


Epoch 13/15 - Loss: 0.7914, Accuracy: 0.8737


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.46it/s, loss=0.7269]


Epoch 14/15 - Loss: 0.7910, Accuracy: 0.8741


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.7710]


Epoch 15/15 - Loss: 0.7909, Accuracy: 0.8740
Fold 2 Accuracy: 0.8273
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.85it/s, loss=0.6806]


Epoch 1/15 - Loss: 0.7914, Accuracy: 0.8735


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.94it/s, loss=0.8711]


Epoch 2/15 - Loss: 0.7901, Accuracy: 0.8749


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.64it/s, loss=0.8059]


Epoch 3/15 - Loss: 0.7897, Accuracy: 0.8744


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.19it/s, loss=0.7261]


Epoch 4/15 - Loss: 0.7887, Accuracy: 0.8749


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.59it/s, loss=0.7583]


Epoch 5/15 - Loss: 0.7883, Accuracy: 0.8748


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.39it/s, loss=0.6911]


Epoch 6/15 - Loss: 0.7872, Accuracy: 0.8758


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.48it/s, loss=0.8538]


Epoch 7/15 - Loss: 0.7868, Accuracy: 0.8755


Epoch 8/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.68it/s, loss=0.7580]


Epoch 8/15 - Loss: 0.7867, Accuracy: 0.8762


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.92it/s, loss=0.8020]


Epoch 9/15 - Loss: 0.7853, Accuracy: 0.8767


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.8095]


Epoch 10/15 - Loss: 0.7845, Accuracy: 0.8771


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.50it/s, loss=0.8013]


Epoch 11/15 - Loss: 0.7846, Accuracy: 0.8771


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.69it/s, loss=0.9328]


Epoch 12/15 - Loss: 0.7839, Accuracy: 0.8777


Epoch 13/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.39it/s, loss=0.6841]


Epoch 13/15 - Loss: 0.7836, Accuracy: 0.8772


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.06it/s, loss=0.8804]


Epoch 14/15 - Loss: 0.7829, Accuracy: 0.8780


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.61it/s, loss=0.8588]


Epoch 15/15 - Loss: 0.7823, Accuracy: 0.8785
Fold 3 Accuracy: 0.8297
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.47it/s, loss=0.7547]


Epoch 1/15 - Loss: 0.7836, Accuracy: 0.8780


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.41it/s, loss=0.8063]


Epoch 2/15 - Loss: 0.7828, Accuracy: 0.8778


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.69it/s, loss=0.7090]


Epoch 3/15 - Loss: 0.7820, Accuracy: 0.8781


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.72it/s, loss=0.7231]


Epoch 4/15 - Loss: 0.7812, Accuracy: 0.8787


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.97it/s, loss=0.7170]


Epoch 5/15 - Loss: 0.7812, Accuracy: 0.8790


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.14it/s, loss=0.6316]


Epoch 6/15 - Loss: 0.7801, Accuracy: 0.8798


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.77it/s, loss=0.7758]


Epoch 7/15 - Loss: 0.7797, Accuracy: 0.8800


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.74it/s, loss=0.6759]


Epoch 8/15 - Loss: 0.7793, Accuracy: 0.8801


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.63it/s, loss=0.7266]


Epoch 9/15 - Loss: 0.7789, Accuracy: 0.8802


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.75it/s, loss=0.7011]


Epoch 10/15 - Loss: 0.7782, Accuracy: 0.8804


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.88it/s, loss=0.7917]


Epoch 11/15 - Loss: 0.7779, Accuracy: 0.8810


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.7473]


Epoch 12/15 - Loss: 0.7773, Accuracy: 0.8811


Epoch 13/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.42it/s, loss=0.9102]


Epoch 13/15 - Loss: 0.7764, Accuracy: 0.8812


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.91it/s, loss=0.7128]


Epoch 14/15 - Loss: 0.7768, Accuracy: 0.8810


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.52it/s, loss=0.8233]


Epoch 15/15 - Loss: 0.7759, Accuracy: 0.8818
Fold 4 Accuracy: 0.8292
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.63it/s, loss=0.7058]


Epoch 1/15 - Loss: 0.7782, Accuracy: 0.8803


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.13it/s, loss=0.7221]


Epoch 2/15 - Loss: 0.7778, Accuracy: 0.8808


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.70it/s, loss=0.8024]


Epoch 3/15 - Loss: 0.7772, Accuracy: 0.8813


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.63it/s, loss=0.7094]


Epoch 4/15 - Loss: 0.7769, Accuracy: 0.8810


Epoch 5/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.22it/s, loss=0.8455]


Epoch 5/15 - Loss: 0.7764, Accuracy: 0.8817


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.21it/s, loss=0.7695]


Epoch 6/15 - Loss: 0.7763, Accuracy: 0.8819


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.88it/s, loss=0.7723]


Epoch 7/15 - Loss: 0.7751, Accuracy: 0.8827


Epoch 8/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.29it/s, loss=0.7188]


Epoch 8/15 - Loss: 0.7748, Accuracy: 0.8823


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.68it/s, loss=0.8706]


Epoch 9/15 - Loss: 0.7742, Accuracy: 0.8831


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.74it/s, loss=0.7587]


Epoch 10/15 - Loss: 0.7742, Accuracy: 0.8823


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.51it/s, loss=0.7766]


Epoch 11/15 - Loss: 0.7734, Accuracy: 0.8832


Epoch 12/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.46it/s, loss=0.8078]


Epoch 12/15 - Loss: 0.7735, Accuracy: 0.8836


Epoch 13/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.35it/s, loss=0.8973]


Epoch 13/15 - Loss: 0.7729, Accuracy: 0.8835


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.44it/s, loss=0.7867]


Epoch 14/15 - Loss: 0.7732, Accuracy: 0.8837


Epoch 15/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.42it/s, loss=0.7853]


Epoch 15/15 - Loss: 0.7723, Accuracy: 0.8836
Fold 5 Accuracy: 0.8406
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.46it/s, loss=0.7150]


Epoch 1/15 - Loss: 0.7737, Accuracy: 0.8829


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.06it/s, loss=0.8199]


Epoch 2/15 - Loss: 0.7730, Accuracy: 0.8832


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.55it/s, loss=0.7928]


Epoch 3/15 - Loss: 0.7729, Accuracy: 0.8837


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.68it/s, loss=0.8670]


Epoch 4/15 - Loss: 0.7724, Accuracy: 0.8843


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.57it/s, loss=0.8390]


Epoch 5/15 - Loss: 0.7713, Accuracy: 0.8844


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.51it/s, loss=0.8603]


Epoch 6/15 - Loss: 0.7709, Accuracy: 0.8851


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.72it/s, loss=0.7412]


Epoch 7/15 - Loss: 0.7705, Accuracy: 0.8848


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.55it/s, loss=0.7085]


Epoch 8/15 - Loss: 0.7701, Accuracy: 0.8852


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.68it/s, loss=0.8509]


Epoch 9/15 - Loss: 0.7701, Accuracy: 0.8854


Epoch 10/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.43it/s, loss=0.6796]


Epoch 10/15 - Loss: 0.7694, Accuracy: 0.8856


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.59it/s, loss=0.8133]


Epoch 11/15 - Loss: 0.7696, Accuracy: 0.8856


Epoch 12/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.37it/s, loss=0.7541]


Epoch 12/15 - Loss: 0.7686, Accuracy: 0.8865


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.64it/s, loss=0.7627]


Epoch 13/15 - Loss: 0.7684, Accuracy: 0.8860


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.51it/s, loss=0.6654]


Epoch 14/15 - Loss: 0.7683, Accuracy: 0.8861


Epoch 15/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.31it/s, loss=0.7184]


Epoch 15/15 - Loss: 0.7681, Accuracy: 0.8863
Fold 6 Accuracy: 0.8418
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.32it/s, loss=0.7865]


Epoch 1/15 - Loss: 0.7686, Accuracy: 0.8858


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.75it/s, loss=0.7558]


Epoch 2/15 - Loss: 0.7684, Accuracy: 0.8862


Epoch 3/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.38it/s, loss=0.7965]


Epoch 3/15 - Loss: 0.7676, Accuracy: 0.8869


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.83it/s, loss=0.7117]


Epoch 4/15 - Loss: 0.7676, Accuracy: 0.8866


Epoch 5/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.45it/s, loss=0.7679]


Epoch 5/15 - Loss: 0.7669, Accuracy: 0.8868


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.59it/s, loss=0.6683]


Epoch 6/15 - Loss: 0.7670, Accuracy: 0.8869


Epoch 7/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.17it/s, loss=0.6829]


Epoch 7/15 - Loss: 0.7661, Accuracy: 0.8878


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.49it/s, loss=0.7648]


Epoch 8/15 - Loss: 0.7659, Accuracy: 0.8877


Epoch 9/15: 100%|██████████| 4929/4929 [00:55<00:00, 88.22it/s, loss=0.6991]


Epoch 9/15 - Loss: 0.7658, Accuracy: 0.8874


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.99it/s, loss=0.7796]


Epoch 10/15 - Loss: 0.7654, Accuracy: 0.8877


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.85it/s, loss=0.9236]


Epoch 11/15 - Loss: 0.7646, Accuracy: 0.8883


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.58it/s, loss=0.6911]


Epoch 12/15 - Loss: 0.7650, Accuracy: 0.8883


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.90it/s, loss=0.8472]


Epoch 13/15 - Loss: 0.7649, Accuracy: 0.8884


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.53it/s, loss=0.7597]


Epoch 14/15 - Loss: 0.7644, Accuracy: 0.8887


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.65it/s, loss=0.7879]


Epoch 15/15 - Loss: 0.7635, Accuracy: 0.8891
Fold 7 Accuracy: 0.8421
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.74it/s, loss=0.7653]


Epoch 1/15 - Loss: 0.7665, Accuracy: 0.8872


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.89it/s, loss=0.7850]


Epoch 2/15 - Loss: 0.7651, Accuracy: 0.8883


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.89it/s, loss=0.6885]


Epoch 3/15 - Loss: 0.7653, Accuracy: 0.8883


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.31it/s, loss=0.8449]


Epoch 4/15 - Loss: 0.7649, Accuracy: 0.8884


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.83it/s, loss=0.7506]


Epoch 5/15 - Loss: 0.7644, Accuracy: 0.8884


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.90it/s, loss=0.8680]


Epoch 6/15 - Loss: 0.7640, Accuracy: 0.8884


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.7288]


Epoch 7/15 - Loss: 0.7639, Accuracy: 0.8885


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.60it/s, loss=0.6886]


Epoch 8/15 - Loss: 0.7629, Accuracy: 0.8894


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.77it/s, loss=0.8704]


Epoch 9/15 - Loss: 0.7631, Accuracy: 0.8893


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.64it/s, loss=0.8342]


Epoch 10/15 - Loss: 0.7631, Accuracy: 0.8893


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.7343]


Epoch 11/15 - Loss: 0.7622, Accuracy: 0.8899


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.48it/s, loss=0.7022]


Epoch 12/15 - Loss: 0.7621, Accuracy: 0.8901


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.72it/s, loss=0.6997]


Epoch 13/15 - Loss: 0.7615, Accuracy: 0.8904


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.7663]


Epoch 14/15 - Loss: 0.7613, Accuracy: 0.8901


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.59it/s, loss=0.7527]


Epoch 15/15 - Loss: 0.7612, Accuracy: 0.8906
Fold 8 Accuracy: 0.8491
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.52it/s, loss=0.6800]


Epoch 1/15 - Loss: 0.7629, Accuracy: 0.8893


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.38it/s, loss=0.7286]


Epoch 2/15 - Loss: 0.7620, Accuracy: 0.8893


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.94it/s, loss=0.6775]


Epoch 3/15 - Loss: 0.7622, Accuracy: 0.8899


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.43it/s, loss=0.6771]


Epoch 4/15 - Loss: 0.7614, Accuracy: 0.8902


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.92it/s, loss=0.7334]


Epoch 5/15 - Loss: 0.7615, Accuracy: 0.8908


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.65it/s, loss=0.8632]


Epoch 6/15 - Loss: 0.7611, Accuracy: 0.8910


Epoch 7/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.45it/s, loss=0.7050]


Epoch 7/15 - Loss: 0.7605, Accuracy: 0.8905


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.57it/s, loss=0.7425]


Epoch 8/15 - Loss: 0.7603, Accuracy: 0.8909


Epoch 9/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.40it/s, loss=0.7636]


Epoch 9/15 - Loss: 0.7600, Accuracy: 0.8914


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.71it/s, loss=0.7238]


Epoch 10/15 - Loss: 0.7597, Accuracy: 0.8913


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.7356]


Epoch 11/15 - Loss: 0.7594, Accuracy: 0.8916


Epoch 12/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.38it/s, loss=0.7294]


Epoch 12/15 - Loss: 0.7591, Accuracy: 0.8917


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.53it/s, loss=0.7478]


Epoch 13/15 - Loss: 0.7592, Accuracy: 0.8916


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.54it/s, loss=0.7572]


Epoch 14/15 - Loss: 0.7590, Accuracy: 0.8920


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.8002]


Epoch 15/15 - Loss: 0.7583, Accuracy: 0.8921
Fold 9 Accuracy: 0.8396
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.04it/s, loss=0.8660]


Epoch 1/15 - Loss: 0.7609, Accuracy: 0.8902


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.98it/s, loss=0.7462]


Epoch 2/15 - Loss: 0.7599, Accuracy: 0.8913


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.98it/s, loss=0.7367]


Epoch 3/15 - Loss: 0.7604, Accuracy: 0.8907


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.13it/s, loss=0.7939]


Epoch 4/15 - Loss: 0.7586, Accuracy: 0.8917


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.68it/s, loss=0.9097]


Epoch 5/15 - Loss: 0.7592, Accuracy: 0.8920


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.20it/s, loss=0.7134]


Epoch 6/15 - Loss: 0.7585, Accuracy: 0.8919


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.21it/s, loss=0.6942]


Epoch 7/15 - Loss: 0.7581, Accuracy: 0.8926


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.68it/s, loss=0.7212]


Epoch 8/15 - Loss: 0.7578, Accuracy: 0.8926


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.97it/s, loss=0.7713]


Epoch 9/15 - Loss: 0.7581, Accuracy: 0.8925


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.78it/s, loss=0.7708]


Epoch 10/15 - Loss: 0.7577, Accuracy: 0.8924


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.81it/s, loss=0.7959]


Epoch 11/15 - Loss: 0.7573, Accuracy: 0.8928


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.81it/s, loss=0.7901]


Epoch 12/15 - Loss: 0.7571, Accuracy: 0.8930


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.63it/s, loss=0.8186]


Epoch 13/15 - Loss: 0.7567, Accuracy: 0.8930


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.36it/s, loss=0.7300]


Epoch 14/15 - Loss: 0.7564, Accuracy: 0.8935


Epoch 15/15: 100%|██████████| 4929/4929 [00:53<00:00, 91.85it/s, loss=0.7978] 


Epoch 15/15 - Loss: 0.7566, Accuracy: 0.8934
Fold 10 Accuracy: 0.8568
Complete model saved to UNSW-LSCEloss.pth
Fold Accuracies:
  Fold 1: 0.8184
  Fold 2: 0.8273
  Fold 3: 0.8297
  Fold 4: 0.8292
  Fold 5: 0.8406
  Fold 6: 0.8418
  Fold 7: 0.8421
  Fold 8: 0.8491
  Fold 9: 0.8396
  Fold 10: 0.8568


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  36    0    3  180   33    0   16    0    0    0]
 [   0   28    8  152   40    0    0    0    4    0]
 [   0    1  226 1335   38    5    8   12    9    1]
 [   0    2   59 4097  111   11   48   95   16   13]
 [   2    0   11  213 1673    0  507    8    9    2]
 [   0    0    4   50    1 5826    4    2    0    0]
 [  15    0    3   39  272    0 8957    8    5    1]
 [   1    0    4  273    3    1    3 1110    4    0]
 [   0    0    6   10    9    3    9    9  105    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.67      0.13      0.22       268
      Backdoor       0.90      0.12      0.21       232
           DoS       0.70      0.14      0.23      1635
      Exploits       0.65      0.92      0.76      4452
       Fuzzers       0.77      0.69      0.73      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.