In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

# ------------------------ 改进 ASTP 模块 ------------------------
class ASTP(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        # 多尺度时间卷积 + 门控线性单元（GLU）
        self.temp_conv = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, kernel_size=32, padding='same', groups=1),  # 深度可分离卷积
                nn.GLU(dim=1)  # 门控线性单元
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, kernel_size=64, padding='same', dilation=2, groups=1),
                nn.GLU(dim=1)
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, kernel_size=96, padding='same', dilation=4, groups=1),
                nn.GLU(dim=1)
            )
        ])
        
        # SE通道注意力
        self.se_block = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(24, 12, kernel_size=1),
            nn.ReLU(),
            nn.Conv1d(12, 24, kernel_size=1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        branch_outs = [conv(x) for conv in self.temp_conv]  # 计算多尺度卷积
        merged = torch.cat(branch_outs, dim=1)  # [B, 24, L]
        return merged * self.se_block(merged)  # SE 注意力增强特征

# ------------------------ BiLSTM-AGRU（增强时序建模） ------------------------
class BiLSTM_AGRU(nn.Module):
    def __init__(self, feat_dim):
        super().__init__()
        self.bilstm = nn.LSTM(feat_dim, feat_dim // 2, num_layers=2, bidirectional=True, batch_first=True)
        self.agru = nn.GRU(feat_dim, feat_dim, num_layers=1, batch_first=True)
        self.att_weight = nn.Linear(feat_dim, 1)  # AGRU 的注意力权重
        
    def forward(self, x):
        # BiLSTM
        lstm_out, _ = self.bilstm(x)  # [B, L, D]
        
        # AGRU（使用注意力加权）
        agru_out, _ = self.agru(lstm_out)  # [B, L, D]
        att_scores = torch.sigmoid(self.att_weight(agru_out))  # [B, L, 1]
        
        return agru_out * att_scores  # 注意力加权 AGRU 输出

# ------------------------ 改进 Transformer（Local Attention + GLU） ------------------------
class LocalTransformer(nn.Module):
    def __init__(self, feat_dim, num_layers=2):
        super().__init__()
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=feat_dim,
            nhead=4,
            dim_feedforward=feat_dim * 4,
            batch_first=True,
            activation=F.gelu
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # GLU 变换增强特征表达
        self.glu = nn.Sequential(
            nn.Linear(feat_dim, feat_dim * 2),
            nn.GLU(dim=-1)
        )
    
    def forward(self, x):
        x = self.transformer(x)  # 局部注意力 Transformer
        return self.glu(x)  # GLU 进行特征选择

# ------------------------ 改进 NSLKDDModel ------------------------
class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10):
        super().__init__()

        # 特征提取层（ASTP）
        self.astp = ASTP(in_channels=1)
        self.pool = nn.AdaptiveMaxPool1d(input_dim // 4)  # 维度降采样
        self.bn = nn.BatchNorm1d(24)  # 特征标准化

        # 时序建模（BiLSTM-AGRU + Transformer）
        self.time_modeling = nn.Sequential(
            BiLSTM_AGRU(24),
            LocalTransformer(24, num_layers=2)
        )

        # 分类头（IEEE TDSC 2023 改进）
        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(24, 128),
            nn.BatchNorm1d(128),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        # 输入形状: [B, 1, 122]
        x = self.astp(x)           # [B, 24, 122]
        x = self.pool(x)           # [B, 24, 30]
        x = self.bn(x)             # 特征标准化
        x = x.permute(0, 2, 1)     # [B, 30, 24]
        x = self.time_modeling(x)  # [B, 30, 24]
        x = x.permute(0, 2, 1)     # [B, 24, 30]
        return self.classifier(x)  # [B, num_classes]


In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =25   #15 0.0008 82.40  25 0.0006 82.65  25 0.0008 82.68  25 0.0008 87.09 30 0.0008 87.21
learning_rate = 0.0008
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
oversample = RandomOverSampler(sampling_strategy='minority')

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
        pt = torch.exp(-ce_loss)  # 预测的概率
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "modelU8.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/25:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/25: 100%|██████████| 4929/4929 [00:51<00:00, 95.80it/s, loss=0.2302] 


Epoch 1/25 - Loss: 0.3547, Accuracy: 0.7833


Epoch 2/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.50it/s, loss=0.2553] 


Epoch 2/25 - Loss: 0.2656, Accuracy: 0.8203


Epoch 3/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.40it/s, loss=0.2132] 


Epoch 3/25 - Loss: 0.2390, Accuracy: 0.8329


Epoch 4/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.67it/s, loss=0.2213] 


Epoch 4/25 - Loss: 0.2261, Accuracy: 0.8371


Epoch 5/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.78it/s, loss=0.1524] 


Epoch 5/25 - Loss: 0.2173, Accuracy: 0.8408


Epoch 6/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.51it/s, loss=0.1190] 


Epoch 6/25 - Loss: 0.2106, Accuracy: 0.8436


Epoch 7/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.64it/s, loss=0.1846] 


Epoch 7/25 - Loss: 0.2056, Accuracy: 0.8468


Epoch 8/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.24it/s, loss=0.2839] 


Epoch 8/25 - Loss: 0.2026, Accuracy: 0.8475


Epoch 9/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.99it/s, loss=0.1840] 


Epoch 9/25 - Loss: 0.1993, Accuracy: 0.8492


Epoch 10/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.34it/s, loss=0.2057] 


Epoch 10/25 - Loss: 0.1960, Accuracy: 0.8508


Epoch 11/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.46it/s, loss=0.1917] 


Epoch 11/25 - Loss: 0.1947, Accuracy: 0.8511


Epoch 12/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.56it/s, loss=0.1657] 


Epoch 12/25 - Loss: 0.1917, Accuracy: 0.8537


Epoch 13/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.70it/s, loss=0.1259] 


Epoch 13/25 - Loss: 0.1897, Accuracy: 0.8537


Epoch 14/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.65it/s, loss=0.2704] 


Epoch 14/25 - Loss: 0.1878, Accuracy: 0.8546


Epoch 15/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.45it/s, loss=0.1661] 


Epoch 15/25 - Loss: 0.1864, Accuracy: 0.8552


Epoch 16/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.78it/s, loss=0.2016] 


Epoch 16/25 - Loss: 0.1849, Accuracy: 0.8563


Epoch 17/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.57it/s, loss=0.1912] 


Epoch 17/25 - Loss: 0.1840, Accuracy: 0.8562


Epoch 18/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.85it/s, loss=0.3486] 


Epoch 18/25 - Loss: 0.1827, Accuracy: 0.8562


Epoch 19/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.41it/s, loss=0.1221] 


Epoch 19/25 - Loss: 0.1816, Accuracy: 0.8577


Epoch 20/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.63it/s, loss=0.1880] 


Epoch 20/25 - Loss: 0.1811, Accuracy: 0.8576


Epoch 21/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.88it/s, loss=0.2739] 


Epoch 21/25 - Loss: 0.1801, Accuracy: 0.8582


Epoch 22/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.77it/s, loss=0.1569] 


Epoch 22/25 - Loss: 0.1794, Accuracy: 0.8579


Epoch 23/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.67it/s, loss=0.1622] 


Epoch 23/25 - Loss: 0.1784, Accuracy: 0.8594


Epoch 24/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.09it/s, loss=0.2938] 


Epoch 24/25 - Loss: 0.1772, Accuracy: 0.8596


Epoch 25/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.79it/s, loss=0.2789] 


Epoch 25/25 - Loss: 0.1761, Accuracy: 0.8600
Fold 1 Accuracy: 0.8098
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.08it/s, loss=0.2041] 


Epoch 1/25 - Loss: 0.1773, Accuracy: 0.8593


Epoch 2/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.65it/s, loss=0.1445] 


Epoch 2/25 - Loss: 0.1758, Accuracy: 0.8602


Epoch 3/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.22it/s, loss=0.2851] 


Epoch 3/25 - Loss: 0.1750, Accuracy: 0.8609


Epoch 4/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.61it/s, loss=0.3519] 


Epoch 4/25 - Loss: 0.1742, Accuracy: 0.8615


Epoch 5/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.31it/s, loss=0.1235] 


Epoch 5/25 - Loss: 0.1740, Accuracy: 0.8612


Epoch 6/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.94it/s, loss=0.2695] 


Epoch 6/25 - Loss: 0.1741, Accuracy: 0.8613


Epoch 7/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.62it/s, loss=0.1402] 


Epoch 7/25 - Loss: 0.1734, Accuracy: 0.8613


Epoch 8/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.32it/s, loss=0.1354] 


Epoch 8/25 - Loss: 0.1724, Accuracy: 0.8618


Epoch 9/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.92it/s, loss=0.0999] 


Epoch 9/25 - Loss: 0.1717, Accuracy: 0.8619


Epoch 10/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.74it/s, loss=0.2138] 


Epoch 10/25 - Loss: 0.1721, Accuracy: 0.8619


Epoch 11/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.68it/s, loss=0.0897] 


Epoch 11/25 - Loss: 0.1710, Accuracy: 0.8621


Epoch 12/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.70it/s, loss=0.0697] 


Epoch 12/25 - Loss: 0.1710, Accuracy: 0.8622


Epoch 13/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.36it/s, loss=0.1677] 


Epoch 13/25 - Loss: 0.1700, Accuracy: 0.8627


Epoch 14/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.74it/s, loss=0.3355] 


Epoch 14/25 - Loss: 0.1701, Accuracy: 0.8629


Epoch 15/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.74it/s, loss=0.1277] 


Epoch 15/25 - Loss: 0.1695, Accuracy: 0.8629


Epoch 16/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.01it/s, loss=0.2025] 


Epoch 16/25 - Loss: 0.1690, Accuracy: 0.8632


Epoch 17/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.54it/s, loss=0.2325] 


Epoch 17/25 - Loss: 0.1683, Accuracy: 0.8637


Epoch 18/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.98it/s, loss=0.1622] 


Epoch 18/25 - Loss: 0.1683, Accuracy: 0.8638


Epoch 19/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.17it/s, loss=0.1301] 


Epoch 19/25 - Loss: 0.1682, Accuracy: 0.8638


Epoch 20/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.70it/s, loss=0.1908] 


Epoch 20/25 - Loss: 0.1678, Accuracy: 0.8635


Epoch 21/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.04it/s, loss=0.1623] 


Epoch 21/25 - Loss: 0.1674, Accuracy: 0.8641


Epoch 22/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.03it/s, loss=0.1586] 


Epoch 22/25 - Loss: 0.1666, Accuracy: 0.8642


Epoch 23/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.72it/s, loss=0.0749] 


Epoch 23/25 - Loss: 0.1666, Accuracy: 0.8644


Epoch 24/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.38it/s, loss=0.1220] 


Epoch 24/25 - Loss: 0.1662, Accuracy: 0.8642


Epoch 25/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.87it/s, loss=0.1571] 


Epoch 25/25 - Loss: 0.1663, Accuracy: 0.8651
Fold 2 Accuracy: 0.8174
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.72it/s, loss=0.1966] 


Epoch 1/25 - Loss: 0.1678, Accuracy: 0.8643


Epoch 2/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.28it/s, loss=0.1966] 


Epoch 2/25 - Loss: 0.1668, Accuracy: 0.8651


Epoch 3/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.08it/s, loss=0.1528] 


Epoch 3/25 - Loss: 0.1672, Accuracy: 0.8641


Epoch 4/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.45it/s, loss=0.1474] 


Epoch 4/25 - Loss: 0.1659, Accuracy: 0.8648


Epoch 5/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.59it/s, loss=0.1585] 


Epoch 5/25 - Loss: 0.1658, Accuracy: 0.8649


Epoch 6/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.10it/s, loss=0.1578] 


Epoch 6/25 - Loss: 0.1655, Accuracy: 0.8653


Epoch 7/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.74it/s, loss=0.1802] 


Epoch 7/25 - Loss: 0.1648, Accuracy: 0.8652


Epoch 8/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.15it/s, loss=0.0731] 


Epoch 8/25 - Loss: 0.1654, Accuracy: 0.8652


Epoch 9/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.48it/s, loss=0.2453] 


Epoch 9/25 - Loss: 0.1645, Accuracy: 0.8651


Epoch 10/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.83it/s, loss=0.1364] 


Epoch 10/25 - Loss: 0.1644, Accuracy: 0.8654


Epoch 11/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.88it/s, loss=0.1643] 


Epoch 11/25 - Loss: 0.1643, Accuracy: 0.8656


Epoch 12/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.42it/s, loss=0.0883] 


Epoch 12/25 - Loss: 0.1638, Accuracy: 0.8657


Epoch 13/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.70it/s, loss=0.1921] 


Epoch 13/25 - Loss: 0.1635, Accuracy: 0.8654


Epoch 14/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.89it/s, loss=0.1384] 


Epoch 14/25 - Loss: 0.1636, Accuracy: 0.8662


Epoch 15/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.31it/s, loss=0.1570] 


Epoch 15/25 - Loss: 0.1634, Accuracy: 0.8657


Epoch 16/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.66it/s, loss=0.2280] 


Epoch 16/25 - Loss: 0.1631, Accuracy: 0.8663


Epoch 17/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.47it/s, loss=0.2450] 


Epoch 17/25 - Loss: 0.1625, Accuracy: 0.8668


Epoch 18/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.07it/s, loss=0.1412] 


Epoch 18/25 - Loss: 0.1626, Accuracy: 0.8659


Epoch 19/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.52it/s, loss=0.1063] 


Epoch 19/25 - Loss: 0.1621, Accuracy: 0.8658


Epoch 20/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.70it/s, loss=0.1364] 


Epoch 20/25 - Loss: 0.1628, Accuracy: 0.8665


Epoch 21/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.62it/s, loss=0.1526] 


Epoch 21/25 - Loss: 0.1623, Accuracy: 0.8666


Epoch 22/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.98it/s, loss=0.1204] 


Epoch 22/25 - Loss: 0.1616, Accuracy: 0.8669


Epoch 23/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.51it/s, loss=0.1632] 


Epoch 23/25 - Loss: 0.1612, Accuracy: 0.8665


Epoch 24/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.58it/s, loss=0.2896] 


Epoch 24/25 - Loss: 0.1614, Accuracy: 0.8671


Epoch 25/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.06it/s, loss=0.1945] 


Epoch 25/25 - Loss: 0.1608, Accuracy: 0.8671
Fold 3 Accuracy: 0.8188
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.47it/s, loss=0.1864] 


Epoch 1/25 - Loss: 0.1624, Accuracy: 0.8663


Epoch 2/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.66it/s, loss=0.2611] 


Epoch 2/25 - Loss: 0.1620, Accuracy: 0.8665


Epoch 3/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.50it/s, loss=0.3193] 


Epoch 3/25 - Loss: 0.1619, Accuracy: 0.8670


Epoch 4/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.73it/s, loss=0.1820] 


Epoch 4/25 - Loss: 0.1616, Accuracy: 0.8671


Epoch 5/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.96it/s, loss=0.1993] 


Epoch 5/25 - Loss: 0.1612, Accuracy: 0.8666


Epoch 6/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.58it/s, loss=0.1241] 


Epoch 6/25 - Loss: 0.1610, Accuracy: 0.8670


Epoch 7/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.76it/s, loss=0.1409]


Epoch 7/25 - Loss: 0.1609, Accuracy: 0.8668


Epoch 8/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.50it/s, loss=0.1832]


Epoch 8/25 - Loss: 0.1603, Accuracy: 0.8674


Epoch 9/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.53it/s, loss=0.1536] 


Epoch 9/25 - Loss: 0.1602, Accuracy: 0.8669


Epoch 10/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.14it/s, loss=0.2381] 


Epoch 10/25 - Loss: 0.1601, Accuracy: 0.8673


Epoch 11/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.74it/s, loss=0.0997] 


Epoch 11/25 - Loss: 0.1600, Accuracy: 0.8673


Epoch 12/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.01it/s, loss=0.0495] 


Epoch 12/25 - Loss: 0.1605, Accuracy: 0.8666


Epoch 13/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.88it/s, loss=0.0781] 


Epoch 13/25 - Loss: 0.1598, Accuracy: 0.8674


Epoch 14/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.05it/s, loss=0.0854] 


Epoch 14/25 - Loss: 0.1601, Accuracy: 0.8674


Epoch 15/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.77it/s, loss=0.0952]


Epoch 15/25 - Loss: 0.1593, Accuracy: 0.8675


Epoch 16/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.65it/s, loss=0.2012] 


Epoch 16/25 - Loss: 0.1593, Accuracy: 0.8675


Epoch 17/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.10it/s, loss=0.1269]


Epoch 17/25 - Loss: 0.1590, Accuracy: 0.8676


Epoch 18/25: 100%|██████████| 4929/4929 [01:24<00:00, 58.28it/s, loss=0.1731] 


Epoch 18/25 - Loss: 0.1590, Accuracy: 0.8672


Epoch 19/25: 100%|██████████| 4929/4929 [01:43<00:00, 47.83it/s, loss=0.2490]


Epoch 19/25 - Loss: 0.1588, Accuracy: 0.8675


Epoch 20/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.51it/s, loss=0.1953]


Epoch 20/25 - Loss: 0.1584, Accuracy: 0.8688


Epoch 21/25: 100%|██████████| 4929/4929 [01:37<00:00, 50.47it/s, loss=0.2159]


Epoch 21/25 - Loss: 0.1590, Accuracy: 0.8684


Epoch 22/25: 100%|██████████| 4929/4929 [01:44<00:00, 46.96it/s, loss=0.2236]


Epoch 22/25 - Loss: 0.1584, Accuracy: 0.8681


Epoch 23/25: 100%|██████████| 4929/4929 [01:43<00:00, 47.46it/s, loss=0.1349]


Epoch 23/25 - Loss: 0.1585, Accuracy: 0.8680


Epoch 24/25: 100%|██████████| 4929/4929 [01:45<00:00, 46.90it/s, loss=0.1582]


Epoch 24/25 - Loss: 0.1582, Accuracy: 0.8680


Epoch 25/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.34it/s, loss=0.1210]


Epoch 25/25 - Loss: 0.1578, Accuracy: 0.8681
Fold 4 Accuracy: 0.8221
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.42it/s, loss=0.1388]


Epoch 1/25 - Loss: 0.1587, Accuracy: 0.8676


Epoch 2/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.32it/s, loss=0.1015]


Epoch 2/25 - Loss: 0.1584, Accuracy: 0.8678


Epoch 3/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.60it/s, loss=0.1779]


Epoch 3/25 - Loss: 0.1582, Accuracy: 0.8679


Epoch 4/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.58it/s, loss=0.1047]


Epoch 4/25 - Loss: 0.1575, Accuracy: 0.8681


Epoch 5/25: 100%|██████████| 4929/4929 [01:42<00:00, 47.90it/s, loss=0.1413]


Epoch 5/25 - Loss: 0.1574, Accuracy: 0.8685


Epoch 6/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.30it/s, loss=0.2838]


Epoch 6/25 - Loss: 0.1576, Accuracy: 0.8684


Epoch 7/25: 100%|██████████| 4929/4929 [01:40<00:00, 49.12it/s, loss=0.1273]


Epoch 7/25 - Loss: 0.1570, Accuracy: 0.8685


Epoch 8/25: 100%|██████████| 4929/4929 [01:43<00:00, 47.85it/s, loss=0.1136]


Epoch 8/25 - Loss: 0.1568, Accuracy: 0.8688


Epoch 9/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.70it/s, loss=0.1519]


Epoch 9/25 - Loss: 0.1568, Accuracy: 0.8685


Epoch 10/25: 100%|██████████| 4929/4929 [01:45<00:00, 46.83it/s, loss=0.0744]


Epoch 10/25 - Loss: 0.1564, Accuracy: 0.8683


Epoch 11/25: 100%|██████████| 4929/4929 [01:42<00:00, 47.97it/s, loss=0.1454]


Epoch 11/25 - Loss: 0.1566, Accuracy: 0.8684


Epoch 12/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.03it/s, loss=0.0887]


Epoch 12/25 - Loss: 0.1564, Accuracy: 0.8689


Epoch 13/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.67it/s, loss=0.2731]


Epoch 13/25 - Loss: 0.1558, Accuracy: 0.8688


Epoch 14/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.61it/s, loss=0.1142]


Epoch 14/25 - Loss: 0.1562, Accuracy: 0.8689


Epoch 15/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.42it/s, loss=0.1861]


Epoch 15/25 - Loss: 0.1559, Accuracy: 0.8693


Epoch 16/25: 100%|██████████| 4929/4929 [01:44<00:00, 47.26it/s, loss=0.1230]


Epoch 16/25 - Loss: 0.1556, Accuracy: 0.8691


Epoch 17/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.21it/s, loss=0.0872]


Epoch 17/25 - Loss: 0.1554, Accuracy: 0.8691


Epoch 18/25: 100%|██████████| 4929/4929 [01:44<00:00, 47.19it/s, loss=0.1186]


Epoch 18/25 - Loss: 0.1558, Accuracy: 0.8691


Epoch 19/25: 100%|██████████| 4929/4929 [01:44<00:00, 47.04it/s, loss=0.1330]


Epoch 19/25 - Loss: 0.1548, Accuracy: 0.8693


Epoch 20/25: 100%|██████████| 4929/4929 [01:45<00:00, 46.91it/s, loss=0.2884]


Epoch 20/25 - Loss: 0.1553, Accuracy: 0.8690


Epoch 21/25: 100%|██████████| 4929/4929 [01:44<00:00, 47.23it/s, loss=0.2381]


Epoch 21/25 - Loss: 0.1551, Accuracy: 0.8696


Epoch 22/25: 100%|██████████| 4929/4929 [01:42<00:00, 47.88it/s, loss=0.1542]


Epoch 22/25 - Loss: 0.1551, Accuracy: 0.8691


Epoch 23/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.18it/s, loss=0.1239]


Epoch 23/25 - Loss: 0.1551, Accuracy: 0.8695


Epoch 24/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.03it/s, loss=0.0994]


Epoch 24/25 - Loss: 0.1550, Accuracy: 0.8688


Epoch 25/25: 100%|██████████| 4929/4929 [01:42<00:00, 47.88it/s, loss=0.2391]


Epoch 25/25 - Loss: 0.1549, Accuracy: 0.8694
Fold 5 Accuracy: 0.8185
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [01:43<00:00, 47.64it/s, loss=0.0552]


Epoch 1/25 - Loss: 0.1564, Accuracy: 0.8687


Epoch 2/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.59it/s, loss=0.1171]


Epoch 2/25 - Loss: 0.1564, Accuracy: 0.8691


Epoch 3/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.30it/s, loss=0.1987]


Epoch 3/25 - Loss: 0.1559, Accuracy: 0.8687


Epoch 4/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.21it/s, loss=0.1598]


Epoch 4/25 - Loss: 0.1561, Accuracy: 0.8689


Epoch 5/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.46it/s, loss=0.2365]


Epoch 5/25 - Loss: 0.1555, Accuracy: 0.8690


Epoch 6/25: 100%|██████████| 4929/4929 [01:42<00:00, 47.90it/s, loss=0.1867]


Epoch 6/25 - Loss: 0.1547, Accuracy: 0.8699


Epoch 7/25: 100%|██████████| 4929/4929 [01:04<00:00, 76.81it/s, loss=0.1281] 


Epoch 7/25 - Loss: 0.1550, Accuracy: 0.8691


Epoch 8/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.66it/s, loss=0.1528]


Epoch 8/25 - Loss: 0.1548, Accuracy: 0.8700


Epoch 9/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.92it/s, loss=0.2529]


Epoch 9/25 - Loss: 0.1548, Accuracy: 0.8693


Epoch 10/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.56it/s, loss=0.1450]


Epoch 10/25 - Loss: 0.1547, Accuracy: 0.8692


Epoch 11/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.25it/s, loss=0.2901]


Epoch 11/25 - Loss: 0.1545, Accuracy: 0.8695


Epoch 12/25: 100%|██████████| 4929/4929 [00:48<00:00, 100.70it/s, loss=0.1297]


Epoch 12/25 - Loss: 0.1546, Accuracy: 0.8693


Epoch 13/25: 100%|██████████| 4929/4929 [00:49<00:00, 99.30it/s, loss=0.1648] 


Epoch 13/25 - Loss: 0.1540, Accuracy: 0.8693


Epoch 14/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.98it/s, loss=0.1901] 


Epoch 14/25 - Loss: 0.1542, Accuracy: 0.8696


Epoch 15/25: 100%|██████████| 4929/4929 [01:19<00:00, 62.31it/s, loss=0.2420] 


Epoch 15/25 - Loss: 0.1539, Accuracy: 0.8699


Epoch 16/25: 100%|██████████| 4929/4929 [01:47<00:00, 46.01it/s, loss=0.2419] 


Epoch 16/25 - Loss: 0.1539, Accuracy: 0.8699


Epoch 17/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.23it/s, loss=0.1043] 


Epoch 17/25 - Loss: 0.1542, Accuracy: 0.8695


Epoch 18/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.34it/s, loss=0.2072] 


Epoch 18/25 - Loss: 0.1539, Accuracy: 0.8698


Epoch 19/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.29it/s, loss=0.1025] 


Epoch 19/25 - Loss: 0.1540, Accuracy: 0.8698


Epoch 20/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.09it/s, loss=0.1347] 


Epoch 20/25 - Loss: 0.1537, Accuracy: 0.8694


Epoch 21/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.80it/s, loss=0.3393] 


Epoch 21/25 - Loss: 0.1540, Accuracy: 0.8697


Epoch 22/25: 100%|██████████| 4929/4929 [00:51<00:00, 95.78it/s, loss=0.1896] 


Epoch 22/25 - Loss: 0.1532, Accuracy: 0.8700


Epoch 23/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.30it/s, loss=0.1554] 


Epoch 23/25 - Loss: 0.1536, Accuracy: 0.8705


Epoch 24/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.21it/s, loss=0.0828] 


Epoch 24/25 - Loss: 0.1532, Accuracy: 0.8700


Epoch 25/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.23it/s, loss=0.1624] 


Epoch 25/25 - Loss: 0.1535, Accuracy: 0.8697
Fold 6 Accuracy: 0.8215
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.53it/s, loss=0.1296] 


Epoch 1/25 - Loss: 0.1546, Accuracy: 0.8696


Epoch 2/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.89it/s, loss=0.2000]


Epoch 2/25 - Loss: 0.1539, Accuracy: 0.8703


Epoch 3/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.82it/s, loss=0.2934] 


Epoch 3/25 - Loss: 0.1537, Accuracy: 0.8691


Epoch 4/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.68it/s, loss=0.1396] 


Epoch 4/25 - Loss: 0.1540, Accuracy: 0.8695


Epoch 5/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.58it/s, loss=0.1298] 


Epoch 5/25 - Loss: 0.1534, Accuracy: 0.8701


Epoch 6/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.01it/s, loss=0.1364] 


Epoch 6/25 - Loss: 0.1539, Accuracy: 0.8692


Epoch 7/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.79it/s, loss=0.1199] 


Epoch 7/25 - Loss: 0.1534, Accuracy: 0.8700


Epoch 8/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.34it/s, loss=0.1254] 


Epoch 8/25 - Loss: 0.1535, Accuracy: 0.8695


Epoch 9/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.06it/s, loss=0.1342] 


Epoch 9/25 - Loss: 0.1534, Accuracy: 0.8694


Epoch 10/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.14it/s, loss=0.1494] 


Epoch 10/25 - Loss: 0.1534, Accuracy: 0.8702


Epoch 11/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.89it/s, loss=0.1683] 


Epoch 11/25 - Loss: 0.1527, Accuracy: 0.8701


Epoch 12/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.99it/s, loss=0.2371] 


Epoch 12/25 - Loss: 0.1531, Accuracy: 0.8703


Epoch 13/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.64it/s, loss=0.0856] 


Epoch 13/25 - Loss: 0.1532, Accuracy: 0.8700


Epoch 14/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.97it/s, loss=0.3104] 


Epoch 14/25 - Loss: 0.1530, Accuracy: 0.8700


Epoch 15/25: 100%|██████████| 4929/4929 [00:51<00:00, 95.95it/s, loss=0.0712] 


Epoch 15/25 - Loss: 0.1526, Accuracy: 0.8705


Epoch 16/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.16it/s, loss=0.1902] 


Epoch 16/25 - Loss: 0.1524, Accuracy: 0.8702


Epoch 17/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.26it/s, loss=0.2612] 


Epoch 17/25 - Loss: 0.1525, Accuracy: 0.8704


Epoch 18/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.41it/s, loss=0.1270] 


Epoch 18/25 - Loss: 0.1523, Accuracy: 0.8708


Epoch 19/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.43it/s, loss=0.1568] 


Epoch 19/25 - Loss: 0.1523, Accuracy: 0.8706


Epoch 20/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.73it/s, loss=0.1453] 


Epoch 20/25 - Loss: 0.1526, Accuracy: 0.8704


Epoch 21/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.37it/s, loss=0.1005] 


Epoch 21/25 - Loss: 0.1526, Accuracy: 0.8708


Epoch 22/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.75it/s, loss=0.1632] 


Epoch 22/25 - Loss: 0.1524, Accuracy: 0.8702


Epoch 23/25: 100%|██████████| 4929/4929 [00:50<00:00, 96.66it/s, loss=0.1334] 


Epoch 23/25 - Loss: 0.1522, Accuracy: 0.8705


Epoch 24/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.41it/s, loss=0.1395] 


Epoch 24/25 - Loss: 0.1523, Accuracy: 0.8706


Epoch 25/25: 100%|██████████| 4929/4929 [00:51<00:00, 96.58it/s, loss=0.0650] 


Epoch 25/25 - Loss: 0.1518, Accuracy: 0.8706
Fold 7 Accuracy: 0.8247
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.07it/s, loss=0.3052] 


Epoch 1/25 - Loss: 0.1531, Accuracy: 0.8693


Epoch 2/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.03it/s, loss=0.2460] 


Epoch 2/25 - Loss: 0.1528, Accuracy: 0.8697


Epoch 3/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.25it/s, loss=0.1237] 


Epoch 3/25 - Loss: 0.1522, Accuracy: 0.8708


Epoch 4/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.29it/s, loss=0.1891] 


Epoch 4/25 - Loss: 0.1527, Accuracy: 0.8704


Epoch 5/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.47it/s, loss=0.0819] 


Epoch 5/25 - Loss: 0.1520, Accuracy: 0.8705


Epoch 6/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.25it/s, loss=0.0947] 


Epoch 6/25 - Loss: 0.1522, Accuracy: 0.8706


Epoch 7/25: 100%|██████████| 4929/4929 [00:50<00:00, 97.29it/s, loss=0.1158] 


Epoch 7/25 - Loss: 0.1519, Accuracy: 0.8711


Epoch 8/25: 100%|██████████| 4929/4929 [00:50<00:00, 98.13it/s, loss=0.2794] 


Epoch 8/25 - Loss: 0.1520, Accuracy: 0.8704


Epoch 9/25: 100%|██████████| 4929/4929 [01:08<00:00, 71.90it/s, loss=0.1581] 


Epoch 9/25 - Loss: 0.1518, Accuracy: 0.8710


Epoch 10/25: 100%|██████████| 4929/4929 [01:37<00:00, 50.41it/s, loss=0.0711]


Epoch 10/25 - Loss: 0.1516, Accuracy: 0.8705


Epoch 11/25: 100%|██████████| 4929/4929 [01:35<00:00, 51.54it/s, loss=0.1814]


Epoch 11/25 - Loss: 0.1516, Accuracy: 0.8705


Epoch 12/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.57it/s, loss=0.2193]


Epoch 12/25 - Loss: 0.1515, Accuracy: 0.8707


Epoch 13/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.27it/s, loss=0.1572]


Epoch 13/25 - Loss: 0.1518, Accuracy: 0.8703


Epoch 14/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.62it/s, loss=0.1840]


Epoch 14/25 - Loss: 0.1514, Accuracy: 0.8706


Epoch 15/25: 100%|██████████| 4929/4929 [01:34<00:00, 52.15it/s, loss=0.0922]


Epoch 15/25 - Loss: 0.1515, Accuracy: 0.8714


Epoch 16/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.96it/s, loss=0.1438]


Epoch 16/25 - Loss: 0.1516, Accuracy: 0.8704


Epoch 17/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.97it/s, loss=0.0757]


Epoch 17/25 - Loss: 0.1519, Accuracy: 0.8715


Epoch 18/25: 100%|██████████| 4929/4929 [01:38<00:00, 49.93it/s, loss=0.2057]


Epoch 18/25 - Loss: 0.1511, Accuracy: 0.8712


Epoch 19/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.26it/s, loss=0.1314]


Epoch 19/25 - Loss: 0.1508, Accuracy: 0.8709


Epoch 20/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.22it/s, loss=0.1442]


Epoch 20/25 - Loss: 0.1510, Accuracy: 0.8713


Epoch 21/25: 100%|██████████| 4929/4929 [01:40<00:00, 49.04it/s, loss=0.0987]


Epoch 21/25 - Loss: 0.1498, Accuracy: 0.8718


Epoch 22/25: 100%|██████████| 4929/4929 [01:35<00:00, 51.74it/s, loss=0.2789]


Epoch 22/25 - Loss: 0.1508, Accuracy: 0.8714


Epoch 23/25: 100%|██████████| 4929/4929 [01:34<00:00, 52.38it/s, loss=0.1360]


Epoch 23/25 - Loss: 0.1512, Accuracy: 0.8716


Epoch 24/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.94it/s, loss=0.1079]


Epoch 24/25 - Loss: 0.1505, Accuracy: 0.8709


Epoch 25/25: 100%|██████████| 4929/4929 [01:34<00:00, 52.43it/s, loss=0.2837]


Epoch 25/25 - Loss: 0.1505, Accuracy: 0.8718
Fold 8 Accuracy: 0.8214
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [01:32<00:00, 53.09it/s, loss=0.1096]


Epoch 1/25 - Loss: 0.1517, Accuracy: 0.8709


Epoch 2/25: 100%|██████████| 4929/4929 [01:32<00:00, 53.39it/s, loss=0.2127]


Epoch 2/25 - Loss: 0.1515, Accuracy: 0.8711


Epoch 3/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.45it/s, loss=0.1313]


Epoch 3/25 - Loss: 0.1521, Accuracy: 0.8708


Epoch 4/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.24it/s, loss=0.1752]


Epoch 4/25 - Loss: 0.1509, Accuracy: 0.8708


Epoch 5/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.69it/s, loss=0.1640]


Epoch 5/25 - Loss: 0.1509, Accuracy: 0.8709


Epoch 6/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.69it/s, loss=0.0593]


Epoch 6/25 - Loss: 0.1511, Accuracy: 0.8707


Epoch 7/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.84it/s, loss=0.1477]


Epoch 7/25 - Loss: 0.1504, Accuracy: 0.8713


Epoch 8/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.35it/s, loss=0.1300]


Epoch 8/25 - Loss: 0.1508, Accuracy: 0.8717


Epoch 9/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.84it/s, loss=0.1189]


Epoch 9/25 - Loss: 0.1514, Accuracy: 0.8712


Epoch 10/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.49it/s, loss=0.1130]


Epoch 10/25 - Loss: 0.1511, Accuracy: 0.8711


Epoch 11/25: 100%|██████████| 4929/4929 [01:29<00:00, 54.83it/s, loss=0.1099]


Epoch 11/25 - Loss: 0.1503, Accuracy: 0.8721


Epoch 12/25: 100%|██████████| 4929/4929 [01:31<00:00, 54.04it/s, loss=0.1428]


Epoch 12/25 - Loss: 0.1507, Accuracy: 0.8715


Epoch 13/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.90it/s, loss=0.2303]


Epoch 13/25 - Loss: 0.1508, Accuracy: 0.8708


Epoch 14/25: 100%|██████████| 4929/4929 [01:31<00:00, 54.00it/s, loss=0.1956]


Epoch 14/25 - Loss: 0.1504, Accuracy: 0.8708


Epoch 15/25: 100%|██████████| 4929/4929 [01:31<00:00, 54.10it/s, loss=0.0894]


Epoch 15/25 - Loss: 0.1508, Accuracy: 0.8714


Epoch 16/25: 100%|██████████| 4929/4929 [01:37<00:00, 50.37it/s, loss=0.1171]


Epoch 16/25 - Loss: 0.1505, Accuracy: 0.8712


Epoch 17/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.65it/s, loss=0.1253]


Epoch 17/25 - Loss: 0.1504, Accuracy: 0.8715


Epoch 18/25: 100%|██████████| 4929/4929 [01:40<00:00, 48.91it/s, loss=0.0689]


Epoch 18/25 - Loss: 0.1503, Accuracy: 0.8713


Epoch 19/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.61it/s, loss=0.2401]


Epoch 19/25 - Loss: 0.1499, Accuracy: 0.8711


Epoch 20/25: 100%|██████████| 4929/4929 [01:43<00:00, 47.59it/s, loss=0.2121]


Epoch 20/25 - Loss: 0.1514, Accuracy: 0.8710


Epoch 21/25: 100%|██████████| 4929/4929 [01:42<00:00, 47.90it/s, loss=0.3422]


Epoch 21/25 - Loss: 0.1498, Accuracy: 0.8719


Epoch 22/25: 100%|██████████| 4929/4929 [01:01<00:00, 80.21it/s, loss=0.0923] 


Epoch 22/25 - Loss: 0.1501, Accuracy: 0.8718


Epoch 23/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.30it/s, loss=0.1712]


Epoch 23/25 - Loss: 0.1501, Accuracy: 0.8713


Epoch 24/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.11it/s, loss=0.1325]


Epoch 24/25 - Loss: 0.1495, Accuracy: 0.8715


Epoch 25/25: 100%|██████████| 4929/4929 [00:48<00:00, 100.71it/s, loss=0.1342]


Epoch 25/25 - Loss: 0.1500, Accuracy: 0.8719
Fold 9 Accuracy: 0.8223
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.68it/s, loss=0.1954]


Epoch 1/25 - Loss: 0.1515, Accuracy: 0.8705


Epoch 2/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.07it/s, loss=0.1293]


Epoch 2/25 - Loss: 0.1507, Accuracy: 0.8707


Epoch 3/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.09it/s, loss=0.1421]


Epoch 3/25 - Loss: 0.1507, Accuracy: 0.8709


Epoch 4/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.30it/s, loss=0.1901]


Epoch 4/25 - Loss: 0.1505, Accuracy: 0.8717


Epoch 5/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.01it/s, loss=0.1818]


Epoch 5/25 - Loss: 0.1505, Accuracy: 0.8716


Epoch 6/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.66it/s, loss=0.0828]


Epoch 6/25 - Loss: 0.1503, Accuracy: 0.8716


Epoch 7/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.29it/s, loss=0.1321]


Epoch 7/25 - Loss: 0.1504, Accuracy: 0.8717


Epoch 8/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.63it/s, loss=0.1560]


Epoch 8/25 - Loss: 0.1501, Accuracy: 0.8717


Epoch 9/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.78it/s, loss=0.1217]


Epoch 9/25 - Loss: 0.1507, Accuracy: 0.8713


Epoch 10/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.08it/s, loss=0.1175]


Epoch 10/25 - Loss: 0.1509, Accuracy: 0.8718


Epoch 11/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.78it/s, loss=0.0794]


Epoch 11/25 - Loss: 0.1498, Accuracy: 0.8717


Epoch 12/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.09it/s, loss=0.1657]


Epoch 12/25 - Loss: 0.1504, Accuracy: 0.8712


Epoch 13/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.63it/s, loss=0.1568]


Epoch 13/25 - Loss: 0.1499, Accuracy: 0.8716


Epoch 14/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.84it/s, loss=0.0925]


Epoch 14/25 - Loss: 0.1502, Accuracy: 0.8711


Epoch 15/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.48it/s, loss=0.0579]


Epoch 15/25 - Loss: 0.1500, Accuracy: 0.8712


Epoch 16/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.10it/s, loss=0.1334]


Epoch 16/25 - Loss: 0.1495, Accuracy: 0.8721


Epoch 17/25: 100%|██████████| 4929/4929 [00:48<00:00, 102.24it/s, loss=0.2558]


Epoch 17/25 - Loss: 0.1494, Accuracy: 0.8719


Epoch 18/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.74it/s, loss=0.0604]


Epoch 18/25 - Loss: 0.1492, Accuracy: 0.8723


Epoch 19/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.59it/s, loss=0.0626]


Epoch 19/25 - Loss: 0.1499, Accuracy: 0.8722


Epoch 20/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.58it/s, loss=0.1052]


Epoch 20/25 - Loss: 0.1489, Accuracy: 0.8719


Epoch 21/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.96it/s, loss=0.1687]


Epoch 21/25 - Loss: 0.1496, Accuracy: 0.8721


Epoch 22/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.78it/s, loss=0.1237]


Epoch 22/25 - Loss: 0.1493, Accuracy: 0.8712


Epoch 23/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.19it/s, loss=0.1902]


Epoch 23/25 - Loss: 0.1492, Accuracy: 0.8717


Epoch 24/25: 100%|██████████| 4929/4929 [00:49<00:00, 100.10it/s, loss=0.1363]


Epoch 24/25 - Loss: 0.1492, Accuracy: 0.8722


Epoch 25/25: 100%|██████████| 4929/4929 [00:48<00:00, 101.83it/s, loss=0.1512]


Epoch 25/25 - Loss: 0.1493, Accuracy: 0.8726
Fold 10 Accuracy: 0.8268
Complete model saved to modelU8.pth
Fold Accuracies:
  Fold 1: 0.8098
  Fold 2: 0.8174
  Fold 3: 0.8188
  Fold 4: 0.8221
  Fold 5: 0.8185
  Fold 6: 0.8215
  Fold 7: 0.8247
  Fold 8: 0.8214
  Fold 9: 0.8223
  Fold 10: 0.8268


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  19    0   17  199    0    0   33    0    0    0]
 [   0   17   18  194    0    1    0    0    2    0]
 [   0    7  229 1337    4   14   19   12   12    1]
 [   0   14  184 4017   20   27   97   59   19   15]
 [   0    0   31  273 1188    2  905   15   10    1]
 [   0    0   12   84    7 5778    2    0    3    1]
 [   1    0    3   42  323    1 8889   28   11    2]
 [   0    0   26  282    5    2   19 1060    5    0]
 [   0    0    1   24    5    1   19   13   88    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.95      0.07      0.13       268
      Backdoor       0.45      0.07      0.13       232
           DoS       0.44      0.14      0.21      1635
      Exploits       0.62      0.90      0.74      4452
       Fuzzers       0.77      0.49      0.60      2425
       Generic       0.99      0.98      0.99      5887
        Normal       0.