In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15    
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

# class FocalLoss(nn.Module):
#     def __init__(self, alpha=1, gamma=2, reduction='mean'):
#         super(FocalLoss, self).__init__()
#         self.alpha = alpha
#         self.gamma = gamma
#         self.reduction = reduction
# 
#     def forward(self, inputs, targets):
#         ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
#         pt = torch.exp(-ce_loss)  # 预测的概率
#         focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss
# 
#         if self.reduction == 'mean':
#             return focal_loss.mean()
#         elif self.reduction == 'sum':
#             return focal_loss.sum()
#         else:
#             return focal_loss

# criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    # X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-CEloss2.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 231905 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/3624 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.12it/s, loss=0.5261]


Epoch 1/15 - Loss: 0.5618, Accuracy: 0.7782


Epoch 2/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.70it/s, loss=0.6861]


Epoch 2/15 - Loss: 0.4903, Accuracy: 0.8028


Epoch 3/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.00it/s, loss=0.6421]


Epoch 3/15 - Loss: 0.4739, Accuracy: 0.8079


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.30it/s, loss=0.3766]


Epoch 4/15 - Loss: 0.4643, Accuracy: 0.8109


Epoch 5/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.19it/s, loss=0.6730]


Epoch 5/15 - Loss: 0.4564, Accuracy: 0.8132


Epoch 6/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.93it/s, loss=0.4049]


Epoch 6/15 - Loss: 0.4518, Accuracy: 0.8144


Epoch 7/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.15it/s, loss=0.3823]


Epoch 7/15 - Loss: 0.4461, Accuracy: 0.8159


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.16it/s, loss=0.5669]


Epoch 8/15 - Loss: 0.4414, Accuracy: 0.8172


Epoch 9/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.09it/s, loss=0.7191]


Epoch 9/15 - Loss: 0.4387, Accuracy: 0.8181


Epoch 10/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.19it/s, loss=0.2070]


Epoch 10/15 - Loss: 0.4355, Accuracy: 0.8198


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.22it/s, loss=0.4077]


Epoch 11/15 - Loss: 0.4325, Accuracy: 0.8205


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.63it/s, loss=0.5564]


Epoch 12/15 - Loss: 0.4302, Accuracy: 0.8212


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.03it/s, loss=0.4637]


Epoch 13/15 - Loss: 0.4288, Accuracy: 0.8222


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.11it/s, loss=0.2082]


Epoch 14/15 - Loss: 0.4277, Accuracy: 0.8221


Epoch 15/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.03it/s, loss=0.6379]


Epoch 15/15 - Loss: 0.4257, Accuracy: 0.8226
Fold 1 Accuracy: 0.8231
Fold 2: 231905 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.83it/s, loss=0.3825]


Epoch 1/15 - Loss: 0.4256, Accuracy: 0.8229


Epoch 2/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.16it/s, loss=0.4498]


Epoch 2/15 - Loss: 0.4237, Accuracy: 0.8241


Epoch 3/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.43it/s, loss=0.1901]


Epoch 3/15 - Loss: 0.4220, Accuracy: 0.8256


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.97it/s, loss=0.2482]


Epoch 4/15 - Loss: 0.4211, Accuracy: 0.8255


Epoch 5/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.14it/s, loss=0.4221]


Epoch 5/15 - Loss: 0.4190, Accuracy: 0.8261


Epoch 6/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.21it/s, loss=0.4990]


Epoch 6/15 - Loss: 0.4180, Accuracy: 0.8257


Epoch 7/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.97it/s, loss=0.4576]


Epoch 7/15 - Loss: 0.4160, Accuracy: 0.8271


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.17it/s, loss=0.5075]


Epoch 8/15 - Loss: 0.4154, Accuracy: 0.8273


Epoch 9/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.15it/s, loss=0.3558]


Epoch 9/15 - Loss: 0.4148, Accuracy: 0.8274


Epoch 10/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.24it/s, loss=0.3309]


Epoch 10/15 - Loss: 0.4134, Accuracy: 0.8283


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.58it/s, loss=0.3806]


Epoch 11/15 - Loss: 0.4123, Accuracy: 0.8285


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.13it/s, loss=0.3026]


Epoch 12/15 - Loss: 0.4107, Accuracy: 0.8295


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.08it/s, loss=0.2597]


Epoch 13/15 - Loss: 0.4093, Accuracy: 0.8296


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.13it/s, loss=0.3788]


Epoch 14/15 - Loss: 0.4081, Accuracy: 0.8298


Epoch 15/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.14it/s, loss=0.2789]


Epoch 15/15 - Loss: 0.4076, Accuracy: 0.8303
Fold 2 Accuracy: 0.8276
Fold 3: 231905 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.11it/s, loss=0.2921]


Epoch 1/15 - Loss: 0.4081, Accuracy: 0.8297


Epoch 2/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.12it/s, loss=0.3018]


Epoch 2/15 - Loss: 0.4067, Accuracy: 0.8303


Epoch 3/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.17it/s, loss=0.3567]


Epoch 3/15 - Loss: 0.4062, Accuracy: 0.8305


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.06it/s, loss=0.4525]


Epoch 4/15 - Loss: 0.4050, Accuracy: 0.8306


Epoch 5/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.54it/s, loss=0.2710]


Epoch 5/15 - Loss: 0.4028, Accuracy: 0.8320


Epoch 6/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.35it/s, loss=0.2429]


Epoch 6/15 - Loss: 0.4030, Accuracy: 0.8322


Epoch 7/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.05it/s, loss=0.4434]


Epoch 7/15 - Loss: 0.4011, Accuracy: 0.8323


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.83it/s, loss=0.4210]


Epoch 8/15 - Loss: 0.4001, Accuracy: 0.8332


Epoch 9/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.66it/s, loss=0.6459]


Epoch 9/15 - Loss: 0.3997, Accuracy: 0.8325


Epoch 10/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.02it/s, loss=0.4306]


Epoch 10/15 - Loss: 0.3981, Accuracy: 0.8339


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.83it/s, loss=0.3379]


Epoch 11/15 - Loss: 0.3968, Accuracy: 0.8342


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.11it/s, loss=0.2700]


Epoch 12/15 - Loss: 0.3960, Accuracy: 0.8346


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.15it/s, loss=0.3536]


Epoch 13/15 - Loss: 0.3953, Accuracy: 0.8344


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.85it/s, loss=0.3125]


Epoch 14/15 - Loss: 0.3944, Accuracy: 0.8340


Epoch 15/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.68it/s, loss=0.6551]


Epoch 15/15 - Loss: 0.3943, Accuracy: 0.8352
Fold 3 Accuracy: 0.8318
Fold 4: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.01it/s, loss=0.2186]


Epoch 1/15 - Loss: 0.3945, Accuracy: 0.8353


Epoch 2/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.44it/s, loss=0.4781]


Epoch 2/15 - Loss: 0.3933, Accuracy: 0.8354


Epoch 3/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.21it/s, loss=0.5798]


Epoch 3/15 - Loss: 0.3922, Accuracy: 0.8360


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.57it/s, loss=0.3948]


Epoch 4/15 - Loss: 0.3911, Accuracy: 0.8363


Epoch 5/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.01it/s, loss=0.3392]


Epoch 5/15 - Loss: 0.3906, Accuracy: 0.8377


Epoch 6/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.99it/s, loss=0.3459]


Epoch 6/15 - Loss: 0.3893, Accuracy: 0.8371


Epoch 7/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.19it/s, loss=0.4951]


Epoch 7/15 - Loss: 0.3892, Accuracy: 0.8373


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.07it/s, loss=0.2588]


Epoch 8/15 - Loss: 0.3879, Accuracy: 0.8376


Epoch 9/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.87it/s, loss=0.4296]


Epoch 9/15 - Loss: 0.3875, Accuracy: 0.8382


Epoch 10/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.24it/s, loss=0.6031]


Epoch 10/15 - Loss: 0.3859, Accuracy: 0.8381


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.60it/s, loss=0.3400]


Epoch 11/15 - Loss: 0.3849, Accuracy: 0.8391


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.18it/s, loss=0.4971]


Epoch 12/15 - Loss: 0.3846, Accuracy: 0.8381


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.13it/s, loss=0.1746]


Epoch 13/15 - Loss: 0.3839, Accuracy: 0.8393


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.29it/s, loss=0.2661]


Epoch 14/15 - Loss: 0.3828, Accuracy: 0.8399


Epoch 15/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.89it/s, loss=0.4582]


Epoch 15/15 - Loss: 0.3827, Accuracy: 0.8395
Fold 4 Accuracy: 0.8328
Fold 5: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.42it/s, loss=0.2561]


Epoch 1/15 - Loss: 0.3855, Accuracy: 0.8386


Epoch 2/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.34it/s, loss=0.2972]


Epoch 2/15 - Loss: 0.3842, Accuracy: 0.8390


Epoch 3/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.39it/s, loss=0.2494]


Epoch 3/15 - Loss: 0.3836, Accuracy: 0.8390


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.94it/s, loss=0.2802]


Epoch 4/15 - Loss: 0.3824, Accuracy: 0.8398


Epoch 5/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.21it/s, loss=0.2385]


Epoch 5/15 - Loss: 0.3817, Accuracy: 0.8401


Epoch 6/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.11it/s, loss=0.2350]


Epoch 6/15 - Loss: 0.3806, Accuracy: 0.8407


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.72it/s, loss=0.4232]


Epoch 7/15 - Loss: 0.3802, Accuracy: 0.8412


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.96it/s, loss=0.4920]


Epoch 8/15 - Loss: 0.3794, Accuracy: 0.8408


Epoch 9/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.33it/s, loss=0.2549]


Epoch 9/15 - Loss: 0.3788, Accuracy: 0.8410


Epoch 10/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.36it/s, loss=0.4901]


Epoch 10/15 - Loss: 0.3779, Accuracy: 0.8412


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.20it/s, loss=0.4621]


Epoch 11/15 - Loss: 0.3769, Accuracy: 0.8424


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.02it/s, loss=0.3528]


Epoch 12/15 - Loss: 0.3765, Accuracy: 0.8423


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.30it/s, loss=0.5862]


Epoch 13/15 - Loss: 0.3750, Accuracy: 0.8426


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.49it/s, loss=0.3119]


Epoch 14/15 - Loss: 0.3739, Accuracy: 0.8432


Epoch 15/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.47it/s, loss=0.2701]


Epoch 15/15 - Loss: 0.3734, Accuracy: 0.8432
Fold 5 Accuracy: 0.8419
Fold 6: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.59it/s, loss=0.3549]


Epoch 1/15 - Loss: 0.3760, Accuracy: 0.8422


Epoch 2/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.52it/s, loss=0.4061]


Epoch 2/15 - Loss: 0.3749, Accuracy: 0.8429


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.96it/s, loss=0.2890]


Epoch 3/15 - Loss: 0.3738, Accuracy: 0.8431


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.43it/s, loss=0.3795]


Epoch 4/15 - Loss: 0.3729, Accuracy: 0.8435


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.53it/s, loss=0.2728]


Epoch 5/15 - Loss: 0.3721, Accuracy: 0.8432


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.01it/s, loss=0.1336]


Epoch 6/15 - Loss: 0.3717, Accuracy: 0.8438


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.79it/s, loss=0.1882]


Epoch 7/15 - Loss: 0.3710, Accuracy: 0.8446


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.79it/s, loss=0.4092]


Epoch 8/15 - Loss: 0.3701, Accuracy: 0.8449


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.69it/s, loss=0.3102]


Epoch 9/15 - Loss: 0.3692, Accuracy: 0.8454


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.59it/s, loss=0.2911]


Epoch 10/15 - Loss: 0.3681, Accuracy: 0.8459


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.06it/s, loss=0.2806]


Epoch 11/15 - Loss: 0.3674, Accuracy: 0.8451


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.59it/s, loss=0.2277]


Epoch 12/15 - Loss: 0.3670, Accuracy: 0.8463


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.02it/s, loss=0.1767]


Epoch 13/15 - Loss: 0.3660, Accuracy: 0.8464


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.79it/s, loss=0.2706]


Epoch 14/15 - Loss: 0.3661, Accuracy: 0.8460


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.69it/s, loss=0.3701]


Epoch 15/15 - Loss: 0.3649, Accuracy: 0.8470
Fold 6 Accuracy: 0.8447
Fold 7: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.85it/s, loss=0.3091]


Epoch 1/15 - Loss: 0.3685, Accuracy: 0.8451


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.36it/s, loss=0.4216]


Epoch 2/15 - Loss: 0.3661, Accuracy: 0.8461


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.4580]


Epoch 3/15 - Loss: 0.3656, Accuracy: 0.8467


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.84it/s, loss=0.2955]


Epoch 4/15 - Loss: 0.3640, Accuracy: 0.8476


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.63it/s, loss=0.3858]


Epoch 5/15 - Loss: 0.3634, Accuracy: 0.8470


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.53it/s, loss=0.1749]


Epoch 6/15 - Loss: 0.3628, Accuracy: 0.8480


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.79it/s, loss=0.2362]


Epoch 7/15 - Loss: 0.3613, Accuracy: 0.8479


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.67it/s, loss=0.4232]


Epoch 8/15 - Loss: 0.3614, Accuracy: 0.8483


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.4717]


Epoch 9/15 - Loss: 0.3606, Accuracy: 0.8483


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.75it/s, loss=0.3400]


Epoch 10/15 - Loss: 0.3604, Accuracy: 0.8486


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.3615]


Epoch 11/15 - Loss: 0.3601, Accuracy: 0.8488


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.66it/s, loss=0.2636]


Epoch 12/15 - Loss: 0.3586, Accuracy: 0.8493


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.62it/s, loss=0.3953]


Epoch 13/15 - Loss: 0.3577, Accuracy: 0.8498


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.20it/s, loss=0.2528]


Epoch 14/15 - Loss: 0.3571, Accuracy: 0.8499


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.47it/s, loss=0.3362]


Epoch 15/15 - Loss: 0.3569, Accuracy: 0.8503
Fold 7 Accuracy: 0.8441
Fold 8: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.56it/s, loss=0.3610]


Epoch 1/15 - Loss: 0.3617, Accuracy: 0.8483


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.04it/s, loss=0.4134]


Epoch 2/15 - Loss: 0.3607, Accuracy: 0.8487


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.76it/s, loss=0.3566]


Epoch 3/15 - Loss: 0.3602, Accuracy: 0.8491


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.13it/s, loss=0.4502]


Epoch 4/15 - Loss: 0.3581, Accuracy: 0.8492


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.05it/s, loss=0.2524]


Epoch 5/15 - Loss: 0.3572, Accuracy: 0.8503


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.09it/s, loss=0.6067]


Epoch 6/15 - Loss: 0.3574, Accuracy: 0.8501


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.50it/s, loss=0.2999]


Epoch 7/15 - Loss: 0.3553, Accuracy: 0.8506


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.06it/s, loss=0.5315]


Epoch 8/15 - Loss: 0.3561, Accuracy: 0.8505


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.08it/s, loss=0.4597]


Epoch 9/15 - Loss: 0.3550, Accuracy: 0.8504


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.57it/s, loss=0.4099]


Epoch 10/15 - Loss: 0.3537, Accuracy: 0.8512


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.19it/s, loss=0.3305]


Epoch 11/15 - Loss: 0.3535, Accuracy: 0.8503


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.03it/s, loss=0.3774]


Epoch 12/15 - Loss: 0.3521, Accuracy: 0.8520


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.03it/s, loss=0.3410]


Epoch 13/15 - Loss: 0.3525, Accuracy: 0.8518


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.34it/s, loss=0.1229]


Epoch 14/15 - Loss: 0.3516, Accuracy: 0.8521


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.64it/s, loss=0.3318]


Epoch 15/15 - Loss: 0.3513, Accuracy: 0.8526
Fold 8 Accuracy: 0.8492
Fold 9: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.80it/s, loss=0.4124]


Epoch 1/15 - Loss: 0.3553, Accuracy: 0.8505


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.31it/s, loss=0.1102]


Epoch 2/15 - Loss: 0.3531, Accuracy: 0.8517


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.97it/s, loss=0.2194]


Epoch 3/15 - Loss: 0.3523, Accuracy: 0.8517


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.13it/s, loss=0.2477]


Epoch 4/15 - Loss: 0.3512, Accuracy: 0.8521


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.89it/s, loss=0.4231]


Epoch 5/15 - Loss: 0.3510, Accuracy: 0.8527


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.57it/s, loss=0.4151]


Epoch 6/15 - Loss: 0.3507, Accuracy: 0.8530


Epoch 7/15: 100%|██████████| 3624/3624 [00:43<00:00, 84.03it/s, loss=0.3414]


Epoch 7/15 - Loss: 0.3491, Accuracy: 0.8530


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.83it/s, loss=0.7644]


Epoch 8/15 - Loss: 0.3485, Accuracy: 0.8537


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.13it/s, loss=0.3531]


Epoch 9/15 - Loss: 0.3488, Accuracy: 0.8538


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.92it/s, loss=0.4117]


Epoch 10/15 - Loss: 0.3475, Accuracy: 0.8540


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.03it/s, loss=0.4149]


Epoch 11/15 - Loss: 0.3486, Accuracy: 0.8537


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.25it/s, loss=0.4794]


Epoch 12/15 - Loss: 0.3476, Accuracy: 0.8538


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.70it/s, loss=0.4632]


Epoch 13/15 - Loss: 0.3455, Accuracy: 0.8553


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.20it/s, loss=0.2550]


Epoch 14/15 - Loss: 0.3454, Accuracy: 0.8541


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.40it/s, loss=0.3319]


Epoch 15/15 - Loss: 0.3446, Accuracy: 0.8557
Fold 9 Accuracy: 0.8508
Fold 10: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.05it/s, loss=0.5382]


Epoch 1/15 - Loss: 0.3499, Accuracy: 0.8536


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.67it/s, loss=0.2183]


Epoch 2/15 - Loss: 0.3487, Accuracy: 0.8524


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.87it/s, loss=0.2697]


Epoch 3/15 - Loss: 0.3470, Accuracy: 0.8543


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.36it/s, loss=0.3863]


Epoch 4/15 - Loss: 0.3471, Accuracy: 0.8538


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.19it/s, loss=0.4836]


Epoch 5/15 - Loss: 0.3458, Accuracy: 0.8542


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.99it/s, loss=0.5455]


Epoch 6/15 - Loss: 0.3453, Accuracy: 0.8550


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.48it/s, loss=0.3424]


Epoch 7/15 - Loss: 0.3441, Accuracy: 0.8551


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.70it/s, loss=0.5480]


Epoch 8/15 - Loss: 0.3435, Accuracy: 0.8555


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.84it/s, loss=0.2838]


Epoch 9/15 - Loss: 0.3436, Accuracy: 0.8557


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.18it/s, loss=0.4244]


Epoch 10/15 - Loss: 0.3429, Accuracy: 0.8555


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.41it/s, loss=0.2734]


Epoch 11/15 - Loss: 0.3421, Accuracy: 0.8558


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.64it/s, loss=0.5014]


Epoch 12/15 - Loss: 0.3421, Accuracy: 0.8561


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.20it/s, loss=0.5540]


Epoch 13/15 - Loss: 0.3408, Accuracy: 0.8565


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.07it/s, loss=0.3809]


Epoch 14/15 - Loss: 0.3406, Accuracy: 0.8564


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.55it/s, loss=0.3583]


Epoch 15/15 - Loss: 0.3414, Accuracy: 0.8561
Fold 10 Accuracy: 0.8570
Complete model saved to UNSW-CEloss2.pth
Fold Accuracies:
  Fold 1: 0.8231
  Fold 2: 0.8276
  Fold 3: 0.8318
  Fold 4: 0.8328
  Fold 5: 0.8419
  Fold 6: 0.8447
  Fold 7: 0.8441
  Fold 8: 0.8492
  Fold 9: 0.8508
  Fold 10: 0.8570


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  36    0   39  136   41    0   16    0    0    0]
 [   0   35   40  111   46    0    0    0    0    0]
 [   0    1  447 1104   46    6   13   12    6    0]
 [   1    2  325 3848  115   15   54   74   12    6]
 [   0    0   39  156 1738    1  474    7   10    0]
 [   0    0   10   33    4 5837    1    2    0    0]
 [   4    0    9   33  313    0 8929    5    7    0]
 [   0    0   61  230    2    0    1 1103    2    0]
 [   0    0    4   17    6    2   14    5  103    0]
 [   0    0    0    9    1    0    0    0    1    7]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.88      0.13      0.23       268
      Backdoor       0.92      0.15      0.26       232
           DoS       0.46      0.27      0.34      1635
      Exploits       0.68      0.86      0.76      4452
       Fuzzers       0.75      0.72      0.73      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.