In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# 需要进行 One-hot 编码的列
cols = ['proto', 'state', 'service']

# One-hot 编码函数
def one_hot_encode(df, cols):
    return pd.get_dummies(df, columns=cols, drop_first=False)

# 合并数据进行 One-hot 编码
combined_data = pd.concat([train_df, test_df])
combined_data = one_hot_encode(combined_data, cols)

# 分离特征和目标变量
target = combined_data.pop('attack_cat')

# 归一化函数
def normalize(df):
    scaler = StandardScaler()
    df[:] = scaler.fit_transform(df)
    return df

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data["Class"] = target

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 进行 One-hot 编码
encoder = OneHotEncoder(sparse=False)
y_onehot = encoder.fit_transform(y.reshape(-1, 1))

# 转换为 PyTorch 张量
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y_onehot, dtype=torch.float32)


Train missing values: 0
Test missing values: 0
(257673, 196)


E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [2]:
import torch
import torch.nn as nn

class ASTP(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        # 多尺度时间卷积（避免小卷积核）
        self.temp_conv = nn.ModuleList([
            nn.Conv1d(in_channels, 16, 32, padding='same'),  # 空洞率2
            nn.Conv1d(in_channels, 16, 64, padding='same', dilation=2),
            nn.Conv1d(in_channels, 16, 96, padding='same', dilation=4)
        ])
        # 特征动态融合（参考IEEE TDSC 2023）
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )
        # 空间注意力（参考ACM CCS 2022）
        self.spatial_att = nn.Sequential(
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [conv(x) for conv in self.temp_conv]
        merged = torch.cat(branch_outs, dim=1)  # [B,48,L]
        # 动态特征融合
        fused = merged * self.fusion_gate(merged)  # [B,48,L]
        # 空间注意力增强
        return fused * self.spatial_att(fused)

class TRGU(nn.Module):
    def __init__(self, feat_dim):
        super().__init__()
        # 门控机制（参考ICML 2023）
        self.gate = nn.Sequential(
            nn.Linear(feat_dim, feat_dim),
            nn.Sigmoid()
        )
        # 残差时序卷积（替代LSTM）
        self.res_conv = nn.Sequential(
            nn.Conv1d(feat_dim, feat_dim, 64, padding='same'),
            nn.BatchNorm1d(feat_dim),
            nn.GELU()
        )
        # 时间注意力
        self.time_att = nn.MultiheadAttention(feat_dim, 4, batch_first=True)

    def forward(self, x):
        # x shape: [B,L,D]
        # 残差路径
        residual = x
        # 时序卷积
        x_conv = self.res_conv(x.permute(0,2,1)).permute(0,2,1)  # [B,L,D]
        # 时间注意力
        x_att, _ = self.time_att(x, x, x)  # [B,L,D]
        # 门控融合
        gate = self.gate(x)
        return residual + gate*x_conv + (1-gate)*x_att

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10):
        super().__init__()
        
        # 特征提取层
        self.astp = ASTP(in_channels=1)
        self.pool = nn.AdaptiveMaxPool1d(input_dim//4)
        self.bn = nn.BatchNorm1d(48)
        
        # 时序建模
        self.trgu = nn.Sequential(
            TRGU(48),
            TRGU(48),
            nn.TransformerEncoder(
                encoder_layer=nn.TransformerEncoderLayer(
                    d_model=48,
                    nhead=4,
                    dim_feedforward=192,
                    batch_first=True
                ),
                num_layers=2
            )
        )
        
        # 分类头（改进自IEEE TDSC 2023）
        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(48, 128),
            nn.BatchNorm1d(128),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        # 输入形状: [B,1,122]
        x = self.astp(x)          # [B,48,122]
        x = self.pool(x)          # [B,48,30]
        x = self.bn(x)            # 特征标准化
        x = x.permute(0,2,1)      # [B,30,48]
        x = self.trgu(x)          # [B,30,48]
        x = x.permute(0,2,1)      # [B,48,30]
        return self.classifier(x) # [B,num_classes]


In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs = 20    #15轮 84.16左右
learning_rate = 0.0008
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
oversample = RandomOverSampler(sampling_strategy='minority')

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
        pt = torch.exp(-ce_loss)  # 预测的概率
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 遍历折叠
for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y), start=1):

    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 使用 LabelEncoder 转换 y_train 和 y_test
    label_encoder = LabelEncoder()
    y_train = label_encoder.fit_transform(y_train)  # 转换成整数标签
    y_test = label_encoder.transform(y_test)

    # 确保 y_train 和 y_test 是 numpy 数组的 int 类型
    y_train = y_train.astype(np.int64)
    y_test = y_test.astype(np.int64)

    # 转换为 PyTorch 数据集
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32), torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32), torch.tensor(y_test, dtype=torch.long))

    # 加载数据
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "modelU8.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Epoch 1/20:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/20: 100%|██████████| 4929/4929 [00:52<00:00, 93.44it/s, loss=0.3568] 


Epoch 1/20 - Loss: 0.3117, Accuracy: 0.8041


Epoch 2/20: 100%|██████████| 4929/4929 [00:47<00:00, 103.56it/s, loss=0.3238]


Epoch 2/20 - Loss: 0.2420, Accuracy: 0.8309


Epoch 3/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.12it/s, loss=0.1463]


Epoch 3/20 - Loss: 0.2249, Accuracy: 0.8390


Epoch 4/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.32it/s, loss=0.2177]


Epoch 4/20 - Loss: 0.2154, Accuracy: 0.8434


Epoch 5/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.54it/s, loss=0.2935]


Epoch 5/20 - Loss: 0.2074, Accuracy: 0.8474


Epoch 6/20: 100%|██████████| 4929/4929 [00:50<00:00, 96.79it/s, loss=0.1940] 


Epoch 6/20 - Loss: 0.2021, Accuracy: 0.8492


Epoch 7/20: 100%|██████████| 4929/4929 [00:50<00:00, 97.05it/s, loss=0.1862] 


Epoch 7/20 - Loss: 0.1986, Accuracy: 0.8503


Epoch 8/20: 100%|██████████| 4929/4929 [00:51<00:00, 96.06it/s, loss=0.2507] 


Epoch 8/20 - Loss: 0.1950, Accuracy: 0.8520


Epoch 9/20: 100%|██████████| 4929/4929 [00:49<00:00, 98.62it/s, loss=0.1829] 


Epoch 9/20 - Loss: 0.1923, Accuracy: 0.8529


Epoch 10/20: 100%|██████████| 4929/4929 [00:50<00:00, 98.48it/s, loss=0.1342] 


Epoch 10/20 - Loss: 0.1901, Accuracy: 0.8542


Epoch 11/20: 100%|██████████| 4929/4929 [00:49<00:00, 98.76it/s, loss=0.1092] 


Epoch 11/20 - Loss: 0.1885, Accuracy: 0.8550


Epoch 12/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.25it/s, loss=0.3100]


Epoch 12/20 - Loss: 0.1863, Accuracy: 0.8561


Epoch 13/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.09it/s, loss=0.1662]


Epoch 13/20 - Loss: 0.1847, Accuracy: 0.8571


Epoch 14/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.12it/s, loss=0.1682]


Epoch 14/20 - Loss: 0.1832, Accuracy: 0.8579


Epoch 15/20: 100%|██████████| 4929/4929 [00:49<00:00, 99.77it/s, loss=0.1019] 


Epoch 15/20 - Loss: 0.1817, Accuracy: 0.8585


Epoch 16/20: 100%|██████████| 4929/4929 [00:50<00:00, 97.79it/s, loss=0.1699] 


Epoch 16/20 - Loss: 0.1804, Accuracy: 0.8590


Epoch 17/20: 100%|██████████| 4929/4929 [00:49<00:00, 98.82it/s, loss=0.1748] 


Epoch 17/20 - Loss: 0.1795, Accuracy: 0.8598


Epoch 18/20: 100%|██████████| 4929/4929 [00:49<00:00, 99.08it/s, loss=0.1295] 


Epoch 18/20 - Loss: 0.1775, Accuracy: 0.8599


Epoch 19/20: 100%|██████████| 4929/4929 [00:49<00:00, 99.79it/s, loss=0.1952] 


Epoch 19/20 - Loss: 0.1765, Accuracy: 0.8606


Epoch 20/20: 100%|██████████| 4929/4929 [00:50<00:00, 98.21it/s, loss=0.2138] 


Epoch 20/20 - Loss: 0.1762, Accuracy: 0.8613
Fold 1 Accuracy: 0.8125


Epoch 1/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.32it/s, loss=0.1657]


Epoch 1/20 - Loss: 0.1770, Accuracy: 0.8606


Epoch 2/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.49it/s, loss=0.0663]


Epoch 2/20 - Loss: 0.1748, Accuracy: 0.8614


Epoch 3/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.72it/s, loss=0.1000]


Epoch 3/20 - Loss: 0.1747, Accuracy: 0.8613


Epoch 4/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.78it/s, loss=0.0796]


Epoch 4/20 - Loss: 0.1729, Accuracy: 0.8625


Epoch 5/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.39it/s, loss=0.0695]


Epoch 5/20 - Loss: 0.1720, Accuracy: 0.8628


Epoch 6/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.03it/s, loss=0.0958]


Epoch 6/20 - Loss: 0.1710, Accuracy: 0.8627


Epoch 7/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.13it/s, loss=0.1587]


Epoch 7/20 - Loss: 0.1700, Accuracy: 0.8630


Epoch 8/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.24it/s, loss=0.2238]


Epoch 8/20 - Loss: 0.1692, Accuracy: 0.8638


Epoch 9/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.97it/s, loss=0.2814]


Epoch 9/20 - Loss: 0.1682, Accuracy: 0.8638


Epoch 10/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.65it/s, loss=0.1425]


Epoch 10/20 - Loss: 0.1683, Accuracy: 0.8637


Epoch 11/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.32it/s, loss=0.1758]


Epoch 11/20 - Loss: 0.1672, Accuracy: 0.8645


Epoch 12/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.05it/s, loss=0.1679]


Epoch 12/20 - Loss: 0.1664, Accuracy: 0.8647


Epoch 13/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.52it/s, loss=0.1587]


Epoch 13/20 - Loss: 0.1660, Accuracy: 0.8650


Epoch 14/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.09it/s, loss=0.2127]


Epoch 14/20 - Loss: 0.1653, Accuracy: 0.8656


Epoch 15/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.45it/s, loss=0.0662]


Epoch 15/20 - Loss: 0.1649, Accuracy: 0.8650


Epoch 16/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.62it/s, loss=0.1051]


Epoch 16/20 - Loss: 0.1645, Accuracy: 0.8656


Epoch 17/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.27it/s, loss=0.1382]


Epoch 17/20 - Loss: 0.1642, Accuracy: 0.8654


Epoch 18/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.16it/s, loss=0.1563]


Epoch 18/20 - Loss: 0.1650, Accuracy: 0.8655


Epoch 19/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.80it/s, loss=0.1367]


Epoch 19/20 - Loss: 0.1653, Accuracy: 0.8655


Epoch 20/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.86it/s, loss=0.0775]


Epoch 20/20 - Loss: 0.1660, Accuracy: 0.8647
Fold 2 Accuracy: 0.8131


Epoch 1/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.92it/s, loss=0.1963]


Epoch 1/20 - Loss: 0.1668, Accuracy: 0.8643


Epoch 2/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.04it/s, loss=0.2141]


Epoch 2/20 - Loss: 0.1670, Accuracy: 0.8644


Epoch 3/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.57it/s, loss=0.1553]


Epoch 3/20 - Loss: 0.1669, Accuracy: 0.8646


Epoch 4/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.66it/s, loss=0.1142]


Epoch 4/20 - Loss: 0.1666, Accuracy: 0.8641


Epoch 5/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.84it/s, loss=0.1088]


Epoch 5/20 - Loss: 0.1652, Accuracy: 0.8651


Epoch 6/20: 100%|██████████| 4929/4929 [00:50<00:00, 97.47it/s, loss=0.1871] 


Epoch 6/20 - Loss: 0.1664, Accuracy: 0.8654


Epoch 7/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.69it/s, loss=0.1970]


Epoch 7/20 - Loss: 0.1642, Accuracy: 0.8657


Epoch 8/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.84it/s, loss=0.2320]


Epoch 8/20 - Loss: 0.1643, Accuracy: 0.8658


Epoch 9/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.99it/s, loss=0.1635]


Epoch 9/20 - Loss: 0.1655, Accuracy: 0.8650


Epoch 10/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.31it/s, loss=0.0575]


Epoch 10/20 - Loss: 0.1632, Accuracy: 0.8662


Epoch 11/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.91it/s, loss=0.3949]


Epoch 11/20 - Loss: 0.1631, Accuracy: 0.8662


Epoch 12/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.46it/s, loss=0.1110]


Epoch 12/20 - Loss: 0.1628, Accuracy: 0.8662


Epoch 13/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.76it/s, loss=0.1507]


Epoch 13/20 - Loss: 0.1621, Accuracy: 0.8672


Epoch 14/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.20it/s, loss=0.1467]


Epoch 14/20 - Loss: 0.1616, Accuracy: 0.8677


Epoch 15/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.48it/s, loss=0.1007]


Epoch 15/20 - Loss: 0.1608, Accuracy: 0.8669


Epoch 16/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.33it/s, loss=0.2333]


Epoch 16/20 - Loss: 0.1608, Accuracy: 0.8670


Epoch 17/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.79it/s, loss=0.1553]


Epoch 17/20 - Loss: 0.1603, Accuracy: 0.8674


Epoch 18/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.72it/s, loss=0.1328]


Epoch 18/20 - Loss: 0.1600, Accuracy: 0.8682


Epoch 19/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.52it/s, loss=0.1858]


Epoch 19/20 - Loss: 0.1597, Accuracy: 0.8676


Epoch 20/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.73it/s, loss=0.1304]


Epoch 20/20 - Loss: 0.1591, Accuracy: 0.8682
Fold 3 Accuracy: 0.8097


Epoch 1/20: 100%|██████████| 4929/4929 [00:46<00:00, 104.92it/s, loss=0.1959]


Epoch 1/20 - Loss: 0.1596, Accuracy: 0.8684


Epoch 2/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.30it/s, loss=0.2276]


Epoch 2/20 - Loss: 0.1594, Accuracy: 0.8682


Epoch 3/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.95it/s, loss=0.1542]


Epoch 3/20 - Loss: 0.1590, Accuracy: 0.8685


Epoch 4/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.03it/s, loss=0.2226]


Epoch 4/20 - Loss: 0.1581, Accuracy: 0.8687


Epoch 5/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.75it/s, loss=0.1778]


Epoch 5/20 - Loss: 0.1577, Accuracy: 0.8689


Epoch 6/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.63it/s, loss=0.1953]


Epoch 6/20 - Loss: 0.1575, Accuracy: 0.8688


Epoch 7/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.95it/s, loss=0.1140]


Epoch 7/20 - Loss: 0.1569, Accuracy: 0.8694


Epoch 8/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.34it/s, loss=0.1694]


Epoch 8/20 - Loss: 0.1560, Accuracy: 0.8697


Epoch 9/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.86it/s, loss=0.1947]


Epoch 9/20 - Loss: 0.1556, Accuracy: 0.8697


Epoch 10/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.74it/s, loss=0.1356]


Epoch 10/20 - Loss: 0.1554, Accuracy: 0.8702


Epoch 11/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.33it/s, loss=0.1758]


Epoch 11/20 - Loss: 0.1548, Accuracy: 0.8699


Epoch 12/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.53it/s, loss=0.1828]


Epoch 12/20 - Loss: 0.1549, Accuracy: 0.8703


Epoch 13/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.15it/s, loss=0.2026]


Epoch 13/20 - Loss: 0.1546, Accuracy: 0.8702


Epoch 14/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.37it/s, loss=0.1906]


Epoch 14/20 - Loss: 0.1543, Accuracy: 0.8703


Epoch 15/20: 100%|██████████| 4929/4929 [00:48<00:00, 100.79it/s, loss=0.1383]


Epoch 15/20 - Loss: 0.1537, Accuracy: 0.8709


Epoch 16/20: 100%|██████████| 4929/4929 [00:47<00:00, 104.29it/s, loss=0.1483]


Epoch 16/20 - Loss: 0.1531, Accuracy: 0.8715


Epoch 17/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.63it/s, loss=0.1234]


Epoch 17/20 - Loss: 0.1579, Accuracy: 0.8695


Epoch 18/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.42it/s, loss=0.1773]


Epoch 18/20 - Loss: 0.1560, Accuracy: 0.8704


Epoch 19/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.78it/s, loss=0.0712]


Epoch 19/20 - Loss: 0.1560, Accuracy: 0.8697


Epoch 20/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.53it/s, loss=0.0978]


Epoch 20/20 - Loss: 0.1548, Accuracy: 0.8706
Fold 4 Accuracy: 0.8172


Epoch 1/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.96it/s, loss=0.0594]


Epoch 1/20 - Loss: 0.1565, Accuracy: 0.8699


Epoch 2/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.51it/s, loss=0.1087]


Epoch 2/20 - Loss: 0.1555, Accuracy: 0.8702


Epoch 3/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.36it/s, loss=0.1730]


Epoch 3/20 - Loss: 0.1550, Accuracy: 0.8705


Epoch 4/20: 100%|██████████| 4929/4929 [00:44<00:00, 109.59it/s, loss=0.2109]


Epoch 4/20 - Loss: 0.1553, Accuracy: 0.8698


Epoch 5/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.32it/s, loss=0.2793]


Epoch 5/20 - Loss: 0.1557, Accuracy: 0.8696


Epoch 6/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.33it/s, loss=0.1351]


Epoch 6/20 - Loss: 0.1555, Accuracy: 0.8696


Epoch 7/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.60it/s, loss=0.2522]


Epoch 7/20 - Loss: 0.1547, Accuracy: 0.8704


Epoch 8/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.01it/s, loss=0.1155]


Epoch 8/20 - Loss: 0.1535, Accuracy: 0.8708


Epoch 9/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.39it/s, loss=0.1619]


Epoch 9/20 - Loss: 0.1549, Accuracy: 0.8707


Epoch 10/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.93it/s, loss=0.0931]


Epoch 10/20 - Loss: 0.1550, Accuracy: 0.8705


Epoch 11/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.87it/s, loss=0.1919]


Epoch 11/20 - Loss: 0.1562, Accuracy: 0.8700


Epoch 12/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.90it/s, loss=0.2255]


Epoch 12/20 - Loss: 0.1540, Accuracy: 0.8708


Epoch 13/20: 100%|██████████| 4929/4929 [00:44<00:00, 109.61it/s, loss=0.1435]


Epoch 13/20 - Loss: 0.1529, Accuracy: 0.8710


Epoch 14/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.23it/s, loss=0.1531]


Epoch 14/20 - Loss: 0.1526, Accuracy: 0.8714


Epoch 15/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.33it/s, loss=0.1441]


Epoch 15/20 - Loss: 0.1523, Accuracy: 0.8715


Epoch 16/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.22it/s, loss=0.1052]


Epoch 16/20 - Loss: 0.1515, Accuracy: 0.8719


Epoch 17/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.93it/s, loss=0.1444]


Epoch 17/20 - Loss: 0.1513, Accuracy: 0.8720


Epoch 18/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.03it/s, loss=0.1142]


Epoch 18/20 - Loss: 0.1511, Accuracy: 0.8721


Epoch 19/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.77it/s, loss=0.0727]


Epoch 19/20 - Loss: 0.1508, Accuracy: 0.8722


Epoch 20/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.60it/s, loss=0.0472]


Epoch 20/20 - Loss: 0.1502, Accuracy: 0.8731
Fold 5 Accuracy: 0.8233


Epoch 1/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.71it/s, loss=0.1975]


Epoch 1/20 - Loss: 0.1508, Accuracy: 0.8720


Epoch 2/20: 100%|██████████| 4929/4929 [00:43<00:00, 112.54it/s, loss=0.1544]


Epoch 2/20 - Loss: 0.1501, Accuracy: 0.8724


Epoch 3/20: 100%|██████████| 4929/4929 [00:43<00:00, 112.24it/s, loss=0.1158]


Epoch 3/20 - Loss: 0.1498, Accuracy: 0.8729


Epoch 4/20: 100%|██████████| 4929/4929 [00:43<00:00, 112.21it/s, loss=0.2251]


Epoch 4/20 - Loss: 0.1493, Accuracy: 0.8725


Epoch 5/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.94it/s, loss=0.1159]


Epoch 5/20 - Loss: 0.1502, Accuracy: 0.8723


Epoch 6/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.99it/s, loss=0.1427]


Epoch 6/20 - Loss: 0.1481, Accuracy: 0.8736


Epoch 7/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.41it/s, loss=0.1897]


Epoch 7/20 - Loss: 0.1479, Accuracy: 0.8738


Epoch 8/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.27it/s, loss=0.0750]


Epoch 8/20 - Loss: 0.1484, Accuracy: 0.8735


Epoch 9/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.36it/s, loss=0.1189]


Epoch 9/20 - Loss: 0.1480, Accuracy: 0.8736


Epoch 10/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.89it/s, loss=0.1296]


Epoch 10/20 - Loss: 0.1476, Accuracy: 0.8741


Epoch 11/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.69it/s, loss=0.1566]


Epoch 11/20 - Loss: 0.1477, Accuracy: 0.8738


Epoch 12/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.96it/s, loss=0.0438]


Epoch 12/20 - Loss: 0.1471, Accuracy: 0.8744


Epoch 13/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.29it/s, loss=0.1799]


Epoch 13/20 - Loss: 0.1466, Accuracy: 0.8745


Epoch 14/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.44it/s, loss=0.1244]


Epoch 14/20 - Loss: 0.1462, Accuracy: 0.8743


Epoch 15/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.09it/s, loss=0.0982]


Epoch 15/20 - Loss: 0.1464, Accuracy: 0.8747


Epoch 16/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.63it/s, loss=0.1581]


Epoch 16/20 - Loss: 0.1455, Accuracy: 0.8748


Epoch 17/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.51it/s, loss=0.0974]


Epoch 17/20 - Loss: 0.1450, Accuracy: 0.8749


Epoch 18/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.69it/s, loss=0.0589]


Epoch 18/20 - Loss: 0.1451, Accuracy: 0.8752


Epoch 19/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.59it/s, loss=0.0827]


Epoch 19/20 - Loss: 0.1440, Accuracy: 0.8758


Epoch 20/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.12it/s, loss=0.1840]


Epoch 20/20 - Loss: 0.1442, Accuracy: 0.8756
Fold 6 Accuracy: 0.8247


Epoch 1/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.01it/s, loss=0.0673]


Epoch 1/20 - Loss: 0.1462, Accuracy: 0.8752


Epoch 2/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.00it/s, loss=0.2059]


Epoch 2/20 - Loss: 0.1454, Accuracy: 0.8750


Epoch 3/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.71it/s, loss=0.2151]


Epoch 3/20 - Loss: 0.1448, Accuracy: 0.8761


Epoch 4/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.36it/s, loss=0.0753]


Epoch 4/20 - Loss: 0.1446, Accuracy: 0.8755


Epoch 5/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.07it/s, loss=0.1896]


Epoch 5/20 - Loss: 0.1439, Accuracy: 0.8761


Epoch 6/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.49it/s, loss=0.0946]


Epoch 6/20 - Loss: 0.1434, Accuracy: 0.8766


Epoch 7/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.67it/s, loss=0.0959]


Epoch 7/20 - Loss: 0.1428, Accuracy: 0.8764


Epoch 8/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.25it/s, loss=0.1029]


Epoch 8/20 - Loss: 0.1434, Accuracy: 0.8760


Epoch 9/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.21it/s, loss=0.1339]


Epoch 9/20 - Loss: 0.1429, Accuracy: 0.8767


Epoch 10/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.06it/s, loss=0.1821]


Epoch 10/20 - Loss: 0.1426, Accuracy: 0.8773


Epoch 11/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.27it/s, loss=0.1051]


Epoch 11/20 - Loss: 0.1416, Accuracy: 0.8772


Epoch 12/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.68it/s, loss=0.1206]


Epoch 12/20 - Loss: 0.1418, Accuracy: 0.8770


Epoch 13/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.09it/s, loss=0.1096]


Epoch 13/20 - Loss: 0.1418, Accuracy: 0.8768


Epoch 14/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.64it/s, loss=0.1289]


Epoch 14/20 - Loss: 0.1412, Accuracy: 0.8778


Epoch 15/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.57it/s, loss=0.0655]


Epoch 15/20 - Loss: 0.1405, Accuracy: 0.8782


Epoch 16/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.36it/s, loss=0.1370]


Epoch 16/20 - Loss: 0.1409, Accuracy: 0.8781


Epoch 17/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.69it/s, loss=0.1983]


Epoch 17/20 - Loss: 0.1404, Accuracy: 0.8790


Epoch 18/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.10it/s, loss=0.1174]


Epoch 18/20 - Loss: 0.1420, Accuracy: 0.8777


Epoch 19/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.71it/s, loss=0.0650]


Epoch 19/20 - Loss: 0.1410, Accuracy: 0.8781


Epoch 20/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.09it/s, loss=0.2193]


Epoch 20/20 - Loss: 0.1438, Accuracy: 0.8765
Fold 7 Accuracy: 0.8253


Epoch 1/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.77it/s, loss=0.2388]


Epoch 1/20 - Loss: 0.1434, Accuracy: 0.8762


Epoch 2/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.10it/s, loss=0.2334]


Epoch 2/20 - Loss: 0.1429, Accuracy: 0.8771


Epoch 3/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.97it/s, loss=0.1680]


Epoch 3/20 - Loss: 0.1421, Accuracy: 0.8771


Epoch 4/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.26it/s, loss=0.2165]


Epoch 4/20 - Loss: 0.1426, Accuracy: 0.8766


Epoch 5/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.14it/s, loss=0.1308]


Epoch 5/20 - Loss: 0.1438, Accuracy: 0.8760


Epoch 6/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.25it/s, loss=0.1342]


Epoch 6/20 - Loss: 0.1423, Accuracy: 0.8770


Epoch 7/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.10it/s, loss=0.1920]


Epoch 7/20 - Loss: 0.1412, Accuracy: 0.8775


Epoch 8/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.56it/s, loss=0.3128]


Epoch 8/20 - Loss: 0.1412, Accuracy: 0.8779


Epoch 9/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.36it/s, loss=0.1859]


Epoch 9/20 - Loss: 0.1406, Accuracy: 0.8785


Epoch 10/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.62it/s, loss=0.1232]


Epoch 10/20 - Loss: 0.1407, Accuracy: 0.8781


Epoch 11/20: 100%|██████████| 4929/4929 [00:44<00:00, 110.35it/s, loss=0.1614]


Epoch 11/20 - Loss: 0.1401, Accuracy: 0.8794


Epoch 12/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.71it/s, loss=0.1875]


Epoch 12/20 - Loss: 0.1394, Accuracy: 0.8796


Epoch 13/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.08it/s, loss=0.1668]


Epoch 13/20 - Loss: 0.1393, Accuracy: 0.8791


Epoch 14/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.68it/s, loss=0.1696]


Epoch 14/20 - Loss: 0.1396, Accuracy: 0.8789


Epoch 15/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.12it/s, loss=0.1274]


Epoch 15/20 - Loss: 0.1396, Accuracy: 0.8783


Epoch 16/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.97it/s, loss=0.0911]


Epoch 16/20 - Loss: 0.1396, Accuracy: 0.8786


Epoch 17/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.99it/s, loss=0.0444]


Epoch 17/20 - Loss: 0.1390, Accuracy: 0.8793


Epoch 18/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.24it/s, loss=0.0942]


Epoch 18/20 - Loss: 0.1384, Accuracy: 0.8792


Epoch 19/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.64it/s, loss=0.1015]


Epoch 19/20 - Loss: 0.1384, Accuracy: 0.8796


Epoch 20/20: 100%|██████████| 4929/4929 [00:46<00:00, 105.47it/s, loss=0.0984]


Epoch 20/20 - Loss: 0.1381, Accuracy: 0.8798
Fold 8 Accuracy: 0.8278


Epoch 1/20: 100%|██████████| 4929/4929 [00:44<00:00, 109.86it/s, loss=0.0977]


Epoch 1/20 - Loss: 0.1399, Accuracy: 0.8788


Epoch 2/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.34it/s, loss=0.2602]


Epoch 2/20 - Loss: 0.1388, Accuracy: 0.8789


Epoch 3/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.60it/s, loss=0.1421]


Epoch 3/20 - Loss: 0.1386, Accuracy: 0.8793


Epoch 4/20: 100%|██████████| 4929/4929 [00:46<00:00, 106.81it/s, loss=0.1524]


Epoch 4/20 - Loss: 0.1391, Accuracy: 0.8793


Epoch 5/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.72it/s, loss=0.0795]


Epoch 5/20 - Loss: 0.1379, Accuracy: 0.8795


Epoch 6/20: 100%|██████████| 4929/4929 [00:46<00:00, 107.01it/s, loss=0.0714]


Epoch 6/20 - Loss: 0.1377, Accuracy: 0.8799


Epoch 7/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.51it/s, loss=0.1699]


Epoch 7/20 - Loss: 0.1375, Accuracy: 0.8799


Epoch 8/20: 100%|██████████| 4929/4929 [00:45<00:00, 109.46it/s, loss=0.2037]


Epoch 8/20 - Loss: 0.1370, Accuracy: 0.8799


Epoch 9/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.01it/s, loss=0.1262]


Epoch 9/20 - Loss: 0.1366, Accuracy: 0.8805


Epoch 10/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.62it/s, loss=0.2368]


Epoch 10/20 - Loss: 0.1362, Accuracy: 0.8807


Epoch 11/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.17it/s, loss=0.1404]


Epoch 11/20 - Loss: 0.1362, Accuracy: 0.8815


Epoch 12/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.54it/s, loss=0.1571]


Epoch 12/20 - Loss: 0.1405, Accuracy: 0.8781


Epoch 13/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.97it/s, loss=0.1524]


Epoch 13/20 - Loss: 0.1375, Accuracy: 0.8795


Epoch 14/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.22it/s, loss=0.2350]


Epoch 14/20 - Loss: 0.1360, Accuracy: 0.8805


Epoch 15/20: 100%|██████████| 4929/4929 [00:45<00:00, 107.15it/s, loss=0.0897]


Epoch 15/20 - Loss: 0.1361, Accuracy: 0.8813


Epoch 16/20: 100%|██████████| 4929/4929 [00:44<00:00, 111.49it/s, loss=0.1577]


Epoch 16/20 - Loss: 0.1354, Accuracy: 0.8813


Epoch 17/20: 100%|██████████| 4929/4929 [00:43<00:00, 112.03it/s, loss=0.1896]


Epoch 17/20 - Loss: 0.1351, Accuracy: 0.8819


Epoch 18/20: 100%|██████████| 4929/4929 [00:45<00:00, 108.07it/s, loss=0.0566]


Epoch 18/20 - Loss: 0.1347, Accuracy: 0.8817


Epoch 19/20: 100%|██████████| 4929/4929 [00:47<00:00, 103.49it/s, loss=0.0802]


Epoch 19/20 - Loss: 0.1344, Accuracy: 0.8823


Epoch 20/20: 100%|██████████| 4929/4929 [01:41<00:00, 48.45it/s, loss=0.1542] 


Epoch 20/20 - Loss: 0.1336, Accuracy: 0.8825
Fold 9 Accuracy: 0.8335


Epoch 1/20: 100%|██████████| 4929/4929 [01:08<00:00, 72.32it/s, loss=0.2264] 


Epoch 1/20 - Loss: 0.1360, Accuracy: 0.8816


Epoch 2/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.44it/s, loss=0.1800]


Epoch 2/20 - Loss: 0.1352, Accuracy: 0.8818


Epoch 3/20: 100%|██████████| 4929/4929 [00:48<00:00, 100.99it/s, loss=0.1834]


Epoch 3/20 - Loss: 0.1348, Accuracy: 0.8815


Epoch 4/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.36it/s, loss=0.2167]


Epoch 4/20 - Loss: 0.1342, Accuracy: 0.8826


Epoch 5/20: 100%|██████████| 4929/4929 [00:47<00:00, 102.83it/s, loss=0.2071]


Epoch 5/20 - Loss: 0.1346, Accuracy: 0.8824


Epoch 6/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.30it/s, loss=0.1153]


Epoch 6/20 - Loss: 0.1326, Accuracy: 0.8838


Epoch 7/20: 100%|██████████| 4929/4929 [00:48<00:00, 100.90it/s, loss=0.0945]


Epoch 7/20 - Loss: 0.1339, Accuracy: 0.8828


Epoch 8/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.35it/s, loss=0.0586]


Epoch 8/20 - Loss: 0.1334, Accuracy: 0.8826


Epoch 9/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.40it/s, loss=0.4861]


Epoch 9/20 - Loss: 0.1331, Accuracy: 0.8833


Epoch 10/20: 100%|██████████| 4929/4929 [00:48<00:00, 100.75it/s, loss=0.0479]


Epoch 10/20 - Loss: 0.1328, Accuracy: 0.8834


Epoch 11/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.70it/s, loss=0.1057]


Epoch 11/20 - Loss: 0.1330, Accuracy: 0.8833


Epoch 12/20: 100%|██████████| 4929/4929 [00:47<00:00, 103.07it/s, loss=0.1019]


Epoch 12/20 - Loss: 0.1325, Accuracy: 0.8834


Epoch 13/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.11it/s, loss=0.1569]


Epoch 13/20 - Loss: 0.1323, Accuracy: 0.8841


Epoch 14/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.82it/s, loss=0.1701]


Epoch 14/20 - Loss: 0.1322, Accuracy: 0.8842


Epoch 15/20: 100%|██████████| 4929/4929 [00:48<00:00, 100.93it/s, loss=0.1229]


Epoch 15/20 - Loss: 0.1310, Accuracy: 0.8844


Epoch 16/20: 100%|██████████| 4929/4929 [00:49<00:00, 100.37it/s, loss=0.1123]


Epoch 16/20 - Loss: 0.1317, Accuracy: 0.8847


Epoch 17/20: 100%|██████████| 4929/4929 [00:48<00:00, 100.81it/s, loss=0.2058]


Epoch 17/20 - Loss: 0.1317, Accuracy: 0.8849


Epoch 18/20: 100%|██████████| 4929/4929 [00:48<00:00, 101.03it/s, loss=0.0834]


Epoch 18/20 - Loss: 0.1310, Accuracy: 0.8853


Epoch 19/20: 100%|██████████| 4929/4929 [00:49<00:00, 98.97it/s, loss=0.1436] 


Epoch 19/20 - Loss: 0.1313, Accuracy: 0.8852


Epoch 20/20: 100%|██████████| 4929/4929 [00:50<00:00, 98.50it/s, loss=0.1645] 


Epoch 20/20 - Loss: 0.1344, Accuracy: 0.8836
Fold 10 Accuracy: 0.8328
Complete model saved to modelU8.pth
Fold Accuracies:
  Fold 1: 0.8125
  Fold 2: 0.8131
  Fold 3: 0.8097
  Fold 4: 0.8172
  Fold 5: 0.8233
  Fold 6: 0.8247
  Fold 7: 0.8253
  Fold 8: 0.8278
  Fold 9: 0.8335
  Fold 10: 0.8328


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  40    0    7  203    4    0   14    0    0    0]
 [   0   26    2  198    3    0    1    3    0    0]
 [   2    7  209 1364   11    6   10   13   11    2]
 [   8   13  135 3942   51   47   77  150   21    9]
 [   0    0    9  271 1566    7  546   13   11    1]
 [   0    0   13   34    4 5828    4    2    2    0]
 [  36    3    6   38  592    4 8592   10   19    0]
 [   0    1   12  253    1    2    6 1122    1    0]
 [   0    2    3    8    6    4    9    4  115    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.47      0.15      0.23       268
      Backdoor       0.50      0.11      0.18       233
           DoS       0.53      0.13      0.21      1635
      Exploits       0.62      0.89      0.73      4453
       Fuzzers       0.70      0.65      0.67      2424
       Generic       0.99      0.99      0.99      5887
        Normal       0.