In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        # self.att_gate = nn.Sequential(
        #     nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
        #     nn.GELU(),
        #     nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
        #     nn.Sigmoid()
        # )

        # 残差连接
        # self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        # res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        # att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        # attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return lstm_out                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
        pt = torch.exp(-ce_loss)  # 预测的概率
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-PCNN-BiLSTM.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4929/4929 [00:43<00:00, 113.99it/s, loss=0.2435]


Epoch 1/15 - Loss: 0.2874, Accuracy: 0.8082


Epoch 2/15: 100%|██████████| 4929/4929 [00:38<00:00, 128.30it/s, loss=0.1388]


Epoch 2/15 - Loss: 0.2187, Accuracy: 0.8400


Epoch 3/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.52it/s, loss=0.1649]


Epoch 3/15 - Loss: 0.2025, Accuracy: 0.8473


Epoch 4/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.18it/s, loss=0.2496]


Epoch 4/15 - Loss: 0.1937, Accuracy: 0.8514


Epoch 5/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.49it/s, loss=0.2454]


Epoch 5/15 - Loss: 0.1885, Accuracy: 0.8541


Epoch 6/15: 100%|██████████| 4929/4929 [00:40<00:00, 120.81it/s, loss=0.1914]


Epoch 6/15 - Loss: 0.1840, Accuracy: 0.8558


Epoch 7/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.09it/s, loss=0.2043]


Epoch 7/15 - Loss: 0.1808, Accuracy: 0.8578


Epoch 8/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.51it/s, loss=0.2948]


Epoch 8/15 - Loss: 0.1786, Accuracy: 0.8589


Epoch 9/15: 100%|██████████| 4929/4929 [00:40<00:00, 120.89it/s, loss=0.1145]


Epoch 9/15 - Loss: 0.1761, Accuracy: 0.8597


Epoch 10/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.04it/s, loss=0.1424]


Epoch 10/15 - Loss: 0.1741, Accuracy: 0.8602


Epoch 11/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.49it/s, loss=0.1396]


Epoch 11/15 - Loss: 0.1721, Accuracy: 0.8613


Epoch 12/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.49it/s, loss=0.0732]


Epoch 12/15 - Loss: 0.1704, Accuracy: 0.8620


Epoch 13/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.81it/s, loss=0.1758]


Epoch 13/15 - Loss: 0.1693, Accuracy: 0.8625


Epoch 14/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.23it/s, loss=0.1078]


Epoch 14/15 - Loss: 0.1681, Accuracy: 0.8626


Epoch 15/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.29it/s, loss=0.2868]


Epoch 15/15 - Loss: 0.1663, Accuracy: 0.8640
Fold 1 Accuracy: 0.8164
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.47it/s, loss=0.3322]


Epoch 1/15 - Loss: 0.1674, Accuracy: 0.8634


Epoch 2/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.88it/s, loss=0.2292]


Epoch 2/15 - Loss: 0.1653, Accuracy: 0.8649


Epoch 3/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.25it/s, loss=0.1888]


Epoch 3/15 - Loss: 0.1644, Accuracy: 0.8654


Epoch 4/15: 100%|██████████| 4929/4929 [00:39<00:00, 124.27it/s, loss=0.1407]


Epoch 4/15 - Loss: 0.1633, Accuracy: 0.8655


Epoch 5/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.85it/s, loss=0.1358]


Epoch 5/15 - Loss: 0.1626, Accuracy: 0.8668


Epoch 6/15: 100%|██████████| 4929/4929 [00:39<00:00, 124.28it/s, loss=0.1485]


Epoch 6/15 - Loss: 0.1608, Accuracy: 0.8669


Epoch 7/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.44it/s, loss=0.0948]


Epoch 7/15 - Loss: 0.1606, Accuracy: 0.8669


Epoch 8/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.25it/s, loss=0.1047]


Epoch 8/15 - Loss: 0.1593, Accuracy: 0.8677


Epoch 9/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.37it/s, loss=0.1704]


Epoch 9/15 - Loss: 0.1590, Accuracy: 0.8678


Epoch 10/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.81it/s, loss=0.0871]


Epoch 10/15 - Loss: 0.1579, Accuracy: 0.8680


Epoch 11/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.11it/s, loss=0.1787]


Epoch 11/15 - Loss: 0.1576, Accuracy: 0.8685


Epoch 12/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.13it/s, loss=0.0722]


Epoch 12/15 - Loss: 0.1569, Accuracy: 0.8684


Epoch 13/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.38it/s, loss=0.1222]


Epoch 13/15 - Loss: 0.1565, Accuracy: 0.8686


Epoch 14/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.74it/s, loss=0.2106]


Epoch 14/15 - Loss: 0.1558, Accuracy: 0.8693


Epoch 15/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.94it/s, loss=0.1134]


Epoch 15/15 - Loss: 0.1554, Accuracy: 0.8700
Fold 2 Accuracy: 0.8218
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.66it/s, loss=0.2427]


Epoch 1/15 - Loss: 0.1562, Accuracy: 0.8693


Epoch 2/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.38it/s, loss=0.1462]


Epoch 2/15 - Loss: 0.1556, Accuracy: 0.8695


Epoch 3/15: 100%|██████████| 4929/4929 [00:40<00:00, 120.95it/s, loss=0.1975]


Epoch 3/15 - Loss: 0.1549, Accuracy: 0.8696


Epoch 4/15: 100%|██████████| 4929/4929 [00:51<00:00, 95.47it/s, loss=0.1505] 


Epoch 4/15 - Loss: 0.1537, Accuracy: 0.8697


Epoch 5/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.51it/s, loss=0.1825]


Epoch 5/15 - Loss: 0.1533, Accuracy: 0.8701


Epoch 6/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.48it/s, loss=0.1719]


Epoch 6/15 - Loss: 0.1523, Accuracy: 0.8703


Epoch 7/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.81it/s, loss=0.2410]


Epoch 7/15 - Loss: 0.1523, Accuracy: 0.8708


Epoch 8/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.36it/s, loss=0.1210]


Epoch 8/15 - Loss: 0.1517, Accuracy: 0.8711


Epoch 9/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.11it/s, loss=0.1159]


Epoch 9/15 - Loss: 0.1517, Accuracy: 0.8713


Epoch 10/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.15it/s, loss=0.1885]


Epoch 10/15 - Loss: 0.1510, Accuracy: 0.8713


Epoch 11/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.43it/s, loss=0.2037]


Epoch 11/15 - Loss: 0.1503, Accuracy: 0.8721


Epoch 12/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.09it/s, loss=0.2038]


Epoch 12/15 - Loss: 0.1502, Accuracy: 0.8713


Epoch 13/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.83it/s, loss=0.1115]


Epoch 13/15 - Loss: 0.1490, Accuracy: 0.8725


Epoch 14/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.45it/s, loss=0.1141]


Epoch 14/15 - Loss: 0.1491, Accuracy: 0.8727


Epoch 15/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.75it/s, loss=0.1092]


Epoch 15/15 - Loss: 0.1486, Accuracy: 0.8721
Fold 3 Accuracy: 0.8266
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.21it/s, loss=0.1015]


Epoch 1/15 - Loss: 0.1496, Accuracy: 0.8725


Epoch 2/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.97it/s, loss=0.1592]


Epoch 2/15 - Loss: 0.1490, Accuracy: 0.8726


Epoch 3/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.20it/s, loss=0.2158]


Epoch 3/15 - Loss: 0.1483, Accuracy: 0.8729


Epoch 4/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.92it/s, loss=0.2888]


Epoch 4/15 - Loss: 0.1480, Accuracy: 0.8733


Epoch 5/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.39it/s, loss=0.0662]


Epoch 5/15 - Loss: 0.1474, Accuracy: 0.8736


Epoch 6/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.97it/s, loss=0.1100]


Epoch 6/15 - Loss: 0.1471, Accuracy: 0.8737


Epoch 7/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.46it/s, loss=0.2179]


Epoch 7/15 - Loss: 0.1463, Accuracy: 0.8745


Epoch 8/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.31it/s, loss=0.1471]


Epoch 8/15 - Loss: 0.1465, Accuracy: 0.8739


Epoch 9/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.01it/s, loss=0.1515]


Epoch 9/15 - Loss: 0.1463, Accuracy: 0.8747


Epoch 10/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.93it/s, loss=0.0849]


Epoch 10/15 - Loss: 0.1456, Accuracy: 0.8745


Epoch 11/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.34it/s, loss=0.1107]


Epoch 11/15 - Loss: 0.1452, Accuracy: 0.8752


Epoch 12/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.04it/s, loss=0.2627]


Epoch 12/15 - Loss: 0.1447, Accuracy: 0.8748


Epoch 13/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.06it/s, loss=0.1586]


Epoch 13/15 - Loss: 0.1450, Accuracy: 0.8752


Epoch 14/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.93it/s, loss=0.1504]


Epoch 14/15 - Loss: 0.1444, Accuracy: 0.8755


Epoch 15/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.51it/s, loss=0.1304]


Epoch 15/15 - Loss: 0.1438, Accuracy: 0.8757
Fold 4 Accuracy: 0.8254
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.09it/s, loss=0.1129]


Epoch 1/15 - Loss: 0.1464, Accuracy: 0.8741


Epoch 2/15: 100%|██████████| 4929/4929 [00:53<00:00, 92.30it/s, loss=0.1410] 


Epoch 2/15 - Loss: 0.1454, Accuracy: 0.8743


Epoch 3/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.28it/s, loss=0.1633]


Epoch 3/15 - Loss: 0.1448, Accuracy: 0.8749


Epoch 4/15: 100%|██████████| 4929/4929 [00:50<00:00, 97.51it/s, loss=0.2247] 


Epoch 4/15 - Loss: 0.1443, Accuracy: 0.8751


Epoch 5/15: 100%|██████████| 4929/4929 [00:49<00:00, 99.92it/s, loss=0.1674] 


Epoch 5/15 - Loss: 0.1442, Accuracy: 0.8752


Epoch 6/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.97it/s, loss=0.1673]


Epoch 6/15 - Loss: 0.1443, Accuracy: 0.8757


Epoch 7/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.25it/s, loss=0.1717]


Epoch 7/15 - Loss: 0.1435, Accuracy: 0.8751


Epoch 8/15: 100%|██████████| 4929/4929 [00:48<00:00, 101.66it/s, loss=0.1132]


Epoch 8/15 - Loss: 0.1434, Accuracy: 0.8762


Epoch 9/15: 100%|██████████| 4929/4929 [00:49<00:00, 98.81it/s, loss=0.1546] 


Epoch 9/15 - Loss: 0.1431, Accuracy: 0.8765


Epoch 10/15: 100%|██████████| 4929/4929 [00:49<00:00, 99.38it/s, loss=0.2279] 


Epoch 10/15 - Loss: 0.1432, Accuracy: 0.8763


Epoch 11/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.49it/s, loss=0.0662]


Epoch 11/15 - Loss: 0.1424, Accuracy: 0.8764


Epoch 12/15: 100%|██████████| 4929/4929 [00:48<00:00, 101.68it/s, loss=0.0907]


Epoch 12/15 - Loss: 0.1424, Accuracy: 0.8765


Epoch 13/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.83it/s, loss=0.1232]


Epoch 13/15 - Loss: 0.1422, Accuracy: 0.8761


Epoch 14/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.22it/s, loss=0.1372]


Epoch 14/15 - Loss: 0.1417, Accuracy: 0.8772


Epoch 15/15: 100%|██████████| 4929/4929 [00:52<00:00, 93.81it/s, loss=0.2358] 


Epoch 15/15 - Loss: 0.1412, Accuracy: 0.8766
Fold 5 Accuracy: 0.8366
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:46<00:00, 107.11it/s, loss=0.2153]


Epoch 1/15 - Loss: 0.1426, Accuracy: 0.8770


Epoch 2/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.43it/s, loss=0.2244]


Epoch 2/15 - Loss: 0.1425, Accuracy: 0.8771


Epoch 3/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.56it/s, loss=0.2037]


Epoch 3/15 - Loss: 0.1421, Accuracy: 0.8769


Epoch 4/15: 100%|██████████| 4929/4929 [00:51<00:00, 95.06it/s, loss=0.2200] 


Epoch 4/15 - Loss: 0.1413, Accuracy: 0.8767


Epoch 5/15: 100%|██████████| 4929/4929 [00:48<00:00, 101.94it/s, loss=0.0878]


Epoch 5/15 - Loss: 0.1410, Accuracy: 0.8771


Epoch 6/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.34it/s, loss=0.2988]


Epoch 6/15 - Loss: 0.1406, Accuracy: 0.8775


Epoch 7/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.44it/s, loss=0.1768]


Epoch 7/15 - Loss: 0.1404, Accuracy: 0.8784


Epoch 8/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.43it/s, loss=0.2348]


Epoch 8/15 - Loss: 0.1399, Accuracy: 0.8783


Epoch 9/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.64it/s, loss=0.1802]


Epoch 9/15 - Loss: 0.1399, Accuracy: 0.8779


Epoch 10/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.40it/s, loss=0.0958]


Epoch 10/15 - Loss: 0.1396, Accuracy: 0.8782


Epoch 11/15: 100%|██████████| 4929/4929 [00:46<00:00, 104.90it/s, loss=0.2295]


Epoch 11/15 - Loss: 0.1394, Accuracy: 0.8787


Epoch 12/15: 100%|██████████| 4929/4929 [00:50<00:00, 98.47it/s, loss=0.0863] 


Epoch 12/15 - Loss: 0.1390, Accuracy: 0.8787


Epoch 13/15: 100%|██████████| 4929/4929 [00:45<00:00, 107.67it/s, loss=0.1007]


Epoch 13/15 - Loss: 0.1385, Accuracy: 0.8782


Epoch 14/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.76it/s, loss=0.1934]


Epoch 14/15 - Loss: 0.1385, Accuracy: 0.8792


Epoch 15/15: 100%|██████████| 4929/4929 [00:51<00:00, 96.26it/s, loss=0.1435] 


Epoch 15/15 - Loss: 0.1388, Accuracy: 0.8793
Fold 6 Accuracy: 0.8372
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:49<00:00, 100.12it/s, loss=0.2389]


Epoch 1/15 - Loss: 0.1398, Accuracy: 0.8782


Epoch 2/15: 100%|██████████| 4929/4929 [00:52<00:00, 93.85it/s, loss=0.1966] 


Epoch 2/15 - Loss: 0.1388, Accuracy: 0.8791


Epoch 3/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.23it/s, loss=0.0888]


Epoch 3/15 - Loss: 0.1382, Accuracy: 0.8789


Epoch 4/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.04it/s, loss=0.1783]


Epoch 4/15 - Loss: 0.1378, Accuracy: 0.8794


Epoch 5/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.69it/s, loss=0.0707]


Epoch 5/15 - Loss: 0.1376, Accuracy: 0.8794


Epoch 6/15: 100%|██████████| 4929/4929 [00:46<00:00, 107.13it/s, loss=0.0827]


Epoch 6/15 - Loss: 0.1372, Accuracy: 0.8791


Epoch 7/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.56it/s, loss=0.1681]


Epoch 7/15 - Loss: 0.1379, Accuracy: 0.8792


Epoch 8/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.38it/s, loss=0.0850]


Epoch 8/15 - Loss: 0.1369, Accuracy: 0.8803


Epoch 9/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.57it/s, loss=0.1782]


Epoch 9/15 - Loss: 0.1368, Accuracy: 0.8796


Epoch 10/15: 100%|██████████| 4929/4929 [00:50<00:00, 98.18it/s, loss=0.1757] 


Epoch 10/15 - Loss: 0.1360, Accuracy: 0.8805


Epoch 11/15: 100%|██████████| 4929/4929 [00:48<00:00, 101.38it/s, loss=0.1361]


Epoch 11/15 - Loss: 0.1366, Accuracy: 0.8804


Epoch 12/15: 100%|██████████| 4929/4929 [00:49<00:00, 99.02it/s, loss=0.0922] 


Epoch 12/15 - Loss: 0.1364, Accuracy: 0.8806


Epoch 13/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.29it/s, loss=0.1388]


Epoch 13/15 - Loss: 0.1357, Accuracy: 0.8807


Epoch 14/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.65it/s, loss=0.0833]


Epoch 14/15 - Loss: 0.1361, Accuracy: 0.8798


Epoch 15/15: 100%|██████████| 4929/4929 [00:47<00:00, 102.87it/s, loss=0.1473]


Epoch 15/15 - Loss: 0.1359, Accuracy: 0.8808
Fold 7 Accuracy: 0.8347
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.26it/s, loss=0.0846]


Epoch 1/15 - Loss: 0.1380, Accuracy: 0.8794


Epoch 2/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.66it/s, loss=0.0881]


Epoch 2/15 - Loss: 0.1374, Accuracy: 0.8797


Epoch 3/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.23it/s, loss=0.1679]


Epoch 3/15 - Loss: 0.1368, Accuracy: 0.8800


Epoch 4/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.24it/s, loss=0.1101]


Epoch 4/15 - Loss: 0.1366, Accuracy: 0.8802


Epoch 5/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.10it/s, loss=0.0745]


Epoch 5/15 - Loss: 0.1362, Accuracy: 0.8808


Epoch 6/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.09it/s, loss=0.1112]


Epoch 6/15 - Loss: 0.1364, Accuracy: 0.8805


Epoch 7/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.85it/s, loss=0.0687]


Epoch 7/15 - Loss: 0.1359, Accuracy: 0.8807


Epoch 8/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.59it/s, loss=0.1610]


Epoch 8/15 - Loss: 0.1354, Accuracy: 0.8808


Epoch 9/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.53it/s, loss=0.1904]


Epoch 9/15 - Loss: 0.1354, Accuracy: 0.8814


Epoch 10/15: 100%|██████████| 4929/4929 [00:49<00:00, 98.74it/s, loss=0.1175] 


Epoch 10/15 - Loss: 0.1346, Accuracy: 0.8818


Epoch 11/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.89it/s, loss=0.0730]


Epoch 11/15 - Loss: 0.1350, Accuracy: 0.8816


Epoch 12/15: 100%|██████████| 4929/4929 [00:48<00:00, 100.90it/s, loss=0.1189]


Epoch 12/15 - Loss: 0.1346, Accuracy: 0.8817


Epoch 13/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.64it/s, loss=0.1447]


Epoch 13/15 - Loss: 0.1349, Accuracy: 0.8821


Epoch 14/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.66it/s, loss=0.1253]


Epoch 14/15 - Loss: 0.1344, Accuracy: 0.8814


Epoch 15/15: 100%|██████████| 4929/4929 [00:47<00:00, 103.92it/s, loss=0.0877]


Epoch 15/15 - Loss: 0.1345, Accuracy: 0.8821
Fold 8 Accuracy: 0.8432
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:49<00:00, 99.92it/s, loss=0.1987] 


Epoch 1/15 - Loss: 0.1357, Accuracy: 0.8811


Epoch 2/15: 100%|██████████| 4929/4929 [00:48<00:00, 101.68it/s, loss=0.1202]


Epoch 2/15 - Loss: 0.1352, Accuracy: 0.8810


Epoch 3/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.77it/s, loss=0.1334]


Epoch 3/15 - Loss: 0.1349, Accuracy: 0.8821


Epoch 4/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.35it/s, loss=0.1338]


Epoch 4/15 - Loss: 0.1346, Accuracy: 0.8820


Epoch 5/15: 100%|██████████| 4929/4929 [00:48<00:00, 102.53it/s, loss=0.1296]


Epoch 5/15 - Loss: 0.1341, Accuracy: 0.8825


Epoch 6/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.02it/s, loss=0.2518]


Epoch 6/15 - Loss: 0.1339, Accuracy: 0.8818


Epoch 7/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.98it/s, loss=0.0966]


Epoch 7/15 - Loss: 0.1339, Accuracy: 0.8819


Epoch 8/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.23it/s, loss=0.1163]


Epoch 8/15 - Loss: 0.1338, Accuracy: 0.8826


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.33it/s, loss=0.1770] 


Epoch 9/15 - Loss: 0.1334, Accuracy: 0.8826


Epoch 10/15: 100%|██████████| 4929/4929 [00:47<00:00, 104.53it/s, loss=0.1277]


Epoch 10/15 - Loss: 0.1332, Accuracy: 0.8826


Epoch 11/15: 100%|██████████| 4929/4929 [00:46<00:00, 104.99it/s, loss=0.1012]


Epoch 11/15 - Loss: 0.1331, Accuracy: 0.8830


Epoch 12/15: 100%|██████████| 4929/4929 [00:46<00:00, 106.95it/s, loss=0.2289]


Epoch 12/15 - Loss: 0.1328, Accuracy: 0.8832


Epoch 13/15: 100%|██████████| 4929/4929 [00:46<00:00, 104.94it/s, loss=0.1324]


Epoch 13/15 - Loss: 0.1326, Accuracy: 0.8830


Epoch 14/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.19it/s, loss=0.0832]


Epoch 14/15 - Loss: 0.1328, Accuracy: 0.8827


Epoch 15/15: 100%|██████████| 4929/4929 [00:49<00:00, 99.82it/s, loss=0.0775] 


Epoch 15/15 - Loss: 0.1325, Accuracy: 0.8830
Fold 9 Accuracy: 0.8423
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:46<00:00, 105.93it/s, loss=0.1509]


Epoch 1/15 - Loss: 0.1344, Accuracy: 0.8818


Epoch 2/15: 100%|██████████| 4929/4929 [00:41<00:00, 119.02it/s, loss=0.1451]


Epoch 2/15 - Loss: 0.1336, Accuracy: 0.8825


Epoch 3/15: 100%|██████████| 4929/4929 [00:40<00:00, 123.07it/s, loss=0.1022]


Epoch 3/15 - Loss: 0.1328, Accuracy: 0.8832


Epoch 4/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.84it/s, loss=0.1863]


Epoch 4/15 - Loss: 0.1334, Accuracy: 0.8827


Epoch 5/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.29it/s, loss=0.1245]


Epoch 5/15 - Loss: 0.1331, Accuracy: 0.8829


Epoch 6/15: 100%|██████████| 4929/4929 [00:39<00:00, 124.06it/s, loss=0.1345]


Epoch 6/15 - Loss: 0.1325, Accuracy: 0.8830


Epoch 7/15: 100%|██████████| 4929/4929 [00:39<00:00, 125.17it/s, loss=0.1965]


Epoch 7/15 - Loss: 0.1329, Accuracy: 0.8834


Epoch 8/15: 100%|██████████| 4929/4929 [00:39<00:00, 125.90it/s, loss=0.1138]


Epoch 8/15 - Loss: 0.1327, Accuracy: 0.8835


Epoch 9/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.52it/s, loss=0.0687]


Epoch 9/15 - Loss: 0.1321, Accuracy: 0.8837


Epoch 10/15: 100%|██████████| 4929/4929 [00:39<00:00, 123.97it/s, loss=0.2669]


Epoch 10/15 - Loss: 0.1320, Accuracy: 0.8842


Epoch 11/15: 100%|██████████| 4929/4929 [00:39<00:00, 124.61it/s, loss=0.0401]


Epoch 11/15 - Loss: 0.1320, Accuracy: 0.8838


Epoch 12/15: 100%|██████████| 4929/4929 [00:39<00:00, 124.64it/s, loss=0.1023]


Epoch 12/15 - Loss: 0.1317, Accuracy: 0.8842


Epoch 13/15: 100%|██████████| 4929/4929 [00:40<00:00, 122.87it/s, loss=0.0819]


Epoch 13/15 - Loss: 0.1318, Accuracy: 0.8838


Epoch 14/15: 100%|██████████| 4929/4929 [00:40<00:00, 121.91it/s, loss=0.0689]


Epoch 14/15 - Loss: 0.1311, Accuracy: 0.8842


Epoch 15/15: 100%|██████████| 4929/4929 [00:39<00:00, 124.42it/s, loss=0.1152]


Epoch 15/15 - Loss: 0.1310, Accuracy: 0.8844
Fold 10 Accuracy: 0.8450
Complete model saved to UNSW-PCNN-BiLSTM.pth
Fold Accuracies:
  Fold 1: 0.8164
  Fold 2: 0.8218
  Fold 3: 0.8266
  Fold 4: 0.8254
  Fold 5: 0.8366
  Fold 6: 0.8372
  Fold 7: 0.8347
  Fold 8: 0.8432
  Fold 9: 0.8423
  Fold 10: 0.8450


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  31    0   49  125   42    0   21    0    0    0]
 [   0   33   55   98   46    0    0    0    0    0]
 [   0    1  565  979   47    9   11   13    9    1]
 [   2    3  479 3645  119   19   54  107   12   12]
 [   0    0   59  133 1379    2  836    8    6    2]
 [   0    0   17   31    3 5831    2    2    1    0]
 [  13    0    4   34  204    0 9031    9    5    0]
 [   0    0   82  179    1    1    4 1130    2    0]
 [   0    0    2    8    8    0   13   11  109    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.67      0.12      0.20       268
      Backdoor       0.89      0.14      0.25       232
           DoS       0.43      0.35      0.38      1635
      Exploits       0.70      0.82      0.75      4452
       Fuzzers       0.75      0.57      0.65      2425
       Generic       0.99      0.99      0.99      5887
        Normal       0.