In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   #15 0.0005 85.43  15 0.0003 85.05  20 0.0005 85.20     25 0.0005 85.11     30 0.0008 84.69  10 0.0005 84.19 
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
        pt = torch.exp(-ce_loss)  # 预测的概率
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    # X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-FOCALloss.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 231905 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/3624 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 3624/3624 [00:44<00:00, 80.70it/s, loss=0.3076]


Epoch 1/15 - Loss: 0.3261, Accuracy: 0.7724


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.20it/s, loss=0.2570]


Epoch 2/15 - Loss: 0.2730, Accuracy: 0.7954


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.80it/s, loss=0.3223]


Epoch 3/15 - Loss: 0.2588, Accuracy: 0.8021


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.43it/s, loss=0.1809]


Epoch 4/15 - Loss: 0.2507, Accuracy: 0.8043


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.17it/s, loss=0.1702]


Epoch 5/15 - Loss: 0.2461, Accuracy: 0.8068


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.19it/s, loss=0.1186]


Epoch 6/15 - Loss: 0.2411, Accuracy: 0.8091


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.18it/s, loss=0.2138]


Epoch 7/15 - Loss: 0.2388, Accuracy: 0.8108


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.3903]


Epoch 8/15 - Loss: 0.2363, Accuracy: 0.8112


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.02it/s, loss=0.2464]


Epoch 9/15 - Loss: 0.2338, Accuracy: 0.8126


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.19it/s, loss=0.4213]


Epoch 10/15 - Loss: 0.2320, Accuracy: 0.8136


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.34it/s, loss=0.1990]


Epoch 11/15 - Loss: 0.2299, Accuracy: 0.8144


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.43it/s, loss=0.1350]


Epoch 12/15 - Loss: 0.2281, Accuracy: 0.8150


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.39it/s, loss=0.1943]


Epoch 13/15 - Loss: 0.2272, Accuracy: 0.8152


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.32it/s, loss=0.1251]


Epoch 14/15 - Loss: 0.2252, Accuracy: 0.8158


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.05it/s, loss=0.1455]


Epoch 15/15 - Loss: 0.2235, Accuracy: 0.8181
Fold 1 Accuracy: 0.8185
Fold 2: 231905 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.56it/s, loss=0.2275]


Epoch 1/15 - Loss: 0.2233, Accuracy: 0.8180


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.00it/s, loss=0.1118]


Epoch 2/15 - Loss: 0.2227, Accuracy: 0.8180


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.05it/s, loss=0.1899]


Epoch 3/15 - Loss: 0.2207, Accuracy: 0.8192


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.08it/s, loss=0.1940]


Epoch 4/15 - Loss: 0.2192, Accuracy: 0.8189


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.27it/s, loss=0.1804]


Epoch 5/15 - Loss: 0.2180, Accuracy: 0.8203


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.06it/s, loss=0.1811]


Epoch 6/15 - Loss: 0.2171, Accuracy: 0.8205


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.20it/s, loss=0.2187]


Epoch 7/15 - Loss: 0.2169, Accuracy: 0.8206


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.61it/s, loss=0.2546]


Epoch 8/15 - Loss: 0.2155, Accuracy: 0.8219


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.27it/s, loss=0.1206]


Epoch 9/15 - Loss: 0.2144, Accuracy: 0.8221


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.82it/s, loss=0.1707]


Epoch 10/15 - Loss: 0.2143, Accuracy: 0.8219


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.09it/s, loss=0.2150]


Epoch 11/15 - Loss: 0.2126, Accuracy: 0.8230


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.16it/s, loss=0.2547]


Epoch 12/15 - Loss: 0.2118, Accuracy: 0.8232


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.62it/s, loss=0.1689]


Epoch 13/15 - Loss: 0.2116, Accuracy: 0.8239


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.09it/s, loss=0.2144]


Epoch 14/15 - Loss: 0.2107, Accuracy: 0.8241


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.04it/s, loss=0.1642]


Epoch 15/15 - Loss: 0.2100, Accuracy: 0.8245
Fold 2 Accuracy: 0.8220
Fold 3: 231905 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.56it/s, loss=0.2832]


Epoch 1/15 - Loss: 0.2103, Accuracy: 0.8245


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.42it/s, loss=0.1446]


Epoch 2/15 - Loss: 0.2093, Accuracy: 0.8247


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.77it/s, loss=0.1082]


Epoch 3/15 - Loss: 0.2081, Accuracy: 0.8252


Epoch 4/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.68it/s, loss=0.0906]


Epoch 4/15 - Loss: 0.2082, Accuracy: 0.8247


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.07it/s, loss=0.0993]


Epoch 5/15 - Loss: 0.2066, Accuracy: 0.8254


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.66it/s, loss=0.1451]


Epoch 6/15 - Loss: 0.2060, Accuracy: 0.8261


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.01it/s, loss=0.3222]


Epoch 7/15 - Loss: 0.2056, Accuracy: 0.8269


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.64it/s, loss=0.1408]


Epoch 8/15 - Loss: 0.2052, Accuracy: 0.8274


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.97it/s, loss=0.0920]


Epoch 9/15 - Loss: 0.2044, Accuracy: 0.8268


Epoch 10/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.94it/s, loss=0.1051]


Epoch 10/15 - Loss: 0.2036, Accuracy: 0.8273


Epoch 11/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.38it/s, loss=0.2704]


Epoch 11/15 - Loss: 0.2025, Accuracy: 0.8278


Epoch 12/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.86it/s, loss=0.1822]


Epoch 12/15 - Loss: 0.2022, Accuracy: 0.8277


Epoch 13/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.51it/s, loss=0.2038]


Epoch 13/15 - Loss: 0.2020, Accuracy: 0.8284


Epoch 14/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.92it/s, loss=0.1389]


Epoch 14/15 - Loss: 0.2014, Accuracy: 0.8291


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.26it/s, loss=0.1045]


Epoch 15/15 - Loss: 0.2012, Accuracy: 0.8282
Fold 3 Accuracy: 0.8301
Fold 4: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.13it/s, loss=0.0743]


Epoch 1/15 - Loss: 0.2019, Accuracy: 0.8289


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.20it/s, loss=0.2598]


Epoch 2/15 - Loss: 0.2016, Accuracy: 0.8288


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.59it/s, loss=0.3086]


Epoch 3/15 - Loss: 0.2007, Accuracy: 0.8294


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.76it/s, loss=0.2655]


Epoch 4/15 - Loss: 0.1997, Accuracy: 0.8305


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.23it/s, loss=0.1216]


Epoch 5/15 - Loss: 0.1993, Accuracy: 0.8305


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.74it/s, loss=0.3595]


Epoch 6/15 - Loss: 0.1990, Accuracy: 0.8305


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.23it/s, loss=0.2269]


Epoch 7/15 - Loss: 0.1983, Accuracy: 0.8311


Epoch 8/15: 100%|██████████| 3624/3624 [00:41<00:00, 87.00it/s, loss=0.2289]


Epoch 8/15 - Loss: 0.1984, Accuracy: 0.8301


Epoch 9/15: 100%|██████████| 3624/3624 [00:41<00:00, 86.39it/s, loss=0.1867]


Epoch 9/15 - Loss: 0.1971, Accuracy: 0.8311


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.79it/s, loss=0.4528]


Epoch 10/15 - Loss: 0.1970, Accuracy: 0.8317


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.48it/s, loss=0.3453]


Epoch 11/15 - Loss: 0.1963, Accuracy: 0.8315


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.28it/s, loss=0.2193]


Epoch 12/15 - Loss: 0.1959, Accuracy: 0.8325


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.50it/s, loss=0.1783]


Epoch 13/15 - Loss: 0.1957, Accuracy: 0.8319


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.58it/s, loss=0.2175]


Epoch 14/15 - Loss: 0.1956, Accuracy: 0.8325


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.78it/s, loss=0.2752]


Epoch 15/15 - Loss: 0.1946, Accuracy: 0.8332
Fold 4 Accuracy: 0.8294
Fold 5: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.62it/s, loss=0.4095]


Epoch 1/15 - Loss: 0.1974, Accuracy: 0.8318


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.50it/s, loss=0.1352]


Epoch 2/15 - Loss: 0.1966, Accuracy: 0.8323


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.65it/s, loss=0.2731]


Epoch 3/15 - Loss: 0.1962, Accuracy: 0.8321


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.20it/s, loss=0.3359]


Epoch 4/15 - Loss: 0.1950, Accuracy: 0.8328


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.42it/s, loss=0.0911]


Epoch 5/15 - Loss: 0.1949, Accuracy: 0.8325


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.31it/s, loss=0.1093]


Epoch 6/15 - Loss: 0.1944, Accuracy: 0.8337


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.99it/s, loss=0.2405]


Epoch 7/15 - Loss: 0.1935, Accuracy: 0.8342


Epoch 8/15: 100%|██████████| 3624/3624 [00:45<00:00, 79.39it/s, loss=0.3491]


Epoch 8/15 - Loss: 0.1932, Accuracy: 0.8337


Epoch 9/15: 100%|██████████| 3624/3624 [00:44<00:00, 81.25it/s, loss=0.1378]


Epoch 9/15 - Loss: 0.1935, Accuracy: 0.8340


Epoch 10/15: 100%|██████████| 3624/3624 [00:44<00:00, 81.01it/s, loss=0.1925]


Epoch 10/15 - Loss: 0.1926, Accuracy: 0.8340


Epoch 11/15: 100%|██████████| 3624/3624 [00:44<00:00, 80.96it/s, loss=0.1212]


Epoch 11/15 - Loss: 0.1925, Accuracy: 0.8348


Epoch 12/15: 100%|██████████| 3624/3624 [00:44<00:00, 80.76it/s, loss=0.2921]


Epoch 12/15 - Loss: 0.1920, Accuracy: 0.8347


Epoch 13/15: 100%|██████████| 3624/3624 [00:45<00:00, 79.65it/s, loss=0.1802]


Epoch 13/15 - Loss: 0.1914, Accuracy: 0.8356


Epoch 14/15: 100%|██████████| 3624/3624 [00:56<00:00, 64.65it/s, loss=0.2634]


Epoch 14/15 - Loss: 0.1911, Accuracy: 0.8350


Epoch 15/15: 100%|██████████| 3624/3624 [01:10<00:00, 51.48it/s, loss=0.2296]


Epoch 15/15 - Loss: 0.1910, Accuracy: 0.8357
Fold 5 Accuracy: 0.8336
Fold 6: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [01:10<00:00, 51.52it/s, loss=0.2148]


Epoch 1/15 - Loss: 0.1929, Accuracy: 0.8345


Epoch 2/15: 100%|██████████| 3624/3624 [01:01<00:00, 58.87it/s, loss=0.0966]


Epoch 2/15 - Loss: 0.1918, Accuracy: 0.8355


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.83it/s, loss=0.0557]


Epoch 3/15 - Loss: 0.1911, Accuracy: 0.8353


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.50it/s, loss=0.1669]


Epoch 4/15 - Loss: 0.1909, Accuracy: 0.8348


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.23it/s, loss=0.2968]


Epoch 5/15 - Loss: 0.1901, Accuracy: 0.8363


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.86it/s, loss=0.2011]


Epoch 6/15 - Loss: 0.1902, Accuracy: 0.8364


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.75it/s, loss=0.1402]


Epoch 7/15 - Loss: 0.1891, Accuracy: 0.8369


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.1413]


Epoch 8/15 - Loss: 0.1893, Accuracy: 0.8375


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.97it/s, loss=0.1725]


Epoch 9/15 - Loss: 0.1886, Accuracy: 0.8373


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.79it/s, loss=0.0860]


Epoch 10/15 - Loss: 0.1881, Accuracy: 0.8381


Epoch 11/15: 100%|██████████| 3624/3624 [00:44<00:00, 81.36it/s, loss=0.1055]


Epoch 11/15 - Loss: 0.1880, Accuracy: 0.8383


Epoch 12/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.49it/s, loss=0.1100]


Epoch 12/15 - Loss: 0.1877, Accuracy: 0.8375


Epoch 13/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.49it/s, loss=0.3067]


Epoch 13/15 - Loss: 0.1876, Accuracy: 0.8378


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.51it/s, loss=0.1914]


Epoch 14/15 - Loss: 0.1875, Accuracy: 0.8379


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.1592]


Epoch 15/15 - Loss: 0.1870, Accuracy: 0.8387
Fold 6 Accuracy: 0.8368
Fold 7: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.60it/s, loss=0.1658]


Epoch 1/15 - Loss: 0.1879, Accuracy: 0.8378


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.54it/s, loss=0.2265]


Epoch 2/15 - Loss: 0.1872, Accuracy: 0.8387


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.58it/s, loss=0.1327]


Epoch 3/15 - Loss: 0.1870, Accuracy: 0.8381


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.89it/s, loss=0.1220]


Epoch 4/15 - Loss: 0.1864, Accuracy: 0.8386


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 86.04it/s, loss=0.2056]


Epoch 5/15 - Loss: 0.1859, Accuracy: 0.8390


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.72it/s, loss=0.0750]


Epoch 6/15 - Loss: 0.1857, Accuracy: 0.8391


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.49it/s, loss=0.1382]


Epoch 7/15 - Loss: 0.1855, Accuracy: 0.8398


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.36it/s, loss=0.1544]


Epoch 8/15 - Loss: 0.1842, Accuracy: 0.8398


Epoch 9/15: 100%|██████████| 3624/3624 [01:08<00:00, 53.02it/s, loss=0.1181]


Epoch 9/15 - Loss: 0.1843, Accuracy: 0.8402


Epoch 10/15: 100%|██████████| 3624/3624 [01:11<00:00, 50.94it/s, loss=0.2096]


Epoch 10/15 - Loss: 0.1845, Accuracy: 0.8398


Epoch 11/15: 100%|██████████| 3624/3624 [01:09<00:00, 52.49it/s, loss=0.2055]


Epoch 11/15 - Loss: 0.1845, Accuracy: 0.8401


Epoch 12/15: 100%|██████████| 3624/3624 [01:10<00:00, 51.59it/s, loss=0.1494]


Epoch 12/15 - Loss: 0.1840, Accuracy: 0.8400


Epoch 13/15: 100%|██████████| 3624/3624 [01:09<00:00, 52.24it/s, loss=0.1864]


Epoch 13/15 - Loss: 0.1836, Accuracy: 0.8411


Epoch 14/15: 100%|██████████| 3624/3624 [01:13<00:00, 49.36it/s, loss=0.1277]


Epoch 14/15 - Loss: 0.1834, Accuracy: 0.8411


Epoch 15/15: 100%|██████████| 3624/3624 [01:11<00:00, 50.91it/s, loss=0.2976]


Epoch 15/15 - Loss: 0.1833, Accuracy: 0.8405
Fold 7 Accuracy: 0.8403
Fold 8: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [01:01<00:00, 58.97it/s, loss=0.1395]


Epoch 1/15 - Loss: 0.1858, Accuracy: 0.8393


Epoch 2/15: 100%|██████████| 3624/3624 [01:08<00:00, 53.10it/s, loss=0.2620]


Epoch 2/15 - Loss: 0.1851, Accuracy: 0.8403


Epoch 3/15: 100%|██████████| 3624/3624 [00:56<00:00, 63.74it/s, loss=0.1892]


Epoch 3/15 - Loss: 0.1846, Accuracy: 0.8405


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.53it/s, loss=0.3090]


Epoch 4/15 - Loss: 0.1841, Accuracy: 0.8406


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.23it/s, loss=0.1753]


Epoch 5/15 - Loss: 0.1833, Accuracy: 0.8412


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.53it/s, loss=0.3221]


Epoch 6/15 - Loss: 0.1835, Accuracy: 0.8402


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.26it/s, loss=0.1725]


Epoch 7/15 - Loss: 0.1829, Accuracy: 0.8412


Epoch 8/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.46it/s, loss=0.1718]


Epoch 8/15 - Loss: 0.1838, Accuracy: 0.8407


Epoch 9/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.45it/s, loss=0.1325]


Epoch 9/15 - Loss: 0.1823, Accuracy: 0.8424


Epoch 10/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.42it/s, loss=0.2116]


Epoch 10/15 - Loss: 0.1817, Accuracy: 0.8421


Epoch 11/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.39it/s, loss=0.0360]


Epoch 11/15 - Loss: 0.1819, Accuracy: 0.8419


Epoch 12/15: 100%|██████████| 3624/3624 [00:55<00:00, 65.10it/s, loss=0.1367]


Epoch 12/15 - Loss: 0.1817, Accuracy: 0.8418


Epoch 13/15: 100%|██████████| 3624/3624 [01:00<00:00, 59.52it/s, loss=0.2619]


Epoch 13/15 - Loss: 0.1816, Accuracy: 0.8422


Epoch 14/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.45it/s, loss=0.1572]


Epoch 14/15 - Loss: 0.1815, Accuracy: 0.8424


Epoch 15/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.44it/s, loss=0.1442]


Epoch 15/15 - Loss: 0.1808, Accuracy: 0.8430
Fold 8 Accuracy: 0.8449
Fold 9: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:42<00:00, 84.98it/s, loss=0.2432]


Epoch 1/15 - Loss: 0.1830, Accuracy: 0.8415


Epoch 2/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.37it/s, loss=0.2270]


Epoch 2/15 - Loss: 0.1829, Accuracy: 0.8413


Epoch 3/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.26it/s, loss=0.1689]


Epoch 3/15 - Loss: 0.1813, Accuracy: 0.8424


Epoch 4/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.23it/s, loss=0.1215]


Epoch 4/15 - Loss: 0.1814, Accuracy: 0.8433


Epoch 5/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.48it/s, loss=0.0916]


Epoch 5/15 - Loss: 0.1809, Accuracy: 0.8424


Epoch 6/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.50it/s, loss=0.1405]


Epoch 6/15 - Loss: 0.1807, Accuracy: 0.8429


Epoch 7/15: 100%|██████████| 3624/3624 [00:42<00:00, 85.46it/s, loss=0.0771]


Epoch 7/15 - Loss: 0.1804, Accuracy: 0.8432


Epoch 8/15: 100%|██████████| 3624/3624 [00:47<00:00, 75.69it/s, loss=0.0271]


Epoch 8/15 - Loss: 0.1801, Accuracy: 0.8431


Epoch 9/15: 100%|██████████| 3624/3624 [01:10<00:00, 51.32it/s, loss=0.1883]


Epoch 9/15 - Loss: 0.1799, Accuracy: 0.8434


Epoch 10/15: 100%|██████████| 3624/3624 [01:09<00:00, 51.86it/s, loss=0.1317]


Epoch 10/15 - Loss: 0.1799, Accuracy: 0.8432


Epoch 11/15: 100%|██████████| 3624/3624 [01:04<00:00, 56.62it/s, loss=0.3343]


Epoch 11/15 - Loss: 0.1793, Accuracy: 0.8436


Epoch 12/15: 100%|██████████| 3624/3624 [01:06<00:00, 54.22it/s, loss=0.1216]


Epoch 12/15 - Loss: 0.1784, Accuracy: 0.8450


Epoch 13/15: 100%|██████████| 3624/3624 [01:11<00:00, 50.84it/s, loss=0.1149]


Epoch 13/15 - Loss: 0.1787, Accuracy: 0.8445


Epoch 14/15: 100%|██████████| 3624/3624 [00:47<00:00, 76.93it/s, loss=0.1045]


Epoch 14/15 - Loss: 0.1784, Accuracy: 0.8443


Epoch 15/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.20it/s, loss=0.2666]


Epoch 15/15 - Loss: 0.1780, Accuracy: 0.8446
Fold 9 Accuracy: 0.8451
Fold 10: 231906 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.38it/s, loss=0.1988]


Epoch 1/15 - Loss: 0.1808, Accuracy: 0.8429


Epoch 2/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.43it/s, loss=0.2042]


Epoch 2/15 - Loss: 0.1803, Accuracy: 0.8437


Epoch 3/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.56it/s, loss=0.3133]


Epoch 3/15 - Loss: 0.1796, Accuracy: 0.8434


Epoch 4/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.44it/s, loss=0.2568]


Epoch 4/15 - Loss: 0.1792, Accuracy: 0.8436


Epoch 5/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.35it/s, loss=0.2271]


Epoch 5/15 - Loss: 0.1792, Accuracy: 0.8440


Epoch 6/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.39it/s, loss=0.1654]


Epoch 6/15 - Loss: 0.1784, Accuracy: 0.8447


Epoch 7/15: 100%|██████████| 3624/3624 [00:44<00:00, 82.25it/s, loss=0.0893]


Epoch 7/15 - Loss: 0.1786, Accuracy: 0.8446


Epoch 8/15: 100%|██████████| 3624/3624 [01:06<00:00, 54.32it/s, loss=0.2819]


Epoch 8/15 - Loss: 0.1784, Accuracy: 0.8442


Epoch 9/15: 100%|██████████| 3624/3624 [01:04<00:00, 55.78it/s, loss=0.1946]


Epoch 9/15 - Loss: 0.1781, Accuracy: 0.8445


Epoch 10/15: 100%|██████████| 3624/3624 [00:43<00:00, 82.98it/s, loss=0.4669]


Epoch 10/15 - Loss: 0.1778, Accuracy: 0.8451


Epoch 11/15: 100%|██████████| 3624/3624 [00:43<00:00, 82.66it/s, loss=0.2073]


Epoch 11/15 - Loss: 0.1776, Accuracy: 0.8453


Epoch 12/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.09it/s, loss=0.2095]


Epoch 12/15 - Loss: 0.1772, Accuracy: 0.8458


Epoch 13/15: 100%|██████████| 3624/3624 [00:43<00:00, 82.99it/s, loss=0.1035]


Epoch 13/15 - Loss: 0.1770, Accuracy: 0.8460


Epoch 14/15: 100%|██████████| 3624/3624 [00:43<00:00, 83.13it/s, loss=0.2354]


Epoch 14/15 - Loss: 0.1763, Accuracy: 0.8465


Epoch 15/15: 100%|██████████| 3624/3624 [00:43<00:00, 82.58it/s, loss=0.0784]


Epoch 15/15 - Loss: 0.1772, Accuracy: 0.8455
Fold 10 Accuracy: 0.8491
Complete model saved to UNSW-FOCALloss.pth
Fold Accuracies:
  Fold 1: 0.8185
  Fold 2: 0.8220
  Fold 3: 0.8301
  Fold 4: 0.8294
  Fold 5: 0.8336
  Fold 6: 0.8368
  Fold 7: 0.8403
  Fold 8: 0.8449
  Fold 9: 0.8451
  Fold 10: 0.8491


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  28    0    6  164   43    0   27    0    0    0]
 [   0   28    8  148   46    0    1    0    1    0]
 [   0    1  238 1314   47    7   10   10    8    0]
 [   2    0   94 4056  118   14   64   81   17    6]
 [   0    0   13  187 1601    2  603    6   13    0]
 [   0    0    7   53    1 5820    3    2    1    0]
 [   9    0    2   35  357    1 8881    7    8    0]
 [   0    0   12  277    3    1    1 1104    1    0]
 [   0    0    1   12    8    1   10    5  114    0]
 [   0    0    0    7    1    0    0    0    1    9]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.72      0.10      0.18       268
      Backdoor       0.97      0.12      0.21       232
           DoS       0.62      0.15      0.24      1635
      Exploits       0.65      0.91      0.76      4452
       Fuzzers       0.72      0.66      0.69      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.