In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [16]:
import torch
import torch.nn as nn

# ------------------------ 改进 ASTP 模块 ------------------------
class ASTP(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        # 多尺度时间卷积 + 门控线性单元（GLU）
        self.temp_conv = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 32, kernel_size=32, padding='same', groups=1),  # 深度可分离卷积
                nn.GLU(dim=1)  # 门控线性单元
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 32, kernel_size=64, padding='same', groups=1),
                nn.GLU(dim=1)
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 32, kernel_size=96, padding='same', groups=1),
                nn.GLU(dim=1)
            )
        ])
        
        # SE通道注意力
        self.se_block = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 24, kernel_size=1),
            nn.ReLU(),
            nn.Conv1d(24, 48, kernel_size=1),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        branch_outs = [conv(x) for conv in self.temp_conv]  # 计算多尺度卷积
        merged = torch.cat(branch_outs, dim=1)  # [B, 24, L]
        return merged * self.se_block(merged)  # SE 注意力增强特征

# ------------------------ BiLSTM-AGRU（增强时序建模） ------------------------
class BiLSTM_AGRU(nn.Module):
    def __init__(self, feat_dim):
        super().__init__()
        self.bilstm = nn.LSTM(feat_dim, feat_dim // 2, num_layers=2, bidirectional=True, batch_first=True)
        self.agru = nn.GRU(feat_dim, feat_dim, num_layers=1, batch_first=True)
        self.att_weight = nn.Linear(feat_dim, 1)  # AGRU 的注意力权重
        
    def forward(self, x):
        # BiLSTM
        lstm_out, _ = self.bilstm(x)  # [B, L, D]
        
        # AGRU（使用注意力加权）
        agru_out, _ = self.agru(lstm_out)  # [B, L, D]
        att_scores = torch.sigmoid(self.att_weight(agru_out))  # [B, L, 1]
        
        return agru_out * att_scores  # 注意力加权 AGRU 输出

# ------------------------ 改进 Transformer（Local Attention + GLU） ------------------------
class LocalTransformer(nn.Module):
    def __init__(self, feat_dim, num_layers=2):
        super().__init__()
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=feat_dim,
            nhead=4,
            dim_feedforward=feat_dim * 4,
            batch_first=True,
            activation=F.gelu
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # GLU 变换增强特征表达
        self.glu = nn.Sequential(
            nn.Linear(feat_dim, feat_dim * 2),
            nn.GLU(dim=-1)
        )
    
    def forward(self, x):
        x = self.transformer(x)  # 局部注意力 Transformer
        return self.glu(x)  # GLU 进行特征选择

# ------------------------ 改进 NSLKDDModel ------------------------
class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10):
        super().__init__()

        # 特征提取层（ASTP）
        self.astp = ASTP(in_channels=1)
        self.pool = nn.AdaptiveMaxPool1d(input_dim // 4)  # 维度降采样
        self.bn = nn.BatchNorm1d(48)  # 特征标准化

        # 时序建模（BiLSTM-AGRU + Transformer）
        self.time_modeling = nn.Sequential(
            BiLSTM_AGRU(48),
            LocalTransformer(48, num_layers=2)
        )

        # 分类头（IEEE TDSC 2023 改进）
        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(48, 128),
            nn.BatchNorm1d(128),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        # 输入形状: [B, 1, 122]
        x = self.astp(x)           # [B, 24, 122]
        x = self.pool(x)           # [B, 24, 30]
        x = self.bn(x)             # 特征标准化
        x = x.permute(0, 2, 1)     # [B, 30, 24]
        x = self.time_modeling(x)  # [B, 30, 24]
        x = x.permute(0, 2, 1)     # [B, 24, 30]
        return self.classifier(x)  # [B, num_classes]


In [17]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =25   #15 0.0005  83.68  25 0.0005 83.80  20 0.0005   
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

class FocalLoss(nn.Module):
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = nn.CrossEntropyLoss(reduction='none')(inputs, targets)
        pt = torch.exp(-ce_loss)  # 预测的概率
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

criterion = FocalLoss()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
#criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "modelU10.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:53<00:00, 91.72it/s, loss=0.4940]


Epoch 1/25 - Loss: 0.3427, Accuracy: 0.7878


Epoch 2/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.24it/s, loss=0.1754]


Epoch 2/25 - Loss: 0.2619, Accuracy: 0.8194


Epoch 3/25: 100%|██████████| 4929/4929 [00:53<00:00, 92.78it/s, loss=0.1610]


Epoch 3/25 - Loss: 0.2383, Accuracy: 0.8313


Epoch 4/25: 100%|██████████| 4929/4929 [00:53<00:00, 92.59it/s, loss=0.1426]


Epoch 4/25 - Loss: 0.2281, Accuracy: 0.8356


Epoch 5/25: 100%|██████████| 4929/4929 [00:53<00:00, 92.43it/s, loss=0.1859]


Epoch 5/25 - Loss: 0.2192, Accuracy: 0.8406


Epoch 6/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.45it/s, loss=0.2768]


Epoch 6/25 - Loss: 0.2127, Accuracy: 0.8434


Epoch 7/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.90it/s, loss=0.1027]


Epoch 7/25 - Loss: 0.2080, Accuracy: 0.8453


Epoch 8/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.29it/s, loss=0.2762]


Epoch 8/25 - Loss: 0.2041, Accuracy: 0.8476


Epoch 9/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.54it/s, loss=0.1327]


Epoch 9/25 - Loss: 0.2008, Accuracy: 0.8495


Epoch 10/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.33it/s, loss=0.1793]


Epoch 10/25 - Loss: 0.1974, Accuracy: 0.8502


Epoch 11/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.93it/s, loss=0.2028]


Epoch 11/25 - Loss: 0.1935, Accuracy: 0.8519


Epoch 12/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.48it/s, loss=0.1797]


Epoch 12/25 - Loss: 0.1915, Accuracy: 0.8532


Epoch 13/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.83it/s, loss=0.1367]


Epoch 13/25 - Loss: 0.1889, Accuracy: 0.8541


Epoch 14/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.90it/s, loss=0.2687]


Epoch 14/25 - Loss: 0.1870, Accuracy: 0.8543


Epoch 15/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.15it/s, loss=0.1356]


Epoch 15/25 - Loss: 0.1850, Accuracy: 0.8554


Epoch 16/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.64it/s, loss=0.1052]


Epoch 16/25 - Loss: 0.1832, Accuracy: 0.8560


Epoch 17/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.05it/s, loss=0.1478]


Epoch 17/25 - Loss: 0.1818, Accuracy: 0.8567


Epoch 18/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.21it/s, loss=0.1934]


Epoch 18/25 - Loss: 0.1805, Accuracy: 0.8580


Epoch 19/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.40it/s, loss=0.2709]


Epoch 19/25 - Loss: 0.1796, Accuracy: 0.8582


Epoch 20/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.31it/s, loss=0.1871]


Epoch 20/25 - Loss: 0.1778, Accuracy: 0.8595


Epoch 21/25: 100%|██████████| 4929/4929 [01:00<00:00, 81.95it/s, loss=0.1233]


Epoch 21/25 - Loss: 0.1769, Accuracy: 0.8597


Epoch 22/25: 100%|██████████| 4929/4929 [00:58<00:00, 83.89it/s, loss=0.1780]


Epoch 22/25 - Loss: 0.1760, Accuracy: 0.8596


Epoch 23/25: 100%|██████████| 4929/4929 [00:58<00:00, 84.76it/s, loss=0.2014]


Epoch 23/25 - Loss: 0.1751, Accuracy: 0.8595


Epoch 24/25: 100%|██████████| 4929/4929 [00:57<00:00, 86.40it/s, loss=0.1845]


Epoch 24/25 - Loss: 0.1736, Accuracy: 0.8613


Epoch 25/25: 100%|██████████| 4929/4929 [00:57<00:00, 86.16it/s, loss=0.1043]


Epoch 25/25 - Loss: 0.1733, Accuracy: 0.8619
Fold 1 Accuracy: 0.8137
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.54it/s, loss=0.3365]


Epoch 1/25 - Loss: 0.1746, Accuracy: 0.8604


Epoch 2/25: 100%|██████████| 4929/4929 [00:57<00:00, 86.20it/s, loss=0.2165]


Epoch 2/25 - Loss: 0.1731, Accuracy: 0.8612


Epoch 3/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.63it/s, loss=0.1603]


Epoch 3/25 - Loss: 0.1716, Accuracy: 0.8621


Epoch 4/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.47it/s, loss=0.2092]


Epoch 4/25 - Loss: 0.1711, Accuracy: 0.8622


Epoch 5/25: 100%|██████████| 4929/4929 [00:56<00:00, 86.99it/s, loss=0.1547]


Epoch 5/25 - Loss: 0.1697, Accuracy: 0.8630


Epoch 6/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.62it/s, loss=0.4066]


Epoch 6/25 - Loss: 0.1693, Accuracy: 0.8635


Epoch 7/25: 100%|██████████| 4929/4929 [01:06<00:00, 73.84it/s, loss=0.2264]


Epoch 7/25 - Loss: 0.1681, Accuracy: 0.8636


Epoch 8/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.34it/s, loss=0.3615]


Epoch 8/25 - Loss: 0.1674, Accuracy: 0.8637


Epoch 9/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.96it/s, loss=0.3220]


Epoch 9/25 - Loss: 0.1667, Accuracy: 0.8648


Epoch 10/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.86it/s, loss=0.0425]


Epoch 10/25 - Loss: 0.1670, Accuracy: 0.8647


Epoch 11/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.70it/s, loss=0.2123]


Epoch 11/25 - Loss: 0.1652, Accuracy: 0.8652


Epoch 12/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.35it/s, loss=0.1572]


Epoch 12/25 - Loss: 0.1649, Accuracy: 0.8654


Epoch 13/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.52it/s, loss=0.0703]


Epoch 13/25 - Loss: 0.1644, Accuracy: 0.8652


Epoch 14/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.91it/s, loss=0.1416]


Epoch 14/25 - Loss: 0.1640, Accuracy: 0.8654


Epoch 15/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.29it/s, loss=0.1780]


Epoch 15/25 - Loss: 0.1633, Accuracy: 0.8660


Epoch 16/25: 100%|██████████| 4929/4929 [01:26<00:00, 57.08it/s, loss=0.1892]


Epoch 16/25 - Loss: 0.1621, Accuracy: 0.8666


Epoch 17/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.62it/s, loss=0.2601]


Epoch 17/25 - Loss: 0.1626, Accuracy: 0.8660


Epoch 18/25: 100%|██████████| 4929/4929 [01:09<00:00, 71.41it/s, loss=0.0731]


Epoch 18/25 - Loss: 0.1612, Accuracy: 0.8671


Epoch 19/25: 100%|██████████| 4929/4929 [00:51<00:00, 95.01it/s, loss=0.1006]


Epoch 19/25 - Loss: 0.1599, Accuracy: 0.8680


Epoch 20/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.79it/s, loss=0.1685]


Epoch 20/25 - Loss: 0.1608, Accuracy: 0.8674


Epoch 21/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.52it/s, loss=0.1021]


Epoch 21/25 - Loss: 0.1599, Accuracy: 0.8681


Epoch 22/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.08it/s, loss=0.2895]


Epoch 22/25 - Loss: 0.1597, Accuracy: 0.8679


Epoch 23/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.54it/s, loss=0.2488]


Epoch 23/25 - Loss: 0.1587, Accuracy: 0.8676


Epoch 24/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.10it/s, loss=0.1670]


Epoch 24/25 - Loss: 0.1582, Accuracy: 0.8683


Epoch 25/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.21it/s, loss=0.2433]


Epoch 25/25 - Loss: 0.1582, Accuracy: 0.8689
Fold 2 Accuracy: 0.8144
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.26it/s, loss=0.1299]


Epoch 1/25 - Loss: 0.1598, Accuracy: 0.8679


Epoch 2/25: 100%|██████████| 4929/4929 [00:56<00:00, 86.91it/s, loss=0.1937]


Epoch 2/25 - Loss: 0.1582, Accuracy: 0.8688


Epoch 3/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.17it/s, loss=0.1525]


Epoch 3/25 - Loss: 0.1579, Accuracy: 0.8683


Epoch 4/25: 100%|██████████| 4929/4929 [00:59<00:00, 83.03it/s, loss=0.1419]


Epoch 4/25 - Loss: 0.1568, Accuracy: 0.8688


Epoch 5/25: 100%|██████████| 4929/4929 [01:42<00:00, 48.08it/s, loss=0.0864]


Epoch 5/25 - Loss: 0.1570, Accuracy: 0.8689


Epoch 6/25: 100%|██████████| 4929/4929 [01:41<00:00, 48.36it/s, loss=0.1216]


Epoch 6/25 - Loss: 0.1567, Accuracy: 0.8696


Epoch 7/25: 100%|██████████| 4929/4929 [01:40<00:00, 48.83it/s, loss=0.0923]


Epoch 7/25 - Loss: 0.1554, Accuracy: 0.8693


Epoch 8/25: 100%|██████████| 4929/4929 [01:37<00:00, 50.40it/s, loss=0.2605]


Epoch 8/25 - Loss: 0.1551, Accuracy: 0.8699


Epoch 9/25: 100%|██████████| 4929/4929 [01:39<00:00, 49.43it/s, loss=0.1017]


Epoch 9/25 - Loss: 0.1546, Accuracy: 0.8704


Epoch 10/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.53it/s, loss=0.1015]


Epoch 10/25 - Loss: 0.1545, Accuracy: 0.8701


Epoch 11/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.50it/s, loss=0.1377]


Epoch 11/25 - Loss: 0.1541, Accuracy: 0.8702


Epoch 12/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.99it/s, loss=0.0770]


Epoch 12/25 - Loss: 0.1535, Accuracy: 0.8709


Epoch 13/25: 100%|██████████| 4929/4929 [00:57<00:00, 86.46it/s, loss=0.1100]


Epoch 13/25 - Loss: 0.1529, Accuracy: 0.8708


Epoch 14/25: 100%|██████████| 4929/4929 [00:57<00:00, 86.03it/s, loss=0.2228]


Epoch 14/25 - Loss: 0.1525, Accuracy: 0.8708


Epoch 15/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.88it/s, loss=0.1271]


Epoch 15/25 - Loss: 0.1525, Accuracy: 0.8710


Epoch 16/25: 100%|██████████| 4929/4929 [00:58<00:00, 84.92it/s, loss=0.2260]


Epoch 16/25 - Loss: 0.1524, Accuracy: 0.8710


Epoch 17/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.75it/s, loss=0.1132]


Epoch 17/25 - Loss: 0.1519, Accuracy: 0.8714


Epoch 18/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.37it/s, loss=0.2133]


Epoch 18/25 - Loss: 0.1510, Accuracy: 0.8716


Epoch 19/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.43it/s, loss=0.1052]


Epoch 19/25 - Loss: 0.1511, Accuracy: 0.8721


Epoch 20/25: 100%|██████████| 4929/4929 [00:58<00:00, 84.87it/s, loss=0.0832]


Epoch 20/25 - Loss: 0.1501, Accuracy: 0.8722


Epoch 21/25: 100%|██████████| 4929/4929 [00:57<00:00, 85.26it/s, loss=0.0856]


Epoch 21/25 - Loss: 0.1502, Accuracy: 0.8719


Epoch 22/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.10it/s, loss=0.0764]


Epoch 22/25 - Loss: 0.1499, Accuracy: 0.8726


Epoch 23/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.05it/s, loss=0.0858]


Epoch 23/25 - Loss: 0.1497, Accuracy: 0.8724


Epoch 24/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.75it/s, loss=0.1500]


Epoch 24/25 - Loss: 0.1496, Accuracy: 0.8724


Epoch 25/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.00it/s, loss=0.0609]


Epoch 25/25 - Loss: 0.1484, Accuracy: 0.8730
Fold 3 Accuracy: 0.8252
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:54<00:00, 89.67it/s, loss=0.2005]


Epoch 1/25 - Loss: 0.1507, Accuracy: 0.8724


Epoch 2/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.47it/s, loss=0.2462]


Epoch 2/25 - Loss: 0.1490, Accuracy: 0.8729


Epoch 3/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.60it/s, loss=0.1157]


Epoch 3/25 - Loss: 0.1492, Accuracy: 0.8732


Epoch 4/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.22it/s, loss=0.1665]


Epoch 4/25 - Loss: 0.1487, Accuracy: 0.8730


Epoch 5/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.91it/s, loss=0.0689]


Epoch 5/25 - Loss: 0.1486, Accuracy: 0.8736


Epoch 6/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.44it/s, loss=0.1475]


Epoch 6/25 - Loss: 0.1482, Accuracy: 0.8736


Epoch 7/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.16it/s, loss=0.1815]


Epoch 7/25 - Loss: 0.1478, Accuracy: 0.8741


Epoch 8/25: 100%|██████████| 4929/4929 [00:56<00:00, 86.83it/s, loss=0.1197]


Epoch 8/25 - Loss: 0.1469, Accuracy: 0.8736


Epoch 9/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.66it/s, loss=0.1011]


Epoch 9/25 - Loss: 0.1474, Accuracy: 0.8734


Epoch 10/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.83it/s, loss=0.2713]


Epoch 10/25 - Loss: 0.1471, Accuracy: 0.8743


Epoch 11/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.75it/s, loss=0.1959]


Epoch 11/25 - Loss: 0.1469, Accuracy: 0.8737


Epoch 12/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.96it/s, loss=0.1486]


Epoch 12/25 - Loss: 0.1464, Accuracy: 0.8745


Epoch 13/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.96it/s, loss=0.0372]


Epoch 13/25 - Loss: 0.1463, Accuracy: 0.8743


Epoch 14/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.03it/s, loss=0.0786]


Epoch 14/25 - Loss: 0.1452, Accuracy: 0.8752


Epoch 15/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.36it/s, loss=0.1339]


Epoch 15/25 - Loss: 0.1455, Accuracy: 0.8751


Epoch 16/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.83it/s, loss=0.1943]


Epoch 16/25 - Loss: 0.1453, Accuracy: 0.8758


Epoch 17/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.24it/s, loss=0.0944]


Epoch 17/25 - Loss: 0.1447, Accuracy: 0.8755


Epoch 18/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.27it/s, loss=0.1714]


Epoch 18/25 - Loss: 0.1445, Accuracy: 0.8758


Epoch 19/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.24it/s, loss=0.1042]


Epoch 19/25 - Loss: 0.1442, Accuracy: 0.8757


Epoch 20/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.10it/s, loss=0.2123]


Epoch 20/25 - Loss: 0.1437, Accuracy: 0.8751


Epoch 21/25: 100%|██████████| 4929/4929 [01:29<00:00, 54.96it/s, loss=0.1521]


Epoch 21/25 - Loss: 0.1438, Accuracy: 0.8760


Epoch 22/25: 100%|██████████| 4929/4929 [01:35<00:00, 51.83it/s, loss=0.1357]


Epoch 22/25 - Loss: 0.1431, Accuracy: 0.8768


Epoch 23/25: 100%|██████████| 4929/4929 [01:00<00:00, 81.65it/s, loss=0.2406]


Epoch 23/25 - Loss: 0.1435, Accuracy: 0.8764


Epoch 24/25: 100%|██████████| 4929/4929 [01:00<00:00, 81.13it/s, loss=0.0677]


Epoch 24/25 - Loss: 0.1435, Accuracy: 0.8757


Epoch 25/25: 100%|██████████| 4929/4929 [01:36<00:00, 51.18it/s, loss=0.1362]


Epoch 25/25 - Loss: 0.1431, Accuracy: 0.8768
Fold 4 Accuracy: 0.8229
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [01:36<00:00, 51.30it/s, loss=0.1066]


Epoch 1/25 - Loss: 0.1453, Accuracy: 0.8754


Epoch 2/25: 100%|██████████| 4929/4929 [01:35<00:00, 51.75it/s, loss=0.2732]


Epoch 2/25 - Loss: 0.1444, Accuracy: 0.8761


Epoch 3/25: 100%|██████████| 4929/4929 [01:36<00:00, 51.23it/s, loss=0.1295]


Epoch 3/25 - Loss: 0.1438, Accuracy: 0.8759


Epoch 4/25: 100%|██████████| 4929/4929 [01:34<00:00, 52.23it/s, loss=0.0998]


Epoch 4/25 - Loss: 0.1442, Accuracy: 0.8750


Epoch 5/25: 100%|██████████| 4929/4929 [01:37<00:00, 50.34it/s, loss=0.1484]


Epoch 5/25 - Loss: 0.1452, Accuracy: 0.8757


Epoch 6/25: 100%|██████████| 4929/4929 [01:25<00:00, 57.38it/s, loss=0.1849]


Epoch 6/25 - Loss: 0.1433, Accuracy: 0.8762


Epoch 7/25: 100%|██████████| 4929/4929 [00:51<00:00, 94.95it/s, loss=0.1524]


Epoch 7/25 - Loss: 0.1427, Accuracy: 0.8759


Epoch 8/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.70it/s, loss=0.2300]


Epoch 8/25 - Loss: 0.1429, Accuracy: 0.8762


Epoch 9/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.99it/s, loss=0.1127]


Epoch 9/25 - Loss: 0.1433, Accuracy: 0.8762


Epoch 10/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.22it/s, loss=0.0433]


Epoch 10/25 - Loss: 0.1425, Accuracy: 0.8770


Epoch 11/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.05it/s, loss=0.1129]


Epoch 11/25 - Loss: 0.1420, Accuracy: 0.8773


Epoch 12/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.78it/s, loss=0.2434]


Epoch 12/25 - Loss: 0.1418, Accuracy: 0.8771


Epoch 13/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.56it/s, loss=0.1212]


Epoch 13/25 - Loss: 0.1421, Accuracy: 0.8776


Epoch 14/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.90it/s, loss=0.1558]


Epoch 14/25 - Loss: 0.1414, Accuracy: 0.8772


Epoch 15/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.62it/s, loss=0.1938]


Epoch 15/25 - Loss: 0.1408, Accuracy: 0.8777


Epoch 16/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.83it/s, loss=0.0658]


Epoch 16/25 - Loss: 0.1409, Accuracy: 0.8776


Epoch 17/25: 100%|██████████| 4929/4929 [00:58<00:00, 84.03it/s, loss=0.1323]


Epoch 17/25 - Loss: 0.1404, Accuracy: 0.8780


Epoch 18/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.16it/s, loss=0.1845]


Epoch 18/25 - Loss: 0.1409, Accuracy: 0.8777


Epoch 19/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.68it/s, loss=0.1526]


Epoch 19/25 - Loss: 0.1401, Accuracy: 0.8780


Epoch 20/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.48it/s, loss=0.1567]


Epoch 20/25 - Loss: 0.1399, Accuracy: 0.8781


Epoch 21/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.76it/s, loss=0.4119]


Epoch 21/25 - Loss: 0.1398, Accuracy: 0.8777


Epoch 22/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.25it/s, loss=0.0577]


Epoch 22/25 - Loss: 0.1395, Accuracy: 0.8790


Epoch 23/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.46it/s, loss=0.2499]


Epoch 23/25 - Loss: 0.1399, Accuracy: 0.8783


Epoch 24/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.21it/s, loss=0.2683]


Epoch 24/25 - Loss: 0.1394, Accuracy: 0.8786


Epoch 25/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.85it/s, loss=0.1316]


Epoch 25/25 - Loss: 0.1391, Accuracy: 0.8787
Fold 5 Accuracy: 0.8275
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.98it/s, loss=0.1000]


Epoch 1/25 - Loss: 0.1410, Accuracy: 0.8778


Epoch 2/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.76it/s, loss=0.1303]


Epoch 2/25 - Loss: 0.1401, Accuracy: 0.8785


Epoch 3/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.92it/s, loss=0.2255]


Epoch 3/25 - Loss: 0.1398, Accuracy: 0.8781


Epoch 4/25: 100%|██████████| 4929/4929 [00:56<00:00, 87.21it/s, loss=0.0929]


Epoch 4/25 - Loss: 0.1396, Accuracy: 0.8786


Epoch 5/25: 100%|██████████| 4929/4929 [00:55<00:00, 88.17it/s, loss=0.3362]


Epoch 5/25 - Loss: 0.1390, Accuracy: 0.8785


Epoch 6/25: 100%|██████████| 4929/4929 [00:55<00:00, 89.38it/s, loss=0.1332]


Epoch 6/25 - Loss: 0.1390, Accuracy: 0.8790


Epoch 7/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.27it/s, loss=0.0789]


Epoch 7/25 - Loss: 0.1391, Accuracy: 0.8789


Epoch 8/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.97it/s, loss=0.2943]


Epoch 8/25 - Loss: 0.1381, Accuracy: 0.8794


Epoch 9/25: 100%|██████████| 4929/4929 [01:07<00:00, 72.91it/s, loss=0.1471]


Epoch 9/25 - Loss: 0.1387, Accuracy: 0.8790


Epoch 10/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.87it/s, loss=0.3360]


Epoch 10/25 - Loss: 0.1385, Accuracy: 0.8796


Epoch 11/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.98it/s, loss=0.1160]


Epoch 11/25 - Loss: 0.1376, Accuracy: 0.8800


Epoch 12/25: 100%|██████████| 4929/4929 [01:29<00:00, 54.82it/s, loss=0.3797]


Epoch 12/25 - Loss: 0.1379, Accuracy: 0.8802


Epoch 13/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.40it/s, loss=0.0631]


Epoch 13/25 - Loss: 0.1375, Accuracy: 0.8799


Epoch 14/25: 100%|██████████| 4929/4929 [01:29<00:00, 54.99it/s, loss=0.1750]


Epoch 14/25 - Loss: 0.1374, Accuracy: 0.8802


Epoch 15/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.88it/s, loss=0.1231]


Epoch 15/25 - Loss: 0.1368, Accuracy: 0.8804


Epoch 16/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.47it/s, loss=0.2906]


Epoch 16/25 - Loss: 0.1371, Accuracy: 0.8798


Epoch 17/25: 100%|██████████| 4929/4929 [01:25<00:00, 57.36it/s, loss=0.2163]


Epoch 17/25 - Loss: 0.1366, Accuracy: 0.8802


Epoch 18/25: 100%|██████████| 4929/4929 [01:27<00:00, 56.01it/s, loss=0.1256]


Epoch 18/25 - Loss: 0.1371, Accuracy: 0.8803


Epoch 19/25: 100%|██████████| 4929/4929 [01:27<00:00, 56.46it/s, loss=0.0997]


Epoch 19/25 - Loss: 0.1364, Accuracy: 0.8807


Epoch 20/25: 100%|██████████| 4929/4929 [01:27<00:00, 56.06it/s, loss=0.1734]


Epoch 20/25 - Loss: 0.1364, Accuracy: 0.8803


Epoch 21/25: 100%|██████████| 4929/4929 [01:28<00:00, 55.53it/s, loss=0.1926]


Epoch 21/25 - Loss: 0.1359, Accuracy: 0.8804


Epoch 22/25: 100%|██████████| 4929/4929 [01:26<00:00, 56.84it/s, loss=0.1495]


Epoch 22/25 - Loss: 0.1366, Accuracy: 0.8807


Epoch 23/25: 100%|██████████| 4929/4929 [01:29<00:00, 55.00it/s, loss=0.1290]


Epoch 23/25 - Loss: 0.1359, Accuracy: 0.8813


Epoch 24/25: 100%|██████████| 4929/4929 [01:09<00:00, 70.80it/s, loss=0.2553]


Epoch 24/25 - Loss: 0.1357, Accuracy: 0.8808


Epoch 25/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.64it/s, loss=0.0802]


Epoch 25/25 - Loss: 0.1356, Accuracy: 0.8811
Fold 6 Accuracy: 0.8309
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.27it/s, loss=0.2356]


Epoch 1/25 - Loss: 0.1373, Accuracy: 0.8801


Epoch 2/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.69it/s, loss=0.0819]


Epoch 2/25 - Loss: 0.1365, Accuracy: 0.8808


Epoch 3/25: 100%|██████████| 4929/4929 [01:14<00:00, 65.84it/s, loss=0.1069]


Epoch 3/25 - Loss: 0.1366, Accuracy: 0.8806


Epoch 4/25: 100%|██████████| 4929/4929 [01:26<00:00, 56.72it/s, loss=0.0674]


Epoch 4/25 - Loss: 0.1359, Accuracy: 0.8810


Epoch 5/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.52it/s, loss=0.0848]


Epoch 5/25 - Loss: 0.1357, Accuracy: 0.8805


Epoch 6/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.04it/s, loss=0.1331]


Epoch 6/25 - Loss: 0.1354, Accuracy: 0.8812


Epoch 7/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.93it/s, loss=0.0394]


Epoch 7/25 - Loss: 0.1353, Accuracy: 0.8818


Epoch 8/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.25it/s, loss=0.0854]


Epoch 8/25 - Loss: 0.1352, Accuracy: 0.8810


Epoch 9/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.97it/s, loss=0.2138]


Epoch 9/25 - Loss: 0.1348, Accuracy: 0.8819


Epoch 10/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.65it/s, loss=0.1278]


Epoch 10/25 - Loss: 0.1348, Accuracy: 0.8820


Epoch 11/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.64it/s, loss=0.0802]


Epoch 11/25 - Loss: 0.1339, Accuracy: 0.8819


Epoch 12/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.66it/s, loss=0.1017]


Epoch 12/25 - Loss: 0.1348, Accuracy: 0.8814


Epoch 13/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.41it/s, loss=0.1580]


Epoch 13/25 - Loss: 0.1345, Accuracy: 0.8822


Epoch 14/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.41it/s, loss=0.0546]


Epoch 14/25 - Loss: 0.1334, Accuracy: 0.8825


Epoch 15/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.75it/s, loss=0.1528]


Epoch 15/25 - Loss: 0.1338, Accuracy: 0.8820


Epoch 16/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.48it/s, loss=0.0562]


Epoch 16/25 - Loss: 0.1333, Accuracy: 0.8824


Epoch 17/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.32it/s, loss=0.1736]


Epoch 17/25 - Loss: 0.1338, Accuracy: 0.8817


Epoch 18/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.55it/s, loss=0.1755]


Epoch 18/25 - Loss: 0.1332, Accuracy: 0.8826


Epoch 19/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.02it/s, loss=0.1515]


Epoch 19/25 - Loss: 0.1334, Accuracy: 0.8826


Epoch 20/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.11it/s, loss=0.0805]


Epoch 20/25 - Loss: 0.1332, Accuracy: 0.8824


Epoch 21/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.25it/s, loss=0.1002]


Epoch 21/25 - Loss: 0.1332, Accuracy: 0.8826


Epoch 22/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.95it/s, loss=0.1562]


Epoch 22/25 - Loss: 0.1330, Accuracy: 0.8822


Epoch 23/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.28it/s, loss=0.0727]


Epoch 23/25 - Loss: 0.1326, Accuracy: 0.8830


Epoch 24/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.51it/s, loss=0.1173]


Epoch 24/25 - Loss: 0.1325, Accuracy: 0.8831


Epoch 25/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.14it/s, loss=0.1627]


Epoch 25/25 - Loss: 0.1329, Accuracy: 0.8833
Fold 7 Accuracy: 0.8255
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.13it/s, loss=0.2124]


Epoch 1/25 - Loss: 0.1355, Accuracy: 0.8815


Epoch 2/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.59it/s, loss=0.1892]


Epoch 2/25 - Loss: 0.1352, Accuracy: 0.8820


Epoch 3/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.10it/s, loss=0.0873]


Epoch 3/25 - Loss: 0.1344, Accuracy: 0.8821


Epoch 4/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.98it/s, loss=0.1976]


Epoch 4/25 - Loss: 0.1340, Accuracy: 0.8832


Epoch 5/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.02it/s, loss=0.1342]


Epoch 5/25 - Loss: 0.1335, Accuracy: 0.8824


Epoch 6/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.94it/s, loss=0.1689]


Epoch 6/25 - Loss: 0.1336, Accuracy: 0.8821


Epoch 7/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.65it/s, loss=0.1363]


Epoch 7/25 - Loss: 0.1332, Accuracy: 0.8834


Epoch 8/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.21it/s, loss=0.1185]


Epoch 8/25 - Loss: 0.1339, Accuracy: 0.8832


Epoch 9/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.12it/s, loss=0.0785]


Epoch 9/25 - Loss: 0.1330, Accuracy: 0.8832


Epoch 10/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.97it/s, loss=0.1897]


Epoch 10/25 - Loss: 0.1326, Accuracy: 0.8832


Epoch 11/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.94it/s, loss=0.1084]


Epoch 11/25 - Loss: 0.1334, Accuracy: 0.8829


Epoch 12/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.29it/s, loss=0.1401]


Epoch 12/25 - Loss: 0.1323, Accuracy: 0.8838


Epoch 13/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.09it/s, loss=0.3320]


Epoch 13/25 - Loss: 0.1323, Accuracy: 0.8835


Epoch 14/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.96it/s, loss=0.0916]


Epoch 14/25 - Loss: 0.1327, Accuracy: 0.8833


Epoch 15/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.34it/s, loss=0.2061]


Epoch 15/25 - Loss: 0.1316, Accuracy: 0.8837


Epoch 16/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.47it/s, loss=0.0387]


Epoch 16/25 - Loss: 0.1325, Accuracy: 0.8839


Epoch 17/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.29it/s, loss=0.1072]


Epoch 17/25 - Loss: 0.1325, Accuracy: 0.8833


Epoch 18/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.59it/s, loss=0.1663]


Epoch 18/25 - Loss: 0.1320, Accuracy: 0.8832


Epoch 19/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.14it/s, loss=0.1403]


Epoch 19/25 - Loss: 0.1319, Accuracy: 0.8831


Epoch 20/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.43it/s, loss=0.1647]


Epoch 20/25 - Loss: 0.1319, Accuracy: 0.8835


Epoch 21/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.62it/s, loss=0.1935]


Epoch 21/25 - Loss: 0.1315, Accuracy: 0.8842


Epoch 22/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.38it/s, loss=0.1022]


Epoch 22/25 - Loss: 0.1319, Accuracy: 0.8839


Epoch 23/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.00it/s, loss=0.1212]


Epoch 23/25 - Loss: 0.1311, Accuracy: 0.8844


Epoch 24/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.44it/s, loss=0.1589]


Epoch 24/25 - Loss: 0.1311, Accuracy: 0.8843


Epoch 25/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.26it/s, loss=0.0821]


Epoch 25/25 - Loss: 0.1309, Accuracy: 0.8842
Fold 8 Accuracy: 0.8348
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.45it/s, loss=0.1506]


Epoch 1/25 - Loss: 0.1327, Accuracy: 0.8834


Epoch 2/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.90it/s, loss=0.1303]


Epoch 2/25 - Loss: 0.1322, Accuracy: 0.8833


Epoch 3/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.06it/s, loss=0.1365]


Epoch 3/25 - Loss: 0.1320, Accuracy: 0.8842


Epoch 4/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.11it/s, loss=0.1115]


Epoch 4/25 - Loss: 0.1312, Accuracy: 0.8829


Epoch 5/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.43it/s, loss=0.0285]


Epoch 5/25 - Loss: 0.1317, Accuracy: 0.8837


Epoch 6/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.44it/s, loss=0.2273]


Epoch 6/25 - Loss: 0.1306, Accuracy: 0.8842


Epoch 7/25: 100%|██████████| 4929/4929 [00:51<00:00, 94.93it/s, loss=0.1082]


Epoch 7/25 - Loss: 0.1305, Accuracy: 0.8849


Epoch 8/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.35it/s, loss=0.0747]


Epoch 8/25 - Loss: 0.1306, Accuracy: 0.8843


Epoch 9/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.91it/s, loss=0.1071]


Epoch 9/25 - Loss: 0.1307, Accuracy: 0.8837


Epoch 10/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.25it/s, loss=0.0658]


Epoch 10/25 - Loss: 0.1312, Accuracy: 0.8845


Epoch 11/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.53it/s, loss=0.1593]


Epoch 11/25 - Loss: 0.1301, Accuracy: 0.8850


Epoch 12/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.61it/s, loss=0.1126]


Epoch 12/25 - Loss: 0.1308, Accuracy: 0.8847


Epoch 13/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.40it/s, loss=0.1599]


Epoch 13/25 - Loss: 0.1306, Accuracy: 0.8847


Epoch 14/25: 100%|██████████| 4929/4929 [00:54<00:00, 91.10it/s, loss=0.1505]


Epoch 14/25 - Loss: 0.1300, Accuracy: 0.8852


Epoch 15/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.73it/s, loss=0.3029]


Epoch 15/25 - Loss: 0.1298, Accuracy: 0.8856


Epoch 16/25: 100%|██████████| 4929/4929 [01:32<00:00, 53.30it/s, loss=0.0939]


Epoch 16/25 - Loss: 0.1299, Accuracy: 0.8851


Epoch 17/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.68it/s, loss=0.1415]


Epoch 17/25 - Loss: 0.1298, Accuracy: 0.8855


Epoch 18/25: 100%|██████████| 4929/4929 [01:31<00:00, 53.88it/s, loss=0.1722]


Epoch 18/25 - Loss: 0.1298, Accuracy: 0.8851


Epoch 19/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.30it/s, loss=0.0846]


Epoch 19/25 - Loss: 0.1296, Accuracy: 0.8852


Epoch 20/25: 100%|██████████| 4929/4929 [01:32<00:00, 53.57it/s, loss=0.0867]


Epoch 20/25 - Loss: 0.1292, Accuracy: 0.8859


Epoch 21/25: 100%|██████████| 4929/4929 [01:27<00:00, 56.40it/s, loss=0.0689]


Epoch 21/25 - Loss: 0.1288, Accuracy: 0.8861


Epoch 22/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.87it/s, loss=0.3320]


Epoch 22/25 - Loss: 0.1290, Accuracy: 0.8855


Epoch 23/25: 100%|██████████| 4929/4929 [01:35<00:00, 51.62it/s, loss=0.0481]


Epoch 23/25 - Loss: 0.1291, Accuracy: 0.8856


Epoch 24/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.69it/s, loss=0.1110]


Epoch 24/25 - Loss: 0.1292, Accuracy: 0.8852


Epoch 25/25: 100%|██████████| 4929/4929 [01:28<00:00, 55.91it/s, loss=0.1199]


Epoch 25/25 - Loss: 0.1293, Accuracy: 0.8857
Fold 9 Accuracy: 0.8386
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/25: 100%|██████████| 4929/4929 [01:22<00:00, 59.94it/s, loss=0.1179]


Epoch 1/25 - Loss: 0.1315, Accuracy: 0.8843


Epoch 2/25: 100%|██████████| 4929/4929 [00:58<00:00, 83.79it/s, loss=0.1475]


Epoch 2/25 - Loss: 0.1306, Accuracy: 0.8844


Epoch 3/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.64it/s, loss=0.1264]


Epoch 3/25 - Loss: 0.1306, Accuracy: 0.8846


Epoch 4/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.69it/s, loss=0.1205]


Epoch 4/25 - Loss: 0.1301, Accuracy: 0.8849


Epoch 5/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.14it/s, loss=0.2460]


Epoch 5/25 - Loss: 0.1303, Accuracy: 0.8845


Epoch 6/25: 100%|██████████| 4929/4929 [01:16<00:00, 64.35it/s, loss=0.1591]


Epoch 6/25 - Loss: 0.1293, Accuracy: 0.8856


Epoch 7/25: 100%|██████████| 4929/4929 [01:28<00:00, 55.59it/s, loss=0.0826]


Epoch 7/25 - Loss: 0.1291, Accuracy: 0.8853


Epoch 8/25: 100%|██████████| 4929/4929 [01:26<00:00, 56.96it/s, loss=0.0714]


Epoch 8/25 - Loss: 0.1298, Accuracy: 0.8853


Epoch 9/25: 100%|██████████| 4929/4929 [01:08<00:00, 72.13it/s, loss=0.1283]


Epoch 9/25 - Loss: 0.1291, Accuracy: 0.8853


Epoch 10/25: 100%|██████████| 4929/4929 [01:02<00:00, 79.28it/s, loss=0.1616]


Epoch 10/25 - Loss: 0.1288, Accuracy: 0.8860


Epoch 11/25: 100%|██████████| 4929/4929 [01:28<00:00, 55.40it/s, loss=0.1469]


Epoch 11/25 - Loss: 0.1291, Accuracy: 0.8855


Epoch 12/25: 100%|██████████| 4929/4929 [01:27<00:00, 56.20it/s, loss=0.0883]


Epoch 12/25 - Loss: 0.1282, Accuracy: 0.8866


Epoch 13/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.48it/s, loss=0.1494]


Epoch 13/25 - Loss: 0.1293, Accuracy: 0.8853


Epoch 14/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.71it/s, loss=0.2604]


Epoch 14/25 - Loss: 0.1284, Accuracy: 0.8861


Epoch 15/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.75it/s, loss=0.2369]


Epoch 15/25 - Loss: 0.1291, Accuracy: 0.8855


Epoch 16/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.31it/s, loss=0.1872]


Epoch 16/25 - Loss: 0.1282, Accuracy: 0.8862


Epoch 17/25: 100%|██████████| 4929/4929 [01:30<00:00, 54.52it/s, loss=0.1100]


Epoch 17/25 - Loss: 0.1284, Accuracy: 0.8859


Epoch 18/25: 100%|██████████| 4929/4929 [01:35<00:00, 51.65it/s, loss=0.0937]


Epoch 18/25 - Loss: 0.1285, Accuracy: 0.8861


Epoch 19/25: 100%|██████████| 4929/4929 [01:33<00:00, 52.52it/s, loss=0.1583]


Epoch 19/25 - Loss: 0.1291, Accuracy: 0.8858


Epoch 20/25: 100%|██████████| 4929/4929 [01:36<00:00, 51.23it/s, loss=0.1392]


Epoch 20/25 - Loss: 0.1283, Accuracy: 0.8859


Epoch 21/25: 100%|██████████| 4929/4929 [00:52<00:00, 93.39it/s, loss=0.1690]


Epoch 21/25 - Loss: 0.1282, Accuracy: 0.8863


Epoch 22/25: 100%|██████████| 4929/4929 [00:51<00:00, 94.97it/s, loss=0.1133]


Epoch 22/25 - Loss: 0.1282, Accuracy: 0.8870


Epoch 23/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.79it/s, loss=0.0569]


Epoch 23/25 - Loss: 0.1282, Accuracy: 0.8867


Epoch 24/25: 100%|██████████| 4929/4929 [00:51<00:00, 94.95it/s, loss=0.1480]


Epoch 24/25 - Loss: 0.1274, Accuracy: 0.8862


Epoch 25/25: 100%|██████████| 4929/4929 [00:52<00:00, 94.71it/s, loss=0.1667]


Epoch 25/25 - Loss: 0.1280, Accuracy: 0.8864
Fold 10 Accuracy: 0.8380
Complete model saved to modelU10.pth
Fold Accuracies:
  Fold 1: 0.8137
  Fold 2: 0.8144
  Fold 3: 0.8252
  Fold 4: 0.8229
  Fold 5: 0.8275
  Fold 6: 0.8309
  Fold 7: 0.8255
  Fold 8: 0.8348
  Fold 9: 0.8386
  Fold 10: 0.8380


In [18]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  24    0    3  215    0    0   26    0    0    0]
 [   0   34   10  185    0    0    0    1    2    0]
 [   0    5  194 1383    8    7    9   16   12    1]
 [   1   11  100 4027   22   30   81  126   44   10]
 [   0    1   20  269 1279    3  801   30   22    0]
 [   0    0    5   43    1 5831    2    3    2    0]
 [   5    0    1   36  246    3 8947   43   19    0]
 [   0    1   13  255    5    0    3 1112   10    0]
 [   0    0    2    5    5    1    3    9  126    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.80      0.09      0.16       268
      Backdoor       0.65      0.15      0.24       232
           DoS       0.56      0.12      0.20      1635
      Exploits       0.63      0.90      0.74      4452
       Fuzzers       0.82      0.53      0.64      2425
       Generic       0.99      0.99      0.99      5887
        Normal       0.