In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import LabelEncoder
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 读取数据
train_df = pd.read_csv('unsw-nb15/UNSW_NB15_training-set.csv')
test_df = pd.read_csv('unsw-nb15/UNSW_NB15_testing-set.csv')

# 移除无关列
train_df.drop(columns=['id', 'label'], inplace=True)
test_df.drop(columns=['id', 'label'], inplace=True)

# 检查是否有缺失值
print("Train missing values:", train_df.isnull().sum().sum())
print("Test missing values:", test_df.isnull().sum().sum())

# One-hot 编码列
cols = ['proto', 'state', 'service']

def one_hot(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df.drop(col, axis=1, inplace=True)
    return df

# 合并数据进行统一处理
combined_data = pd.concat([test_df, train_df], ignore_index=True)

# 分离目标变量
target = combined_data.pop('attack_cat')

# One-hot 编码
combined_data = one_hot(combined_data, cols)

# Min-Max 归一化
def normalize(df):
    result = df.copy()
    for col in df.columns:
        max_val = df[col].max()
        min_val = df[col].min()
        if max_val > min_val:
            result[col] = (df[col] - min_val) / (max_val - min_val)
    return result

# 归一化数据
normalized_data = normalize(combined_data)

# 添加目标列
normalized_data['Class'] = target

# 检查是否有缺失值
assert not normalized_data.isnull().values.any(), "归一化后的数据存在缺失值"

# 分离特征和标签
X = normalized_data.drop(columns=['Class']).values
y = normalized_data['Class'].values
print(X.shape)
# 将目标变量转换为整数编码
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

Train missing values: 0
Test missing values: 0
(257673, 196)


In [2]:
import torch
import torch.nn as nn

class ParallelDilatedTCN(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 32, padding='same', dilation=1),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 64, padding='same', dilation=3),
                nn.BatchNorm1d(16),
                nn.GELU()
            ),
            nn.Sequential(
                nn.Conv1d(in_channels, 16, 96, padding='same', dilation=9),
                nn.BatchNorm1d(16),
                nn.GELU()
            )
        ])
        self.fusion_gate = nn.Sequential(
            nn.AdaptiveAvgPool1d(1),
            nn.Conv1d(48, 48, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        branch_outs = [branch(x) for branch in self.branches]
        merged = torch.cat(branch_outs, dim=1)
        return merged * self.fusion_gate(merged)



import torch
import torch.nn as nn
import torch.nn.functional as F

# ========================= Bi-ResAtt-LSTM ========================= #
class BiResAttLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=2, dropout=0.2):
        super(BiResAttLSTM, self).__init__()

        # 双向 LSTM
        self.bilstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # 自适应注意力门控
        self.att_gate = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),  # [B, L, H*2] -> [B, L, H]
            nn.GELU(),
            nn.Linear(hidden_size, 1),               # [B, L, H] -> [B, L, 1]
            nn.Sigmoid()
        )

        # 残差连接
        self.res_proj = nn.Linear(input_size, hidden_size * 2)  # 输入和输出维度对齐

    def forward(self, x):
        # x: [B, L, input_size]
        res = self.res_proj(x)                  # 残差映射
        lstm_out, _ = self.bilstm(x)            # 双向 LSTM 输出 [B, L, H*2]

        att_weights = self.att_gate(lstm_out)   # 注意力权重 [B, L, 1]
        attended = lstm_out * att_weights       # 加权 LSTM 输出 [B, L, H*2]

        return attended + res                   # 残差连接增强 [B, L, H*2]

class NSLKDDModel(nn.Module):
    def __init__(self, input_dim=196, num_classes=10, hidden_size=32):  # 新增hidden_size参数
        super().__init__()
        
        # 改进的TCN模块（保持原样）
        self.tcn = nn.Sequential(
            ParallelDilatedTCN(in_channels=1),
            nn.AdaptiveMaxPool1d(input_dim//4),  # 输出长度=input_dim//4
            nn.BatchNorm1d(48)                   # 3个分支各16通道 → 48
        )
        
        # 使用改进的 Bi-ResAtt-LSTM
        self.lstm = BiResAttLSTM(
            input_size=48,
            hidden_size=hidden_size,
            num_layers=2,
            dropout=0.2
        )

        # Transformer 编码器
        self.transformer_encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=hidden_size * 2,  # 匹配 BiLSTM 输出
                nhead=4,
                dim_feedforward=256,
                batch_first=True,
                activation=F.gelu
            ),
            num_layers=2
        )

        # 分类器
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear((input_dim // 4) * (hidden_size * 2), 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )
        

    def forward(self, x):
        x = self.tcn(x)                 # [B, 48, L]
        x = x.permute(0, 2, 1)          # [B, L, 48]

        lstm_out = self.lstm(x)         # [B, L, hidden_size*2]
        trans_out = self.transformer_encoder(lstm_out)  # [B, L, hidden_size*2]

        return self.classifier(trans_out)



In [3]:
from sklearn import metrics
from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
# 设置超参数
batch_size = 64
epochs =15   
learning_rate = 0.0005
k=10
# 交叉验证
kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=40)
oversample = RandomOverSampler(sampling_strategy='minority')

class LabelSmoothingCrossEntropy(nn.Module):
    def __init__(self, smoothing=0.1, reduction='mean'):
        """
        Args:
            smoothing: 平滑系数，通常在0.0~0.2之间。
            reduction: 损失聚合方式 ('mean', 'sum' or 'none')。
        """
        super(LabelSmoothingCrossEntropy, self).__init__()
        self.smoothing = smoothing
        self.reduction = reduction

    def forward(self, inputs, targets):
        """
        inputs: [B, num_classes] 的 logits（未经过 softmax）
        targets: [B] 的类别标签（long 类型）
        """
        num_classes = inputs.size(1)
        # 将标签进行 one-hot 编码
        with torch.no_grad():
            true_dist = torch.zeros_like(inputs)
            true_dist.fill_(self.smoothing / (num_classes - 1))
            true_dist.scatter_(1, targets.unsqueeze(1), 1 - self.smoothing)
        log_prob = F.log_softmax(inputs, dim=1)
        loss = -(true_dist * log_prob).sum(dim=1)
        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:
            return loss

criterion = LabelSmoothingCrossEntropy()
# 统计结果
oos_pred = []
# 初始化结果列表
oos_accuracies = []
last_fold_y_true = []
last_fold_y_pred = []

# 初始化模型
model = NSLKDDModel(input_dim=196, num_classes=10).to(device)
# criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-5)

# 遍历折叠
# 过采样少数类
#X_resampled, y_resampled = oversample.fit_resample(X, y_encoded)

for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y_encoded), start=1):
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X_resampled, y_resampled), start=1):
    # 划分数据集
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y_encoded[train_idx], y_encoded[test_idx]

    #X_train, X_test = X_resampled[train_idx], X_resampled[test_idx]
    #y_train, y_test = y_resampled[train_idx], y_resampled[test_idx]

    # 过采样少数类
    X_train, y_train = oversample.fit_resample(X_train, y_train)

    # 转换为 PyTorch TensorDataset
    train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                  torch.tensor(y_train, dtype=torch.long))
    test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                torch.tensor(y_test, dtype=torch.long))

    # DataLoader
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    print(f"Fold {fold}: {len(train_loader.dataset)} train samples, {len(test_loader.dataset)} validation samples")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        correct = 0
        total = 0

        # 使用 tqdm 显示进度条
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for batch_data, batch_labels in progress_bar:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)

            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            optimizer.zero_grad()
            outputs = model(batch_data)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()

            # 累积损失和准确性
            epoch_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

            # 更新进度条
            progress_bar.set_postfix({"loss": f"{loss.item():.4f}"})

        # 计算每轮的平均损失和准确率
        epoch_loss /= len(train_loader)
        epoch_acc = correct / total
        print(f"Epoch {epoch+1}/{epochs} - Loss: {epoch_loss:.4f}, Accuracy: {epoch_acc:.4f}")    

    model.eval()
    y_true, y_pred = [], []
    with torch.no_grad():
        for batch_data, batch_labels in test_loader:
            batch_data, batch_labels = batch_data.to(device), batch_labels.to(device)
            batch_data = batch_data.unsqueeze(1)  # 添加通道维度
            outputs = model(batch_data)
            _, preds = torch.max(outputs, 1)

            y_true.extend(batch_labels.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())

    # 测试集各类别数量
    # test_class_counts = Counter(y_true)
    # print("\nTest Set Class Distribution:")
    # for label, count in sorted(test_class_counts.items()):
    #     print(f"  Class {label}: {count}")

    # 计算准确率
    acc = metrics.accuracy_score(y_true, y_pred)
    oos_accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")

    # 保存最后一折的结果
    if fold == kfold.get_n_splits():
        last_fold_y_true = y_true
        last_fold_y_pred = y_pred

# 保存模型
model_save_path = "UNSW-LSCEloss1.pth"
torch.save(model, model_save_path)
print(f"Complete model saved to {model_save_path}")

# 输出每一折的准确率
print("Fold Accuracies:")
for i, acc in enumerate(oos_accuracies, start=1):
    print(f"  Fold {i}: {acc:.4f}")
 

Fold 1: 315449 train samples, 25768 validation samples


Epoch 1/15:   0%|          | 0/4929 [00:00<?, ?it/s]E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1041.)
  return F.conv1d(input, weight, bias, self.stride,
E:\shendu\anaconda3\envs\pytorch1\lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Epoch 1/15: 100%|██████████| 4929/4929 [00:54<00:00, 90.50it/s, loss=0.9403] 


Epoch 1/15 - Loss: 0.9198, Accuracy: 0.8223


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.55it/s, loss=0.7469]


Epoch 2/15 - Loss: 0.8521, Accuracy: 0.8504


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.93it/s, loss=1.0115]


Epoch 3/15 - Loss: 0.8383, Accuracy: 0.8549


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.89it/s, loss=0.8174]


Epoch 4/15 - Loss: 0.8300, Accuracy: 0.8580


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.57it/s, loss=0.9385]


Epoch 5/15 - Loss: 0.8245, Accuracy: 0.8597


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.87it/s, loss=0.7833]


Epoch 6/15 - Loss: 0.8207, Accuracy: 0.8614


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.7573]


Epoch 7/15 - Loss: 0.8179, Accuracy: 0.8624


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.80it/s, loss=1.0202]


Epoch 8/15 - Loss: 0.8155, Accuracy: 0.8628


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.90it/s, loss=0.8257]


Epoch 9/15 - Loss: 0.8128, Accuracy: 0.8638


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.58it/s, loss=0.7472]


Epoch 10/15 - Loss: 0.8112, Accuracy: 0.8647


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.8099]


Epoch 11/15 - Loss: 0.8095, Accuracy: 0.8653


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.93it/s, loss=0.8841]


Epoch 12/15 - Loss: 0.8081, Accuracy: 0.8662


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.70it/s, loss=0.8195]


Epoch 13/15 - Loss: 0.8065, Accuracy: 0.8667


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.61it/s, loss=0.8341]


Epoch 14/15 - Loss: 0.8054, Accuracy: 0.8675


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.79it/s, loss=0.7795]


Epoch 15/15 - Loss: 0.8045, Accuracy: 0.8677
Fold 1 Accuracy: 0.8188
Fold 2: 315449 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.82it/s, loss=0.6955]


Epoch 1/15 - Loss: 0.8047, Accuracy: 0.8679


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.81it/s, loss=0.8041]


Epoch 2/15 - Loss: 0.8028, Accuracy: 0.8688


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.85it/s, loss=0.8066]


Epoch 3/15 - Loss: 0.8019, Accuracy: 0.8687


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.7670]


Epoch 4/15 - Loss: 0.8010, Accuracy: 0.8691


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.88it/s, loss=0.7542]


Epoch 5/15 - Loss: 0.7997, Accuracy: 0.8694


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.8952]


Epoch 6/15 - Loss: 0.7987, Accuracy: 0.8702


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.78it/s, loss=0.7817]


Epoch 7/15 - Loss: 0.7976, Accuracy: 0.8703


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.87it/s, loss=0.7644]


Epoch 8/15 - Loss: 0.7968, Accuracy: 0.8711


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.90it/s, loss=0.8856]


Epoch 9/15 - Loss: 0.7961, Accuracy: 0.8714


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.98it/s, loss=0.7279]


Epoch 10/15 - Loss: 0.7950, Accuracy: 0.8717


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.7862]


Epoch 11/15 - Loss: 0.7948, Accuracy: 0.8719


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.81it/s, loss=0.7676]


Epoch 12/15 - Loss: 0.7938, Accuracy: 0.8721


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.18it/s, loss=0.9046]


Epoch 13/15 - Loss: 0.7923, Accuracy: 0.8725


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.78it/s, loss=0.8929]


Epoch 14/15 - Loss: 0.7916, Accuracy: 0.8733


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.82it/s, loss=0.8300]


Epoch 15/15 - Loss: 0.7912, Accuracy: 0.8735
Fold 2 Accuracy: 0.8247
Fold 3: 315448 train samples, 25768 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.60it/s, loss=0.7602]


Epoch 1/15 - Loss: 0.7914, Accuracy: 0.8734


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.87it/s, loss=0.7109]


Epoch 2/15 - Loss: 0.7901, Accuracy: 0.8743


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.88it/s, loss=0.7678]


Epoch 3/15 - Loss: 0.7898, Accuracy: 0.8743


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.7031]


Epoch 4/15 - Loss: 0.7887, Accuracy: 0.8744


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.78it/s, loss=0.8946]


Epoch 5/15 - Loss: 0.7877, Accuracy: 0.8751


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.7447]


Epoch 6/15 - Loss: 0.7879, Accuracy: 0.8750


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.99it/s, loss=0.9523]


Epoch 7/15 - Loss: 0.7873, Accuracy: 0.8753


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.04it/s, loss=0.7901]


Epoch 8/15 - Loss: 0.7866, Accuracy: 0.8756


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.7374]


Epoch 9/15 - Loss: 0.7862, Accuracy: 0.8758


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.7901]


Epoch 10/15 - Loss: 0.7852, Accuracy: 0.8762


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.74it/s, loss=0.8044]


Epoch 11/15 - Loss: 0.7845, Accuracy: 0.8767


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.8185]


Epoch 12/15 - Loss: 0.7843, Accuracy: 0.8769


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.58it/s, loss=0.7615]


Epoch 13/15 - Loss: 0.7837, Accuracy: 0.8772


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.08it/s, loss=0.6346]


Epoch 14/15 - Loss: 0.7833, Accuracy: 0.8771


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.61it/s, loss=0.6840]


Epoch 15/15 - Loss: 0.7826, Accuracy: 0.8777
Fold 3 Accuracy: 0.8310
Fold 4: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.39it/s, loss=0.7282]


Epoch 1/15 - Loss: 0.7847, Accuracy: 0.8769


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.47it/s, loss=0.7696]


Epoch 2/15 - Loss: 0.7828, Accuracy: 0.8777


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.87it/s, loss=0.7969]


Epoch 3/15 - Loss: 0.7822, Accuracy: 0.8778


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.83it/s, loss=0.8143]


Epoch 4/15 - Loss: 0.7819, Accuracy: 0.8778


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.57it/s, loss=0.7400]


Epoch 5/15 - Loss: 0.7809, Accuracy: 0.8791


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.04it/s, loss=0.7425]


Epoch 6/15 - Loss: 0.7810, Accuracy: 0.8783


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.73it/s, loss=0.7944]


Epoch 7/15 - Loss: 0.7805, Accuracy: 0.8790


Epoch 8/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.32it/s, loss=0.8481]


Epoch 8/15 - Loss: 0.7801, Accuracy: 0.8791


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.77it/s, loss=0.8016]


Epoch 9/15 - Loss: 0.7793, Accuracy: 0.8797


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.73it/s, loss=0.7143]


Epoch 10/15 - Loss: 0.7790, Accuracy: 0.8792


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.66it/s, loss=0.7376]


Epoch 11/15 - Loss: 0.7786, Accuracy: 0.8799


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.18it/s, loss=0.7776]


Epoch 12/15 - Loss: 0.7782, Accuracy: 0.8800


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.67it/s, loss=0.7470]


Epoch 13/15 - Loss: 0.7775, Accuracy: 0.8802


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.40it/s, loss=0.6917]


Epoch 14/15 - Loss: 0.7770, Accuracy: 0.8809


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.04it/s, loss=0.7600]


Epoch 15/15 - Loss: 0.7773, Accuracy: 0.8803
Fold 4 Accuracy: 0.8282
Fold 5: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.57it/s, loss=0.8022]


Epoch 1/15 - Loss: 0.7796, Accuracy: 0.8792


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.56it/s, loss=0.9049]


Epoch 2/15 - Loss: 0.7789, Accuracy: 0.8800


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.95it/s, loss=0.7680]


Epoch 3/15 - Loss: 0.7779, Accuracy: 0.8801


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.84it/s, loss=0.8850]


Epoch 4/15 - Loss: 0.7780, Accuracy: 0.8799


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.60it/s, loss=0.7120]


Epoch 5/15 - Loss: 0.7771, Accuracy: 0.8809


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.10it/s, loss=0.8838]


Epoch 6/15 - Loss: 0.7769, Accuracy: 0.8805


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.82it/s, loss=0.7012]


Epoch 7/15 - Loss: 0.7769, Accuracy: 0.8808


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.56it/s, loss=0.7315]


Epoch 8/15 - Loss: 0.7761, Accuracy: 0.8811


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.67it/s, loss=0.7246]


Epoch 9/15 - Loss: 0.7759, Accuracy: 0.8812


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.82it/s, loss=0.7853]


Epoch 10/15 - Loss: 0.7755, Accuracy: 0.8813


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.70it/s, loss=0.6792]


Epoch 11/15 - Loss: 0.7747, Accuracy: 0.8821


Epoch 12/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.43it/s, loss=0.7626]


Epoch 12/15 - Loss: 0.7745, Accuracy: 0.8820


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.52it/s, loss=0.8105]


Epoch 13/15 - Loss: 0.7743, Accuracy: 0.8826


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.84it/s, loss=0.8716]


Epoch 14/15 - Loss: 0.7740, Accuracy: 0.8823


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.90it/s, loss=0.7319]


Epoch 15/15 - Loss: 0.7738, Accuracy: 0.8824
Fold 5 Accuracy: 0.8351
Fold 6: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.11it/s, loss=0.8347]


Epoch 1/15 - Loss: 0.7753, Accuracy: 0.8823


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.31it/s, loss=0.8318]


Epoch 2/15 - Loss: 0.7742, Accuracy: 0.8822


Epoch 3/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.41it/s, loss=0.7722]


Epoch 3/15 - Loss: 0.7742, Accuracy: 0.8824


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.24it/s, loss=0.7407]


Epoch 4/15 - Loss: 0.7739, Accuracy: 0.8824


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.86it/s, loss=0.7327]


Epoch 5/15 - Loss: 0.7731, Accuracy: 0.8827


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.94it/s, loss=0.6992]


Epoch 6/15 - Loss: 0.7730, Accuracy: 0.8825


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.73it/s, loss=0.8527]


Epoch 7/15 - Loss: 0.7724, Accuracy: 0.8831


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.58it/s, loss=0.7873]


Epoch 8/15 - Loss: 0.7718, Accuracy: 0.8835


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.88it/s, loss=0.7086]


Epoch 9/15 - Loss: 0.7720, Accuracy: 0.8830


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.50it/s, loss=0.8117]


Epoch 10/15 - Loss: 0.7722, Accuracy: 0.8834


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.8737]


Epoch 11/15 - Loss: 0.7712, Accuracy: 0.8839


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.93it/s, loss=0.7189]


Epoch 12/15 - Loss: 0.7710, Accuracy: 0.8839


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.55it/s, loss=0.6956]


Epoch 13/15 - Loss: 0.7710, Accuracy: 0.8838


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.58it/s, loss=0.7524]


Epoch 14/15 - Loss: 0.7705, Accuracy: 0.8846


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.92it/s, loss=0.6929]


Epoch 15/15 - Loss: 0.7706, Accuracy: 0.8840
Fold 6 Accuracy: 0.8420
Fold 7: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.77it/s, loss=0.8020]


Epoch 1/15 - Loss: 0.7709, Accuracy: 0.8837


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.44it/s, loss=0.8310]


Epoch 2/15 - Loss: 0.7705, Accuracy: 0.8847


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.86it/s, loss=0.7222]


Epoch 3/15 - Loss: 0.7700, Accuracy: 0.8846


Epoch 4/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.60it/s, loss=0.7895]


Epoch 4/15 - Loss: 0.7695, Accuracy: 0.8850


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.01it/s, loss=0.7128]


Epoch 5/15 - Loss: 0.7693, Accuracy: 0.8852


Epoch 6/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.58it/s, loss=0.8223]


Epoch 6/15 - Loss: 0.7685, Accuracy: 0.8852


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.07it/s, loss=0.8881]


Epoch 7/15 - Loss: 0.7685, Accuracy: 0.8855


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.8635]


Epoch 8/15 - Loss: 0.7689, Accuracy: 0.8851


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.54it/s, loss=0.9895]


Epoch 9/15 - Loss: 0.7680, Accuracy: 0.8858


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.57it/s, loss=0.8120]


Epoch 10/15 - Loss: 0.7679, Accuracy: 0.8854


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.62it/s, loss=0.8189]


Epoch 11/15 - Loss: 0.7669, Accuracy: 0.8863


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.98it/s, loss=0.7006]


Epoch 12/15 - Loss: 0.7676, Accuracy: 0.8863


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.53it/s, loss=0.8421]


Epoch 13/15 - Loss: 0.7672, Accuracy: 0.8863


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.45it/s, loss=0.7774]


Epoch 14/15 - Loss: 0.7667, Accuracy: 0.8864


Epoch 15/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.43it/s, loss=0.7416]


Epoch 15/15 - Loss: 0.7662, Accuracy: 0.8864
Fold 7 Accuracy: 0.8409
Fold 8: 315449 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.03it/s, loss=0.8228]


Epoch 1/15 - Loss: 0.7688, Accuracy: 0.8856


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.55it/s, loss=0.7328]


Epoch 2/15 - Loss: 0.7681, Accuracy: 0.8853


Epoch 3/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.36it/s, loss=0.7653]


Epoch 3/15 - Loss: 0.7676, Accuracy: 0.8859


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.28it/s, loss=0.7422]


Epoch 4/15 - Loss: 0.7676, Accuracy: 0.8856


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.00it/s, loss=0.7862]


Epoch 5/15 - Loss: 0.7671, Accuracy: 0.8864


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.25it/s, loss=0.7271]


Epoch 6/15 - Loss: 0.7667, Accuracy: 0.8864


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.53it/s, loss=0.8450]


Epoch 7/15 - Loss: 0.7665, Accuracy: 0.8867


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.33it/s, loss=0.7201]


Epoch 8/15 - Loss: 0.7660, Accuracy: 0.8871


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.79it/s, loss=0.8011]


Epoch 9/15 - Loss: 0.7664, Accuracy: 0.8863


Epoch 10/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.46it/s, loss=0.7219]


Epoch 10/15 - Loss: 0.7658, Accuracy: 0.8869


Epoch 11/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.36it/s, loss=0.9411]


Epoch 11/15 - Loss: 0.7652, Accuracy: 0.8869


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.63it/s, loss=0.8569]


Epoch 12/15 - Loss: 0.7649, Accuracy: 0.8871


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.70it/s, loss=0.7861]


Epoch 13/15 - Loss: 0.7644, Accuracy: 0.8877


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.87it/s, loss=0.7790]


Epoch 14/15 - Loss: 0.7643, Accuracy: 0.8877


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.55it/s, loss=0.7619]


Epoch 15/15 - Loss: 0.7648, Accuracy: 0.8879
Fold 8 Accuracy: 0.8424
Fold 9: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.64it/s, loss=0.7868]


Epoch 1/15 - Loss: 0.7656, Accuracy: 0.8877


Epoch 2/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.09it/s, loss=0.7846]


Epoch 2/15 - Loss: 0.7655, Accuracy: 0.8865


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.82it/s, loss=0.7800]


Epoch 3/15 - Loss: 0.7648, Accuracy: 0.8874


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.21it/s, loss=0.6715]


Epoch 4/15 - Loss: 0.7645, Accuracy: 0.8878


Epoch 5/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.56it/s, loss=0.8805]


Epoch 5/15 - Loss: 0.7641, Accuracy: 0.8879


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.30it/s, loss=0.7199]


Epoch 6/15 - Loss: 0.7639, Accuracy: 0.8879


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.69it/s, loss=0.6653]


Epoch 7/15 - Loss: 0.7639, Accuracy: 0.8878


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.05it/s, loss=0.7080]


Epoch 8/15 - Loss: 0.7629, Accuracy: 0.8882


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.99it/s, loss=0.7713]


Epoch 9/15 - Loss: 0.7632, Accuracy: 0.8885


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.67it/s, loss=0.7723]


Epoch 10/15 - Loss: 0.7629, Accuracy: 0.8886


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.76it/s, loss=0.7429]


Epoch 11/15 - Loss: 0.7634, Accuracy: 0.8888


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.70it/s, loss=0.7437]


Epoch 12/15 - Loss: 0.7623, Accuracy: 0.8886


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.22it/s, loss=0.7212]


Epoch 13/15 - Loss: 0.7624, Accuracy: 0.8891


Epoch 14/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.42it/s, loss=0.6738]


Epoch 14/15 - Loss: 0.7619, Accuracy: 0.8894


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.79it/s, loss=0.7641]


Epoch 15/15 - Loss: 0.7612, Accuracy: 0.8896
Fold 9 Accuracy: 0.8465
Fold 10: 315450 train samples, 25767 validation samples


Epoch 1/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.05it/s, loss=0.7812]


Epoch 1/15 - Loss: 0.7633, Accuracy: 0.8882


Epoch 2/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.50it/s, loss=0.6918]


Epoch 2/15 - Loss: 0.7633, Accuracy: 0.8886


Epoch 3/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.94it/s, loss=0.8380]


Epoch 3/15 - Loss: 0.7624, Accuracy: 0.8890


Epoch 4/15: 100%|██████████| 4929/4929 [00:57<00:00, 85.66it/s, loss=0.7456]


Epoch 4/15 - Loss: 0.7624, Accuracy: 0.8891


Epoch 5/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.20it/s, loss=0.7078]


Epoch 5/15 - Loss: 0.7622, Accuracy: 0.8884


Epoch 6/15: 100%|██████████| 4929/4929 [00:57<00:00, 86.22it/s, loss=0.7017]


Epoch 6/15 - Loss: 0.7621, Accuracy: 0.8886


Epoch 7/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.61it/s, loss=0.6799]


Epoch 7/15 - Loss: 0.7619, Accuracy: 0.8890


Epoch 8/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.54it/s, loss=0.8628]


Epoch 8/15 - Loss: 0.7614, Accuracy: 0.8888


Epoch 9/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.96it/s, loss=0.8740]


Epoch 9/15 - Loss: 0.7609, Accuracy: 0.8896


Epoch 10/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.82it/s, loss=0.7925]


Epoch 10/15 - Loss: 0.7607, Accuracy: 0.8899


Epoch 11/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.48it/s, loss=0.6881]


Epoch 11/15 - Loss: 0.7607, Accuracy: 0.8891


Epoch 12/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.77it/s, loss=0.7196]


Epoch 12/15 - Loss: 0.7605, Accuracy: 0.8899


Epoch 13/15: 100%|██████████| 4929/4929 [00:56<00:00, 86.56it/s, loss=0.8710]


Epoch 13/15 - Loss: 0.7600, Accuracy: 0.8906


Epoch 14/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.05it/s, loss=0.9657]


Epoch 14/15 - Loss: 0.7599, Accuracy: 0.8902


Epoch 15/15: 100%|██████████| 4929/4929 [00:56<00:00, 87.05it/s, loss=0.8278]


Epoch 15/15 - Loss: 0.7600, Accuracy: 0.8899
Fold 10 Accuracy: 0.8537
Complete model saved to UNSW-LSCEloss1.pth
Fold Accuracies:
  Fold 1: 0.8188
  Fold 2: 0.8247
  Fold 3: 0.8310
  Fold 4: 0.8282
  Fold 5: 0.8351
  Fold 6: 0.8420
  Fold 7: 0.8409
  Fold 8: 0.8424
  Fold 9: 0.8465
  Fold 10: 0.8537


In [4]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# 分类类别
categories = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic','Normal', 'Reconnaissance', 'Shellcode', 'Worms']

# 混淆矩阵（最后一折的结果）
last_cm = confusion_matrix(last_fold_y_true, last_fold_y_pred, labels=range(10))

print("\nLast Fold Confusion Matrix:")
print(last_cm)

report = classification_report(last_fold_y_true, last_fold_y_pred, target_names=categories)
print("\nClassification Report:")
print(report)

# 从混淆矩阵提取所有类别的统计信息
total_samples = last_cm.sum()  # 总样本数
correct_predictions = np.trace(last_cm)  # 对角线元素的和，即正确分类的总数

# 总体准确率（直接计算）
overall_accuracy = correct_predictions / total_samples

# 初始化总体指标
overall_TP = 0
overall_FN = 0
overall_FP = 0
overall_TN = 0


# 重新计算分类报告中的 TP、FP、FN、TN
detection_rates = {}
false_positive_rates = {}

for i, category in enumerate(categories):
    TP = last_cm[i, i]
    FN = last_cm[i, :].sum() - TP
    FP = last_cm[:, i].sum() - TP
    TN = total_samples - (TP + FP + FN)

    if category != "Normal":  # 统计攻击类型的总 TP 和 FN
        overall_TP += TP
        overall_FN += FN
    else:  # 统计正常类型的 TN 和 FP
        overall_TN += TN
        overall_FP += FP

    # 每类检测率和误报率
    detection_rates[category] = TP / (TP + FN) if (TP + FN) > 0 else 0.0
    false_positive_rates[category] = FP / (FP + TN) if (FP + TN) > 0 else 0.0

    print(f"Category: {category}")
    print(f"  Detection Rate (DR): {detection_rates[category]:.4f}")
    print(f"  False Positive Rate (FPR): {false_positive_rates[category]:.4f}")

# 总体检测率（攻击类型的 DR）和误报率（Normal 的 FPR）
overall_dr = overall_TP / (overall_TP + overall_FN) if (overall_TP + overall_FN) > 0 else 0.0
overall_fpr = overall_FP / (overall_FP + overall_TN) if (overall_FP + overall_TN) > 0 else 0.0

print("\nOverall Metrics:")
print(f"  Accuracy (Acc): {overall_accuracy:.4f}")
print(f"  Detection Rate (DR): {overall_dr:.4f}")
print(f"  False Positive Rate (FPR): {overall_fpr:.4f}")


Last Fold Confusion Matrix:
[[  30    0    5  204    6    0   23    0    0    0]
 [   0   29    5  188   10    0    0    0    0    0]
 [   0    0  216 1360   17    9    9   10   12    2]
 [   0    3   79 4159   44   16   56   61   21   13]
 [   1    0   11  247 1602    1  542    9    8    4]
 [   0    0    5   52    2 5822    4    2    0    0]
 [   3    0    6   24  327    0 8923    9    7    1]
 [   0    1    9  288    2    0    2 1093    4    0]
 [   0    0    1   11   14    2    9    9  105    0]
 [   0    0    0    0    0    0    0    0    0   18]]

Classification Report:
                precision    recall  f1-score   support

      Analysis       0.88      0.11      0.20       268
      Backdoor       0.88      0.12      0.22       232
           DoS       0.64      0.13      0.22      1635
      Exploits       0.64      0.93      0.76      4452
       Fuzzers       0.79      0.66      0.72      2425
       Generic       1.00      0.99      0.99      5887
        Normal       0.